# MediaPipelineRemuxEncodeAIO config template for new-user deployments.
# Copy or generate this as MediaPipeline_config.psd1 with the setup wizard.
# (Legacy operator copies named MediaPipeline_config_chatgpt.psd1 are still loaded as a fallback.)
# Keep operator-specific paths and machine-only tuning in the live config, not here.
@{
    ConfigSchemaVersion = 1
    SourceMovies = 'C:\MediaPipeline\Incoming\Movies'
    SourceTV = 'C:\MediaPipeline\Incoming\TV'
    Outsource = 'C:\MediaPipeline\Processed'
    LocalBase = 'C:\MediaPipeline\Scratch'
    MovieRoute1080pTargetSizeGB = 8
    MovieRoute1440pTargetSizeGB = 8
    MovieRoute4KTargetSizeGB = 8
    TVRoute1080pTargetSizeGB = 3
    TVRoute1440pTargetSizeGB = 3
    TVRoute4KTargetSizeGB = 3
    RoutingProfile = 'plex_direct_stream'
    RouteThresholdMode = 'compatibility_advisory'
    Route1080pUpperHeightTolerancePercent = 11.111111
    Route1080pMaxVideoBitrateMbps = 20
    Route1440pLowerHeightTolerancePercent = 16.597222
    Route1440pUpperHeightTolerancePercent = 24.930556
    Route1440pMaxVideoBitrateMbps = 35
    Route4KLowerHeightTolerancePercent = 16.666667
    Route4KMaxVideoBitrateMbps = 35
    AllowH264RemuxIfPlexCompatible = $true
    H264RemuxMaxBitrateMbps = 35
    H264RemuxMaxHeight = 1080
    SizeGuardMode = 'advisory'
    MaxEncodeGrowthPercent = 5
    CompatibilityEncodeGrowthPercent = 15
    EncodeWasteGuardMode = 'off'
    EncodeWasteGuardPreflightEnabled = $false
    EncodeWasteGuardMinProgressPercent = 15
    EncodeWasteGuardMinElapsedSeconds = 120
    EncodeWasteGuardOversizeMarginPercent = 20
    EncodeWasteGuardConsecutiveSamples = 2
    EncodeWasteGuardPollSeconds = 10
    EncodeWasteGuardPreflightSampleSeconds = 30
    EncodeWasteGuardPreflightSampleCount = 3
    EncodeWasteGuardPreflightTimeoutSeconds = 900
    MinFreeSpaceGB = 50
    OutsourceMinFreeSpaceGB = 50
    DeferredPublish = $false
    FinalLibraryPromotionEnabled = $false
    FinalLibraryPromotionRules = @()
    FinalLibraryPromotionVerificationMode = 'cautious'
    FinalLibraryPromotionCleanupAfterVerified = $false
    FinalLibraryPromotionOverwriteExisting = $false
    VideoCodec = 'hevc_nvenc'
    EncoderBackend = 'auto'
    VideoPreset = 'p7'
    VideoQuality = 22
    OutputContainer = 'mkv'
    DynamicHdrPolicy = 'warn'
    DoviToolPath = ''
    Hdr10PlusToolPath = ''
    EncodeTuningPreset = 'balanced_nvenc'
    EncodeLadder = 'auto'
    ExtraVideoFlags = @()
    AudioPassthroughProfile = 'plex_balanced'
    CompatibleAudioCodecs = @('aac', 'ac3', 'eac3', 'mp3', 'opus', 'vorbis', 'truehd', 'mlp')
    PreferredDefaultAudioLanguages = @('english')
    SubKeepLanguages = @('eng', 'en', 'und', '')
    ConvertTx3gToSrt = $true
    DropTx3gAfterConversion = $false
    CreateExternalTx3gSrtSidecars = $false
    Tx3gExtractLanguages = @('eng', 'en', 'und')
    Tx3gPreserveExistingSrt = $true
    Tx3gTreatForcedAsSeparate = $true
    ConvertBdpgsToSrt = $false
    DropBdpgsAfterConversion = $false
    BdpgsExtractLanguages = @('eng', 'en', 'und')
    BdpgsOcrToolPath = 'tools\PgsToSrt\PgsToSrt.exe'
    BdpgsOcrTessdataPath = 'tools\PgsToSrt\tessdata'
    ConvertVobSubToSrt = $false
    DropVobSubAfterConversion = $false
    VobSubExtractLanguages = @('eng', 'en', 'und')
    VobSubOcrToolPath = 'tools\SubtitleEditLegacy\SubtitleEdit.exe'
    SubSDHTitleKeywords = @('sdh', 'hearing impaired', 'hearing-impaired', 'cc', 'closed caption', 'closedcaption')
    SubSupplementalKeywords = @('sign', 'song', 'karaoke', 'chapter', 'opening', 'ending')
    DropAssAfterConversion = $false
    StripFormatting = $true
    RemoveKaraoke = $true
    MergeAdjacent = $true
    MergeThresholdMs = 150
    KeepSignsAndSongs = $true
    TreatAssSignsSongsAsForced = $false
    TreatTx3gSignsSongsAsForced = $false
    TreatBdpgsSignsSongsAsForced = $false
    TreatVobSubSignsSongsAsForced = $false
    ExcludeSubtitleStyles = @('Sign', 'Sign *', 'Sign-*', 'Signs', 'Signs *', 'Signs-*', 'OP', 'OP *', 'OP-*', 'OP_*', 'Opening*', 'ED', 'ED *', 'ED-*', 'ED_*', 'Ending*', '*Lyrics*', '*Romaji*', '*Kanji*', 'Song', 'Song *', 'Song-*', 'Title', 'Show Title', 'Episode Title', 'Next Episode', 'Next *', 'Credits', 'Credit*', 'Note', 'Note*', 'Caption', 'Caption*', 'fs')
    IncludeSubtitleStyles = @()
    RemuxSafeVideoCodecs = @('hevc', 'h265', 'h.265')
    RenameMovieFilterOptions = @{
        video_source = $true
        audio_channels = $true
        editions = $true
        file_size = $true
        services_containers = $true
        release_groups = $true
    }
    RenameMovieFilterTerms = @{
        video_source = @('2160p', '1080p', '1080i', '720p', '720i', '480p', '4k', 'uhd', 'hdr', 'hdr10', 'hdr10+', 'hlg', 'dv', 'dovi', 'dolby vision', 'hevc', 'h264', 'h.264', 'h265', 'h.265', 'x264', 'x265', 'av1', 'avc', 'xvid', 'divx', 'blu ray', 'bluray', 'brrip', 'bdrip', 'webrip', 'web dl', 'webdl', 'web', 'hdtv', 'hdrip', 'dvdrip', 'dvd', 'dvdscr', 'ts', 'cam', 'scr', 'remux', 'hybrid', '10 bit', '8 bit')
        audio_channels = @('truehd', 'atmos', 'flac', 'opus', 'eac3', 'ac3', 'aac', 'dd', 'dd+', 'ddp', 'dts', 'dts hd', 'dts-x', 'dtsx', 'dtshd', 'lpcm', 'pcm', 'mp3', 'mp2', '1.0', '2.0', '5.1', '7.1', 'stereo', 'mono', '6ch', '6 ch', '8ch', '8 ch')
        editions = @('imax', 'proper', 'repack', 'rerip', 'extended', 'remastered', 'remaster', 'restored', 'restoration', 'unrated', 'theatrical', 'criterion', 'director cut', 'directors cut', "director's cut", 'dc', 'final cut', 'open matte', 'redux', 'special edition', 'se', 'anniversary', 'collectors edition', 'supercut')
        file_size = @('500mb', '700mb', '1400mb', '1gb', '1.5gb', '2gb', '3gb', '4.7gb', '5gb', '6gb', '8gb', '10gb', '15gb', '20gb', '25gb', '30gb')
        services_containers = @('amzn', 'nf', 'dsnp', 'hmax', 'hulu', 'itunes', 'appletv', 'atvp', 'peacock', 'pck', 'vudu', 'stan', 'sho', 'mkv', 'mp4', 'm4v', 'avi', 'mov', 'wmv', 'MA')
        release_groups = @('rarbg', 'rbg', 'yify', 'yts', 'yts lt', 'galaxyrg', 'bone', 'psa', 'tigole', 'kris', 'sparks', 'ntb', 'evo', 'tepes', 'flux', 'framestor', 'cmrg', 'neonoir', 'supaCvnt', 'BYNDR', 'Kira')
    }
    RenameMovieRemoveTerms = @('sample', 'trailer', 'extras', 'featurette', 'deleted scenes', 'behind the scenes', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12')
    ValidExtensions = @('.mkv', '.mp4', '.avi', '.mov', '.m4v', '.ts', '.m2ts')
    FileStabilityWait = 15
    EnableWatchFolders = $false
    WatchFolderRoots = @()
    WatchDebounceSeconds = 30
    WatchAction = 'enqueue_only'
    WatchRespectScheduleWindow = $true
    SkipStabilityCheck = $false
    EnableIntegrityCheck = $true
    CreateTVSubfolder = $true
    AggressiveEpisodeParsing = $false
    RobocopyFlags = @('/J', '/R:3', '/W:15', '/MT:2', '/NP', '/NDL', '/NFL')
    DebugMode = $true
    LogRetentionDays = 7
    PriorityMarkers = @('!', '[NOW]')
    MaxParallelEncodes = 1
    ParallelEncodeMode = 'single'
    FallbackCpuQuality = 20
    CpuEncodePreset = 'medium'
    CpuEncodeProcessPriority = 'belownormal'
    CpuEncodeMaxThreads = 0
    OutputSizeMultiplier = 0.7
    FFmpegEncodeTimeoutSeconds = 21600
    FFmpegCpuEncodeTimeoutSeconds = 43200
    FFmpegRemuxTimeoutSeconds = 7200
    MkvmergeRemuxTimeoutSeconds = 7200
    SubtitleExtractTimeoutSeconds = 180
    SubtitleProbeTimeoutSeconds = 30
    BdpgsOcrTimeoutSeconds = 1800
    VobSubOcrTimeoutSeconds = 1800
    OutputValidationProbeTimeoutSeconds = 60
    OutputValidationMinSizeBytes = 1024
    OutputValidationDurationToleranceSeconds = 2
    EnableQualityVerification = $false
    QualityMetric = 'vmaf'
    QualitySampleMode = 'sampled'
    QualitySampleSeconds = 10
    QualitySampleCount = 3
    QualityWarnThreshold = 90
    QualityFailThreshold = 75
    QualityFailAction = 'warn_only'
    QualityVerifyTimeoutSeconds = 1800
    AllowSystemTools = $false
    RobocopyTimeoutSeconds = 14400
    TransientFailureRetryLimit = 3
    SourceScanTimeoutSeconds = 1800
    IndexScanTimeoutSeconds = 1800
    CleanupScanTimeoutSeconds = 300
    CleanupRemoteStaging = $false
    CleanupStaleAgeHours = 24
    SourceScanIntervalSeconds = 300
    ProcessedIndexRefreshSeconds = 900
    ReprocessAll = $false
    PlannerRolloutStage = 'legacy'
    UsePythonPlanner = $false
    EnableHandBrakeSettingsUi = $false
    PlannerComparisonLogging = $false
    NewPlannerCutoverApproved = $false
}
