from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
UNRELEASED_DIR = REPO_ROOT / "changes" / "unreleased"
RELEASED_DIR = REPO_ROOT / "changes" / "released"
CHANGELOG_PATH = REPO_ROOT / "Docs" / "change_control" / "CHANGELOG.md"


def _packet_paths(root: Path, pattern: str) -> list[Path]:
    if not root.exists():
        return []
    return sorted(path for path in root.glob(pattern) if path.is_file())


def _load_packet(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _as_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def _line_text(value: Any) -> str:
    text = _as_text(value).strip()
    return text.replace("\n", " ") if text else "-"


def _list_lines(label: str, value: Any) -> list[str]:
    lines = [f"- {label}:"]
    if isinstance(value, list) and value:
        lines.extend(f"  - {_line_text(item)}" for item in value)
    else:
        lines.append("  - -")
    return lines


def _version_key(version: str) -> list[tuple[int, object]]:
    parts = re.split(r"(\d+)", version)
    key: list[tuple[int, object]] = []
    for part in parts:
        if not part:
            continue
        if part.isdigit():
            key.append((1, int(part)))
        else:
            key.append((0, part))
    return key


def _entry(packet: dict[str, Any]) -> list[str]:
    lines = [
        f"### {_line_text(packet.get('id'))} - {_line_text(packet.get('title'))}",
        "",
        f"- Type: `{_line_text(packet.get('type'))}`",
        f"- Risk level: `{_line_text(packet.get('risk_level'))}`",
        f"- Status: `{_line_text(packet.get('status'))}`",
        f"- Version target: `{_line_text(packet.get('version_target'))}`",
        f"- Summary: {_line_text(packet.get('summary'))}",
    ]
    lines.extend(_list_lines("Affected areas", packet.get("affected_areas")))
    lines.extend(_list_lines("Files touched", packet.get("files_touched")))
    lines.append("")
    return lines


def _section(title: str, packets: list[dict[str, Any]], level: int = 2) -> list[str]:
    prefix = "#" * level
    lines = [f"{prefix} {title}", ""]
    if not packets:
        lines.extend([f"No {title.lower()} changes.", ""])
        return lines

    for packet in sorted(packets, key=lambda item: _as_text(item.get("id"))):
        lines.extend(_entry(packet))
    return lines


def _released_groups() -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for path in _packet_paths(RELEASED_DIR, "**/*.json"):
        relative = path.relative_to(RELEASED_DIR)
        version = relative.parts[0] if len(relative.parts) > 1 else "unknown"
        groups.setdefault(version, []).append(_load_packet(path))
    return groups


def build_changelog() -> str:
    unreleased = [_load_packet(path) for path in _packet_paths(UNRELEASED_DIR, "*.json")]
    released = _released_groups()

    lines = [
        "# Change Log",
        "",
        "Generated by `scripts/change_control/build_changelog.py`. Do not hand-edit.",
        "",
    ]
    lines.extend(_section("Unreleased", unreleased))

    lines.extend(["## Released", ""])
    if not released:
        lines.extend(["No released changes.", ""])
    else:
        for version in sorted(released, key=_version_key, reverse=True):
            lines.extend(_section(version, released[version], level=3))

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    CHANGELOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CHANGELOG_PATH.write_text(build_changelog(), encoding="utf-8")
    relative_path = CHANGELOG_PATH.relative_to(REPO_ROOT).as_posix()
    print(f"Generated {relative_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
