from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
UNRELEASED_DIR = REPO_ROOT / "changes" / "unreleased"
RELEASED_DIR = REPO_ROOT / "changes" / "released"
INDEX_PATH = REPO_ROOT / "Docs" / "change_control" / "CHANGE_INDEX.md"


def _packet_paths(root: Path, pattern: str) -> list[Path]:
    if not root.exists():
        return []
    return sorted(path for path in root.glob(pattern) if path.is_file())


def _load_packet(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _as_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def _table_escape(value: Any) -> str:
    text = _as_text(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def _list_text(value: Any) -> str:
    if not isinstance(value, list) or not value:
        return "-"
    return "<br>".join(_table_escape(item) for item in value)


def _version_key(version: str) -> list[tuple[int, object]]:
    parts = re.split(r"(\d+)", version)
    key: list[tuple[int, object]] = []
    for part in parts:
        if not part:
            continue
        if part.isdigit():
            key.append((1, int(part)))
        else:
            key.append((0, part))
    return key


def _row(packet: dict[str, Any]) -> str:
    values = [
        _table_escape(packet.get("id", "")),
        _table_escape(packet.get("title", "")),
        _table_escape(packet.get("version_target", "")),
        _table_escape(packet.get("status", "")),
        _table_escape(packet.get("type", "")),
        _table_escape(packet.get("risk_level", "")),
        _list_text(packet.get("affected_areas")),
        _list_text(packet.get("files_touched")),
    ]
    return "| " + " | ".join(values) + " |"


def _section(title: str, packets: list[dict[str, Any]], level: int = 2) -> list[str]:
    prefix = "#" * level
    lines = [f"{prefix} {title}", ""]
    if not packets:
        lines.extend([f"No {title.lower()} change packets found.", ""])
        return lines

    lines.extend(
        [
            "| ID | Title | Version target | Status | Type | Risk | Affected areas | Files touched |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )
    for packet in sorted(packets, key=lambda item: _as_text(item.get("id"))):
        lines.append(_row(packet))
    lines.append("")
    return lines


def _read_group(root: Path, pattern: str) -> list[dict[str, Any]]:
    packets: list[dict[str, Any]] = []
    for path in _packet_paths(root, pattern):
        packets.append(_load_packet(path))
    return packets


def _released_groups() -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for path in _packet_paths(RELEASED_DIR, "**/*.json"):
        relative = path.relative_to(RELEASED_DIR)
        version = relative.parts[0] if len(relative.parts) > 1 else "unknown"
        groups.setdefault(version, []).append(_load_packet(path))
    return groups


def build_index() -> str:
    unreleased = _read_group(UNRELEASED_DIR, "*.json")
    released = _released_groups()

    lines = [
        "# Change Index",
        "",
        "Generated by `scripts/change_control/build_change_index.py`. Do not hand-edit.",
        "",
    ]
    lines.extend(_section("Unreleased", unreleased))
    lines.extend(["## Released", ""])
    if not released:
        lines.extend(["No released change packets found.", ""])
    else:
        for version in sorted(released, key=_version_key, reverse=True):
            lines.extend(_section(version, released[version], level=3))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(build_index(), encoding="utf-8")
    relative_path = INDEX_PATH.relative_to(REPO_ROOT).as_posix()
    print(f"Generated {relative_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
