from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
RELEASED_DIR = REPO_ROOT / "changes" / "released"
HISTORY_ROOT = REPO_ROOT / "release" / "history"
HISTORY_DOC = REPO_ROOT / "Docs" / "change_control" / "RELEASE_HISTORY.md"

RISK_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}


def _packet_paths(version_dir: Path) -> list[Path]:
    if not version_dir.exists():
        return []
    return sorted(path for path in version_dir.glob("*.json") if path.is_file())


def _load_packet(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _as_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def _version_key(version: str) -> list[tuple[int, object]]:
    parts = re.split(r"(\d+)", version)
    key: list[tuple[int, object]] = []
    for part in parts:
        if not part:
            continue
        if part.isdigit():
            key.append((1, int(part)))
        else:
            key.append((0, part))
    return key


def _dedupe_sorted(values: list[Any]) -> list[str]:
    return sorted({str(value) for value in values if str(value).strip()})


def _list_values(packets: list[dict[str, Any]], field: str) -> list[str]:
    values: list[Any] = []
    for packet in packets:
        field_value = packet.get(field)
        if isinstance(field_value, list):
            values.extend(field_value)
    return _dedupe_sorted(values)


def _highest_risk(packets: list[dict[str, Any]]) -> str:
    risks = [str(packet.get("risk_level", "")) for packet in packets]
    known = [risk for risk in risks if risk in RISK_ORDER]
    if not known:
        return "-"
    return max(known, key=lambda risk: RISK_ORDER[risk])


def _table_escape(value: Any) -> str:
    text = _as_text(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def _list_text(values: list[str]) -> str:
    return "<br>".join(_table_escape(value) for value in values) if values else "-"


def _release_rows() -> list[str]:
    rows: list[str] = []
    versions = []
    if RELEASED_DIR.exists():
        versions = sorted(
            [path.name for path in RELEASED_DIR.iterdir() if path.is_dir()],
            key=_version_key,
            reverse=True,
        )

    for version in versions:
        packets = [_load_packet(path) for path in _packet_paths(RELEASED_DIR / version)]
        change_ids = sorted(str(packet.get("id", "")) for packet in packets)
        archive_dir = HISTORY_ROOT / version
        archive_path = archive_dir.relative_to(REPO_ROOT).as_posix() if archive_dir.exists() else "-"
        values = [
            version,
            str(len(packets)),
            _list_text(change_ids),
            _list_text(_list_values(packets, "affected_areas")),
            _highest_risk(packets),
            archive_path,
        ]
        rows.append("| " + " | ".join(_table_escape(value) for value in values) + " |")
    return rows


def build_release_history() -> str:
    lines = [
        "# Release History",
        "",
        "Generated by `scripts/change_control/list_releases.py`. Do not hand-edit.",
        "",
    ]
    rows = _release_rows()
    if not rows:
        lines.extend(["No finalized releases found.", ""])
        return "\n".join(lines).rstrip() + "\n"

    lines.extend(
        [
            "| Version | Change count | Change IDs | Affected areas | Highest risk | Archive path |",
            "|---|---:|---|---|---|---|",
        ]
    )
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    HISTORY_DOC.parent.mkdir(parents=True, exist_ok=True)
    HISTORY_ROOT.mkdir(parents=True, exist_ok=True)
    HISTORY_DOC.write_text(build_release_history(), encoding="utf-8")
    relative_path = HISTORY_DOC.relative_to(REPO_ROOT).as_posix()
    print(f"Generated {relative_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
