from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class PowerShellHostServiceProtocol(Protocol):
    app_root: Path
    workspace_root: Path


class PathResolutionServiceProtocol(PowerShellHostServiceProtocol, Protocol):
    def default_audit_script_path(self) -> Path: ...
    def default_rerun_script_path(self) -> Path: ...
    def resolve_powershell_host(self) -> str | None: ...
    def load_config_data(self, config_path: Path, powershell_host: str | None) -> dict[str, Any]: ...
    def settings_store_metadata(self, config_path: Path) -> dict[str, Any]: ...
    def _first_existing(self, *paths: Path) -> Path: ...
    def _migrate_app_state_path(self, preferred_path: Path) -> None: ...
    def _path_or_none(self, value: Any) -> Path | None: ...
    def _state_root_for_local_base(self, local_base: Path) -> Path: ...
