from __future__ import annotations

from typing import Any


LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/queue/priority",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "level", "reason", "items", "clear_all"],
        "allowed_levels": ["high", "normal", "low", "hold"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_priority_manifest.v1",
        "purpose": "Write or clear non-destructive priority manifest entries only. Path/item writes must be absolute paths under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots); clear_all removes priority state only. This does not rename, move, delete, launch, or process media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/strategy",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["strategy"],
        "allowed_strategies": [
            "Standard",
            "FreshestFirst",
            "ShowComplete",
            "RoundRobin",
            "DeadlineAware",
            "SmallFirst",
            "LargeFirst",
            "ManualOrder",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_strategy_state.v1",
        "purpose": "Persist the backend queue ordering strategy for the next queue build without launching work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/scan",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["mode", "force", "scope", "reason"],
        "allowed_modes": ["inventory_then_curate", "inventory_only", "curate_only"],
        "allowed_scopes": ["all"],
        "safe_defaults": {"mode": "inventory_then_curate", "force": True, "scope": "all"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_queue_scan_command.v1",
        "purpose": "Start or observe a serialized backend-owned queue source scan. The fast inventory phase reads configured source roots (SourceMovies, SourceTV, and enabled LibraryProfiles source roots) and writes source-inventory evidence; the curation phase runs the existing queue-plan dry-run to write the authoritative queue snapshot. This does not process, rename, move, delete, publish, drain, or mutate source media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "audio", "subtitles", "routing", "video", "clear", "clear_all", "clear_fields"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Write per-file processing override state only for absolute paths under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), or clear the override manifest. Route/video fields are validated sparse metadata for later processing consumption. This does not process or mutate media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/route-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path", "proposed_override"],
        "response_schema": "queue_file_override_route_preview.v1",
        "purpose": "Preview route/remux/transcode impact for one path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots) using current queue snapshot route evidence. This does not write file_overrides.json, enqueue work, change queue strategy, process media, or mutate queue state.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path", "proposed_override"],
        "response_schema": "queue_file_override_series_preview.v1",
        "purpose": "Preview applying the current per-file override drawer fields to matching current TV queue rows under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Detection is backend-owned from the current queue snapshot and does not write file_overrides.json, create folder/show future policies, enqueue work, process media, or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-apply",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "proposed_override", "confirm_apply", "preview_fingerprint"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "After explicit confirmation and a matching preview fingerprint for a path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), write exact per-file overrides for eligible current TV queue rows in the detected series. Exact manual file overrides are protected, previous series batch overrides may be replaced, and no future folder/show rule is created. This does not process media or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/folder-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["folder_path", "proposed_override", "options"],
        "response_schema": "queue_file_override_folder_preview.v1",
        "purpose": "Preview the bounded impact of a folder-prefix audio/subtitle track override under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots) using known queue snapshot rows and cached track metadata only. This does not write file_overrides.json, scan source folders, run probes, enqueue work, change queue strategy, process media, or mutate queue state.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/folder-rule",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["folder_path", "override", "confirmation", "clear"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Save or clear a validated folder-prefix audio/subtitle track override under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Stream indexes and raw ffmpeg map fields are rejected, source/library roots are rejected, and save requires acknowledgement that future files may match and exact file overrides win. This does not process media or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/failures/clear",
        "auth_required": True,
        "effect": "failure-marker-write",
        "request_keys": ["scope", "marker_path", "marker_paths", "source_json", "dry_run", "confirm_clear"],
        "allowed_scopes": ["selected", "visible", "all_markers"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_marker_clear_result.v1",
        "purpose": "Preview or move backend-owned failure marker JSON files out of State\\Failures\\Markers after explicit confirmation. Paths are accepted only when they resolve inside the backend failure marker folder. This does not delete media, reports, completed manifests, pending publish state, or source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target", "row_scope"],
        "allowed_targets": ["source_file", "source_folder", "source_root"],
        "allowed_row_scopes": ["runnable", "excluded"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a path selected by the backend from a runnable or excluded queue snapshot row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/completed/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["play_output_file", "output_file", "output_folder", "sidecar", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open or play a path selected by the backend from a completed-jobs manifest row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/subtitle-qa/preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["id", "row_key", "path", "source_path", "output_path", "scope", "limit"],
        "response_schema": "subtitle_qa_preview.v1",
        "data_schema": "subtitle_qa_result.v1",
        "purpose": "Preview one already-loaded Queue or Completed row's backend-authored subtitle QA evidence without probing files, running OCR/conversion/sync tools, repairing, rerunning, rewriting sidecars, publishing, draining, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["play_local_file", "local_file", "manifest", "destination_folder", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open or play a path selected by the backend from the current pending-publish scan; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/recovery-plan",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pending_publish_recovery_plan.v1",
        "purpose": "Build a backend-authored dry-run recovery plan from the current pending-publish scan. This does not drain, repair, rewrite, move, delete, or publish files.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/promote-queue",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": ["confirm_promote", "row_keys"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Start the backend-owned queue-wide or selected-row final-library promotion run after explicit confirmation. It copies verified completed outputs from Outsource to configured final-library destinations and may delete only verified publish-output files when cleanup is enabled.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/pause",
        "auth_required": True,
        "effect": "control-state-write",
        "request_keys": ["run_id"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Request cooperative pause of the current final-library promotion run after the active item completes or fails.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/resume",
        "auth_required": True,
        "effect": "control-state-write",
        "request_keys": ["run_id"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Resume a paused backend-owned final-library promotion run using the current completed-output queue state.",
    },
)

LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/maintenance/release-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "keep_personal_config",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": False,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "keep_personal_config": False,
            "timeout_seconds": 900,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the existing release builder with -DryRun only. No release folder, zip, or manifest is written.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/release-build",
        "auth_required": True,
        "effect": "deployment-write",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "keep_personal_config",
            "force",
            "confirm_create",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": False,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "keep_personal_config": False,
            "force": False,
            "confirm_create": False,
            "timeout_seconds": 7200,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Create a deployable release package through the backend release builder after explicit confirmation and active-work checks. It may create a release folder, manifest, and zip outside the source bundle.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/completed-backfill-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["timeout_seconds"],
        "safe_defaults": {"timeout_seconds": 600},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the completed-jobs manifest backfill with -DryRun only. The completed manifest is not rewritten.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/dependency-atlas",
        "auth_required": True,
        "effect": "tooling-artifact-write",
        "request_keys": ["timeout_seconds", "min_overview_edge_count", "min_overview_files"],
        "safe_defaults": {
            "timeout_seconds": 600,
            "min_overview_edge_count": 4,
            "min_overview_files": 2,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Regenerate dependency-atlas HTML, PNG/SVG diagrams, and CSV exports under the repository-root docs/generated/dependency-atlas folder through the backend tooling runner. It does not touch media, queue, settings, manifests, or pipeline state.",
    },
)

LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/metrics/sources",
        "auth_required": True,
        "effect": "metrics-state-write",
        "request_keys": ["action", "path", "source_id", "label", "enabled"],
        "allowed_actions": ["add", "remove", "enable", "disable"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_metrics_sources.v1",
        "purpose": "Add, remove, enable, or disable backend-owned Metrics sidecar source roots. Paths are stored under State\\Metrics only; this does not scan folders, process media, rewrite sidecars, mutate queue state, launch work, or touch source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/metrics/backfill",
        "auth_required": True,
        "effect": "metrics-backfill-state-write",
        "request_keys": ["scope", "source_id", "path", "max_sidecars"],
        "allowed_scopes": ["enabled", "all"],
        "safe_defaults": {"scope": "enabled"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_metrics_backfill.v1",
        "purpose": "Recursively read *.pipeline.json sidecars under configured Metrics source roots and refresh the backend Metrics cache under State\\Metrics. The scanner skips symlinked folders, reads sidecar JSON only, and does not rewrite sidecars, process media, mutate queue state, launch work, drain, publish, rename, or touch source/output files.",
    },
)

LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/diagnostics/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["target"],
        "allowed_targets": [
            "run_logs",
            "cluster_log",
            "config",
            "config_folder",
            "workspace",
            "state",
            "pending_publish",
            "failed_reports",
            "failed_markers",
            "audit_reports",
            "queue_snapshot",
            "active_jobs",
            "completed_manifest",
            "latest_failure_report",
            "latest_failure_json",
            "latest_audit_csv",
            "latest_priority_csv",
            "last_stdout_log",
            "last_stderr_log",
            "sample_validation_log",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open backend-allowlisted diagnostics/log/config locations through the OS shell.",
    },
)

LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/rename/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["paths", "mode", "show_name", "season", "start_episode", "movie_title", "movie_year"],
        "response_schema": "desktop_rename_preview.v1",
        "purpose": "Generate rename predictions without applying filesystem changes.",
    },
    {
        "method": "POST",
        "path": "/api/rename/browse",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path"],
        "allowed_selection_modes": ["files", "folder", "folder_files"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open the native Windows file/folder browser and return operator-selected absolute paths for Rename staging. This does not preview, apply, rename, move, delete, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rename/apply",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": [
            "paths",
            "mode",
            "show_name",
            "season",
            "season_value",
            "start_episode",
            "start_episode_value",
            "movie_title",
            "movie_year",
            "remove_terms",
            "remove_terms_text",
            "movie_filter_options",
            "movie_filter_terms",
            "final_name_overrides",
            "rename_sidecars",
            "force_pipeline_name",
            "force_pipeline_name_overrides",
            "powershell_host",
            "use_pipeline_naming_preview",
            "template_preset",
            "selected_sources",
            "confirm_apply",
            "allow_outside_configured_roots",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Rebuild the rename plan in the backend and apply only explicitly selected source rows through the transactional rename service. Paths outside configured media roots require an additional outside-root confirmation.",
    },
)

LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/settings/validate",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["values"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Validate settings values without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/browse-path",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["setting_key", "selection_mode", "initial_path"],
        "allowed_setting_keys": [
            "SourceMovies",
            "SourceTV",
            "Outsource",
            "LocalBase",
            "FinalLibraryPromotionRuleSourceRoot",
            "FinalLibraryPromotionRuleDestinationRoot",
        ],
        "allowed_selection_modes": ["folder"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_path_browse.v1",
        "purpose": "Open the native Windows folder browser for allowlisted Settings path fields and return backend-validated folder evidence for WebView staging only. This does not save the PSD1, launch work, rewrite queue state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preview-patch",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["changes", "remove_keys", "library_profile_resets"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted config and return a redacted diff without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/pipeline-plan-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["source_media", "changes", "remove_keys"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pipeline_plan.v1",
        "purpose": "Validate strict SourceMediaInfo facts, merge optional staged Settings patch values in memory, and return a backend-owned dry-run PipelinePlan preview without probing paths, saving config, launching work, changing queue state, publishing, draining, renaming, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/save-patch",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["changes", "remove_keys", "library_profile_resets", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted config, validate, back up, atomically save the active PSD1, and reload backend resolved state.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-paths",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_path_validation.v1",
        "purpose": "Validate Settings Wizard source, output, and scratch paths without saving config, launching work, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-tools",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_tools.v1",
        "purpose": "Validate Settings Wizard FFmpeg/ffprobe tool path evidence without changing config or running media work.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/probe-hardware",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_hardware_probe.v1",
        "purpose": "Return conservative encoder probe evidence for wizard review without saving config, launching work, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-workers",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_worker_validation.v1",
        "purpose": "Validate Settings Wizard worker/concurrency choices without saving config or starting worker lifecycle controls.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard.v1",
        "purpose": "Generate a Settings Wizard patch and preview it through the normal backend settings patch validation path without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/save",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["wizard", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard.v1",
        "purpose": "Generate a Settings Wizard patch and save it through the normal backend settings patch writer with confirmation, backup, atomic PSD1 write, and reload.",
    },
    {
        "method": "POST",
        "path": "/api/settings/reload",
        "auth_required": True,
        "effect": "none",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Reload resolved paths and config data from the current PSD1 without writing config or starting pipeline work.",
    },
)

LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/schedule/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["enabled", "day_windows", "grid"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_patch_preview.v1",
        "purpose": "Validate and preview schedule/app-state changes without writing app state, starting work, or editing media state.",
    },
    {
        "method": "POST",
        "path": "/api/schedule/save",
        "auth_required": True,
        "effect": "app-state-write",
        "request_keys": ["enabled", "day_windows", "grid", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_save_result.v1",
        "purpose": "Atomically save schedule_enabled and schedule_grid to desktop app state through the backend service while preserving unrelated app-state keys. This does not launch work, bypass schedule gates, or mutate media files.",
    },
)

LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/sample-validation/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["schema", "shell", "source_path", "output_path", "sample_label", "sample_category", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Validate and normalize a proposed sample validation record without writing the validation log or changing media/pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/sample-validation/append",
        "auth_required": True,
        "effect": "validation-log-write",
        "request_keys": ["schema", "shell", "source_path", "output_path", "sample_label", "sample_category", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Append an operator evidence-only sample validation record under State\\Validation. This must not mark jobs complete, clear failures, drain pending publish, rewrite manifests/sidecars, launch work, or mutate media files.",
    },
)

LOCAL_API_UI_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/ui-preferences",
        "auth_required": True,
        "effect": "ui-state-write",
        "request_keys": ["storage", "source_surface"],
        "response_schema": "desktop_ui_preferences.v1",
        "purpose": "Persist allowlisted local WebView UI preferences such as layout, theme, evidence visibility, and tab choices so Chrome and the Tauri shell share the same operator customization. This does not save config, mutate queue state, launch work, drain, rename, publish, or touch media files.",
    },
)

LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/pipeline/control",
        "auth_required": True,
        "effect": "control-flag-write",
        "request_keys": ["action"],
        "allowed_actions": ["pause", "stop", "rescan", "kill"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Write backend-owned pause, stop, or rescan control flags, or force-kill related pipeline processes.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/browse-file",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path"],
        "allowed_selection_modes": ["files"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_pipeline_single_file_browse.v1",
        "purpose": "Open the native Windows file browser and return one operator-selected file for Launch single-file staging only. This does not save config, launch work, mutate queue state, rename, move, delete, publish, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["mode", "sleep_seconds", "show_config", "show_console", "single_file", "schedule_override"],
        "allowed_modes": ["once", "continuous", "validate", "drain_pending_pushes"],
        "allowed_schedule_overrides": ["", "run_once", "ignore"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing pipeline process through the Python service layer.",
    },
    {
        "method": "POST",
        "path": "/api/audit/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["library_root", "include_sidecars", "show_console"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing audit process through the Python service layer.",
    },
    {
        "method": "POST",
        "path": "/api/audit/score-policy",
        "auth_required": True,
        "effect": "audit-state-write",
        "request_keys": ["policy", "reset"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_score_policy_result.v2",
        "purpose": "Save or reset backend-owned audit score weights used by future audit report generation without changing queue, settings, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/audit/ignore",
        "auth_required": True,
        "effect": "audit-state-write",
        "request_keys": ["action", "row_keys", "paths", "reason", "priority_only", "limit"],
        "allowed_actions": ["add", "remove"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_ignore_result.v1",
        "purpose": "Save or remove audit-only ignored file entries without queue holds, file overrides, settings saves, or media mutation.",
    },
    {
        "method": "POST",
        "path": "/api/audit/export-rerun-csv",
        "auth_required": True,
        "effect": "report-file-write",
        "request_keys": ["row_keys", "priority_only", "limit"],
        "safe_defaults": {"stage_mode": "copy", "original_mode": "keep", "return_mode": "park"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_rerun_export.v1",
        "purpose": "Write a backend-owned rerun CSV from selected or loaded non-ignored audit rows using copy/keep/park defaults without launching rerun work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["csv_path", "dry_run", "stage_mode", "original_mode", "return_mode", "show_console"],
        "safe_defaults": {"dry_run": False, "stage_mode": "copy", "original_mode": "keep", "return_mode": "park"},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing CSV rerun process with conservative media-safe defaults.",
    },
    {
        "method": "POST",
        "path": "/api/backend/shutdown",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "request_keys": ["reason", "force_active_work_shutdown"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Request graceful shutdown of the local API backend owned by the desktop shell; unsafe close-readiness is rejected unless explicit boolean true force cleanup is requested.",
    },
)


LOCAL_API_COMMAND_ROUTE_CONTRACT = (
    LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_UI_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT
)


__all__ = [
    "LOCAL_API_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_UI_COMMAND_ROUTE_CONTRACT",
]
