from __future__ import annotations

from typing import Any

LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/maintenance/release-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "include_tauri_preview_binary",
            "keep_personal_config",
            "force",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": True,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "include_tauri_preview_binary": False,
            "keep_personal_config": False,
            "force": False,
            "timeout_seconds": 900,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the existing release builder with -DryRun only. No release folder, zip, or manifest is written.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/release-build",
        "auth_required": True,
        "effect": "deployment-write",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "include_tauri_preview_binary",
            "keep_personal_config",
            "force",
            "confirm_create",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": True,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "include_tauri_preview_binary": False,
            "keep_personal_config": False,
            "force": False,
            "confirm_create": False,
            "timeout_seconds": 7200,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Create a deployable release package through the backend release builder after explicit confirmation and active-work checks. It may create a release folder, manifest, and zip outside the source bundle.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/completed-backfill-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["timeout_seconds"],
        "safe_defaults": {"timeout_seconds": 600},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the completed-jobs manifest backfill with -DryRun only. The completed manifest is not rewritten.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/retention-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["limit", "reason"],
        "safe_defaults": {"limit": 200},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_retention_dry_run.v1",
        "candidate_command": "maintenance.retention_cleanup",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-owned dry-run retention report for logs, JSONL/state files, temp/scratch orphans, failure reports, and cache artifacts under allowlisted runtime roots. This does not delete, move, archive, truncate, rewrite, drain, publish, or touch source/output/pending-publish media files.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/archive-state-journals",
        "auth_required": True,
        "effect": "runtime-evidence-archive",
        "request_keys": ["confirm_archive", "reason"],
        "safe_defaults": {"confirm_archive": False},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_state_journal_archive.v1",
        "owner": "Maintenance / Diagnostics",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "After explicit confirmation and safe close-readiness, archive only the backend-resolved State\\Progress\\pipeline_events.jsonl runtime event journal when oversized, then create a fresh empty replacement. This does not archive completed manifests, queue snapshots, progress files, pending-publish manifests/payloads, source media, scratch media, or final outputs.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/dependency-atlas",
        "auth_required": True,
        "effect": "tooling-artifact-write",
        "request_keys": ["timeout_seconds", "min_overview_edge_count", "min_overview_files"],
        "safe_defaults": {
            "timeout_seconds": 600,
            "min_overview_edge_count": 4,
            "min_overview_files": 2,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Regenerate dependency-atlas HTML, PNG/SVG diagrams, and CSV exports under the repository-root docs/generated/dependency-atlas folder through the backend tooling runner. It does not touch media, queue, settings, manifests, or pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/dependency-atlas/open-folder",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": [],
        "allowed_targets": ["dependency_atlas_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open the backend-resolved repository-root docs/generated/dependency-atlas folder through the OS shell. The frontend does not submit arbitrary paths, and this does not touch media, queue, settings, manifests, or pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/support-export",
        "auth_required": True,
        "effect": "diagnostics-artifact-write",
        "request_keys": ["reason", "include_recent_logs", "max_log_bytes"],
        "safe_defaults": {"include_recent_logs": True, "max_log_bytes": 131072},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_support_export.v1",
        "purpose": "Write a backend-owned redacted support export under per-user AppData DiagnosticsExports. It includes product/version/update/migration/health evidence and bounded redacted log tails without full private config, signing material, bearer tokens, unredacted personal paths, or media file mutation.",
    },
)

LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/metrics/sources",
        "auth_required": True,
        "effect": "metrics-state-write",
        "request_keys": ["action", "path", "source_id", "label", "enabled"],
        "allowed_actions": ["add", "remove", "enable", "disable"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_metrics_sources.v1",
        "purpose": "Add, remove, enable, or disable backend-owned Metrics sidecar source roots. Paths are stored under State\\Metrics only; this does not scan folders, process media, rewrite sidecars, mutate queue state, launch work, or touch source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/metrics/backfill",
        "auth_required": True,
        "effect": "metrics-backfill-state-write",
        "request_keys": ["scope", "source_id", "path", "max_sidecars"],
        "allowed_scopes": ["enabled", "all"],
        "safe_defaults": {"scope": "enabled"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_metrics_backfill.v1",
        "purpose": "Recursively read *.pipeline.json sidecars under configured Metrics source roots and refresh the backend Metrics cache under State\\Metrics. The scanner skips symlinked folders, reads sidecar JSON only, and does not rewrite sidecars, process media, mutate queue state, launch work, drain, publish, rename, or touch source/output files.",
    },
)

LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/diagnostics/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["target"],
        "allowed_targets": [
            "run_logs",
            "pipeline_log",
            "cluster_log",
            "config",
            "config_folder",
            "workspace",
            "state",
            "pending_publish",
            "failed_reports",
            "failed_markers",
            "audit_reports",
            "queue_snapshot",
            "active_jobs",
            "completed_manifest",
            "latest_failure_report",
            "latest_failure_json",
            "latest_audit_csv",
            "latest_priority_csv",
            "last_stdout_log",
            "last_stderr_log",
            "sample_validation_log",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open backend-allowlisted diagnostics/log/config locations through the OS shell.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/encoder-capabilities/refresh",
        "auth_required": True,
        "effect": "diagnostics-artifact-write",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "mediapipeline.encoder_capabilities.v1",
        "purpose": "Regenerate the bounded backend-owned encoder capability diagnostic artifact and record command evidence. This does not launch media processing, reserve the pipeline lock, change settings, or mutate source, scratch, output, pending-publish, or final-library media.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/tdarr-matrix-audit",
        "auth_required": True,
        "effect": "diagnostic-process",
        "request_keys": ["action", "confirm_delete_full_matrix"],
        "allowed_actions": [
            "prepare-proof-pack",
            "report",
            "smoke-pack",
            "proof-pack",
            "strict-report",
            "cleanup-plan",
            "cleanup-archive",
            "cleanup-delete",
        ],
        "safe_defaults": {"action": "report", "confirm_delete_full_matrix": False},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_tdarr_matrix_audit_result.v1",
        "purpose": "Run backend-owned Tdarr Proof Pack diagnostics through ops/scripts/dev/run-python-tool.py. Presets use backend-approved proof-pack library roots and isolated proof run roots; legacy full-matrix cleanup is backend-owned and requires proof verification plus archive evidence. The frontend cannot submit paths, command arguments, or live operator config.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/tdarr-matrix/evidence/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["run_id", "finding_key", "target"],
        "allowed_targets": ["stdout", "stderr", "worker_result", "source_hashes", "failure_artifact", "output", "report_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a backend-resolved evidence artifact for a selected Tdarr Proof Pack finding. The frontend sends only a run ID, finding key, and allowlisted target name; arbitrary paths are rejected.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/tdarr-matrix/rerun",
        "auth_required": True,
        "effect": "diagnostic-process",
        "request_keys": ["source_run_id", "selection", "finding_keys"],
        "allowed_selections": ["selected", "latest_failures"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_tdarr_matrix_audit_result.v1",
        "purpose": "Rerun selected Tdarr Proof Pack cases, or latest failure cases, into a fresh isolated Proof Pack run root. The backend maps finding keys to manifest case IDs and the frontend cannot submit paths or command arguments.",
    },
)

LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/rename/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["paths", "mode", "show_name", "season", "start_episode", "movie_title", "movie_year"],
        "response_schema": "desktop_rename_preview.v1",
        "optional_response_fields": ["input_counts"],
        "purpose": "Generate media-only rename predictions without applying filesystem changes; sidecar inputs are counted as ignored and attached to media rows automatically.",
    },
    {
        "method": "POST",
        "path": "/api/rename/browse",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path", "paths"],
        "allowed_selection_modes": ["files", "folder", "folder_files"],
        "response_schema": "desktop_command_result.v1",
        "optional_data_fields": ["raw_path_count", "ignored_path_count", "ignored_sidecar_count"],
        "purpose": "Open the native Windows file/folder browser, or resolve already-known dropped paths, and return absolute media paths for Rename staging. Folder-file selection filters sidecars/non-media paths and reports ignored counts. This does not preview, apply, rename, move, delete, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rename/filter-cases",
        "auth_required": True,
        "effect": "test-fixture-write",
        "request_keys": [
            "case_id",
            "kind",
            "source_folder",
            "source_file",
            "expected_name",
            "expected_show",
            "expected_clean_folder",
            "expected_season",
            "expected_episode",
            "expected_episode_title",
            "expected_movie_title",
            "expected_year",
            "season_number",
            "template_preset",
            "status",
            "notes",
            "confirm_append",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "rename_bad_case_corpus_append.v1",
        "purpose": "Append a backend-validated bad rename regression case to tests/fixtures/rename/bad_rename_cases.jsonl after explicit confirmation. Supports tv_auto and movie_auto case payloads. This route writes only the test corpus and never previews, applies, renames, moves, deletes, or touches media files.",
    },
    {
        "method": "POST",
        "path": "/api/rename/apply",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": [
            "paths",
            "mode",
            "show_name",
            "season",
            "season_value",
            "start_episode",
            "start_episode_value",
            "movie_title",
            "movie_year",
            "remove_terms",
            "remove_terms_text",
            "movie_filter_options",
            "movie_filter_terms",
            "final_name_overrides",
            "rename_sidecars",
            "force_pipeline_name",
            "force_pipeline_name_overrides",
            "powershell_host",
            "use_pipeline_naming_preview",
            "template_preset",
            "selected_sources",
            "confirm_apply",
            "allow_outside_configured_roots",
            "preview_fingerprint",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Rebuild the rename plan in the backend, require the current plan/freshness fingerprint to match the operator-reviewed preview, and apply only explicitly selected source rows through the transactional rename service. Paths outside configured media roots require an additional outside-root confirmation.",
    },
    {
        "method": "POST",
        "path": "/api/rename/undo",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": ["undo_manifest", "confirm_undo"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rename_undo_result.v1",
        "purpose": "Undo the last backend rename apply from a backend-owned RenameUndo manifest after explicit confirmation. The backend validates the manifest under its resolved undo root and reverses media/sidecar operations; the frontend cannot rename files directly.",
    },
)

__all__ = (
    "LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT",
)
