from __future__ import annotations

from typing import Any

LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/settings/validate",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["values"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Validate settings values without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/validate",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_validation.v1",
        "purpose": "Validate an inline PresetV2 document without writing the preset library, active PSD1 config, queue state, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/compare",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["left_id", "right_id", "left_preset_v2", "right_preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_compare.v1",
        "purpose": "Compare preset records or inline PresetV2 documents through backend PresetV2-to-legacy patch projection without writing state or config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/import-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["records"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_import_preview.v1",
        "purpose": "Validate preset import candidate records and report the State JSON target without writing the preset library or active config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/save",
        "auth_required": True,
        "effect": "preset-library-state-write",
        "request_keys": ["id", "name", "description", "tags", "source", "imported_from", "preset_v2", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library.v1",
        "purpose": "Save a PresetV2 record to backend State JSON at State/PresetLibrary/presets.json only. This does not save active PSD1 settings, launch work, mutate queue state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/export",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["id", "preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library.v1",
        "purpose": "Return a backend preset library record or inline PresetV2 export payload without writing state, active config, queue state, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/apply-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["id", "preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_apply_preview.v1",
        "purpose": "Convert a PresetV2 record or inline PresetV2 payload to a legacy settings patch and run existing backend settings preview semantics without saving config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/apply",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["id", "preset_v2", "confirm_apply"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_save_reload_progress.v1",
        "purpose": "After explicit confirmation, convert a PresetV2 record or inline PresetV2 payload to a legacy settings patch and save through the existing backend settings save path. Applies to future launches only.",
    },
    {
        "method": "POST",
        "path": "/api/settings/browse-path",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["setting_key", "selection_mode", "initial_path"],
        "allowed_setting_keys": [
            "SourceMovies",
            "SourceTV",
            "Outsource",
            "LocalBase",
            "FinalLibraryPromotionRuleSourceRoot",
            "FinalLibraryPromotionRuleDestinationRoot",
        ],
        "allowed_selection_modes": ["folder"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_path_browse.v1",
        "purpose": "Open the native Windows folder browser for allowlisted Settings path fields and return backend-validated folder evidence for WebView staging only. This does not save the PSD1, launch work, rewrite queue state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preview-patch",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["changes", "remove_keys", "library_profile_resets"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted config and return a redacted diff without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/pipeline-plan-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["source_media", "changes", "remove_keys"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pipeline_plan.v1",
        "purpose": "Validate strict SourceMediaInfo facts, merge optional staged Settings patch values in memory, and return a backend-owned dry-run PipelinePlan preview without probing paths, saving config, launching work, changing queue state, publishing, draining, renaming, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/save-patch",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["changes", "remove_keys", "library_profile_resets", "review_confirmation", "confirm_save"],
        "required_request_keys": ["confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted JSON-authoritative config, validate, back up, atomically save the JSON settings store plus active PSD1 projection, and reload backend resolved state.",
    },
    {
        "method": "POST",
        "path": "/api/settings/import-psd1-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_import_psd1_preview.v1",
        "purpose": "Preview importing the active resolved PSD1 into the JSON settings authority. This reports migrations, legacy extras, and blocking errors without writing the JSON store or PSD1 projection.",
    },
    {
        "method": "POST",
        "path": "/api/settings/import-psd1",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["confirm_import"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_import_psd1_result.v1",
        "purpose": "After explicit confirmation, import the active resolved PSD1 into the JSON settings authority, preserve unknown legacy extras as inert projection-only values, regenerate the PSD1 projection, and reload backend resolved state.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-paths",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_path_validation.v1",
        "purpose": "Validate Settings Wizard source, output, and scratch paths without saving config, launching work, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-tools",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_tools.v1",
        "purpose": "Validate Settings Wizard FFmpeg/ffprobe tool path evidence without changing config or running media work.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/probe-hardware",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_hardware_probe.v1",
        "purpose": "Return conservative encoder probe evidence for wizard review without saving config, launching work, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-workers",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_worker_validation.v1",
        "purpose": "Validate Settings Wizard worker/concurrency choices without saving config or starting worker lifecycle controls.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard.v1",
        "purpose": "Generate a Settings Wizard patch and preview it through the normal backend settings patch validation path without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/save",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["wizard", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard.v1",
        "purpose": "Generate a Settings Wizard patch and save it through the normal backend settings patch writer with confirmation, backup, atomic PSD1 write, and reload.",
    },
    {
        "method": "POST",
        "path": "/api/settings/reload",
        "auth_required": True,
        "effect": "none",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Reload resolved paths and config data from the current PSD1 without writing config or starting pipeline work.",
    },
)

LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/schedule/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["enabled", "day_windows", "grid"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_patch_preview.v1",
        "purpose": "Validate and preview schedule/app-state changes without writing app state, starting work, or editing media state.",
    },
    {
        "method": "POST",
        "path": "/api/schedule/save",
        "auth_required": True,
        "effect": "app-state-write",
        "request_keys": ["enabled", "day_windows", "grid", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_save_result.v1",
        "purpose": "Atomically save schedule_enabled and schedule_grid to desktop app state through the backend service while preserving unrelated app-state keys. This does not launch work, bypass schedule gates, or mutate media files.",
    },
)

LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/sample-validation/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["schema", "shell", "source_path", "output_path", "sample_label", "sample_category", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Validate and normalize a proposed sample validation record without writing the validation log or changing media/pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/sample-validation/append",
        "auth_required": True,
        "effect": "validation-log-write",
        "request_keys": ["schema", "shell", "source_path", "output_path", "sample_label", "sample_category", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Append an operator evidence-only sample validation record under State\\Validation. This must not mark jobs complete, clear failures, drain pending publish, rewrite manifests/sidecars, launch work, or mutate media files.",
    },
)

LOCAL_API_UI_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/ui-preferences",
        "auth_required": True,
        "effect": "ui-state-write",
        "request_keys": ["storage", "source_surface"],
        "response_schema": "desktop_ui_preferences.v1",
        "purpose": "Persist allowlisted local WebView UI preferences such as layout, theme, evidence visibility, and tab choices so Chrome and the Tauri shell share the same operator customization. This does not save config, mutate queue state, launch work, drain, rename, publish, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/path-picker/browse",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["target_key", "selection_mode", "initial_path", "file_filter"],
        "allowed_selection_modes": ["files", "folder", "folder_files"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_path_picker_browse.v1",
        "purpose": "Open a backend-owned native Windows picker for allowlisted operator path fields and return staged-only validation evidence. This does not save config, launch work, scan folders, mutate queue state, rename, move, delete, publish, drain, or touch media files.",
    },
)

__all__ = (
    "LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_UI_COMMAND_ROUTE_CONTRACT",
)
