from __future__ import annotations

from typing import Any

LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/network/coordinator/start-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "coordinator", "action": "start", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned coordinator start preconditions, lifecycle state, state-file posture, active-work evidence, and would_not_touch guarantees without starting a dispatcher, scanning queue records, or touching media/state files.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/stop-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "coordinator", "action": "stop", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned coordinator stop preconditions, active claim posture, state-file preservation evidence, and would_not_touch guarantees without stopping a dispatcher or releasing claims.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/start-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "worker", "action": "start", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned worker start preconditions, coordinator URL/token/path-map posture, pending done report state, and would_not_touch guarantees without polling, claiming, scanning, or launching work.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/stop-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "worker", "action": "stop", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned worker stop preconditions, pending done report posture, worker_state preservation evidence, and would_not_touch guarantees without aborting active work or deleting scratch files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/test-connection",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "request_keys": ["timeout_seconds"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_worker_test_connection.v1",
        "purpose": "Run a backend-owned read-only worker connection preflight for coordinator TCP reachability, signed auth ping, and configured worker library source/output path accessibility. This does not claim work, start or stop lifecycle, save settings, launch processing, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/discover-coordinators",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "request_keys": ["timeout_seconds"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_coordinator_discovery.v1",
        "purpose": "Run backend-owned mDNS coordinator discovery and return selectable coordinator base URLs for worker setup. The route is unjournaled and read-only; selecting a result only fills the worker URL controls until the operator saves settings, and it does not claim work, start or stop lifecycle, save settings, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/join-blob",
        "auth_required": True,
        "effect": "secret-transfer",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": False,
        "request_keys": ["coordinator_url", "confirm_create", "rotate_token", "confirm_rotate"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_join_blob_result.v1",
        "purpose": "Create a coordinator setup blob containing coordinator URL, worker auth token, and advertised library roots for transfer to a worker. The response is intentionally unjournaled because the blob contains a secret; this does not start or stop lifecycle, claim work, launch processing, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/join-cluster",
        "auth_required": True,
        "effect": "config-write",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": False,
        "request_keys": ["join_blob", "confirm_import", "timeout_seconds"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_join_import_result.v1",
        "purpose": "Import a coordinator join blob on a worker, save WorkerCoordinatorUrl, WorkerAuthToken, NetworkRole, and any library-ID-derived WorkerSourcePathMap entries through the backend settings save path, then run the existing read-only worker test-connection. The command response is unjournaled because the request contains a secret; it does not claim work, start or stop lifecycle, launch processing, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/start",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "coordinator", "action": "start", "dry_run": False},
        "request_keys": ["confirm_start", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, start the real coordinator lifecycle provider only. It must not process local files unless CoordinatorAlsoEncodeLocally is enabled and must not touch source/scratch/output/queue/pending-publish media state as part of lifecycle start.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/stop",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "coordinator", "action": "stop", "dry_run": False},
        "request_keys": ["confirm_stop", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, stop the coordinator lifecycle provider while preserving coordinator_inflight.json, worker_state.json, and cluster.log. It must not silently release active claims or mutate media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/start",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "worker", "action": "start", "dry_run": False},
        "request_keys": ["confirm_start", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, start the real worker polling lifecycle provider only. It claims coordinator-assigned work one file at a time and must not scan the local queue or launch normal pipeline start.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/stop",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "worker", "action": "stop", "dry_run": False},
        "request_keys": ["confirm_stop", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, request worker lifecycle stop while preserving pending done reports and worker_state.json. Abort/partial scratch cleanup remains a separate explicit command.",
    },
)

__all__ = (
    "LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT",
)
