from __future__ import annotations

from collections.abc import Mapping, Sequence
from copy import deepcopy
from typing import Any

from .contract import LOCAL_API_ROUTE_CONTRACT
from .contract_shared import LOCAL_API_CONTRACT_SCHEMA_VERSION


LOCAL_API_AUTH_SCHEME = "bearer-or-x-mediapipeline-token"
LOCAL_API_CONTRACT_NOTES = [
    "Health is public so a shell can wait for backend readiness.",
    "All media-affecting or process-affecting commands require the per-run token.",
    "Tokens are accepted only through Authorization: Bearer or X-MediaPipeline-Token headers, not URL query parameters.",
    "The frontend must treat process, control, validation, repair/reconcile write, and config-write effects as operator-confirmed actions.",
]

NETWORK_LIFECYCLE_DRY_RUN_REQUIRED_FIELDS = [
    "schema_version",
    "candidate_command",
    "dry_run_only",
    "role",
    "requested_action",
    "lifecycle_state",
    "precondition_results",
    "would_start_processes",
    "would_stop_processes",
    "dry_run_writes",
    "confirmed_route_would_write",
    "would_not_touch",
    "safe_to_apply",
    "operator_confirmation_scope",
]

NETWORK_LIFECYCLE_SOURCE_FILE_POLICY = {
    "source_media_mutation": "forbidden",
    "source_delete": "forbidden",
    "source_rename": "forbidden",
    "source_path_authority": "backend_resolved_from_config_and_state_only",
}

NETWORK_LIFECYCLE_ROUTE_EXPOSURE_GATES = [
    "document dry-run and mutation routes in API_ROUTE_INVENTORY.md and LOCAL_API_ROUTE_CONTRACT",
    "prove every dry-run route has effect=none and returns dry_run_only=true",
    "add backend precondition tests for role, token, bind address, active work, pending done reports, and duplicate lifecycle commands",
    "add mutation routes only after process cleanup, state reconciliation, command journaling, and close-readiness tests pass",
    "add WebView controls only after command-result evidence, browser no-mutation coverage, and DOC_TOUCH_LOG updates exist",
]

NETWORK_LIFECYCLE_CONTRACTS = [
    {
        "key": "coordinator_start",
        "surface": "Coordinator API start",
        "candidate_command": "network.coordinator.start",
        "owner": "Network / backend dispatcher",
        "current_status": "backend_route_available_provider_guarded",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "network-lifecycle-start",
        "required_preconditions": [
            "NetworkRole_is_coordinator",
            "backend_close_readiness_safe",
            "no_existing_coordinator_dispatcher",
            "bind_address_and_port_valid",
            "coordinator_auth_token_available_or_backend_generates_and_persists_it",
            "active_jobs_registry_reconciled",
        ],
        "required_evidence": [
            "role_config_snapshot",
            "bind_address",
            "port",
            "auth_token_redacted_state",
            "dispatcher_state_before_after",
            "command_id",
        ],
        "rollback_requirements": [
            "shutdown partially-created dispatcher on bind failure",
            "preserve previous standalone dispatcher state when coordinator start fails",
            "journal start attempt and cleanup result",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_network_lifecycle_dry_run.v1",
            "required_result_fields": NETWORK_LIFECYCLE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "role, bind address, port, and redacted token readiness",
                "whether an existing dispatcher or active work blocks start",
                "would_not_touch source media, scratch media, output media, queue manifests, and pending publish payloads",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "journal_required": True,
            "rollback_on": [
                "bind failure",
                "dispatcher construction failure",
                "post-start health failure",
                "command journal write failure before success is reported",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "role",
                "bind_address",
                "port",
                "dispatcher_state_before",
                "dispatcher_state_after",
                "rollback_status",
            ],
        },
        "source_file_policy": NETWORK_LIFECYCLE_SOURCE_FILE_POLICY,
        "route_exposure_gates": NETWORK_LIFECYCLE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "start coordinator while close-readiness reports active unsafe work",
            "expose or echo auth tokens in WebView",
            "mutate queue, completed, pending publish, scratch, output, or source files",
            "trust frontend-only confirmation logic inside the Local API route",
        ],
        "safe_next_step": "Use the backend dry-run route first; confirmed start is backend-owned and blocked if the coordinator lifecycle provider hook is unavailable or preconditions fail.",
    },
    {
        "key": "coordinator_stop",
        "surface": "Coordinator API stop",
        "candidate_command": "network.coordinator.stop",
        "owner": "Network / backend dispatcher",
        "current_status": "backend_route_available_provider_guarded",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "network-lifecycle-stop",
        "required_preconditions": [
            "coordinator_dispatcher_active",
            "backend_close_readiness_safe_or_explicit_active_work_confirmation",
            "active_worker_claims_reported",
            "local_encode_state_reported",
            "pending_done_reports_reported",
            "operator_confirmed_exact_scope",
        ],
        "required_evidence": [
            "dispatcher_state_before_after",
            "active_worker_count",
            "local_encode_state",
            "pending_done_report_count",
            "cluster_log_tail_reference",
            "command_id",
        ],
        "rollback_requirements": [
            "do not mark stopped until dispatcher shutdown returns or times out",
            "record active claims that workers must reclaim after heartbeat timeout",
            "preserve state files for diagnostics and recovery",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_network_lifecycle_dry_run.v1",
            "required_result_fields": NETWORK_LIFECYCLE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "active worker claims, local encode state, and pending done report posture",
                "whether stop is blocked, review-only, or safe to apply",
                "would_not_touch source media, scratch media, output media, queue manifests, and pending publish payloads",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "journal_required": True,
            "rollback_on": [
                "dispatcher shutdown failure",
                "state preservation failure",
                "post-stop state mismatch",
                "command journal write failure before success is reported",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "role",
                "active_worker_count",
                "pending_done_report_count",
                "dispatcher_state_before",
                "dispatcher_state_after",
                "rollback_status",
            ],
        },
        "source_file_policy": NETWORK_LIFECYCLE_SOURCE_FILE_POLICY,
        "route_exposure_gates": NETWORK_LIFECYCLE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "silently abandon active local encode work",
            "delete coordinator in-flight or cluster-log state during stop",
            "force-release worker claims without a separate reclaim contract",
            "mutate media files or publish state as part of lifecycle stop",
        ],
        "safe_next_step": "Use the backend dry-run route first; confirmed stop is backend-owned and blocked if the coordinator lifecycle provider hook is unavailable or preconditions fail.",
    },
    {
        "key": "worker_polling_start_stop",
        "surface": "Worker polling start/stop",
        "candidate_command": "network.worker.polling_lifecycle",
        "owner": "Network / backend dispatcher",
        "current_status": "backend_route_available_provider_guarded",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "network-worker-process-lifecycle",
        "required_preconditions": [
            "NetworkRole_is_worker",
            "coordinator_url_valid",
            "worker_auth_token_present",
            "source_path_map_validated_by_backend",
            "no_duplicate_worker_polling_loop",
            "active_or_pending_done_work_reported_before_stop",
        ],
        "required_evidence": [
            "worker_identity",
            "coordinator_url",
            "path_map_summary",
            "worker_state_before_after",
            "pending_done_report_state",
            "command_id",
        ],
        "rollback_requirements": [
            "stop partially-started polling thread on setup failure",
            "leave worker_state.json intact for pending done reports",
            "journal polling start/stop result and cleanup state",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_network_lifecycle_dry_run.v1",
            "required_result_fields": NETWORK_LIFECYCLE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "worker identity, coordinator URL, token presence, and path-map validity",
                "whether a polling loop is already active or a pending done report blocks stop",
                "would_not_touch source media, scratch media, output media, queue manifests, and pending publish payloads",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "journal_required": True,
            "rollback_on": [
                "polling thread start failure",
                "coordinator probe failure after start",
                "worker state preservation failure",
                "command journal write failure before success is reported",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "worker_identity",
                "coordinator_url_redacted",
                "worker_state_before",
                "worker_state_after",
                "rollback_status",
            ],
        },
        "source_file_policy": NETWORK_LIFECYCLE_SOURCE_FILE_POLICY,
        "route_exposure_gates": NETWORK_LIFECYCLE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "start duplicate polling loops",
            "discard pending done reports",
            "trust frontend-provided filesystem paths for source mapping",
            "launch encode/remux work from WebView-only logic",
        ],
        "safe_next_step": "Use the backend dry-run routes first; confirmed worker start/stop are backend-owned and blocked if the worker lifecycle provider hook is unavailable or preconditions fail.",
    },
]

REPAIR_RECONCILE_DRY_RUN_REQUIRED_FIELDS = [
    "schema_version",
    "candidate_command",
    "dry_run_only",
    "effect",
    "scope",
    "selected_row_keys",
    "precondition_results",
    "diff_summary",
    "would_write_paths",
    "would_move_paths",
    "would_delete_paths",
    "would_not_touch",
    "safe_to_apply",
    "mutation_route_available",
    "apply_route_available",
    "dry_run_fingerprint",
    "operator_confirmation_scope",
    "suppress_command_journal",
]

STARTUP_RECONCILIATION_DRY_RUN_REQUIRED_FIELDS = [
    "schema_version",
    "candidate_command",
    "dry_run_only",
    "effect",
    "scope",
    "precondition_results",
    "categories",
    "overall_status",
    "diff_summary",
    "would_write_paths",
    "would_move_paths",
    "would_delete_paths",
    "would_not_touch",
    "safe_to_apply",
    "mutation_route_available",
    "startup_repair_available",
    "apply_route_available",
    "operator_confirmation_scope",
    "suppress_command_journal",
]

REPAIR_RECONCILE_APPLY_REQUIRED_FIELDS = [
    "schema_version",
    "candidate_command",
    "effect",
    "selected_row_keys",
    "applied",
    "blocked",
    "written_paths",
    "backup_paths",
    "transaction_id",
    "rollback_status",
    "dry_run_fingerprint",
    "expected_dry_run_fingerprint",
    "source_payload_output_unchanged",
]

REPAIR_RECONCILE_SOURCE_FILE_POLICY = {
    "source_media_mutation": "forbidden",
    "source_delete": "forbidden",
    "source_rename": "forbidden",
    "source_path_authority": "backend_resolved_from_state_only",
}

REPAIR_RECONCILE_ROUTE_EXPOSURE_GATES = [
    "document dry-run and confirmed apply routes in API_ROUTE_INVENTORY.md and LOCAL_API_ROUTE_CONTRACT",
    "prove dry-run route has effect=none and returns dry_run_only=true",
    "prove confirmed apply route reruns dry-run and requires matching dry_run_fingerprint plus explicit confirmation",
    "add backend precondition tests for idle pipeline, exact scope, and allowlisted paths",
    "prove backups, rollback status, source-file immutability, and command-result evidence before operator exposure",
    "add WebView control only after command-result evidence and DOC_TOUCH_LOG updates exist",
]

REPAIR_RECONCILE_CONTRACTS = [
    {
        "key": "completed_manifest_reconcile",
        "surface": "Completed manifest reconciliation",
        "candidate_command": "completed.reconcile_manifest",
        "owner": "Completed / Maintenance",
        "current_status": "backend_dry_run_and_confirmed_apply_routes_available",
        "dry_run_route": "/api/completed/reconcile-manifest-dry-run",
        "apply_route": "/api/completed/reconcile-manifest",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "manifest-write",
        "required_preconditions": [
            "pipeline_idle",
            "completed_manifest_readable",
            "source_sidecars_readable",
            "dry_run_diff_reviewed",
            "operator_confirmed_exact_scope",
        ],
        "required_evidence": [
            "before_manifest_digest",
            "after_manifest_digest",
            "sidecar_sample_count",
            "rows_added_updated_removed",
            "atomic_write_path",
            "backup_path",
        ],
        "rollback_requirements": [
            "write backup before replacement",
            "write temp manifest before replace",
            "record command journal entry with backup path and manifest digest",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_repair_reconcile_dry_run.v1",
            "required_result_fields": REPAIR_RECONCILE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "completed manifest path and digest before write",
                "row additions, updates, removals, and unchanged rows",
                "sidecar/output evidence used for every row change",
                "would_not_touch source media, scratch media, pending payloads, and output media",
            ],
        },
        "apply_contract": {
            "effect": "completed-manifest-write",
            "result_schema": "desktop_repair_reconcile_apply.v1",
            "required_request_fields": [
                "scope",
                "row_key",
                "limit",
                "reason",
                "dry_run_fingerprint",
                "confirm_apply",
            ],
            "required_result_fields": REPAIR_RECONCILE_APPLY_REQUIRED_FIELDS,
            "must_report": [
                "confirmed dry_run_fingerprint and selected row keys",
                "manifest backup path, transaction id, and rollback status",
                "written manifest path and source_payload_output_unchanged evidence",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "backup_before_write": True,
            "atomic_write_required": True,
            "journal_required": True,
            "rollback_on": [
                "temp write failure",
                "atomic replace failure",
                "post-write digest mismatch",
                "command journal write failure",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "scope",
                "backup_path",
                "before_manifest_digest",
                "after_manifest_digest",
                "rollback_status",
            ],
        },
        "source_file_policy": REPAIR_RECONCILE_SOURCE_FILE_POLICY,
        "route_exposure_gates": REPAIR_RECONCILE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "scan arbitrary frontend-provided paths",
            "mark media complete without output/sidecar evidence",
            "delete source/output/scratch files",
            "run while pipeline or pending-publish drain is active",
        ],
        "safe_next_step": "Use the backend dry-run route first; confirmed apply rewrites existing selected manifest rows only after matching fingerprint and explicit operator confirmation.",
    },
    {
        "key": "completed_sidecar_repair",
        "surface": "Completed sidecar metadata repair",
        "candidate_command": "completed.repair_sidecar_metadata",
        "owner": "Completed / Rename",
        "current_status": "backend_dry_run_and_confirmed_apply_routes_available",
        "dry_run_route": "/api/completed/repair-sidecar-metadata-dry-run",
        "apply_route": "/api/completed/repair-sidecar-metadata",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "sidecar-json-write",
        "required_preconditions": [
            "pipeline_idle",
            "selected_completed_row_loaded_from_backend_manifest",
            "output_path_exists_or_operator_accepts_missing_output",
            "sidecar_path_within_backend_resolved_roots",
            "dry_run_diff_reviewed",
        ],
        "required_evidence": [
            "before_sidecar_digest",
            "after_sidecar_digest",
            "canonical_output_path_before_after",
            "row_key",
            "backup_path",
        ],
        "rollback_requirements": [
            "write .bak before sidecar replacement",
            "write temp sidecar and atomic replace",
            "record command journal entry with row key and backup path",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_repair_reconcile_dry_run.v1",
            "required_result_fields": REPAIR_RECONCILE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "selected completed row key and backend-loaded sidecar path",
                "before/after sidecar JSON diff with redacted path summary",
                "output-path evidence and missing-output acceptance state",
                "would_not_touch source media, output media, scratch media, and rename manifests",
            ],
        },
        "apply_contract": {
            "effect": "completed-sidecar-json-write",
            "result_schema": "desktop_repair_reconcile_apply.v1",
            "required_request_fields": [
                "scope",
                "row_key",
                "limit",
                "reason",
                "dry_run_fingerprint",
                "confirm_apply",
            ],
            "required_result_fields": REPAIR_RECONCILE_APPLY_REQUIRED_FIELDS,
            "must_report": [
                "confirmed dry_run_fingerprint and selected row keys",
                "sidecar backup path, transaction id, and rollback status",
                "written sidecar path and preserved unknown-field posture",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "backup_before_write": True,
            "atomic_write_required": True,
            "journal_required": True,
            "rollback_on": [
                "backup write failure",
                "temp sidecar write failure",
                "atomic replace failure",
                "post-write JSON validation failure",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "row_key",
                "sidecar_path",
                "backup_path",
                "before_sidecar_digest",
                "after_sidecar_digest",
                "rollback_status",
            ],
        },
        "source_file_policy": REPAIR_RECONCILE_SOURCE_FILE_POLICY,
        "route_exposure_gates": REPAIR_RECONCILE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "rewrite arbitrary frontend-provided JSON paths",
            "rename media files",
            "override route/subtitle/audio policy",
            "hide sidecar-output mismatch without recording the repair",
        ],
        "safe_next_step": "Use the backend dry-run route first; confirmed apply updates only backend-derived sidecar metadata fields after matching fingerprint and explicit operator confirmation.",
    },
    {
        "key": "pending_publish_manifest_repair",
        "surface": "Pending publish manifest repair",
        "candidate_command": "pending_publish.repair_manifest",
        "owner": "Pending Publish",
        "current_status": "backend_dry_run_and_confirmed_apply_routes_available",
        "dry_run_route": "/api/pending-publish/repair-manifest-dry-run",
        "apply_route": "/api/pending-publish/repair-manifest",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "pending-manifest-write",
        "required_preconditions": [
            "pipeline_idle",
            "pending_drain_not_running",
            "pending_publish_scan_current",
            "recovery_plan_dry_run_reviewed",
            "operator_confirmed_exact_scope",
        ],
        "required_evidence": [
            "pending_scan_id",
            "manifest_path",
            "payload_paths_before_after",
            "missing_payload_count",
            "rows_changed",
            "backup_path",
        ],
        "rollback_requirements": [
            "write manifest backup before replacement",
            "write temp manifest and atomic replace",
            "record command journal entry with scan id and backup path",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_repair_reconcile_dry_run.v1",
            "required_result_fields": REPAIR_RECONCILE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "pending scan id and manifest identity",
                "payload path before/after correlation without moving payloads",
                "missing payload, sidecar, and orphan references by row",
                "would_not_touch source media, parked payload bytes, destination output, and completed manifest",
            ],
        },
        "apply_contract": {
            "effect": "pending-manifest-write",
            "result_schema": "desktop_repair_reconcile_apply.v1",
            "required_request_fields": [
                "scope",
                "row_key",
                "limit",
                "reason",
                "dry_run_fingerprint",
                "confirm_apply",
            ],
            "required_result_fields": REPAIR_RECONCILE_APPLY_REQUIRED_FIELDS,
            "must_report": [
                "confirmed dry_run_fingerprint and selected row keys",
                "pending manifest backup path, transaction id, and rollback status",
                "validated backend-derived proposed manifest fields before any write",
                "source/payload/output preservation status",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "backup_before_write": True,
            "atomic_write_required": True,
            "journal_required": True,
            "rollback_on": [
                "manifest backup failure",
                "temp manifest write failure",
                "atomic replace failure",
                "post-write pending scan mismatch",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "pending_scan_id",
                "manifest_path",
                "backup_path",
                "rows_changed",
                "rollback_status",
            ],
        },
        "source_file_policy": REPAIR_RECONCILE_SOURCE_FILE_POLICY,
        "route_exposure_gates": REPAIR_RECONCILE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "move parked payload files",
            "drain or publish files",
            "delete orphan payloads",
            "trust frontend-provided file paths",
        ],
        "safe_next_step": "Use the backend dry-run route first; confirmed apply writes only backend-validated manifest-normalization candidates and blocks incomplete evidence.",
    },
    {
        "key": "orphan_payload_reconcile",
        "surface": "Orphan pending payload reconciliation",
        "candidate_command": "pending_publish.reconcile_orphan_payloads",
        "owner": "Pending Publish",
        "current_status": "backend_dry_run_and_confirmed_apply_routes_available",
        "dry_run_route": "/api/pending-publish/reconcile-orphan-payloads-dry-run",
        "apply_route": "/api/pending-publish/reconcile-orphan-payloads",
        "mutation_enabled": True,
        "frontend_allowed": True,
        "mutation_class": "pending-orphan-manifest-write",
        "required_preconditions": [
            "pipeline_idle",
            "pending_drain_not_running",
            "fresh_pending_publish_scan",
            "destination_collision_check_passed",
            "operator_confirmed_exact_scope",
        ],
        "required_evidence": [
            "pending_scan_id",
            "manifest_correlation",
            "complete_manifest_fields",
            "backup_path",
            "source_payload_output_unchanged",
        ],
        "rollback_requirements": [
            "write manifest backup before replacement",
            "write temp manifest and atomic replace",
            "leave payload parked on uncertainty",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_repair_reconcile_dry_run.v1",
            "required_result_fields": REPAIR_RECONCILE_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "orphan payload row key and backend scan id",
                "manifest correlation strength and uncertainty reason",
                "destination collision status before any move/copy",
                "would_not_touch source media, completed manifest, unrelated parked payloads, and output media",
            ],
        },
        "apply_contract": {
            "effect": "pending-orphan-manifest-write",
            "result_schema": "desktop_repair_reconcile_apply.v1",
            "required_request_fields": [
                "scope",
                "row_key",
                "limit",
                "reason",
                "dry_run_fingerprint",
                "confirm_apply",
            ],
            "required_result_fields": REPAIR_RECONCILE_APPLY_REQUIRED_FIELDS,
            "must_report": [
                "confirmed dry_run_fingerprint and selected row keys",
                "manifest-only write posture with no payload move/delete/drain/publish",
                "complete backend-derived destination and source fields before any write",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "backup_before_write": True,
            "atomic_write_required": True,
            "journal_required": True,
            "rollback_on": [
                "manifest backup failure",
                "temp manifest write failure",
                "atomic replace failure",
                "post-write manifest validation failure",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "pending_scan_id",
                "manifest_path",
                "backup_path",
                "rows_changed",
                "rollback_status",
            ],
        },
        "source_file_policy": REPAIR_RECONCILE_SOURCE_FILE_POLICY,
        "route_exposure_gates": REPAIR_RECONCILE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "delete payloads as cleanup",
            "overwrite destination output",
            "publish when manifest proof is ambiguous",
            "move or delete payload files",
        ],
        "safe_next_step": "Use the backend dry-run route first; confirmed apply is manifest-only and remains blocked unless backend evidence supplies complete proposed fields.",
    },
    {
        "key": "startup_state_reconcile",
        "surface": "Startup state reconciliation",
        "candidate_command": "startup.reconcile_state",
        "owner": "Diagnostics / Maintenance",
        "current_status": "backend_dry_run_route_available",
        "dry_run_route": "/api/startup/reconcile-dry-run",
        "mutation_enabled": False,
        "frontend_allowed": False,
        "mutation_class": "startup-repair-or-rebuild",
        "required_preconditions": [
            "backend_resolved_state_root",
            "pending_publish_scan_current",
            "active_jobs_readable",
            "sqlite_mirror_readable_or_missing_reported",
            "operator_reviewed_ambiguity_before_any_future_repair",
        ],
        "required_evidence": [
            "pending_manifest_status_counts",
            "orphan_payload_rows",
            "active_jobs_record_status",
            "sqlite_mirror_user_version",
            "completed_manifest_to_sqlite_count_comparison",
        ],
        "rollback_requirements": [
            "no mutation route until every repair class has manifest-backed rollback evidence",
            "SQLite rebuild must be dry-run compared against authoritative JSON before mutation",
            "ActiveJobs reconciliation must prove PID identity/death before rewriting records",
        ],
        "dry_run_contract": {
            "effect": "none",
            "result_schema": "desktop_startup_reconciliation_dry_run.v1",
            "required_result_fields": STARTUP_RECONCILIATION_DRY_RUN_REQUIRED_FIELDS,
            "must_report": [
                "pending manifests and orphan parked payloads from backend pending-publish scan",
                "ActiveJobs ambiguity without killing processes or rewriting records",
                "SQLite mirror divergence without creating, migrating, or rebuilding the database",
                "would_not_touch source media, scratch media, output media, parked payloads, manifests, ActiveJobs records, and SQLite files",
            ],
        },
        "rollback_contract": {
            "required_for_mutation_route": True,
            "backup_before_write": True,
            "atomic_write_required": True,
            "journal_required": True,
            "rollback_on": [
                "ActiveJobs rewrite proof mismatch",
                "pending manifest identity mismatch",
                "SQLite rebuild diff mismatch",
                "command journal write failure",
            ],
            "journal_fields": [
                "command_id",
                "candidate_command",
                "startup_reconciliation_snapshot",
                "repair_class",
                "backup_path",
                "rollback_status",
            ],
        },
        "source_file_policy": REPAIR_RECONCILE_SOURCE_FILE_POLICY,
        "route_exposure_gates": REPAIR_RECONCILE_ROUTE_EXPOSURE_GATES,
        "must_not": [
            "create, migrate, or rebuild SQLite from dry-run",
            "rewrite ActiveJobs without proving PID identity or death",
            "repair pending manifests from frontend-supplied paths",
            "move, delete, drain, publish, or reveal parked payloads",
            "mutate source, scratch, output, completed, pending-publish, subtitle, or audio policy state",
        ],
        "safe_next_step": "Use the backend dry-run route for restart ambiguity evidence only; implement proven repair routes separately after backup, rollback, journal, and no-mutation tests pass.",
    },
]


def local_api_contract_payload(
    *,
    app_version: str,
    host: str,
    routes: Sequence[Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    route_rows = list(routes if routes is not None else LOCAL_API_ROUTE_CONTRACT)
    return {
        "schema_version": LOCAL_API_CONTRACT_SCHEMA_VERSION,
        "app_version": app_version,
        "host": host,
        "auth": {
            "scheme": LOCAL_API_AUTH_SCHEME,
            "public_routes": [str(route["path"]) for route in route_rows if not route.get("auth_required")],
            "token_routes": [str(route["path"]) for route in route_rows if route.get("auth_required")],
        },
        "routes": [dict(route) for route in route_rows],
        "network_lifecycle_contracts": deepcopy(NETWORK_LIFECYCLE_CONTRACTS),
        "network_lifecycle_summary": {
            "schema_version": "desktop_network_lifecycle_contracts.v1",
            "mutation_enabled": True,
            "frontend_allowed": True,
            "contract_count": len(NETWORK_LIFECYCLE_CONTRACTS),
            "status": "backend_lifecycle_routes_available_provider_guarded",
            "safe_next_step": "Use Network/Workers dry-runs first. Confirmed start/stop commands are backend-owned, command-journaled, confirmation-gated, and blocked when provider hooks are unavailable or preconditions fail.",
        },
        "repair_reconcile_contracts": deepcopy(REPAIR_RECONCILE_CONTRACTS),
        "repair_reconcile_summary": {
            "schema_version": "desktop_repair_reconcile_contracts.v1",
            "mutation_enabled": True,
            "frontend_allowed": True,
            "contract_count": len(REPAIR_RECONCILE_CONTRACTS),
            "status": "backend_dry_run_and_confirmed_apply_routes_available_startup_dry_run_only",
            "safe_next_step": "Use repair/reconcile dry-runs first. Confirmed apply routes are backend-owned, command-journaled, fingerprint-gated, and confirmation-gated; startup reconciliation remains dry-run only.",
        },
        "notes": list(LOCAL_API_CONTRACT_NOTES),
    }
