from __future__ import annotations

from typing import Any


LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/queue/priority",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "level", "reason", "items", "clear_all"],
        "allowed_levels": ["high", "normal", "low", "hold"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_priority_manifest.v1",
        "purpose": "Write or clear non-destructive priority manifest entries only. Path/item writes must be absolute paths under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots); clear_all removes priority state only. This does not rename, move, delete, launch, or process media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/strategy",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["strategy"],
        "allowed_strategies": [
            "Standard",
            "FreshestFirst",
            "ShowComplete",
            "RoundRobin",
            "DeadlineAware",
            "SmallFirst",
            "LargeFirst",
            "ManualOrder",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_strategy_state.v1",
        "purpose": "Persist the backend queue ordering strategy for the next queue build without launching work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/scan",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["mode", "force", "scope", "reason"],
        "allowed_modes": ["inventory_then_curate", "inventory_only", "curate_only"],
        "allowed_scopes": ["all"],
        "safe_defaults": {"mode": "inventory_then_curate", "force": True, "scope": "all"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_queue_scan_command.v1",
        "purpose": "Start or observe a serialized backend-owned queue source scan. The fast inventory phase reads configured source roots (SourceMovies, SourceTV, and enabled LibraryProfiles source roots) and writes source-inventory evidence; the curation phase runs the existing queue-plan dry-run to write the authoritative queue snapshot. This does not process, rename, move, delete, publish, drain, or mutate source media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "audio", "subtitles", "routing", "video", "clear", "clear_all", "clear_fields"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Write per-file processing override state only for absolute paths under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), or clear the override manifest. Route/video fields are validated sparse metadata for later processing consumption. This does not process or mutate media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/route-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path", "proposed_override"],
        "response_schema": "queue_file_override_route_preview.v1",
        "purpose": "Preview route/remux/transcode impact for one path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots) using current queue snapshot route evidence. This does not write file_overrides.json, enqueue work, change queue strategy, process media, or mutate queue state.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path", "proposed_override"],
        "response_schema": "queue_file_override_series_preview.v1",
        "purpose": "Preview applying the current per-file override drawer fields to matching current TV queue rows under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Detection is backend-owned from the current queue snapshot and does not write file_overrides.json, create folder/show future policies, enqueue work, process media, or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-apply",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "proposed_override", "confirm_apply", "preview_fingerprint"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "After explicit confirmation and a matching preview fingerprint for a path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), write exact per-file overrides for eligible current TV queue rows in the detected series. Exact manual file overrides are protected, previous series batch overrides may be replaced, and no future folder/show rule is created. This does not process media or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/remux-pilot-promote",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["pilot_source_paths", "confirm_apply", "reason"],
        "safe_defaults": {"confirm_apply": False},
        "requires_confirmation": True,
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_remux_pilot_promotion.v1",
        "purpose": "After explicit confirmation, validate exactly three distinct completed TV pilot source paths under configured source roots with final remux route evidence, oversized_encode_remux_fallback route reason, and structured fallback-remux size-policy evidence. The backend then writes exact per-file routing.profile=remux overrides only for eligible remaining current queue rows in the detected series, protects exact manual file overrides, replaces previous series batch overrides, and creates no future folder/show rule. This does not process, remux, encode, publish, rename, move, delete, drain, or mutate source media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/folder-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["folder_path", "proposed_override", "options"],
        "response_schema": "queue_file_override_folder_preview.v1",
        "purpose": "Preview the bounded impact of a folder-prefix audio/subtitle track override under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots) using known queue snapshot rows and cached track metadata only. This does not write file_overrides.json, scan source folders, run probes, enqueue work, change queue strategy, process media, or mutate queue state.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/folder-rule",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["folder_path", "override", "confirmation", "clear"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Save or clear a validated folder-prefix audio/subtitle track override under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Stream indexes and raw ffmpeg map fields are rejected, source/library roots are rejected, and save requires acknowledgement that future files may match and exact file overrides win. This does not process media or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/failures/clear",
        "auth_required": True,
        "effect": "failure-marker-write",
        "request_keys": ["scope", "marker_path", "marker_paths", "source_json", "dry_run", "confirm_clear"],
        "allowed_scopes": ["selected", "visible", "all_markers"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_marker_clear_result.v1",
        "purpose": "Preview or move backend-owned failure marker JSON files out of State\\Failures\\Markers after explicit confirmation. Paths are accepted only when they resolve inside the backend failure marker folder. This does not delete media, reports, completed manifests, pending publish state, or source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target", "row_scope"],
        "allowed_targets": ["source_file", "source_folder", "source_root"],
        "allowed_row_scopes": ["runnable", "excluded"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a path selected by the backend from a runnable or excluded queue snapshot row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/completed/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["play_output_file", "output_file", "output_folder", "sidecar", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open or play a path selected by the backend from a completed-jobs manifest row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/subtitle-qa/preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["id", "row_key", "path", "source_path", "output_path", "scope", "limit"],
        "response_schema": "subtitle_qa_preview.v1",
        "data_schema": "subtitle_qa_result.v1",
        "purpose": "Preview one already-loaded Queue or Completed row's backend-authored subtitle QA evidence without probing files, running OCR/conversion/sync tools, repairing, rerunning, rewriting sidecars, publishing, draining, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["play_local_file", "local_file", "manifest", "destination_folder", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open or play a path selected by the backend from the current pending-publish scan; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/recovery-plan",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pending_publish_recovery_plan.v1",
        "purpose": "Build a backend-authored dry-run recovery plan from the current pending-publish scan. This does not drain, repair, rewrite, move, delete, or publish files.",
    },
    {
        "method": "POST",
        "path": "/api/completed/reconcile-manifest-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "completed.reconcile_manifest",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-authored dry-run diff for reconciling loaded completed-preview manifest rows. This does not rewrite the completed manifest, write sidecars, publish, drain, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/completed/reconcile-manifest",
        "auth_required": True,
        "effect": "completed-manifest-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "completed.reconcile_manifest",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Rerun the backend completed manifest reconcile dry-run and, after matching dry_run_fingerprint plus explicit confirmation, back up and atomically rewrite existing selected manifest rows only. This does not add/remove manifest rows, publish, drain, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/completed/repair-sidecar-metadata-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "completed.repair_sidecar_metadata",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-authored dry-run diff for completed sidecar metadata using loaded completed-preview rows and their backend-derived sidecar paths only. This does not write sidecar JSON, rewrite manifests, publish, drain, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/completed/repair-sidecar-metadata",
        "auth_required": True,
        "effect": "completed-sidecar-json-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "completed.repair_sidecar_metadata",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Rerun the backend completed sidecar metadata dry-run and, after matching dry_run_fingerprint plus explicit confirmation, back up and atomically rewrite only backend-derived sidecar metadata fields. Unknown sidecar fields are preserved.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/repair-manifest-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "pending_publish.repair_manifest",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-authored dry-run diff from the existing pending-publish scan, recovery classification, file inventory, and drain summary evidence. This does not rewrite pending manifests, drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/repair-manifest",
        "auth_required": True,
        "effect": "pending-manifest-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "pending_publish.repair_manifest",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Rerun the backend pending manifest repair dry-run and require matching dry_run_fingerprint, explicit confirmation, complete backend-derived evidence, backup, and validation before any pending manifest write. This does not drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/reconcile-orphan-payloads-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "pending_publish.reconcile_orphan_payloads",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build backend-authored orphan payload review evidence from the existing pending-publish scan and file inventory. This does not create manifests, drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/reconcile-orphan-payloads",
        "auth_required": True,
        "effect": "pending-orphan-manifest-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "pending_publish.reconcile_orphan_payloads",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Manifest-only orphan payload reconcile route. It reruns the backend dry-run and blocks unless backend evidence supplies complete destination/source fields. It never moves, deletes, drains, publishes, or touches payload/source/output media.",
    },
    {
        "method": "POST",
        "path": "/api/startup/reconcile-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "limit", "reason"],
        "allowed_scopes": ["all"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_startup_reconciliation_dry_run.v1",
        "candidate_command": "startup.reconcile_state",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build backend-authored startup reconciliation evidence for pending manifests, orphaned parked payloads, ActiveJobs, and SQLite mirror posture. This does not repair, rewrite, migrate, rebuild, drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/promote-queue",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": ["confirm_promote", "row_keys"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Start the backend-owned queue-wide or selected-row final-library promotion run after explicit confirmation. It copies verified completed outputs from Outsource to configured final-library destinations and may delete only verified publish-output files when cleanup is enabled.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/pause",
        "auth_required": True,
        "effect": "control-state-write",
        "request_keys": ["run_id"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Request cooperative pause of the current final-library promotion run after the active item completes or fails.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/resume",
        "auth_required": True,
        "effect": "control-state-write",
        "request_keys": ["run_id"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Resume a paused backend-owned final-library promotion run using the current completed-output queue state.",
    },
)

LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/maintenance/release-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "include_tauri_preview_binary",
            "keep_personal_config",
            "force",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": False,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "include_tauri_preview_binary": True,
            "keep_personal_config": False,
            "force": False,
            "timeout_seconds": 900,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the existing release builder with -DryRun only. No release folder, zip, or manifest is written.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/release-build",
        "auth_required": True,
        "effect": "deployment-write",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "include_tauri_preview_binary",
            "keep_personal_config",
            "force",
            "confirm_create",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": False,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "include_tauri_preview_binary": True,
            "keep_personal_config": False,
            "force": False,
            "confirm_create": False,
            "timeout_seconds": 7200,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Create a deployable release package through the backend release builder after explicit confirmation and active-work checks. It may create a release folder, manifest, and zip outside the source bundle.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/completed-backfill-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["timeout_seconds"],
        "safe_defaults": {"timeout_seconds": 600},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the completed-jobs manifest backfill with -DryRun only. The completed manifest is not rewritten.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/retention-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["limit", "reason"],
        "safe_defaults": {"limit": 200},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_retention_dry_run.v1",
        "candidate_command": "maintenance.retention_cleanup",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-owned dry-run retention report for logs, JSONL/state files, temp/scratch orphans, failure reports, and cache artifacts under allowlisted runtime roots. This does not delete, move, archive, truncate, rewrite, drain, publish, or touch source/output/pending-publish media files.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/archive-state-journals",
        "auth_required": True,
        "effect": "runtime-evidence-archive",
        "request_keys": ["confirm_archive", "reason"],
        "safe_defaults": {"confirm_archive": False},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_state_journal_archive.v1",
        "owner": "Maintenance / Diagnostics",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "After explicit confirmation and safe close-readiness, archive only the backend-resolved State\\Progress\\pipeline_events.jsonl runtime event journal when oversized, then create a fresh empty replacement. This does not archive completed manifests, queue snapshots, progress files, pending-publish manifests/payloads, source media, scratch media, or final outputs.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/dependency-atlas",
        "auth_required": True,
        "effect": "tooling-artifact-write",
        "request_keys": ["timeout_seconds", "min_overview_edge_count", "min_overview_files"],
        "safe_defaults": {
            "timeout_seconds": 600,
            "min_overview_edge_count": 4,
            "min_overview_files": 2,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Regenerate dependency-atlas HTML, PNG/SVG diagrams, and CSV exports under the repository-root docs/generated/dependency-atlas folder through the backend tooling runner. It does not touch media, queue, settings, manifests, or pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/dependency-atlas/open-folder",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": [],
        "allowed_targets": ["dependency_atlas_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open the backend-resolved repository-root docs/generated/dependency-atlas folder through the OS shell. The frontend does not submit arbitrary paths, and this does not touch media, queue, settings, manifests, or pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/support-export",
        "auth_required": True,
        "effect": "diagnostics-artifact-write",
        "request_keys": ["reason", "include_recent_logs", "max_log_bytes"],
        "safe_defaults": {"include_recent_logs": True, "max_log_bytes": 131072},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_support_export.v1",
        "purpose": "Write a backend-owned redacted support export under per-user AppData DiagnosticsExports. It includes product/version/update/migration/health evidence and bounded redacted log tails without full private config, signing material, bearer tokens, unredacted personal paths, or media file mutation.",
    },
)

LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/metrics/sources",
        "auth_required": True,
        "effect": "metrics-state-write",
        "request_keys": ["action", "path", "source_id", "label", "enabled"],
        "allowed_actions": ["add", "remove", "enable", "disable"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_metrics_sources.v1",
        "purpose": "Add, remove, enable, or disable backend-owned Metrics sidecar source roots. Paths are stored under State\\Metrics only; this does not scan folders, process media, rewrite sidecars, mutate queue state, launch work, or touch source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/metrics/backfill",
        "auth_required": True,
        "effect": "metrics-backfill-state-write",
        "request_keys": ["scope", "source_id", "path", "max_sidecars"],
        "allowed_scopes": ["enabled", "all"],
        "safe_defaults": {"scope": "enabled"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_metrics_backfill.v1",
        "purpose": "Recursively read *.pipeline.json sidecars under configured Metrics source roots and refresh the backend Metrics cache under State\\Metrics. The scanner skips symlinked folders, reads sidecar JSON only, and does not rewrite sidecars, process media, mutate queue state, launch work, drain, publish, rename, or touch source/output files.",
    },
)

LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/diagnostics/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["target"],
        "allowed_targets": [
            "run_logs",
            "cluster_log",
            "config",
            "config_folder",
            "workspace",
            "state",
            "pending_publish",
            "failed_reports",
            "failed_markers",
            "audit_reports",
            "queue_snapshot",
            "active_jobs",
            "completed_manifest",
            "latest_failure_report",
            "latest_failure_json",
            "latest_audit_csv",
            "latest_priority_csv",
            "last_stdout_log",
            "last_stderr_log",
            "sample_validation_log",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open backend-allowlisted diagnostics/log/config locations through the OS shell.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/tdarr-matrix-audit",
        "auth_required": True,
        "effect": "diagnostic-process",
        "request_keys": ["action", "confirm_delete_full_matrix"],
        "allowed_actions": [
            "prepare-proof-pack",
            "report",
            "smoke-pack",
            "proof-pack",
            "strict-report",
            "cleanup-plan",
            "cleanup-archive",
            "cleanup-delete",
        ],
        "safe_defaults": {"action": "report", "confirm_delete_full_matrix": False},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_tdarr_matrix_audit_result.v1",
        "purpose": "Run backend-owned Tdarr Proof Pack diagnostics through ops/scripts/dev/run-python-tool.py. Presets use the E:\\Videos proof library and isolated proof run roots; legacy full-matrix cleanup is backend-owned and requires proof verification plus archive evidence. The frontend cannot submit paths, command arguments, or live operator config.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/tdarr-matrix/evidence/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["run_id", "finding_key", "target"],
        "allowed_targets": ["stdout", "stderr", "worker_result", "source_hashes", "failure_artifact", "output", "report_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a backend-resolved evidence artifact for a selected Tdarr Proof Pack finding. The frontend sends only a run ID, finding key, and allowlisted target name; arbitrary paths are rejected.",
    },
    {
        "method": "POST",
        "path": "/api/diagnostics/tdarr-matrix/rerun",
        "auth_required": True,
        "effect": "diagnostic-process",
        "request_keys": ["source_run_id", "selection", "finding_keys"],
        "allowed_selections": ["selected", "latest_failures"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_tdarr_matrix_audit_result.v1",
        "purpose": "Rerun selected Tdarr Proof Pack cases, or latest failure cases, into a fresh isolated Proof Pack run root. The backend maps finding keys to manifest case IDs and the frontend cannot submit paths or command arguments.",
    },
)

LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/rename/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["paths", "mode", "show_name", "season", "start_episode", "movie_title", "movie_year"],
        "response_schema": "desktop_rename_preview.v1",
        "optional_response_fields": ["input_counts"],
        "purpose": "Generate media-only rename predictions without applying filesystem changes; sidecar inputs are counted as ignored and attached to media rows automatically.",
    },
    {
        "method": "POST",
        "path": "/api/rename/browse",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path", "paths"],
        "allowed_selection_modes": ["files", "folder", "folder_files"],
        "response_schema": "desktop_command_result.v1",
        "optional_data_fields": ["raw_path_count", "ignored_path_count", "ignored_sidecar_count"],
        "purpose": "Open the native Windows file/folder browser, or resolve already-known dropped paths, and return absolute media paths for Rename staging. Folder-file selection filters sidecars/non-media paths and reports ignored counts. This does not preview, apply, rename, move, delete, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rename/filter-cases",
        "auth_required": True,
        "effect": "test-fixture-write",
        "request_keys": [
            "case_id",
            "source_folder",
            "source_file",
            "expected_name",
            "expected_show",
            "expected_clean_folder",
            "expected_season",
            "season_number",
            "status",
            "notes",
            "confirm_append",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "rename_bad_case_corpus_append.v1",
        "purpose": "Append a backend-validated bad rename regression case to tests/fixtures/rename/bad_rename_cases.jsonl after explicit confirmation. This route writes only the test corpus and never previews, applies, renames, moves, deletes, or touches media files.",
    },
    {
        "method": "POST",
        "path": "/api/rename/apply",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": [
            "paths",
            "mode",
            "show_name",
            "season",
            "season_value",
            "start_episode",
            "start_episode_value",
            "movie_title",
            "movie_year",
            "remove_terms",
            "remove_terms_text",
            "movie_filter_options",
            "movie_filter_terms",
            "final_name_overrides",
            "rename_sidecars",
            "force_pipeline_name",
            "force_pipeline_name_overrides",
            "powershell_host",
            "use_pipeline_naming_preview",
            "template_preset",
            "selected_sources",
            "confirm_apply",
            "allow_outside_configured_roots",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Rebuild the rename plan in the backend and apply only explicitly selected source rows through the transactional rename service. Paths outside configured media roots require an additional outside-root confirmation.",
    },
    {
        "method": "POST",
        "path": "/api/rename/undo",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": ["undo_manifest", "confirm_undo"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rename_undo_result.v1",
        "purpose": "Undo the last backend rename apply from a backend-owned RenameUndo manifest after explicit confirmation. The backend validates the manifest under its resolved undo root and reverses media/sidecar operations; the frontend cannot rename files directly.",
    },
)

LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/settings/validate",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["values"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Validate settings values without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/validate",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_validation.v1",
        "purpose": "Validate an inline PresetV2 document without writing the preset library, active PSD1 config, queue state, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/compare",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["left_id", "right_id", "left_preset_v2", "right_preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_compare.v1",
        "purpose": "Compare preset records or inline PresetV2 documents through backend PresetV2-to-legacy patch projection without writing state or config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/import-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["records"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_import_preview.v1",
        "purpose": "Validate preset import candidate records and report the State JSON target without writing the preset library or active config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/save",
        "auth_required": True,
        "effect": "preset-library-state-write",
        "request_keys": ["id", "name", "description", "tags", "source", "imported_from", "preset_v2", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library.v1",
        "purpose": "Save a PresetV2 record to backend State JSON at State/PresetLibrary/presets.json only. This does not save active PSD1 settings, launch work, mutate queue state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/export",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["id", "preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library.v1",
        "purpose": "Return a backend preset library record or inline PresetV2 export payload without writing state, active config, queue state, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/apply-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["id", "preset_v2"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "preset_library_apply_preview.v1",
        "purpose": "Convert a PresetV2 record or inline PresetV2 payload to a legacy settings patch and run existing backend settings preview semantics without saving config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preset-library/apply",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["id", "preset_v2", "confirm_apply"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_save_reload_progress.v1",
        "purpose": "After explicit confirmation, convert a PresetV2 record or inline PresetV2 payload to a legacy settings patch and save through the existing backend settings save path. Applies to future launches only.",
    },
    {
        "method": "POST",
        "path": "/api/settings/browse-path",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["setting_key", "selection_mode", "initial_path"],
        "allowed_setting_keys": [
            "SourceMovies",
            "SourceTV",
            "Outsource",
            "LocalBase",
            "FinalLibraryPromotionRuleSourceRoot",
            "FinalLibraryPromotionRuleDestinationRoot",
        ],
        "allowed_selection_modes": ["folder"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_path_browse.v1",
        "purpose": "Open the native Windows folder browser for allowlisted Settings path fields and return backend-validated folder evidence for WebView staging only. This does not save the PSD1, launch work, rewrite queue state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preview-patch",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["changes", "remove_keys", "library_profile_resets"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted config and return a redacted diff without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/pipeline-plan-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["source_media", "changes", "remove_keys"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pipeline_plan.v1",
        "purpose": "Validate strict SourceMediaInfo facts, merge optional staged Settings patch values in memory, and return a backend-owned dry-run PipelinePlan preview without probing paths, saving config, launching work, changing queue state, publishing, draining, renaming, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/save-patch",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["changes", "remove_keys", "library_profile_resets", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted JSON-authoritative config, validate, back up, atomically save the JSON settings store plus active PSD1 projection, and reload backend resolved state.",
    },
    {
        "method": "POST",
        "path": "/api/settings/import-psd1-preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_import_psd1_preview.v1",
        "purpose": "Preview importing the active resolved PSD1 into the JSON settings authority. This reports migrations, legacy extras, and blocking errors without writing the JSON store or PSD1 projection.",
    },
    {
        "method": "POST",
        "path": "/api/settings/import-psd1",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["confirm_import"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_import_psd1_result.v1",
        "purpose": "After explicit confirmation, import the active resolved PSD1 into the JSON settings authority, preserve unknown legacy extras as inert projection-only values, regenerate the PSD1 projection, and reload backend resolved state.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-paths",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_path_validation.v1",
        "purpose": "Validate Settings Wizard source, output, and scratch paths without saving config, launching work, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-tools",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_tools.v1",
        "purpose": "Validate Settings Wizard FFmpeg/ffprobe tool path evidence without changing config or running media work.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/probe-hardware",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_hardware_probe.v1",
        "purpose": "Return conservative encoder probe evidence for wizard review without saving config, launching work, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/validate-workers",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard_worker_validation.v1",
        "purpose": "Validate Settings Wizard worker/concurrency choices without saving config or starting worker lifecycle controls.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["wizard"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard.v1",
        "purpose": "Generate a Settings Wizard patch and preview it through the normal backend settings patch validation path without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/wizard/save",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["wizard", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_settings_wizard.v1",
        "purpose": "Generate a Settings Wizard patch and save it through the normal backend settings patch writer with confirmation, backup, atomic PSD1 write, and reload.",
    },
    {
        "method": "POST",
        "path": "/api/settings/reload",
        "auth_required": True,
        "effect": "none",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Reload resolved paths and config data from the current PSD1 without writing config or starting pipeline work.",
    },
)

LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/schedule/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["enabled", "day_windows", "grid"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_patch_preview.v1",
        "purpose": "Validate and preview schedule/app-state changes without writing app state, starting work, or editing media state.",
    },
    {
        "method": "POST",
        "path": "/api/schedule/save",
        "auth_required": True,
        "effect": "app-state-write",
        "request_keys": ["enabled", "day_windows", "grid", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_save_result.v1",
        "purpose": "Atomically save schedule_enabled and schedule_grid to desktop app state through the backend service while preserving unrelated app-state keys. This does not launch work, bypass schedule gates, or mutate media files.",
    },
)

LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/sample-validation/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["schema", "shell", "source_path", "output_path", "sample_label", "sample_category", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Validate and normalize a proposed sample validation record without writing the validation log or changing media/pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/sample-validation/append",
        "auth_required": True,
        "effect": "validation-log-write",
        "request_keys": ["schema", "shell", "source_path", "output_path", "sample_label", "sample_category", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Append an operator evidence-only sample validation record under State\\Validation. This must not mark jobs complete, clear failures, drain pending publish, rewrite manifests/sidecars, launch work, or mutate media files.",
    },
)

LOCAL_API_UI_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/ui-preferences",
        "auth_required": True,
        "effect": "ui-state-write",
        "request_keys": ["storage", "source_surface"],
        "response_schema": "desktop_ui_preferences.v1",
        "purpose": "Persist allowlisted local WebView UI preferences such as layout, theme, evidence visibility, and tab choices so Chrome and the Tauri shell share the same operator customization. This does not save config, mutate queue state, launch work, drain, rename, publish, or touch media files.",
    },
)

LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/network/coordinator/start-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "coordinator", "action": "start", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned coordinator start preconditions, lifecycle state, state-file posture, active-work evidence, and would_not_touch guarantees without starting a dispatcher, scanning queue records, or touching media/state files.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/stop-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "coordinator", "action": "stop", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned coordinator stop preconditions, active claim posture, state-file preservation evidence, and would_not_touch guarantees without stopping a dispatcher or releasing claims.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/start-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "worker", "action": "start", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned worker start preconditions, coordinator URL/token/path-map posture, pending done report state, and would_not_touch guarantees without polling, claiming, scanning, or launching work.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/stop-dry-run",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "network_lifecycle": {"role": "worker", "action": "stop", "dry_run": True},
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_dry_run.v1",
        "purpose": "Return backend-owned worker stop preconditions, pending done report posture, worker_state preservation evidence, and would_not_touch guarantees without aborting active work or deleting scratch files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/test-connection",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "request_keys": ["timeout_seconds"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_worker_test_connection.v1",
        "purpose": "Run a backend-owned read-only worker connection preflight for coordinator TCP reachability, signed auth ping, and configured worker library source/output path accessibility. This does not claim work, start or stop lifecycle, save settings, launch processing, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/discover-coordinators",
        "auth_required": True,
        "effect": "none",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": False,
        "journaled": False,
        "request_keys": ["timeout_seconds"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_coordinator_discovery.v1",
        "purpose": "Run backend-owned mDNS coordinator discovery and return selectable coordinator base URLs for worker setup. The route is unjournaled and read-only; selecting a result only fills the worker URL controls until the operator saves settings, and it does not claim work, start or stop lifecycle, save settings, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/join-blob",
        "auth_required": True,
        "effect": "secret-transfer",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": False,
        "request_keys": ["coordinator_url", "confirm_create", "rotate_token", "confirm_rotate"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_join_blob_result.v1",
        "purpose": "Create a coordinator setup blob containing coordinator URL, worker auth token, and advertised library roots for transfer to a worker. The response is intentionally unjournaled because the blob contains a secret; this does not start or stop lifecycle, claim work, launch processing, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/join-cluster",
        "auth_required": True,
        "effect": "config-write",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": False,
        "request_keys": ["join_blob", "confirm_import", "timeout_seconds"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_join_import_result.v1",
        "purpose": "Import a coordinator join blob on a worker, save WorkerCoordinatorUrl, WorkerAuthToken, NetworkRole, and any library-ID-derived WorkerSourcePathMap entries through the backend settings save path, then run the existing read-only worker test-connection. The command response is unjournaled because the request contains a secret; it does not claim work, start or stop lifecycle, launch processing, mutate queue state, publish, drain, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/start",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "coordinator", "action": "start", "dry_run": False},
        "request_keys": ["confirm_start", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, start the real coordinator lifecycle provider only. It must not process local files unless CoordinatorAlsoEncodeLocally is enabled and must not touch source/scratch/output/queue/pending-publish media state as part of lifecycle start.",
    },
    {
        "method": "POST",
        "path": "/api/network/coordinator/stop",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "coordinator", "action": "stop", "dry_run": False},
        "request_keys": ["confirm_stop", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, stop the coordinator lifecycle provider while preserving coordinator_inflight.json, worker_state.json, and cluster.log. It must not silently release active claims or mutate media files.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/start",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "worker", "action": "start", "dry_run": False},
        "request_keys": ["confirm_start", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, start the real worker polling lifecycle provider only. It claims coordinator-assigned work one file at a time and must not scan the local queue or launch normal pipeline start.",
    },
    {
        "method": "POST",
        "path": "/api/network/worker/stop",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "owner": "Network",
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "network_lifecycle": {"role": "worker", "action": "stop", "dry_run": False},
        "request_keys": ["confirm_stop", "reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_network_lifecycle_result.v1",
        "purpose": "After explicit confirmation and backend preconditions, request worker lifecycle stop while preserving pending done reports and worker_state.json. Abort/partial scratch cleanup remains a separate explicit command.",
    },
)

LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/pipeline/control",
        "auth_required": True,
        "effect": "control-flag-write",
        "request_keys": ["action"],
        "allowed_actions": ["pause", "stop", "rescan", "kill"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Write backend-owned pause, stop, or rescan control flags, or force-kill related pipeline processes.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/browse-file",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path"],
        "allowed_selection_modes": ["files"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_pipeline_single_file_browse.v1",
        "purpose": "Open the native Windows file browser and return one operator-selected file for Launch single-file staging only. This does not save config, launch work, mutate queue state, rename, move, delete, publish, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["mode", "sleep_seconds", "show_config", "show_console", "single_file", "schedule_override"],
        "allowed_modes": ["once", "continuous", "validate", "drain_pending_pushes"],
        "allowed_schedule_overrides": ["", "run_once", "ignore"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing pipeline process through the Python service layer.",
    },
    {
        "method": "POST",
        "path": "/api/audit/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["library_root", "include_sidecars", "show_console"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing audit process through the Python service layer.",
    },
    {
        "method": "POST",
        "path": "/api/audit/score-policy",
        "auth_required": True,
        "effect": "audit-state-write",
        "request_keys": ["policy", "reset"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_score_policy_result.v2",
        "purpose": "Save or reset backend-owned audit score weights used by future audit report generation without changing queue, settings, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/audit/ignore",
        "auth_required": True,
        "effect": "audit-state-write",
        "request_keys": ["action", "row_keys", "paths", "reason", "priority_only", "limit"],
        "allowed_actions": ["add", "remove"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_ignore_result.v1",
        "purpose": "Save or remove audit-only ignored file entries without queue holds, file overrides, settings saves, or media mutation.",
    },
    {
        "method": "POST",
        "path": "/api/audit/export-rerun-csv",
        "auth_required": True,
        "effect": "report-file-write",
        "request_keys": ["row_keys", "priority_only", "limit"],
        "safe_defaults": {"stage_mode": "copy", "original_mode": "keep", "return_mode": "park"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_rerun_export.v1",
        "purpose": "Write a backend-owned rerun CSV from selected or loaded non-ignored audit rows using copy/keep/park defaults without launching rerun work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["csv_path", "dry_run", "plan_only", "stage_mode", "original_mode", "return_mode", "show_console"],
        "safe_defaults": {"dry_run": False, "plan_only": False, "stage_mode": "copy", "original_mode": "keep", "return_mode": "park"},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing CSV rerun process with conservative media-safe defaults.",
    },
    {
        "method": "POST",
        "path": "/api/backend/shutdown",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "request_keys": ["reason", "force_active_work_shutdown"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Request graceful shutdown of the local API backend owned by the desktop shell; unsafe close-readiness is rejected unless explicit boolean true force cleanup is requested.",
    },
)


LOCAL_API_COMMAND_ROUTE_CONTRACT = (
    LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_UI_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT
)


__all__ = [
    "LOCAL_API_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_UI_COMMAND_ROUTE_CONTRACT",
]
