from __future__ import annotations

from .routes_shared import RouteHandlerSpec


GET_ROUTE_HANDLERS: dict[str, RouteHandlerSpec] = {
    "/api/contract": RouteHandlerSpec("_contract_payload"),
    "/api/snapshot": RouteHandlerSpec("_snapshot_payload"),
    "/api/telemetry": RouteHandlerSpec("_telemetry_payload"),
    "/api/diagnostics": RouteHandlerSpec("_diagnostics_payload"),
    "/api/diagnostics/tail": RouteHandlerSpec("_diagnostics_tail_payload", needs_query=True),
    "/api/diagnostics/state-summary": RouteHandlerSpec("_diagnostics_state_summary_payload"),
    "/api/diagnostics/tdarr-matrix/latest": RouteHandlerSpec("_tdarr_matrix_console_payload", needs_query=True),
    "/api/diagnostics/tdarr-matrix/runs": RouteHandlerSpec("_tdarr_matrix_runs_payload"),
    "/api/diagnostics/tdarr-matrix/compare": RouteHandlerSpec("_tdarr_matrix_compare_payload", needs_query=True),
    "/api/backend/close-readiness": RouteHandlerSpec("_close_readiness_payload"),
    "/api/ui-preferences": RouteHandlerSpec("_ui_preferences_payload"),
    "/api/launch/preflight": RouteHandlerSpec("_launch_preflight_payload", needs_query=True),
    "/api/commands": RouteHandlerSpec("_command_history_payload", needs_query=True),
    "/api/queue": RouteHandlerSpec("_queue_payload"),
    "/api/queue/priority": RouteHandlerSpec("_queue_priority_read_payload"),
    "/api/queue/strategy": RouteHandlerSpec("_queue_strategy_read_payload"),
    "/api/queue/file-overrides": RouteHandlerSpec("_file_overrides_read_payload", needs_query=True),
    "/api/queue/file-overrides/effective": RouteHandlerSpec("_file_overrides_effective_read_payload", needs_query=True),
    "/api/queue/file-overrides/tracks": RouteHandlerSpec("_file_overrides_tracks_read_payload", needs_query=True),
    "/api/completed": RouteHandlerSpec("_completed_payload", needs_query=True),
    "/api/subtitle-qa/summary": RouteHandlerSpec("_subtitle_qa_summary_payload", needs_query=True),
    "/api/subtitle-qa/item": RouteHandlerSpec("_subtitle_qa_item_payload", needs_query=True),
    "/api/metrics": RouteHandlerSpec("_metrics_payload"),
    "/api/final-library-promotion/status": RouteHandlerSpec("_final_library_promotion_status_payload"),
    "/api/failures": RouteHandlerSpec("_failures_payload", needs_query=True),
    "/api/audit-results": RouteHandlerSpec("_audit_results_payload", needs_query=True),
    "/api/audit-controls": RouteHandlerSpec("_audit_controls_payload"),
    "/api/pending-publish": RouteHandlerSpec("_pending_publish_payload"),
    "/api/publish-reconciliation": RouteHandlerSpec("_publish_reconciliation_payload", needs_query=True),
    "/api/maintenance": RouteHandlerSpec("_maintenance_payload"),
    "/api/maintenance/progress": RouteHandlerSpec("_maintenance_progress_payload"),
    "/api/maintenance/change-ledger": RouteHandlerSpec("_maintenance_change_ledger_payload", needs_query=True),
    "/api/maintenance/productization": RouteHandlerSpec("_maintenance_productization_payload"),
    "/api/schedule": RouteHandlerSpec("_schedule_payload"),
    "/api/watch-folders/status": RouteHandlerSpec("_watch_folders_status_payload"),
    "/api/settings/workspace": RouteHandlerSpec("_settings_workspace_payload"),
    "/api/settings/preset-library": RouteHandlerSpec("_settings_preset_library_payload"),
    "/api/libraries/route-map": RouteHandlerSpec("_libraries_route_map_payload"),
    "/api/libraries/route-map/trace": RouteHandlerSpec("_libraries_route_trace_payload", needs_query=True),
    "/api/libraries/route-map/compare": RouteHandlerSpec("_libraries_route_compare_payload", needs_query=True),
    "/api/libraries/route-map/validation": RouteHandlerSpec("_libraries_route_validation_payload", needs_query=True),
    "/api/settings/wizard/status": RouteHandlerSpec("_settings_wizard_status_payload"),
    "/api/settings/wizard/defaults": RouteHandlerSpec("_settings_wizard_defaults_payload"),
    "/api/rename/cleaning-filters": RouteHandlerSpec("_rename_cleaning_filter_catalog_payload"),
    "/api/rename/movie-cleaning-filters": RouteHandlerSpec("_rename_movie_filter_catalog_payload"),
    "/api/rename/clean-filename-preview": RouteHandlerSpec("_rename_clean_filename_preview_payload", needs_query=True),
    "/api/network/workers": RouteHandlerSpec("_network_workers_payload"),
    "/api/sample-validation": RouteHandlerSpec("_sample_validation_payload", needs_query=True),
}
