from __future__ import annotations

from mediapipeline.desktop.contracts.active_job import ACTIVE_JOB_SCHEMA_VERSION
from mediapipeline.desktop.contracts.control_flag import CONTROL_FLAG_SCHEMA_VERSION

CONTROL_FLAG_STALE_AFTER_SECONDS = 3600.0
PROCESS_LAUNCH_ERROR_TAIL_LINES = 24
PROCESS_LAUNCH_READY_CHECK_SECONDS = 0.35
ACTIVE_JOB_HEARTBEAT_SECONDS = 30.0
ACTIVE_JOB_STALE_VALIDATE_HEARTBEAT_SECONDS = 300.0
PIPELINE_PROGRESS_LAUNCH_CLEANUP_STALE_SECONDS = 120.0
AUDIT_PROGRESS_LAUNCH_CLEANUP_STALE_SECONDS = 120.0
