from __future__ import annotations

from mediapipeline.core.kernel.contracts import ACTIVE_JOB_SCHEMA_VERSION, CONTROL_FLAG_SCHEMA_VERSION

CONTROL_FLAG_STALE_AFTER_SECONDS = 3600.0
PROCESS_LAUNCH_ERROR_TAIL_LINES = 24
PROCESS_LAUNCH_READY_CHECK_SECONDS = 0.35
ACTIVE_JOB_HEARTBEAT_SECONDS = 30.0
ACTIVE_JOB_STALE_VALIDATE_HEARTBEAT_SECONDS = 300.0
PIPELINE_PROGRESS_LAUNCH_CLEANUP_STALE_SECONDS = 120.0
AUDIT_PROGRESS_LAUNCH_CLEANUP_STALE_SECONDS = 120.0

__all__ = [
    "ACTIVE_JOB_HEARTBEAT_SECONDS",
    "ACTIVE_JOB_SCHEMA_VERSION",
    "ACTIVE_JOB_STALE_VALIDATE_HEARTBEAT_SECONDS",
    "AUDIT_PROGRESS_LAUNCH_CLEANUP_STALE_SECONDS",
    "CONTROL_FLAG_SCHEMA_VERSION",
    "CONTROL_FLAG_STALE_AFTER_SECONDS",
    "PIPELINE_PROGRESS_LAUNCH_CLEANUP_STALE_SECONDS",
    "PROCESS_LAUNCH_ERROR_TAIL_LINES",
    "PROCESS_LAUNCH_READY_CHECK_SECONDS",
]
