# MediaPipelineRemuxEncodeAIO config template for new-user deployments.
# Copy or generate this as MediaPipeline_config.psd1 with the setup wizard.
# (Legacy operator copies named MediaPipeline_config_chatgpt.psd1 are still loaded as a fallback.)
# Keep operator-specific paths and machine-only tuning in the live config, not here.
@{
    ConfigSchemaVersion = 1
    SourceMovies = 'C:\MediaPipeline\Incoming\Movies'
    SourceTV = 'C:\MediaPipeline\Incoming\TV'
    Outsource = 'C:\MediaPipeline\Processed'
    LocalBase = 'C:\MediaPipeline\Scratch'
    EncodeThresholdGB = 8
    TVEncodeThresholdGB = 3
    RoutingProfile = 'plex_direct_stream'
    RouteThresholdMode = 'compatibility_advisory'
    MovieRouteMaxVideoBitrateMbps = 35
    TVRouteMaxVideoBitrateMbps = 18
    AllowH264RemuxIfPlexCompatible = $true
    H264RemuxMaxBitrateMbps = 35
    H264RemuxMaxHeight = 1080
    SizeGuardMode = 'advisory'
    MaxEncodeGrowthPercent = 5
    CompatibilityEncodeGrowthPercent = 15
    MinFreeSpaceGB = 50
    OutsourceMinFreeSpaceGB = 50
    DeferredPublish = $false
    FinalLibraryPromotionEnabled = $false
    FinalLibraryPromotionRules = @()
    FinalLibraryPromotionVerificationMode = 'cautious'
    FinalLibraryPromotionCleanupAfterVerified = $false
    FinalLibraryPromotionOverwriteExisting = $false
    VideoCodec = 'hevc_nvenc'
    VideoPreset = 'p7'
    VideoQuality = 22
    OutputContainer = 'mkv'
    EncodeTuningPreset = 'balanced_nvenc'
    EncodeLadder = 'auto'
    ExtraVideoFlags = @()
    AudioPassthroughProfile = 'plex_balanced'
    CompatibleAudioCodecs = @('aac', 'ac3', 'eac3', 'mp3', 'opus', 'vorbis', 'truehd', 'mlp')
    PreferredDefaultAudioLanguages = @('english')
    SubKeepLanguages = @('eng', 'en', 'und', '')
    ConvertTx3gToSrt = $true
    DropTx3gAfterConversion = $false
    CreateExternalTx3gSrtSidecars = $false
    Tx3gExtractLanguages = @('eng', 'en', 'und')
    Tx3gPreserveExistingSrt = $true
    Tx3gTreatForcedAsSeparate = $true
    ConvertBdpgsToSrt = $false
    DropBdpgsAfterConversion = $false
    BdpgsExtractLanguages = @('eng', 'en', 'und')
    BdpgsOcrToolPath = 'Tools\PgsToSrt\PgsToSrt.exe'
    BdpgsOcrTessdataPath = 'Tools\PgsToSrt\tessdata'
    SubSDHTitleKeywords = @('sdh', 'hearing impaired', 'hearing-impaired', 'cc', 'closed caption', 'closedcaption')
    SubSupplementalKeywords = @('sign', 'song', 'karaoke', 'chapter', 'opening', 'ending')
    DropAssAfterConversion = $false
    StripFormatting = $true
    RemoveKaraoke = $true
    MergeAdjacent = $true
    MergeThresholdMs = 150
    KeepSignsAndSongs = $true
    TreatAssSignsSongsAsForced = $false
    TreatTx3gSignsSongsAsForced = $false
    TreatBdpgsSignsSongsAsForced = $false
    ExcludeSubtitleStyles = @('Sign', 'Sign *', 'Sign-*', 'Signs', 'Signs *', 'Signs-*', 'OP', 'OP *', 'OP-*', 'OP_*', 'Opening*', 'ED', 'ED *', 'ED-*', 'ED_*', 'Ending*', '*Lyrics*', '*Romaji*', '*Kanji*', 'Song', 'Song *', 'Song-*', 'Title', 'Show Title', 'Episode Title', 'Next Episode', 'Next *', 'Credits', 'Credit*', 'Note', 'Note*', 'Caption', 'Caption*', 'fs')
    IncludeSubtitleStyles = @()
    RemuxSafeVideoCodecs = @('hevc', 'h265', 'h.265')
    ValidExtensions = @('.mkv', '.mp4', '.avi', '.mov', '.m4v', '.ts', '.m2ts')
    FileStabilityWait = 15
    SkipStabilityCheck = $false
    EnableIntegrityCheck = $true
    CreateTVSubfolder = $true
    AggressiveEpisodeParsing = $false
    RobocopyFlags = @('/J', '/R:3', '/W:15', '/MT:2', '/NP', '/NDL', '/NFL')
    DebugMode = $true
    LogRetentionDays = 7
    PriorityMarkers = @('!', '[NOW]')
    MaxParallelEncodes = 1
    ParallelEncodeMode = 'single'
    FallbackCpuQuality = 20
    CpuEncodePreset = 'medium'
    CpuEncodeProcessPriority = 'belownormal'
    CpuEncodeMaxThreads = 0
    OutputSizeMultiplier = 0.7
    FFmpegEncodeTimeoutSeconds = 21600
    FFmpegCpuEncodeTimeoutSeconds = 43200
    FFmpegRemuxTimeoutSeconds = 7200
    MkvmergeRemuxTimeoutSeconds = 7200
    SubtitleExtractTimeoutSeconds = 180
    SubtitleProbeTimeoutSeconds = 30
    BdpgsOcrTimeoutSeconds = 1800
    OutputValidationProbeTimeoutSeconds = 60
    OutputValidationMinSizeBytes = 1024
    OutputValidationDurationToleranceSeconds = 2
    AllowSystemTools = $false
    RobocopyTimeoutSeconds = 14400
    TransientFailureRetryLimit = 3
    SourceScanTimeoutSeconds = 1800
    IndexScanTimeoutSeconds = 1800
    CleanupScanTimeoutSeconds = 300
    CleanupRemoteStaging = $false
    CleanupStaleAgeHours = 24
    SourceScanIntervalSeconds = 300
    ProcessedIndexRefreshSeconds = 900
    ReprocessAll = $false
}
