# ==============================================================================
# ops\pipeline\engine\shared\versioning.ps1
# ==============================================================================
# Central version semantics. ProductVersion is operator-facing and feeds
# desktop/WebView labels. It is read from ops\release\metadata\VERSION so the
# release identity is generated by change-control tooling instead of hardcoded
# product-line labels. Sidecar and audit versions remain compatibility/schema
# gates and must not be bumped just because the desktop release label changes.
# ==============================================================================

function Get-MediaPipelineRepositoryRoot {
    if ($PSScriptRoot) {
        return [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..\..\..'))
    }
    return [System.IO.Path]::GetFullPath((Get-Location).Path)
}

function Get-MediaPipelineReleaseLabel {
    $root = Get-MediaPipelineRepositoryRoot
    $versionFile = Join-Path $root 'ops\release\metadata\VERSION'
    if (Test-Path -LiteralPath $versionFile -PathType Leaf) {
        $label = (Get-Content -LiteralPath $versionFile -Raw).Trim()
        if ($label) { return $label }
    }
    return '2026.06.04.001'
}

function Get-MediaPipelineProductVersion {
    return Get-MediaPipelineReleaseLabel
}

function Get-MediaPipelineSidecarVersion {
    return '1.0'
}

function Get-MediaPipelineAuditSchemaVersion {
    return '1.0'
}

function Get-MediaPipelineVersionInfo {
    return [pscustomobject]@{
        ProductVersion         = Get-MediaPipelineProductVersion
        PipelineSidecarVersion = Get-MediaPipelineSidecarVersion
        AuditSchemaVersion     = Get-MediaPipelineAuditSchemaVersion
    }
}
