"""Choice metadata for list-like settings controls."""

from __future__ import annotations


CONFIG_LIST_CHOICES = {
    "CompatibleAudioCodecs": (
        ("aac", "AAC"),
        ("ac3", "Dolby Digital"),
        ("eac3", "Dolby Digital Plus"),
        ("mp3", "MP3"),
        ("opus", "Opus"),
        ("vorbis", "Vorbis"),
        ("flac", "FLAC"),
        ("truehd", "Dolby TrueHD"),
        ("mlp", "Meridian Lossless Packing"),
        ("dts", "DTS"),
        ("dts_hd_ma", "DTS-HD MA"),
        ("dts-hd", "DTS-HD"),
        ("pcm_s16le", "PCM 16-bit"),
        ("pcm_s24le", "PCM 24-bit"),
    ),
    "PreferredDefaultAudioLanguages": (
        ("english", "English"),
        ("unknown", "Unknown / undefined"),
        ("japanese", "Japanese"),
        ("spanish", "Spanish"),
        ("french", "French"),
        ("german", "German"),
        ("italian", "Italian"),
        ("portuguese", "Portuguese"),
        ("russian", "Russian"),
        ("korean", "Korean"),
        ("chinese", "Chinese"),
    ),
    "RemuxSafeVideoCodecs": (
        ("hevc", "HEVC / H.265"),
        ("h265", "H.265 alias"),
        ("h.265", "H.265 dotted alias"),
        ("h264", "AVC / H.264"),
        ("avc", "AVC alias"),
        ("av1", "AV1"),
    ),
    "SubKeepLanguages": (
        ("eng", "English (eng)"),
        ("en", "English short tag (en)"),
        ("und", "Undefined (und)"),
        ("", "Blank tag"),
        ("jpn", "Japanese (jpn)"),
        ("ja", "Japanese short tag (ja)"),
        ("spa", "Spanish (spa)"),
        ("es", "Spanish short tag (es)"),
        ("fre", "French (fre)"),
        ("fra", "French alt tag (fra)"),
        ("ger", "German (ger)"),
        ("deu", "German alt tag (deu)"),
        ("ita", "Italian (ita)"),
    ),
    "Tx3gExtractLanguages": (
        ("eng", "English (eng)"),
        ("en", "English short tag (en)"),
        ("und", "Undefined (und)"),
        ("", "Blank tag"),
        ("jpn", "Japanese (jpn)"),
        ("ja", "Japanese short tag (ja)"),
        ("spa", "Spanish (spa)"),
        ("es", "Spanish short tag (es)"),
        ("fre", "French (fre)"),
        ("fra", "French alt tag (fra)"),
        ("ger", "German (ger)"),
        ("deu", "German alt tag (deu)"),
        ("ita", "Italian (ita)"),
    ),
    "BdpgsExtractLanguages": (
        ("eng", "English (eng)"),
        ("en", "English short tag (en)"),
        ("und", "Undefined (und)"),
        ("", "Blank tag"),
        ("jpn", "Japanese (jpn)"),
        ("ja", "Japanese short tag (ja)"),
        ("spa", "Spanish (spa)"),
        ("es", "Spanish short tag (es)"),
        ("fre", "French (fre)"),
        ("fra", "French alt tag (fra)"),
        ("ger", "German (ger)"),
        ("deu", "German alt tag (deu)"),
        ("ita", "Italian (ita)"),
    ),
    "SubSDHTitleKeywords": (
        ("sdh", "sdh"),
        ("hearing impaired", "hearing impaired"),
        ("hearing-impaired", "hearing-impaired"),
        ("cc", "cc"),
        ("closed caption", "closed caption"),
        ("closedcaption", "closedcaption"),
        ("captions", "captions"),
        ("subs for deaf", "subs for deaf"),
        ("deaf", "deaf"),
        ("hoh", "hoh"),
        ("hi", "hi"),
        ("descriptive", "descriptive"),
    ),
    "SubSupplementalKeywords": (
        ("sign", "sign"),
        ("signs", "signs"),
        ("song", "song"),
        ("songs", "songs"),
        ("karaoke", "karaoke"),
        ("chapter", "chapter"),
        ("opening", "opening"),
        ("ending", "ending"),
        ("op", "op"),
        ("ed", "ed"),
        ("credits", "credits"),
        ("lyrics", "lyrics"),
        ("romaji", "romaji"),
        ("kanji", "kanji"),
        ("typeset", "typeset"),
        ("translation note", "translation note"),
        ("translator note", "translator note"),
        ("onscreen", "onscreen"),
        ("title card", "title card"),
        ("eyecatch", "eyecatch"),
        ("preview", "preview"),
    ),
    "ExcludeSubtitleStyles": (
        ("Sign", "Sign"),
        ("Sign *", "Sign *"),
        ("Sign-*", "Sign-*"),
        ("Signs", "Signs"),
        ("Signs *", "Signs *"),
        ("Signs-*", "Signs-*"),
        ("Song", "Song"),
        ("Song *", "Song *"),
        ("Song-*", "Song-*"),
        ("OP", "OP"),
        ("OP *", "OP *"),
        ("OP-*", "OP-*"),
        ("OP_*", "OP_*"),
        ("Opening*", "Opening*"),
        ("ED", "ED"),
        ("ED *", "ED *"),
        ("ED-*", "ED-*"),
        ("ED_*", "ED_*"),
        ("Ending*", "Ending*"),
        ("Insert", "Insert"),
        ("Insert *", "Insert *"),
        ("Insert-*", "Insert-*"),
        ("InsertSong", "InsertSong"),
        ("SignsSongs", "SignsSongs"),
        ("Typeset", "Typeset"),
        ("Typeset *", "Typeset *"),
        ("TS", "TS"),
        ("TS *", "TS *"),
        ("FX", "FX"),
        ("FX *", "FX *"),
        ("FX-*", "FX-*"),
        ("AltSign", "AltSign"),
        ("OnScreen", "OnScreen"),
        ("Onscreen", "Onscreen"),
        ("Location", "Location"),
        ("Title", "Title"),
        ("Show Title", "Show Title"),
        ("Episode Title", "Episode Title"),
        ("Next Episode", "Next Episode"),
        ("Next *", "Next *"),
        ("Preview", "Preview"),
        ("Preview *", "Preview *"),
        ("Recap", "Recap"),
        ("Eyecatch", "Eyecatch"),
        ("Credits", "Credits"),
        ("Credit*", "Credit*"),
        ("Note", "Note"),
        ("Note*", "Note*"),
        ("TL Note", "TL Note"),
        ("Translator Note", "Translator Note"),
        ("Caption", "Caption"),
        ("Caption*", "Caption*"),
        ("Commentary", "Commentary"),
        ("Ruby", "Ruby"),
        ("Furigana", "Furigana"),
        ("Kanji", "Kanji"),
        ("Romaji", "Romaji"),
        ("Lyrics", "Lyrics"),
        ("*Lyrics*", "*Lyrics*"),
        ("*Romaji*", "*Romaji*"),
        ("*Kanji*", "*Kanji*"),
        ("fs", "fs"),
    ),
    "IncludeSubtitleStyles": (
        ("Default", "Default"),
        ("Main", "Main"),
        ("Dialogue", "Dialogue"),
        ("Alt", "Alt"),
        ("Narration", "Narration"),
        ("Forced", "Forced"),
        ("Signs", "Signs"),
        ("Songs", "Songs"),
    ),
    "PriorityMarkers": (
        ("!", "! immediate priority"),
    ),
}
