from __future__ import annotations

from .config_keys import (
    KEY_COORDINATOR_ALSO_ENCODE_LOCALLY,
    KEY_COORDINATOR_AUTH_TOKEN,
    KEY_COORDINATOR_BIND_ADDRESS,
    KEY_COORDINATOR_HEARTBEAT_TIMEOUT_MINS,
    KEY_COORDINATOR_PORT,
    KEY_NETWORK_ROLE,
    KEY_WORKER_AUTH_TOKEN,
    KEY_WORKER_CONFIG_OVERRIDES,
    KEY_WORKER_COORDINATOR_URL,
    KEY_WORKER_NAME,
    KEY_WORKER_POLL_INTERVAL_SECS,
    KEY_WORKER_SOURCE_PATH_MAP,
)
from .config_schema_support import (
    AUDIO_DOWNMIX_MODE_DESCRIPTIONS,
    AUDIO_MAX_CHANNEL_DESCRIPTIONS,
    AUDIO_TRANSCODE_CODEC_DESCRIPTIONS,
    AUDIT_TREE_COLUMNS,
    ENCODE_LADDER_DESCRIPTIONS,
    ENCODE_TUNING_PRESET_DESCRIPTIONS,
    FAILURE_TREE_COLUMNS,
    QUEUE_TREE_COLUMNS,
)
from .config_schema_choices import CONFIG_LIST_CHOICES
from .config_schema_layout import CONFIG_SECTION_ORDER, SETTING_PAGE_ORDER
from .config_schema_network import NETWORK_CONFIG_DEFAULTS, NETWORK_ROLE_CHOICES
from .service_constants import (
    AUDIO_PASSTHROUGH_PROFILE_CODECS,
    AUDIO_PASSTHROUGH_PROFILE_DEFAULT,
    AUDIO_PASSTHROUGH_PROFILE_DESCRIPTIONS,
    AUDIO_PASSTHROUGH_PROFILE_NAMES,
    LOG_LEVEL_VALUES,
    ROUTING_PROFILE_DEFAULT,
    ROUTING_PROFILE_DESCRIPTIONS,
    ROUTING_PROFILE_NAMES,
    SIZE_GUARD_MODE_DEFAULT,
    SIZE_GUARD_MODE_DESCRIPTIONS,
    SIZE_GUARD_MODE_NAMES,
)


DEFAULT_AUDIT_ROOT = r"\\LAYNE-SERVER\Video"
CONFIG_SCHEMA_VERSION = 1

CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Basic",
        "section": "Paths",
        "key": "SourceMovies",
        "label": "Movies Source",
        "kind": "path",
        "help": "Folder the pipeline scans for incoming movie files.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "SourceTV",
        "label": "TV Source",
        "kind": "path",
        "help": "Folder the pipeline scans for incoming TV files.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "Outsource",
        "label": "Final Output",
        "kind": "path",
        "help": "Final processed library destination.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "LocalBase",
        "label": "Scratch Disk",
        "kind": "path",
        "help": "Fast local working directory for copies, remuxes, and temporary files.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "CreateTVSubfolder",
        "label": "Create TV Library Folders",
        "kind": "bool",
        "help": "When enabled, TV outputs are placed under TV\\Show\\Season NN style folders for Plex-style libraries.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioPassthroughProfile",
        "label": "Audio Passthrough Profile",
        "kind": "combo",
        "choices": AUDIO_PASSTHROUGH_PROFILE_NAMES,
        "default": AUDIO_PASSTHROUGH_PROFILE_DEFAULT,
        "choice_help": AUDIO_PASSTHROUGH_PROFILE_DESCRIPTIONS,
        "help": "Structured policy for which audio codecs can be copied. Use custom_codec_list only when you need manual codec control.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "CompatibleAudioCodecs",
        "label": "Custom Audio Passthrough Codecs",
        "kind": "list",
        "help": "Manual codecs copied only when Audio Passthrough Profile is custom_codec_list. Structured profiles populate this list on save.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "PreferredDefaultAudioLanguages",
        "label": "Preferred Default Audio Languages",
        "kind": "list",
        "help": "Ordered language preference for the default audio track. If none of these are present, the highest-fidelity non-commentary track is chosen. The text field controls the exact order.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioTranscodeCodec",
        "label": "Transcode Codec",
        "kind": "combo",
        "choices": ("eac3", "ac3", "aac"),
        "default": "eac3",
        "choice_help": AUDIO_TRANSCODE_CODEC_DESCRIPTIONS,
        "help": "Codec used when an audio track must be normalized instead of copied.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioTranscodeBitrate",
        "label": "Transcode Bitrate",
        "kind": "combo",
        "choices": ("384k", "448k", "640k", "768k"),
        "default": "640k",
        "help": "Bitrate used for normalized audio tracks. Ignored when 'Auto Bitrate by Channels' is on.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioTranscodeAutoBitrateByChannels",
        "label": "Auto Bitrate by Channels",
        "kind": "bool",
        "default": False,
        "help": "When on, audio transcode bitrate is picked from a codec/channel-count table (e.g. 192k for 2.0 EAC3, 448k for 5.1 EAC3, 640k for 7.1 EAC3) instead of the static 'Transcode Bitrate' value. Saves space on commentary / stereo tracks; gives 7.1 mixes more bit pool.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioDownmixMode",
        "label": "Downmix Mode",
        "kind": "combo",
        "choices": ("max_channels", "preserve", "stereo"),
        "default": "max_channels",
        "choice_help": AUDIO_DOWNMIX_MODE_DESCRIPTIONS,
        "help": "Controls channel count when audio is transcoded: cap to the maximum, preserve source channels, or force stereo.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioMaxChannels",
        "label": "Max Channels",
        "kind": "combo_int",
        "choices": ("2", "6", "8"),
        "default": 6,
        "choice_help": AUDIO_MAX_CHANNEL_DESCRIPTIONS,
        "help": "Maximum channels for transcodes when Downmix Mode is max_channels.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AllowNoAudio",
        "label": "Allow No-Audio Outputs",
        "kind": "bool",
        "default": False,
        "help": "Permit silent source files to be processed without audio. Leave off for normal Plex media.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "EncodeThresholdGB",
        "label": "Movie Encode Threshold (GB)",
        "kind": "int",
        "default": 8,
        "help": "Movie files larger than this are candidates for encode instead of remux.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "TVEncodeThresholdGB",
        "label": "TV Encode Threshold (GB)",
        "kind": "int",
        "default": 3,
        "help": "TV files larger than this are candidates for encode instead of remux.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "RoutingProfile",
        "label": "Routing Profile",
        "kind": "combo",
        "choices": ROUTING_PROFILE_NAMES,
        "default": ROUTING_PROFILE_DEFAULT,
        "choice_help": ROUTING_PROFILE_DESCRIPTIONS,
        "help": "High-level remux vs encode policy. Plex Direct/Stream is the default for avoiding unnecessary re-encodes of compatible sources.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "AllowH264RemuxIfPlexCompatible",
        "label": "Copy Compatible H.264",
        "kind": "bool",
        "default": True,
        "help": "Allow low-risk H.264/AVC sources to stay remux/copy when bitrate, resolution, and Plex compatibility are acceptable.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "H264RemuxMaxBitrateMbps",
        "label": "H.264 Copy Max Mbps",
        "kind": "int",
        "default": 35,
        "help": "Maximum estimated source bitrate for the compatible-H.264 copy path.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "H264RemuxMaxHeight",
        "label": "H.264 Copy Max Height",
        "kind": "combo_int",
        "choices": ("720", "1080", "2160"),
        "default": 1080,
        "help": "Maximum video height allowed for the compatible-H.264 copy path.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "SizeGuardMode",
        "label": "Encode Size Guard",
        "kind": "combo",
        "choices": SIZE_GUARD_MODE_NAMES,
        "default": SIZE_GUARD_MODE_DEFAULT,
        "choice_help": SIZE_GUARD_MODE_DESCRIPTIONS,
        "help": "Controls whether encoded outputs that grow past the configured percentage are warned, rejected, or ignored.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "MaxEncodeGrowthPercent",
        "label": "Normal Growth Limit %",
        "kind": "int",
        "default": 5,
        "help": "Allowed output growth for normal encodes before the size guard warns or blocks.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "CompatibilityEncodeGrowthPercent",
        "label": "Compatibility Growth Limit %",
        "kind": "int",
        "default": 15,
        "help": "Allowed output growth when encoding for a stricter compatibility route.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "DeferredPublish",
        "label": "Deferred Publish",
        "kind": "bool",
        "help": "Park completed outputs locally instead of uploading them immediately. Use the recovery action to publish parked outputs later.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "AggressiveEpisodeParsing",
        "label": "Aggressive Episode Parsing",
        "kind": "bool",
        "help": "Use folder season hints and loose anime/import filename patterns to build SxxEyy when strict parsing fails.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoCodec",
        "label": "Hardware / Codec",
        "kind": "combo",
        "choices": ("hevc_nvenc", "libx265", "h264_nvenc", "libx264", "av1_nvenc"),
        "help": "Primary video output path used for encode jobs.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoPreset",
        "label": "Preset",
        "kind": "combo",
        "choices": ("p1", "p2", "p3", "p4", "p5", "p6", "p7"),
        "help": "NVENC preset. p1 is fastest with the weakest compression efficiency. p7 is slowest with the best compression efficiency.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoQuality",
        "label": "Quality",
        "kind": "combo_int",
        "choices": ("18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"),
        "default": 22,
        "help": "CQ/CRF-style target. Lower is cleaner and larger. Higher is softer and smaller.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "OutputContainer",
        "label": "Container",
        "kind": "combo",
        "choices": ("mkv", "mp4"),
        "help": "Final container format for encoded outputs.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "EncodeTuningPreset",
        "label": "Encode Tuning Preset",
        "kind": "combo",
        "choices": ("balanced_nvenc", "quality_nvenc", "fast_nvenc", "compatibility", "custom_legacy_flags"),
        "default": "balanced_nvenc",
        "choice_help": ENCODE_TUNING_PRESET_DESCRIPTIONS,
        "help": "Structured NVENC tuning profile. Use custom_legacy_flags only when you intentionally need raw ExtraVideoFlags.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "EncodeLadder",
        "label": "Encode Ladder",
        "kind": "combo",
        "choices": ("auto", "tv_balanced", "tv_space_saver", "movie_balanced", "movie_archive", "plex_compat"),
        "default": "auto",
        "choice_help": ENCODE_LADDER_DESCRIPTIONS,
        "help": "Structured output target. Auto picks a TV or movie profile; plex_compat uses conservative bitrate and compatibility flags.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "ExtraVideoFlags",
        "label": "Legacy Extra Video Flags",
        "kind": "list",
        "help": "Raw ffmpeg/NVENC flags used only when Encode Tuning Preset is custom_legacy_flags or when loading an old config without a preset.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "RemuxSafeVideoCodecs",
        "label": "Remux-Safe Video Codecs",
        "kind": "list",
        "help": "Video codecs the pipeline may remux directly without re-encoding.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "FallbackCpuQuality",
        "label": "CPU Fallback Quality",
        "kind": "optional_int",
        "help": "Optional quality target used when GPU encoding falls back to CPU. Note: this is a libx265 -crf value, not an NVENC -cq, so a value tuned for NVENC may produce a different size on CPU.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodePreset",
        "label": "CPU Encode Preset",
        "kind": "combo",
        "choices": (
            "ultrafast", "superfast", "veryfast", "faster", "fast",
            "medium", "slow", "slower", "veryslow", "placebo",
        ),
        "default": "medium",
        "help": "libx265 -preset used for CPU encodes (fallback or primary). Faster presets are responsive but lose quality; slower presets compress better but can run for many hours.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodeProcessPriority",
        "label": "CPU Encode Process Priority",
        "kind": "combo",
        "choices": ("inherit", "idle", "belownormal", "normal", "abovenormal", "high"),
        "default": "belownormal",
        "help": "Windows process priority class applied to ffmpeg when running a CPU encode. BelowNormal keeps the desktop UI responsive while libx265 saturates the cores.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "FFmpegCpuEncodeTimeoutSeconds",
        "label": "CPU Encode Timeout (seconds)",
        "kind": "int",
        "default": 43200,
        "help": "Hard ceiling for ffmpeg CPU encode wall-clock time. CPU encodes can take 5-15x longer than NVENC, so this should usually be larger than the GPU timeout.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "MkvmergeRemuxTimeoutSeconds",
        "label": "Mkvmerge Remux Timeout (seconds)",
        "kind": "int",
        "default": 7200,
        "help": "Hard ceiling for the mkvmerge step of a remux job. Defaults to 2 hours, matching the ffmpeg-remux timeout. Replaces a former hard-coded 600s ceiling that was too short for large MKVs over slow scratch volumes.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodeMaxThreads",
        "label": "CPU Encode Max Threads",
        "kind": "int",
        "default": 0,
        "help": "Maximum number of libx265 threads. 0 = autodetect (use every logical core, default libav behavior). Setting a positive value caps both ffmpeg -threads and the libx265 pool/frame-thread budget so the desktop UI stays responsive on smaller CPUs.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "SubKeepLanguages",
        "label": "Subtitle Languages",
        "kind": "list",
        "help": "Subtitle languages to keep during remux/cleanup.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "ConvertTx3gToSrt",
        "label": "Convert TX3G to SRT",
        "kind": "bool",
        "help": "Convert embedded MP4 Timed Text / mov_text subtitle tracks to SRT tracks during output muxing.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "DropTx3gAfterConversion",
        "label": "Drop TX3G After Conversion",
        "kind": "bool",
        "help": "Drop the original TX3G track after conversion. When disabled, FFmpeg MP4 outputs keep the original TX3G track when the container supports it.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "CreateExternalTx3gSrtSidecars",
        "label": "Write TX3G SRT Sidecars",
        "kind": "bool",
        "help": "Also write external TX3G-derived SRT files next to the output. Converted subtitles are still muxed into the output when conversion is enabled.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "Tx3gExtractLanguages",
        "label": "TX3G Extract Languages",
        "kind": "list",
        "help": "Language tags eligible for tx3g-to-SRT extraction. Undefined tracks use und.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "Tx3gPreserveExistingSrt",
        "label": "Preserve Existing TX3G SRTs",
        "kind": "bool",
        "help": "Leave matching external SRT files in place unless full reprocessing is explicitly enabled.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "Tx3gTreatForcedAsSeparate",
        "label": "Separate Forced TX3G",
        "kind": "bool",
        "help": "Include forced status in tx3g SRT filenames so forced and full subtitles do not collide.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "ConvertBdpgsToSrt",
        "label": "OCR BDPGS to SRT",
        "kind": "bool",
        "help": "OCR Blu-ray PGS image subtitles to SRT tracks using an external PgsToSrt-compatible tool.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "DropBdpgsAfterConversion",
        "label": "Drop BDPGS After OCR",
        "kind": "bool",
        "help": "Drop the original BDPGS image subtitle after OCR conversion. When disabled, MKV outputs keep the original image subtitle track.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "BdpgsExtractLanguages",
        "label": "BDPGS OCR Languages",
        "kind": "list",
        "help": "Language tags eligible for BDPGS OCR. Undefined tracks use und.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "BdpgsOcrToolPath",
        "label": "BDPGS OCR Tool",
        "kind": "string",
        "help": "Path to PgsToSrt.exe or PgsToSrt.dll. Relative paths are resolved from the Pipeline folder.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "BdpgsOcrTessdataPath",
        "label": "BDPGS Tessdata",
        "kind": "string",
        "help": "Optional Tesseract tessdata folder for BDPGS OCR.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "DropAssAfterConversion",
        "label": "Drop ASS After Conversion",
        "kind": "bool",
        "help": "Remove the original ASS track after an SRT conversion when enabled.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "RemoveKaraoke",
        "label": "Filter Karaoke Styling",
        "kind": "bool",
        "help": "Exclude karaoke-style events during ASS to SRT conversion.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "KeepSignsAndSongs",
        "label": "Keep Signs & Songs",
        "kind": "bool",
        "help": "Preserve supplemental Signs & Songs subtitle tracks as separate tracks.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "TreatAssSignsSongsAsForced",
        "label": "ASS Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark ASS/SSA supplemental Signs & Songs tracks as forced when they are kept or converted.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "TreatTx3gSignsSongsAsForced",
        "label": "TX3G Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark TX3G supplemental Signs & Songs tracks as forced when converted.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "TreatBdpgsSignsSongsAsForced",
        "label": "BDPGS Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark BDPGS supplemental Signs & Songs tracks as forced when kept or OCR-converted.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "StripFormatting",
        "label": "Strip ASS Formatting",
        "kind": "bool",
        "help": "Remove inline ASS formatting when converting to SRT.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "MergeAdjacent",
        "label": "Merge Adjacent Cues",
        "kind": "bool",
        "help": "Merge neighboring subtitle cues that are separated by a very small gap.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "MergeThresholdMs",
        "label": "Subtitle Merge Threshold (ms)",
        "kind": "int",
        "default": 150,
        "help": "Maximum subtitle cue gap for adjacent merge logic.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "SubSDHTitleKeywords",
        "label": "SDH Title Keywords",
        "kind": "list",
        "help": "Keywords used to identify SDH / hearing-impaired subtitle tracks.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "SubSupplementalKeywords",
        "label": "Supplemental Title Keywords",
        "kind": "list",
        "help": "Keywords used to identify sign/song/supplemental subtitle tracks.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "ExcludeSubtitleStyles",
        "label": "Excluded Subtitle Styles",
        "kind": "list",
        "help": "ASS style names or patterns that should be filtered out during conversion.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "IncludeSubtitleStyles",
        "label": "Included Subtitle Styles",
        "kind": "list",
        "help": "Optional allowlist of ASS style names or patterns to keep.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "DebugMode",
        "label": "Verbose Debug Logging",
        "kind": "bool",
        "help": "Enable more detailed pipeline debug output.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "ConsoleLogLevel",
        "label": "Console Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "Console log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "FileLogLevel",
        "label": "File Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "File log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "LogRetentionDays",
        "label": "Log Retention Days",
        "kind": "int",
        "default": 7,
        "help": "Number of days to keep rotated pipeline log files.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinFreeSpaceGB",
        "label": "Scratch Free Space Reserve (GB)",
        "kind": "int",
        "default": 50,
        "help": "Minimum free space reserved on the scratch drive.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutsourceMinFreeSpaceGB",
        "label": "Output Free Space Reserve (GB)",
        "kind": "int",
        "default": 50,
        "help": "Minimum free space reserved on the output destination.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegEncodeTimeoutSeconds",
        "label": "Encode Timeout (s)",
        "kind": "int",
        "default": 21600,
        "help": "Kill threshold for ffmpeg encode jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegRemuxTimeoutSeconds",
        "label": "Remux Timeout (s)",
        "kind": "int",
        "default": 7200,
        "help": "Kill threshold for ffmpeg remux jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleExtractTimeoutSeconds",
        "label": "Subtitle Extract Timeout (s)",
        "kind": "int",
        "default": 180,
        "help": "Kill threshold for ASS/tx3g subtitle extraction helpers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleProbeTimeoutSeconds",
        "label": "Subtitle Probe Timeout (s)",
        "kind": "int",
        "default": 30,
        "help": "Kill threshold for subtitle stream probing commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "BdpgsOcrTimeoutSeconds",
        "label": "BDPGS OCR Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Kill threshold for external BDPGS OCR commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "AllowSystemTools",
        "label": "Allow PATH Tool Fallback",
        "kind": "bool",
        "help": "Developer-only fallback. Leave off so the portable bundle requires its bundled FFmpeg, ffprobe, mkvmerge, and Python.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyTimeoutSeconds",
        "label": "Copy Timeout (s)",
        "kind": "int",
        "default": 14400,
        "help": "Kill threshold for robocopy source, scratch, and publish transfers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "TransientFailureRetryLimit",
        "label": "Transient Failure Retry Limit",
        "kind": "int",
        "default": 3,
        "help": "Repeated matching transient failures escalate to operator_required at this count.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinPipelineVersion",
        "label": "Minimum Pipeline Version",
        "kind": "optional_string",
        "help": "Optional version floor used for reprocess decisions.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputSizeMultiplier",
        "label": "Output Size Multiplier",
        "kind": "optional_float",
        "help": "Optional size safety multiplier for route validation.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "EnableIntegrityCheck",
        "label": "Enable Integrity Check",
        "kind": "bool",
        "help": "Probe source media before processing so corrupt or incomplete files can be held back.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyFlags",
        "label": "Robocopy Flags",
        "kind": "list",
        "help": "Flags used for source-to-scratch and scratch-to-output robocopy transfers. Keep retries, waits, and logging flags explicit.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "PriorityMarkers",
        "label": "Priority Markers",
        "kind": "list",
        "help": "Filename or folder prefixes used to force priority queue placement.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "SourceScanIntervalSeconds",
        "label": "Source Scan Refresh (s)",
        "kind": "int",
        "default": 300,
        "help": "How often the pipeline scans incoming source folders.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "SourceScanTimeoutSeconds",
        "label": "Source Scan Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Maximum time allowed for each source library scan.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "ProcessedIndexRefreshSeconds",
        "label": "Processed Index Refresh (s)",
        "kind": "int",
        "default": 900,
        "help": "How often the pipeline refreshes its processed output index.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "ReprocessAll",
        "label": "Force One Reprocess Pass",
        "kind": "bool",
        "help": "When enabled, previously completed outputs are reconsidered for one complete pass; use only for deliberate rerun testing.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "IndexScanTimeoutSeconds",
        "label": "Index Scan Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Maximum time allowed for processed index scanning.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "CleanupScanTimeoutSeconds",
        "label": "Cleanup Scan Timeout (s)",
        "kind": "int",
        "default": 300,
        "help": "Maximum time allowed for startup partial/staging cleanup scans.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "ValidExtensions",
        "label": "Valid Media Extensions",
        "kind": "list",
        "help": "File extensions considered media candidates during source discovery.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "CleanupRemoteStaging",
        "label": "Clean Remote Staging",
        "kind": "bool",
        "help": "Allow startup cleanup scans against remote outsource paths. Leave off for normal daily use.",
    },
    {
        "page": "Queue",
        "section": "Queue",
        "key": "CleanupStaleAgeHours",
        "label": "Cleanup Age (h)",
        "kind": "int",
        "default": 24,
        "help": "Minimum age before partial or staging artifacts are removed by startup cleanup.",
    },
    # ------------------------------------------------------------------
    # Network mode fields (Phase 0 — auto-rendered as plain fields;
    # replaced by a hand-built panel in Phase 1)
    # ------------------------------------------------------------------
    {
        "page": "Network",
        "section": "Role",
        "key": KEY_NETWORK_ROLE,
        "label": "Network Role",
        "kind": "combo",
        "choices": ("standalone", "coordinator", "worker"),
        "help": (
            "standalone: one machine, all files local — current behaviour, no change. "
            "coordinator: this machine manages the queue and hands out work via HTTP. "
            "worker: this machine polls a coordinator for files to encode."
        ),
    },
    {
        "page": "Network",
        "section": "Coordinator",
        "key": KEY_COORDINATOR_PORT,
        "label": "Listen Port",
        "kind": "int",
        "default": 7830,
        "help": "TCP port the coordinator HTTP server listens on (default 7830). Workers must use the same port.",
    },
    {
        "page": "Network",
        "section": "Coordinator",
        "key": KEY_COORDINATOR_BIND_ADDRESS,
        "label": "Bind Address",
        "kind": "string",
        "default": "0.0.0.0",
        "help": "Interface address for the plaintext coordinator HTTP API. Use 0.0.0.0 for trusted LAN workers, or 127.0.0.1 for local-only testing.",
    },
    {
        "page": "Network",
        "section": "Coordinator",
        "key": KEY_COORDINATOR_ALSO_ENCODE_LOCALLY,
        "label": "Also Encode Locally",
        "kind": "bool",
        "help": "When enabled, the coordinator also takes files from its own queue and encodes them (requires a GPU). When disabled it only hands out work to remote workers.",
    },
    {
        "page": "Network",
        "section": "Coordinator",
        "key": KEY_COORDINATOR_HEARTBEAT_TIMEOUT_MINS,
        "label": "Heartbeat Timeout (min)",
        "kind": "int",
        "default": 5,
        "help": "Minutes without a heartbeat before a claimed job is considered stale and re-queued for another worker (default 5).",
    },
    {
        "page": "Network",
        "section": "Coordinator",
        "key": KEY_COORDINATOR_AUTH_TOKEN,
        "label": "Auth Token",
        "kind": "string",
        "help": "Shared bearer token. Leave blank for auto-generation on first coordinator-mode start. Must match WorkerAuthToken on all workers.",
    },
    {
        "page": "Network",
        "section": "Worker",
        "key": KEY_WORKER_COORDINATOR_URL,
        "label": "Coordinator URL",
        "kind": "string",
        "help": "Full URL of the coordinator, e.g. http://192.168.1.50:7830. Only used when NetworkRole is 'worker'.",
    },
    {
        "page": "Network",
        "section": "Worker",
        "key": KEY_WORKER_NAME,
        "label": "Worker Name",
        "kind": "string",
        "help": "Human-readable label shown in the coordinator's worker board. Defaults to the machine hostname when left blank.",
    },
    {
        "page": "Network",
        "section": "Worker",
        "key": KEY_WORKER_AUTH_TOKEN,
        "label": "Auth Token",
        "kind": "string",
        "help": "Must match the coordinator's CoordinatorAuthToken. Only used when NetworkRole is 'worker'.",
    },
    {
        "page": "Network",
        "section": "Worker",
        "key": KEY_WORKER_POLL_INTERVAL_SECS,
        "label": "Poll Interval (s)",
        "kind": "int",
        "default": 10,
        "help": "Seconds between coordinator polls when the queue is empty (default 10).",
    },
    {
        "page": "Network",
        "section": "Worker",
        "key": KEY_WORKER_SOURCE_PATH_MAP,
        "label": "Source Path Map",
        "kind": "string",
        "help": (
            'JSON object mapping coordinator paths → locally-accessible paths. '
            'Use when the coordinator hands out paths that this worker cannot reach '
            '(different drive letter, UNC vs local on the server, NFS vs SMB mount). '
            'Each key is matched as a prefix against the incoming source_path; the '
            'first prefix that matches gets rewritten. Backslashes must be escaped. '
            r'Example: {"C:\\Users\\Layne\\Videos\\Encode": "\\\\LAYNE-SERVER\\Users\\Layne\\Videos\\Encode"}'
        ),
    },
    {
        "page": "Network",
        "section": "Coordinator",
        "key": KEY_WORKER_CONFIG_OVERRIDES,
        "label": "Per-Worker Config Overrides",
        "kind": "string",
        "help": (
            'JSON object mapping worker names to partial config overrides. '
            'Applied when the coordinator builds ClaimResponse.encode_config. '
            'Example: {"BEAST-PC": {"VideoPreset": "p4"}, "LAPTOP": {"VideoPreset": "p2"}}'
        ),
    },
)

CONFIG_MANAGED_KEYS = [field["key"] for field in CONFIG_FIELD_DEFINITIONS]
