from __future__ import annotations

from typing import Final

# Canonical MediaPipeline PSD1 config keys used by the Python desktop host.
# Keep this aligned with app.contracts.config, app.config.metadata,
# engine/config/config_schema.ps1, and Docs/architecture/CONFIG_KEY_GLOSSARY.md.

KEY_CONFIG_SCHEMA_VERSION: Final = "ConfigSchemaVersion"
KEY_SOURCE_MOVIES: Final = "SourceMovies"
KEY_SOURCE_TV: Final = "SourceTV"
KEY_OUTSOURCE: Final = "Outsource"
KEY_LIBRARY_PROFILES: Final = "LibraryProfiles"
KEY_LOCAL_BASE: Final = "LocalBase"
KEY_ENCODE_THRESHOLD_GB: Final = "EncodeThresholdGB"
KEY_TV_ENCODE_THRESHOLD_GB: Final = "TVEncodeThresholdGB"
KEY_ROUTING_PROFILE: Final = "RoutingProfile"
KEY_ROUTE_THRESHOLD_MODE: Final = "RouteThresholdMode"
KEY_MOVIE_ROUTE_MAX_VIDEO_BITRATE_MBPS: Final = "MovieRouteMaxVideoBitrateMbps"
KEY_TV_ROUTE_MAX_VIDEO_BITRATE_MBPS: Final = "TVRouteMaxVideoBitrateMbps"
KEY_ALLOW_H264_REMUX_IF_PLEX_COMPATIBLE: Final = "AllowH264RemuxIfPlexCompatible"
KEY_H264_REMUX_MAX_BITRATE_MBPS: Final = "H264RemuxMaxBitrateMbps"
KEY_H264_REMUX_MAX_HEIGHT: Final = "H264RemuxMaxHeight"
KEY_SIZE_GUARD_MODE: Final = "SizeGuardMode"
KEY_MAX_ENCODE_GROWTH_PERCENT: Final = "MaxEncodeGrowthPercent"
KEY_COMPATIBILITY_ENCODE_GROWTH_PERCENT: Final = "CompatibilityEncodeGrowthPercent"
KEY_MIN_FREE_SPACE_GB: Final = "MinFreeSpaceGB"
KEY_OUTSOURCE_MIN_FREE_SPACE_GB: Final = "OutsourceMinFreeSpaceGB"
KEY_DEFERRED_PUBLISH: Final = "DeferredPublish"
KEY_FINAL_LIBRARY_PROMOTION_ENABLED: Final = "FinalLibraryPromotionEnabled"
KEY_FINAL_LIBRARY_PROMOTION_RULES: Final = "FinalLibraryPromotionRules"
KEY_FINAL_LIBRARY_PROMOTION_VERIFICATION_MODE: Final = "FinalLibraryPromotionVerificationMode"
KEY_FINAL_LIBRARY_PROMOTION_CLEANUP_AFTER_VERIFIED: Final = "FinalLibraryPromotionCleanupAfterVerified"
KEY_FINAL_LIBRARY_PROMOTION_OVERWRITE_EXISTING: Final = "FinalLibraryPromotionOverwriteExisting"
KEY_VIDEO_CODEC: Final = "VideoCodec"
KEY_VIDEO_PRESET: Final = "VideoPreset"
KEY_VIDEO_QUALITY: Final = "VideoQuality"
KEY_OUTPUT_CONTAINER: Final = "OutputContainer"
KEY_ENCODE_TUNING_PRESET: Final = "EncodeTuningPreset"
KEY_ENCODE_LADDER: Final = "EncodeLadder"
KEY_EXTRA_VIDEO_FLAGS: Final = "ExtraVideoFlags"
KEY_AUDIO_PASSTHROUGH_PROFILE: Final = "AudioPassthroughProfile"
KEY_COMPATIBLE_AUDIO_CODECS: Final = "CompatibleAudioCodecs"
KEY_PREFERRED_DEFAULT_AUDIO_LANGUAGES: Final = "PreferredDefaultAudioLanguages"
KEY_AUDIO_TRANSCODE_CODEC: Final = "AudioTranscodeCodec"
KEY_AUDIO_TRANSCODE_BITRATE: Final = "AudioTranscodeBitrate"
KEY_AUDIO_TRANSCODE_AUTO_BITRATE_BY_CHANNELS: Final = "AudioTranscodeAutoBitrateByChannels"
KEY_AUDIO_DOWNMIX_MODE: Final = "AudioDownmixMode"
KEY_AUDIO_MAX_CHANNELS: Final = "AudioMaxChannels"
KEY_ALLOW_NO_AUDIO: Final = "AllowNoAudio"
KEY_SUB_KEEP_LANGUAGES: Final = "SubKeepLanguages"
KEY_CONVERT_TX3G_TO_SRT: Final = "ConvertTx3gToSrt"
KEY_DROP_TX3G_AFTER_CONVERSION: Final = "DropTx3gAfterConversion"
KEY_CREATE_EXTERNAL_TX3G_SRT_SIDECARS: Final = "CreateExternalTx3gSrtSidecars"
KEY_TX3G_EXTRACT_LANGUAGES: Final = "Tx3gExtractLanguages"
KEY_TX3G_PRESERVE_EXISTING_SRT: Final = "Tx3gPreserveExistingSrt"
KEY_TX3G_TREAT_FORCED_AS_SEPARATE: Final = "Tx3gTreatForcedAsSeparate"
KEY_CONVERT_BDPGS_TO_SRT: Final = "ConvertBdpgsToSrt"
KEY_DROP_BDPGS_AFTER_CONVERSION: Final = "DropBdpgsAfterConversion"
KEY_BDPGS_EXTRACT_LANGUAGES: Final = "BdpgsExtractLanguages"
KEY_BDPGS_OCR_TOOL_PATH: Final = "BdpgsOcrToolPath"
KEY_BDPGS_OCR_TESSDATA_PATH: Final = "BdpgsOcrTessdataPath"
KEY_CONVERT_VOBSUB_TO_SRT: Final = "ConvertVobSubToSrt"
KEY_DROP_VOBSUB_AFTER_CONVERSION: Final = "DropVobSubAfterConversion"
KEY_VOBSUB_EXTRACT_LANGUAGES: Final = "VobSubExtractLanguages"
KEY_VOBSUB_OCR_TOOL_PATH: Final = "VobSubOcrToolPath"
KEY_SUB_SDH_TITLE_KEYWORDS: Final = "SubSDHTitleKeywords"
KEY_SUB_SUPPLEMENTAL_KEYWORDS: Final = "SubSupplementalKeywords"
KEY_DROP_ASS_AFTER_CONVERSION: Final = "DropAssAfterConversion"
KEY_STRIP_FORMATTING: Final = "StripFormatting"
KEY_REMOVE_KARAOKE: Final = "RemoveKaraoke"
KEY_MERGE_ADJACENT: Final = "MergeAdjacent"
KEY_MERGE_THRESHOLD_MS: Final = "MergeThresholdMs"
KEY_KEEP_SIGNS_AND_SONGS: Final = "KeepSignsAndSongs"
KEY_TREAT_ASS_SIGNS_SONGS_AS_FORCED: Final = "TreatAssSignsSongsAsForced"
KEY_TREAT_TX3G_SIGNS_SONGS_AS_FORCED: Final = "TreatTx3gSignsSongsAsForced"
KEY_TREAT_BDPGS_SIGNS_SONGS_AS_FORCED: Final = "TreatBdpgsSignsSongsAsForced"
KEY_TREAT_VOBSUB_SIGNS_SONGS_AS_FORCED: Final = "TreatVobSubSignsSongsAsForced"
KEY_EXCLUDE_SUBTITLE_STYLES: Final = "ExcludeSubtitleStyles"
KEY_INCLUDE_SUBTITLE_STYLES: Final = "IncludeSubtitleStyles"
KEY_REMUX_SAFE_VIDEO_CODECS: Final = "RemuxSafeVideoCodecs"
KEY_VALID_EXTENSIONS: Final = "ValidExtensions"
KEY_FILE_STABILITY_WAIT: Final = "FileStabilityWait"
KEY_SKIP_STABILITY_CHECK: Final = "SkipStabilityCheck"
KEY_ENABLE_INTEGRITY_CHECK: Final = "EnableIntegrityCheck"
KEY_CREATE_TV_SUBFOLDER: Final = "CreateTVSubfolder"
KEY_AGGRESSIVE_EPISODE_PARSING: Final = "AggressiveEpisodeParsing"
KEY_ROBOCOPY_FLAGS: Final = "RobocopyFlags"
KEY_DEBUG_MODE: Final = "DebugMode"
KEY_LOG_RETENTION_DAYS: Final = "LogRetentionDays"
KEY_PRIORITY_MARKERS: Final = "PriorityMarkers"
KEY_MIX_PRIORITY_PHASE: Final = "MixPriorityPhase"
KEY_QUEUE_ORDERING_STRATEGY: Final = "QueueOrderingStrategy"
KEY_CONSOLE_LOG_LEVEL: Final = "ConsoleLogLevel"
KEY_FILE_LOG_LEVEL: Final = "FileLogLevel"
KEY_MAX_PARALLEL_ENCODES: Final = "MaxParallelEncodes"
KEY_PARALLEL_ENCODE_MODE: Final = "ParallelEncodeMode"
KEY_FALLBACK_CPU_QUALITY: Final = "FallbackCpuQuality"
KEY_CPU_ENCODE_PRESET: Final = "CpuEncodePreset"
KEY_CPU_ENCODE_PROCESS_PRIORITY: Final = "CpuEncodeProcessPriority"
KEY_CPU_ENCODE_MAX_THREADS: Final = "CpuEncodeMaxThreads"
KEY_OUTPUT_SIZE_MULTIPLIER: Final = "OutputSizeMultiplier"
KEY_FFMPEG_ENCODE_TIMEOUT_SECONDS: Final = "FFmpegEncodeTimeoutSeconds"
KEY_FFMPEG_CPU_ENCODE_TIMEOUT_SECONDS: Final = "FFmpegCpuEncodeTimeoutSeconds"
KEY_FFMPEG_REMUX_TIMEOUT_SECONDS: Final = "FFmpegRemuxTimeoutSeconds"
KEY_MKVMERGE_REMUX_TIMEOUT_SECONDS: Final = "MkvmergeRemuxTimeoutSeconds"
KEY_SUBTITLE_EXTRACT_TIMEOUT_SECONDS: Final = "SubtitleExtractTimeoutSeconds"
KEY_SUBTITLE_PROBE_TIMEOUT_SECONDS: Final = "SubtitleProbeTimeoutSeconds"
KEY_BDPGS_OCR_TIMEOUT_SECONDS: Final = "BdpgsOcrTimeoutSeconds"
KEY_VOBSUB_OCR_TIMEOUT_SECONDS: Final = "VobSubOcrTimeoutSeconds"
KEY_OUTPUT_VALIDATION_PROBE_TIMEOUT_SECONDS: Final = "OutputValidationProbeTimeoutSeconds"
KEY_OUTPUT_VALIDATION_MIN_SIZE_BYTES: Final = "OutputValidationMinSizeBytes"
KEY_OUTPUT_VALIDATION_DURATION_TOLERANCE_SECONDS: Final = "OutputValidationDurationToleranceSeconds"
KEY_ALLOW_SYSTEM_TOOLS: Final = "AllowSystemTools"
KEY_ROBOCOPY_TIMEOUT_SECONDS: Final = "RobocopyTimeoutSeconds"
KEY_TRANSIENT_FAILURE_RETRY_LIMIT: Final = "TransientFailureRetryLimit"
KEY_INDEX_SCAN_TIMEOUT_SECONDS: Final = "IndexScanTimeoutSeconds"
KEY_SOURCE_SCAN_TIMEOUT_SECONDS: Final = "SourceScanTimeoutSeconds"
KEY_CLEANUP_SCAN_TIMEOUT_SECONDS: Final = "CleanupScanTimeoutSeconds"
KEY_CLEANUP_REMOTE_STAGING: Final = "CleanupRemoteStaging"
KEY_CLEANUP_STALE_AGE_HOURS: Final = "CleanupStaleAgeHours"
KEY_SOURCE_SCAN_INTERVAL_SECONDS: Final = "SourceScanIntervalSeconds"
KEY_PROCESSED_INDEX_REFRESH_SECONDS: Final = "ProcessedIndexRefreshSeconds"
KEY_MIN_PIPELINE_VERSION: Final = "MinPipelineVersion"
KEY_REPROCESS_ALL: Final = "ReprocessAll"
KEY_SHOW_OVERRIDES: Final = "ShowOverrides"
KEY_NETWORK_ROLE: Final = "NetworkRole"
KEY_COORDINATOR_PORT: Final = "CoordinatorPort"
KEY_COORDINATOR_BIND_ADDRESS: Final = "CoordinatorBindAddress"
KEY_COORDINATOR_ALSO_ENCODE_LOCALLY: Final = "CoordinatorAlsoEncodeLocally"
KEY_COORDINATOR_HEARTBEAT_TIMEOUT_MINS: Final = "CoordinatorHeartbeatTimeoutMins"
KEY_COORDINATOR_AUTH_TOKEN: Final = "CoordinatorAuthToken"
KEY_WORKER_COORDINATOR_URL: Final = "WorkerCoordinatorUrl"
KEY_WORKER_NAME: Final = "WorkerName"
KEY_WORKER_AUTH_TOKEN: Final = "WorkerAuthToken"
KEY_WORKER_POLL_INTERVAL_SECS: Final = "WorkerPollIntervalSecs"
KEY_WORKER_SOURCE_PATH_MAP: Final = "WorkerSourcePathMap"
KEY_WORKER_CONFIG_OVERRIDES: Final = "WorkerConfigOverrides"

CONFIG_KEY_ORDER: Final = (
    KEY_CONFIG_SCHEMA_VERSION,
    KEY_SOURCE_MOVIES,
    KEY_SOURCE_TV,
    KEY_OUTSOURCE,
    KEY_LIBRARY_PROFILES,
    KEY_LOCAL_BASE,
    KEY_ENCODE_THRESHOLD_GB,
    KEY_TV_ENCODE_THRESHOLD_GB,
    KEY_ROUTING_PROFILE,
    KEY_ROUTE_THRESHOLD_MODE,
    KEY_MOVIE_ROUTE_MAX_VIDEO_BITRATE_MBPS,
    KEY_TV_ROUTE_MAX_VIDEO_BITRATE_MBPS,
    KEY_ALLOW_H264_REMUX_IF_PLEX_COMPATIBLE,
    KEY_H264_REMUX_MAX_BITRATE_MBPS,
    KEY_H264_REMUX_MAX_HEIGHT,
    KEY_SIZE_GUARD_MODE,
    KEY_MAX_ENCODE_GROWTH_PERCENT,
    KEY_COMPATIBILITY_ENCODE_GROWTH_PERCENT,
    KEY_MIN_FREE_SPACE_GB,
    KEY_OUTSOURCE_MIN_FREE_SPACE_GB,
    KEY_DEFERRED_PUBLISH,
    KEY_FINAL_LIBRARY_PROMOTION_ENABLED,
    KEY_FINAL_LIBRARY_PROMOTION_RULES,
    KEY_FINAL_LIBRARY_PROMOTION_VERIFICATION_MODE,
    KEY_FINAL_LIBRARY_PROMOTION_CLEANUP_AFTER_VERIFIED,
    KEY_FINAL_LIBRARY_PROMOTION_OVERWRITE_EXISTING,
    KEY_VIDEO_CODEC,
    KEY_VIDEO_PRESET,
    KEY_VIDEO_QUALITY,
    KEY_OUTPUT_CONTAINER,
    KEY_ENCODE_TUNING_PRESET,
    KEY_ENCODE_LADDER,
    KEY_EXTRA_VIDEO_FLAGS,
    KEY_AUDIO_PASSTHROUGH_PROFILE,
    KEY_COMPATIBLE_AUDIO_CODECS,
    KEY_PREFERRED_DEFAULT_AUDIO_LANGUAGES,
    KEY_AUDIO_TRANSCODE_CODEC,
    KEY_AUDIO_TRANSCODE_BITRATE,
    KEY_AUDIO_TRANSCODE_AUTO_BITRATE_BY_CHANNELS,
    KEY_AUDIO_DOWNMIX_MODE,
    KEY_AUDIO_MAX_CHANNELS,
    KEY_ALLOW_NO_AUDIO,
    KEY_SUB_KEEP_LANGUAGES,
    KEY_CONVERT_TX3G_TO_SRT,
    KEY_DROP_TX3G_AFTER_CONVERSION,
    KEY_CREATE_EXTERNAL_TX3G_SRT_SIDECARS,
    KEY_TX3G_EXTRACT_LANGUAGES,
    KEY_TX3G_PRESERVE_EXISTING_SRT,
    KEY_TX3G_TREAT_FORCED_AS_SEPARATE,
    KEY_CONVERT_BDPGS_TO_SRT,
    KEY_DROP_BDPGS_AFTER_CONVERSION,
    KEY_BDPGS_EXTRACT_LANGUAGES,
    KEY_BDPGS_OCR_TOOL_PATH,
    KEY_BDPGS_OCR_TESSDATA_PATH,
    KEY_CONVERT_VOBSUB_TO_SRT,
    KEY_DROP_VOBSUB_AFTER_CONVERSION,
    KEY_VOBSUB_EXTRACT_LANGUAGES,
    KEY_VOBSUB_OCR_TOOL_PATH,
    KEY_SUB_SDH_TITLE_KEYWORDS,
    KEY_SUB_SUPPLEMENTAL_KEYWORDS,
    KEY_DROP_ASS_AFTER_CONVERSION,
    KEY_STRIP_FORMATTING,
    KEY_REMOVE_KARAOKE,
    KEY_MERGE_ADJACENT,
    KEY_MERGE_THRESHOLD_MS,
    KEY_KEEP_SIGNS_AND_SONGS,
    KEY_TREAT_ASS_SIGNS_SONGS_AS_FORCED,
    KEY_TREAT_TX3G_SIGNS_SONGS_AS_FORCED,
    KEY_TREAT_BDPGS_SIGNS_SONGS_AS_FORCED,
    KEY_TREAT_VOBSUB_SIGNS_SONGS_AS_FORCED,
    KEY_EXCLUDE_SUBTITLE_STYLES,
    KEY_INCLUDE_SUBTITLE_STYLES,
    KEY_REMUX_SAFE_VIDEO_CODECS,
    KEY_VALID_EXTENSIONS,
    KEY_FILE_STABILITY_WAIT,
    KEY_SKIP_STABILITY_CHECK,
    KEY_ENABLE_INTEGRITY_CHECK,
    KEY_CREATE_TV_SUBFOLDER,
    KEY_AGGRESSIVE_EPISODE_PARSING,
    KEY_ROBOCOPY_FLAGS,
    KEY_DEBUG_MODE,
    KEY_LOG_RETENTION_DAYS,
    KEY_PRIORITY_MARKERS,
    KEY_MIX_PRIORITY_PHASE,
    KEY_QUEUE_ORDERING_STRATEGY,
    KEY_CONSOLE_LOG_LEVEL,
    KEY_FILE_LOG_LEVEL,
    KEY_MAX_PARALLEL_ENCODES,
    KEY_PARALLEL_ENCODE_MODE,
    KEY_FALLBACK_CPU_QUALITY,
    KEY_CPU_ENCODE_PRESET,
    KEY_CPU_ENCODE_PROCESS_PRIORITY,
    KEY_CPU_ENCODE_MAX_THREADS,
    KEY_OUTPUT_SIZE_MULTIPLIER,
    KEY_FFMPEG_ENCODE_TIMEOUT_SECONDS,
    KEY_FFMPEG_CPU_ENCODE_TIMEOUT_SECONDS,
    KEY_FFMPEG_REMUX_TIMEOUT_SECONDS,
    KEY_MKVMERGE_REMUX_TIMEOUT_SECONDS,
    KEY_SUBTITLE_EXTRACT_TIMEOUT_SECONDS,
    KEY_SUBTITLE_PROBE_TIMEOUT_SECONDS,
    KEY_BDPGS_OCR_TIMEOUT_SECONDS,
    KEY_VOBSUB_OCR_TIMEOUT_SECONDS,
    KEY_OUTPUT_VALIDATION_PROBE_TIMEOUT_SECONDS,
    KEY_OUTPUT_VALIDATION_MIN_SIZE_BYTES,
    KEY_OUTPUT_VALIDATION_DURATION_TOLERANCE_SECONDS,
    KEY_ALLOW_SYSTEM_TOOLS,
    KEY_ROBOCOPY_TIMEOUT_SECONDS,
    KEY_TRANSIENT_FAILURE_RETRY_LIMIT,
    KEY_INDEX_SCAN_TIMEOUT_SECONDS,
    KEY_SOURCE_SCAN_TIMEOUT_SECONDS,
    KEY_CLEANUP_SCAN_TIMEOUT_SECONDS,
    KEY_CLEANUP_REMOTE_STAGING,
    KEY_CLEANUP_STALE_AGE_HOURS,
    KEY_SOURCE_SCAN_INTERVAL_SECONDS,
    KEY_PROCESSED_INDEX_REFRESH_SECONDS,
    KEY_MIN_PIPELINE_VERSION,
    KEY_REPROCESS_ALL,
    KEY_SHOW_OVERRIDES,
)

NETWORK_CONFIG_KEYS: Final = (
    KEY_NETWORK_ROLE,
    KEY_COORDINATOR_PORT,
    KEY_COORDINATOR_BIND_ADDRESS,
    KEY_COORDINATOR_ALSO_ENCODE_LOCALLY,
    KEY_COORDINATOR_HEARTBEAT_TIMEOUT_MINS,
    KEY_COORDINATOR_AUTH_TOKEN,
    KEY_WORKER_COORDINATOR_URL,
    KEY_WORKER_NAME,
    KEY_WORKER_AUTH_TOKEN,
    KEY_WORKER_POLL_INTERVAL_SECS,
    KEY_WORKER_SOURCE_PATH_MAP,
    KEY_WORKER_CONFIG_OVERRIDES,
)

PYTHON_SCHEMA_CONFIG_KEYS: Final = (
    KEY_SOURCE_MOVIES,
    KEY_SOURCE_TV,
    KEY_OUTSOURCE,
    KEY_LIBRARY_PROFILES,
    KEY_LOCAL_BASE,
    KEY_FINAL_LIBRARY_PROMOTION_ENABLED,
    KEY_FINAL_LIBRARY_PROMOTION_RULES,
    KEY_FINAL_LIBRARY_PROMOTION_VERIFICATION_MODE,
    KEY_FINAL_LIBRARY_PROMOTION_CLEANUP_AFTER_VERIFIED,
    KEY_FINAL_LIBRARY_PROMOTION_OVERWRITE_EXISTING,
    KEY_CREATE_TV_SUBFOLDER,
    KEY_AUDIO_PASSTHROUGH_PROFILE,
    KEY_COMPATIBLE_AUDIO_CODECS,
    KEY_PREFERRED_DEFAULT_AUDIO_LANGUAGES,
    KEY_AUDIO_TRANSCODE_CODEC,
    KEY_AUDIO_TRANSCODE_BITRATE,
    KEY_AUDIO_TRANSCODE_AUTO_BITRATE_BY_CHANNELS,
    KEY_AUDIO_DOWNMIX_MODE,
    KEY_AUDIO_MAX_CHANNELS,
    KEY_ALLOW_NO_AUDIO,
    KEY_ENCODE_THRESHOLD_GB,
    KEY_TV_ENCODE_THRESHOLD_GB,
    KEY_ROUTING_PROFILE,
    KEY_ROUTE_THRESHOLD_MODE,
    KEY_MOVIE_ROUTE_MAX_VIDEO_BITRATE_MBPS,
    KEY_TV_ROUTE_MAX_VIDEO_BITRATE_MBPS,
    KEY_ALLOW_H264_REMUX_IF_PLEX_COMPATIBLE,
    KEY_H264_REMUX_MAX_BITRATE_MBPS,
    KEY_H264_REMUX_MAX_HEIGHT,
    KEY_SIZE_GUARD_MODE,
    KEY_MAX_ENCODE_GROWTH_PERCENT,
    KEY_COMPATIBILITY_ENCODE_GROWTH_PERCENT,
    KEY_DEFERRED_PUBLISH,
    KEY_AGGRESSIVE_EPISODE_PARSING,
    KEY_VIDEO_CODEC,
    KEY_VIDEO_PRESET,
    KEY_VIDEO_QUALITY,
    KEY_OUTPUT_CONTAINER,
    KEY_ENCODE_TUNING_PRESET,
    KEY_ENCODE_LADDER,
    KEY_EXTRA_VIDEO_FLAGS,
    KEY_REMUX_SAFE_VIDEO_CODECS,
    KEY_FALLBACK_CPU_QUALITY,
    KEY_CPU_ENCODE_PRESET,
    KEY_CPU_ENCODE_PROCESS_PRIORITY,
    KEY_FFMPEG_CPU_ENCODE_TIMEOUT_SECONDS,
    KEY_MKVMERGE_REMUX_TIMEOUT_SECONDS,
    KEY_CPU_ENCODE_MAX_THREADS,
    KEY_SUB_KEEP_LANGUAGES,
    KEY_CONVERT_TX3G_TO_SRT,
    KEY_DROP_TX3G_AFTER_CONVERSION,
    KEY_CREATE_EXTERNAL_TX3G_SRT_SIDECARS,
    KEY_TX3G_EXTRACT_LANGUAGES,
    KEY_TX3G_PRESERVE_EXISTING_SRT,
    KEY_TX3G_TREAT_FORCED_AS_SEPARATE,
    KEY_CONVERT_BDPGS_TO_SRT,
    KEY_DROP_BDPGS_AFTER_CONVERSION,
    KEY_BDPGS_EXTRACT_LANGUAGES,
    KEY_BDPGS_OCR_TOOL_PATH,
    KEY_BDPGS_OCR_TESSDATA_PATH,
    KEY_CONVERT_VOBSUB_TO_SRT,
    KEY_DROP_VOBSUB_AFTER_CONVERSION,
    KEY_VOBSUB_EXTRACT_LANGUAGES,
    KEY_VOBSUB_OCR_TOOL_PATH,
    KEY_DROP_ASS_AFTER_CONVERSION,
    KEY_REMOVE_KARAOKE,
    KEY_KEEP_SIGNS_AND_SONGS,
    KEY_TREAT_ASS_SIGNS_SONGS_AS_FORCED,
    KEY_TREAT_TX3G_SIGNS_SONGS_AS_FORCED,
    KEY_TREAT_BDPGS_SIGNS_SONGS_AS_FORCED,
    KEY_TREAT_VOBSUB_SIGNS_SONGS_AS_FORCED,
    KEY_STRIP_FORMATTING,
    KEY_MERGE_ADJACENT,
    KEY_MERGE_THRESHOLD_MS,
    KEY_SUB_SDH_TITLE_KEYWORDS,
    KEY_SUB_SUPPLEMENTAL_KEYWORDS,
    KEY_EXCLUDE_SUBTITLE_STYLES,
    KEY_INCLUDE_SUBTITLE_STYLES,
    KEY_CONFIG_SCHEMA_VERSION,
    KEY_MAX_PARALLEL_ENCODES,
    KEY_PARALLEL_ENCODE_MODE,
    KEY_DEBUG_MODE,
    KEY_CONSOLE_LOG_LEVEL,
    KEY_FILE_LOG_LEVEL,
    KEY_LOG_RETENTION_DAYS,
    KEY_MIN_FREE_SPACE_GB,
    KEY_FILE_STABILITY_WAIT,
    KEY_SKIP_STABILITY_CHECK,
    KEY_OUTSOURCE_MIN_FREE_SPACE_GB,
    KEY_FFMPEG_ENCODE_TIMEOUT_SECONDS,
    KEY_FFMPEG_REMUX_TIMEOUT_SECONDS,
    KEY_SUBTITLE_EXTRACT_TIMEOUT_SECONDS,
    KEY_SUBTITLE_PROBE_TIMEOUT_SECONDS,
    KEY_BDPGS_OCR_TIMEOUT_SECONDS,
    KEY_VOBSUB_OCR_TIMEOUT_SECONDS,
    KEY_ALLOW_SYSTEM_TOOLS,
    KEY_ROBOCOPY_TIMEOUT_SECONDS,
    KEY_TRANSIENT_FAILURE_RETRY_LIMIT,
    KEY_MIN_PIPELINE_VERSION,
    KEY_OUTPUT_SIZE_MULTIPLIER,
    KEY_OUTPUT_VALIDATION_PROBE_TIMEOUT_SECONDS,
    KEY_OUTPUT_VALIDATION_MIN_SIZE_BYTES,
    KEY_OUTPUT_VALIDATION_DURATION_TOLERANCE_SECONDS,
    KEY_ENABLE_INTEGRITY_CHECK,
    KEY_ROBOCOPY_FLAGS,
    KEY_PRIORITY_MARKERS,
    KEY_SOURCE_SCAN_INTERVAL_SECONDS,
    KEY_SOURCE_SCAN_TIMEOUT_SECONDS,
    KEY_PROCESSED_INDEX_REFRESH_SECONDS,
    KEY_REPROCESS_ALL,
    KEY_INDEX_SCAN_TIMEOUT_SECONDS,
    KEY_CLEANUP_SCAN_TIMEOUT_SECONDS,
    KEY_VALID_EXTENSIONS,
    KEY_CLEANUP_REMOTE_STAGING,
    KEY_CLEANUP_STALE_AGE_HOURS,
    KEY_NETWORK_ROLE,
    KEY_COORDINATOR_PORT,
    KEY_COORDINATOR_BIND_ADDRESS,
    KEY_COORDINATOR_ALSO_ENCODE_LOCALLY,
    KEY_COORDINATOR_HEARTBEAT_TIMEOUT_MINS,
    KEY_COORDINATOR_AUTH_TOKEN,
    KEY_WORKER_COORDINATOR_URL,
    KEY_WORKER_NAME,
    KEY_WORKER_AUTH_TOKEN,
    KEY_WORKER_POLL_INTERVAL_SECS,
    KEY_WORKER_SOURCE_PATH_MAP,
    KEY_WORKER_CONFIG_OVERRIDES,
)

ALL_CONFIG_KEYS: Final = frozenset(CONFIG_KEY_ORDER + NETWORK_CONFIG_KEYS)

__all__ = tuple(name for name in globals() if name.startswith("KEY_")) + (
    "CONFIG_KEY_ORDER",
    "NETWORK_CONFIG_KEYS",
    "PYTHON_SCHEMA_CONFIG_KEYS",
    "ALL_CONFIG_KEYS",
)
