from __future__ import annotations

import re
from typing import Any

from .service_constants import TOP_LEVEL_CONFIG_ORDER


def serialize_psd1_document(data: dict[str, Any]) -> str:
    ordered = order_top_level_config(data)
    body = "\n".join(psd1_lines(ordered, indent=0, top_level=True))
    header = [
        "# Generated by MediaPipelineRemuxEncodeAIO Desktop App.",
        "# Unknown keys are preserved, but original comments/formatting are not.",
        body,
        "",
    ]
    return "\n".join(header)


def order_top_level_config(data: dict[str, Any]) -> dict[str, Any]:
    order_map = {key: index for index, key in enumerate(TOP_LEVEL_CONFIG_ORDER)}
    ordered_keys = sorted(
        data.keys(),
        key=lambda key: (order_map.get(str(key), len(order_map) + 1000), str(key).casefold()),
    )
    return {key: data[key] for key in ordered_keys}


def psd1_lines(value: Any, indent: int, top_level: bool = False) -> list[str]:
    _ = top_level
    pad = " " * indent
    child_pad = " " * (indent + 4)

    if isinstance(value, dict):
        lines = [f"{pad}@{{"]
        items = value.items()
        for key, item_value in items:
            rendered = psd1_lines(item_value, indent + 4)
            key_text = psd1_key(str(key))
            if len(rendered) == 1:
                lines.append(f"{child_pad}{key_text} = {rendered[0].lstrip()}")
                continue
            lines.append(f"{child_pad}{key_text} = {rendered[0].lstrip()}")
            lines.extend(rendered[1:])
        lines.append(f"{pad}}}")
        return lines

    if isinstance(value, list):
        if not value:
            return [f"{pad}@()"]
        lines = [f"{pad}@("]
        for index, item in enumerate(value):
            is_last = index == len(value) - 1
            rendered = psd1_lines(item, indent + 4)
            if len(rendered) == 1:
                suffix = "" if is_last else ","
                lines.append(f"{child_pad}{rendered[0].lstrip()}{suffix}")
            else:
                lines.append(f"{child_pad}{rendered[0].lstrip()}")
                lines.extend(rendered[1:])
                if not is_last:
                    lines[-1] = f"{lines[-1]},"
        lines.append(f"{pad})")
        return lines

    if isinstance(value, bool):
        return [f"{pad}{'$true' if value else '$false'}"]
    if value is None:
        return [f"{pad}$null"]
    if isinstance(value, int):
        return [f"{pad}{value}"]
    if isinstance(value, float):
        return [f"{pad}{format(value, 'g')}"]
    return [f"{pad}{psd1_quote(str(value))}"]


def psd1_key(key: str) -> str:
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key):
        return key
    return psd1_quote(key)


def psd1_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"
