from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path

from app.contracts.lifecycle import LIFECYCLE_STATES, LIFECYCLE_TRANSITIONS, lifecycle_state_by_id


REPO_ROOT = Path(__file__).resolve().parents[2]
MODULE_PATH = REPO_ROOT / "scripts" / "dev" / "generate_lifecycle_map.py"
spec = importlib.util.spec_from_file_location("generate_lifecycle_map_for_tests", MODULE_PATH)
assert spec and spec.loader
generate_lifecycle_map = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = generate_lifecycle_map
spec.loader.exec_module(generate_lifecycle_map)


class LifecycleMapTests(unittest.TestCase):
    def test_lifecycle_states_have_unique_ids_and_required_fields(self) -> None:
        ids = [state.state_id for state in LIFECYCLE_STATES]

        self.assertEqual(len(ids), len(set(ids)))
        for state in LIFECYCLE_STATES:
            self.assertTrue(state.owner)
            self.assertTrue(state.validation_rung)
            self.assertTrue(state.allowed_operations)
            self.assertTrue(state.forbidden_operations)

    def test_transitions_reference_known_states(self) -> None:
        states = lifecycle_state_by_id()

        for transition in LIFECYCLE_TRANSITIONS:
            self.assertIn(transition.source, states)
            self.assertIn(transition.target, states)
            self.assertTrue(transition.guard)
            self.assertTrue(transition.evidence)

    def test_rendered_map_marks_absent_folder_concepts(self) -> None:
        rendered = generate_lifecycle_map.render_lifecycle_map()

        self.assertIn("Generated by `scripts/dev/generate_lifecycle_map.py`", rendered)
        self.assertIn("ready_archive_quarantine_trash", rendered)
        self.assertIn("Implemented:** no", rendered)


if __name__ == "__main__":
    unittest.main()
