pub(crate) const REQUIRED_ROUTES: &[(&str, &str, bool)] = &[
    ("GET", "/api/health", false),
    ("GET", "/api/contract", true),
    ("GET", "/api/snapshot", true),
    ("GET", "/api/telemetry", true),
    ("GET", "/api/metrics", true),
    ("GET", "/api/diagnostics", true),
    ("GET", "/api/diagnostics/tail", true),
    ("GET", "/api/diagnostics/state-summary", true),
    ("GET", "/api/diagnostics/tdarr-matrix/latest", true),
    ("GET", "/api/diagnostics/tdarr-matrix/runs", true),
    ("GET", "/api/diagnostics/tdarr-matrix/compare", true),
    ("GET", "/api/backend/close-readiness", true),
    ("GET", "/api/backend/recovery-status", true),
    ("GET", "/api/ui-preferences", true),
    ("GET", "/api/launch/preflight", true),
    ("GET", "/api/commands", true),
    ("GET", "/api/queue", true),
    ("GET", "/api/queue/priority", true),
    ("GET", "/api/queue/strategy", true),
    ("GET", "/api/queue/file-overrides", true),
    ("GET", "/api/queue/file-overrides/effective", true),
    ("GET", "/api/queue/file-overrides/tracks", true),
    ("GET", "/api/completed", true),
    ("GET", "/api/final-library-promotion/status", true),
    ("GET", "/api/failures", true),
    ("GET", "/api/failures/artifacts", true),
    ("GET", "/api/audit-results", true),
    ("GET", "/api/audit-controls", true),
    ("GET", "/api/audit-sources", true),
    ("GET", "/api/rerun/results", true),
    ("GET", "/api/pending-publish", true),
    ("GET", "/api/publish-reconciliation", true),
    ("GET", "/api/rename/cleaning-filters", true),
    ("GET", "/api/rename/movie-cleaning-filters", true),
    ("GET", "/api/rename/clean-filename-preview", true),
    ("GET", "/api/maintenance", true),
    ("GET", "/api/maintenance/progress", true),
    ("GET", "/api/maintenance/change-ledger", true),
    ("GET", "/api/maintenance/productization", true),
    ("GET", "/api/schedule", true),
    ("GET", "/api/watch-folders/status", true),
    ("GET", "/api/settings/workspace", true),
    ("GET", "/api/settings/preset-library", true),
    ("GET", "/api/settings/wizard/status", true),
    ("GET", "/api/settings/wizard/defaults", true),
    ("GET", "/api/network/workers", true),
    ("GET", "/api/sample-validation", true),
    ("GET", "/api/subtitle-qa/summary", true),
    ("GET", "/api/subtitle-qa/item", true),
    ("GET", "/api/libraries/summary", true),
    ("GET", "/api/libraries/route-map", true),
    ("GET", "/api/libraries/route-map/compare", true),
    ("GET", "/api/libraries/route-map/trace", true),
    ("GET", "/api/libraries/route-map/validation", true),
    ("POST", "/api/metrics/sources", true),
    ("POST", "/api/metrics/backfill", true),
    ("POST", "/api/queue/priority", true),
    ("POST", "/api/queue/strategy", true),
    ("POST", "/api/queue/scan", true),
    ("POST", "/api/queue/file-overrides", true),
    ("POST", "/api/queue/file-overrides/route-preview", true),
    ("POST", "/api/queue/file-overrides/series-preview", true),
    ("POST", "/api/queue/file-overrides/series-apply", true),
    (
        "POST",
        "/api/queue/file-overrides/series-clear-preview",
        true,
    ),
    ("POST", "/api/queue/file-overrides/series-clear-apply", true),
    ("POST", "/api/queue/file-overrides/folder-preview", true),
    ("POST", "/api/queue/file-overrides/folder-rule", true),
    (
        "POST",
        "/api/queue/file-overrides/remux-pilot-promote",
        true,
    ),
    ("POST", "/api/queue/open", true),
    ("POST", "/api/completed/open", true),
    ("POST", "/api/completed/reconcile-manifest-dry-run", true),
    ("POST", "/api/completed/reconcile-manifest", true),
    (
        "POST",
        "/api/completed/repair-sidecar-metadata-dry-run",
        true,
    ),
    ("POST", "/api/completed/repair-sidecar-metadata", true),
    ("POST", "/api/failures/clear", true),
    ("POST", "/api/failures/archive-evidence", true),
    ("POST", "/api/failures/open", true),
    ("POST", "/api/failures/artifacts/cleanup", true),
    ("POST", "/api/failures/lifecycle", true),
    ("POST", "/api/pending-publish/open", true),
    ("POST", "/api/pending-publish/recovery-plan", true),
    ("POST", "/api/pending-publish/repair-manifest-dry-run", true),
    ("POST", "/api/pending-publish/repair-manifest", true),
    (
        "POST",
        "/api/pending-publish/reconcile-orphan-payloads-dry-run",
        true,
    ),
    (
        "POST",
        "/api/pending-publish/reconcile-orphan-payloads",
        true,
    ),
    ("POST", "/api/startup/reconcile-dry-run", true),
    ("POST", "/api/final-library-promotion/promote-queue", true),
    ("POST", "/api/final-library-promotion/pause", true),
    ("POST", "/api/final-library-promotion/resume", true),
    ("POST", "/api/maintenance/release-dry-run", true),
    ("POST", "/api/maintenance/release-build", true),
    ("POST", "/api/maintenance/completed-backfill-dry-run", true),
    ("POST", "/api/maintenance/archive-state-journals", true),
    ("POST", "/api/maintenance/retention-dry-run", true),
    ("POST", "/api/maintenance/dependency-atlas", true),
    (
        "POST",
        "/api/maintenance/dependency-atlas/open-folder",
        true,
    ),
    ("POST", "/api/maintenance/support-export", true),
    ("POST", "/api/diagnostics/open", true),
    ("POST", "/api/diagnostics/tdarr-matrix-audit", true),
    ("POST", "/api/diagnostics/tdarr-matrix/rerun", true),
    ("POST", "/api/diagnostics/tdarr-matrix/evidence/open", true),
    (
        "POST",
        "/api/diagnostics/encoder-capabilities/refresh",
        true,
    ),
    ("POST", "/api/ui-preferences", true),
    ("POST", "/api/rename/preview", true),
    ("POST", "/api/rename/browse", true),
    ("POST", "/api/rename/apply", true),
    ("POST", "/api/rename/undo", true),
    ("POST", "/api/rename/filter-cases", true),
    ("POST", "/api/schedule/preview", true),
    ("POST", "/api/schedule/save", true),
    ("POST", "/api/settings/validate", true),
    ("POST", "/api/settings/browse-path", true),
    ("POST", "/api/settings/pipeline-plan-preview", true),
    ("POST", "/api/settings/preview-patch", true),
    ("POST", "/api/settings/save-patch", true),
    ("POST", "/api/settings/import-psd1-preview", true),
    ("POST", "/api/settings/import-psd1", true),
    ("POST", "/api/settings/preset-library/validate", true),
    ("POST", "/api/settings/preset-library/save", true),
    ("POST", "/api/settings/preset-library/export", true),
    ("POST", "/api/settings/preset-library/import-preview", true),
    ("POST", "/api/settings/preset-library/apply-preview", true),
    ("POST", "/api/settings/preset-library/apply", true),
    ("POST", "/api/settings/preset-library/compare", true),
    ("POST", "/api/settings/wizard/validate-paths", true),
    ("POST", "/api/settings/wizard/validate-tools", true),
    ("POST", "/api/settings/wizard/probe-hardware", true),
    ("POST", "/api/settings/wizard/validate-workers", true),
    ("POST", "/api/settings/wizard/preview", true),
    ("POST", "/api/settings/wizard/save", true),
    ("POST", "/api/settings/reload", true),
    ("POST", "/api/sample-validation/preview", true),
    ("POST", "/api/sample-validation/append", true),
    ("POST", "/api/subtitle-qa/preview", true),
    ("POST", "/api/path-picker/browse", true),
    ("POST", "/api/pipeline/control", true),
    ("POST", "/api/pipeline/browse-file", true),
    ("POST", "/api/pipeline/start", true),
    ("POST", "/api/audit/start", true),
    ("POST", "/api/audit/stop", true),
    ("POST", "/api/audit/sources", true),
    ("POST", "/api/audit/sources/scan", true),
    ("POST", "/api/audit/score-policy", true),
    ("POST", "/api/audit/ignore", true),
    ("POST", "/api/audit/export-rerun-csv", true),
    ("POST", "/api/rerun/preview", true),
    ("POST", "/api/rerun/network-preview", true),
    ("POST", "/api/rerun/network/start-dry-run", true),
    ("POST", "/api/rerun/network/start", true),
    ("POST", "/api/rerun/network/retry", true),
    ("POST", "/api/rerun/start", true),
    ("POST", "/api/rerun/control", true),
    ("POST", "/api/rerun/continue", true),
    ("POST", "/api/rerun/open", true),
    ("POST", "/api/rerun/promote-dry-run", true),
    ("POST", "/api/rerun/promote", true),
    ("POST", "/api/backend/lifecycle/reconcile-dry-run", true),
    ("POST", "/api/backend/lifecycle/reconcile", true),
    ("POST", "/api/backend/shutdown", true),
    ("POST", "/api/network/coordinator/start-dry-run", true),
    ("POST", "/api/network/coordinator/stop-dry-run", true),
    ("POST", "/api/network/worker/start-dry-run", true),
    ("POST", "/api/network/worker/stop-dry-run", true),
    ("POST", "/api/network/worker/test-connection", true),
    ("POST", "/api/network/worker/discover-coordinators", true),
    ("POST", "/api/network/coordinator/join-blob", true),
    ("POST", "/api/network/worker/join-cluster", true),
    ("POST", "/api/network/coordinator/start", true),
    ("POST", "/api/network/coordinator/stop", true),
    ("POST", "/api/network/worker/start", true),
    ("POST", "/api/network/worker/stop", true),
];

pub(crate) struct RequiredLifecycleReconciliationRoute {
    pub(crate) path: &'static str,
    pub(crate) effect: &'static str,
    pub(crate) request_keys: &'static [&'static str],
    pub(crate) safe_defaults: Option<&'static [(&'static str, bool)]>,
    pub(crate) requires_strict_boolean: &'static [&'static str],
    pub(crate) requires_dry_run_fingerprint: Option<bool>,
    pub(crate) requires_confirmation: bool,
    pub(crate) journaled: bool,
    pub(crate) response_schema: &'static str,
    pub(crate) data_schema: &'static str,
}

pub(crate) const REQUIRED_LIFECYCLE_RECONCILIATION_ROUTES:
    &[RequiredLifecycleReconciliationRoute] = &[
    RequiredLifecycleReconciliationRoute {
        path: "/api/backend/lifecycle/reconcile-dry-run",
        effect: "none",
        request_keys: &["reason"],
        safe_defaults: None,
        requires_strict_boolean: &[],
        requires_dry_run_fingerprint: None,
        requires_confirmation: false,
        journaled: false,
        response_schema: "desktop_command_result.v1",
        data_schema: "desktop_lifecycle_reconciliation.v1",
    },
    RequiredLifecycleReconciliationRoute {
        path: "/api/backend/lifecycle/reconcile",
        effect: "lifecycle-evidence-reconciliation",
        request_keys: &["confirm_apply", "dry_run_fingerprint", "reason"],
        safe_defaults: Some(&[("confirm_apply", false)]),
        requires_strict_boolean: &["confirm_apply"],
        requires_dry_run_fingerprint: Some(true),
        requires_confirmation: true,
        journaled: true,
        response_schema: "desktop_command_result.v1",
        data_schema: "desktop_lifecycle_reconciliation.v1",
    },
];

pub(crate) struct RequiredNetworkLifecycleRoute {
    pub(crate) path: &'static str,
    pub(crate) effect: &'static str,
    pub(crate) requires_confirmation: bool,
    pub(crate) owner: &'static str,
    pub(crate) frontend_exposed: bool,
    pub(crate) role: &'static str,
    pub(crate) action: &'static str,
    pub(crate) dry_run: bool,
}

pub(crate) struct RequiredNetworkSetupRoute {
    pub(crate) path: &'static str,
    pub(crate) effect: &'static str,
    pub(crate) requires_confirmation: bool,
    pub(crate) owner: &'static str,
    pub(crate) frontend_exposed: bool,
    pub(crate) journaled: bool,
}

pub(crate) const REQUIRED_NETWORK_SETUP_ROUTES: &[RequiredNetworkSetupRoute] = &[
    RequiredNetworkSetupRoute {
        path: "/api/network/worker/discover-coordinators",
        effect: "none",
        requires_confirmation: false,
        owner: "Network",
        frontend_exposed: true,
        journaled: false,
    },
    RequiredNetworkSetupRoute {
        path: "/api/network/coordinator/join-blob",
        effect: "secret-transfer",
        requires_confirmation: true,
        owner: "Network",
        frontend_exposed: true,
        journaled: false,
    },
    RequiredNetworkSetupRoute {
        path: "/api/network/worker/join-cluster",
        effect: "config-write",
        requires_confirmation: true,
        owner: "Network",
        frontend_exposed: true,
        journaled: false,
    },
];

pub(crate) const REQUIRED_NETWORK_LIFECYCLE_ROUTES: &[RequiredNetworkLifecycleRoute] = &[
    RequiredNetworkLifecycleRoute {
        path: "/api/network/coordinator/start-dry-run",
        effect: "none",
        requires_confirmation: false,
        owner: "Network",
        frontend_exposed: true,
        role: "coordinator",
        action: "start",
        dry_run: true,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/coordinator/stop-dry-run",
        effect: "none",
        requires_confirmation: false,
        owner: "Network",
        frontend_exposed: true,
        role: "coordinator",
        action: "stop",
        dry_run: true,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/worker/start-dry-run",
        effect: "none",
        requires_confirmation: false,
        owner: "Network",
        frontend_exposed: true,
        role: "worker",
        action: "start",
        dry_run: true,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/worker/stop-dry-run",
        effect: "none",
        requires_confirmation: false,
        owner: "Network",
        frontend_exposed: true,
        role: "worker",
        action: "stop",
        dry_run: true,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/coordinator/start",
        effect: "backend-lifecycle",
        requires_confirmation: true,
        owner: "Network",
        frontend_exposed: true,
        role: "coordinator",
        action: "start",
        dry_run: false,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/coordinator/stop",
        effect: "backend-lifecycle",
        requires_confirmation: true,
        owner: "Network",
        frontend_exposed: true,
        role: "coordinator",
        action: "stop",
        dry_run: false,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/worker/start",
        effect: "backend-lifecycle",
        requires_confirmation: true,
        owner: "Network",
        frontend_exposed: true,
        role: "worker",
        action: "start",
        dry_run: false,
    },
    RequiredNetworkLifecycleRoute {
        path: "/api/network/worker/stop",
        effect: "backend-lifecycle",
        requires_confirmation: true,
        owner: "Network",
        frontend_exposed: true,
        role: "worker",
        action: "stop",
        dry_run: false,
    },
];
