# Dot-sourced helper slice for Setup-MediaPipeline.ps1. Keep CLI orchestration in the parent script.

function Get-DefaultConfig {
    Get-MediaPipelineConfigDefaultValues
}

function Read-ExistingConfig {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return @{ Result = @{}; ParseFailed = $false } }
    try {
        $config = Import-PowerShellDataFile -LiteralPath $Path
        if ($null -eq $config) { $config = @{} }
        return @{ Result = $config; ParseFailed = $false }
    } catch {
        Write-Warn "Existing config could not be parsed: $_"
        return @{ Result = @{}; ParseFailed = $true }
    }
}

function Invoke-ConfigBackup {
    param([string]$Path, [int]$Keep = 5)
    if (-not (Test-Path -LiteralPath $Path)) { return $null }

    $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $backupPath = "$Path.bak.$timestamp"
    Copy-Item -LiteralPath $Path -Destination $backupPath -Force

    $parent = Split-Path -Parent $Path
    $pattern = (Split-Path -Leaf $Path) + '.bak.*'
    $backups = @(Get-ChildItem -LiteralPath $parent -Filter $pattern -File -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending)
    if ($backups.Count -gt $Keep) {
        $backups | Select-Object -Skip $Keep | ForEach-Object {
            Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue
        }
    }

    return $backupPath
}

function Format-PsdKey {
    param([string]$Key)
    if ($Key -match '^[A-Za-z_][A-Za-z0-9_]*$') { return $Key }
    return "'" + ($Key -replace "'", "''") + "'"
}

function Format-PsdValue {
    param(
        [Parameter(Mandatory = $false)]$Value,
        [int]$Indent = 0
    )

    if ($null -eq $Value) { return '$null' }
    if ($Value -is [bool]) { return $(if ($Value) { '$true' } else { '$false' }) }
    if ($Value -is [int] -or $Value -is [long] -or $Value -is [byte] -or $Value -is [System.Int16]) {
        return ([int64]$Value).ToString($script:InvariantCulture)
    }
    if ($Value -is [double] -or $Value -is [float] -or $Value -is [decimal]) {
        return ([double]$Value).ToString('R', $script:InvariantCulture)
    }

    if ($Value -is [hashtable] -or $Value -is [System.Collections.IDictionary]) {
        if ($Value.Count -eq 0) { return '@{}' }
        $innerIndent = ' ' * ($Indent + 4)
        $closingIndent = ' ' * $Indent
        $builder = [System.Text.StringBuilder]::new()
        [void]$builder.Append("@{`r`n")
        foreach ($key in $Value.Keys) {
            $line = "{0}{1} = {2}" -f $innerIndent, (Format-PsdKey $key), (Format-PsdValue -Value $Value[$key] -Indent ($Indent + 4))
            [void]$builder.AppendLine($line)
        }
        [void]$builder.Append("$closingIndent}")
        return $builder.ToString()
    }

    if ($Value -is [System.Collections.IEnumerable] -and -not ($Value -is [string])) {
        $items = @($Value)
        if ($items.Count -eq 0) { return '@()' }
        $parts = foreach ($item in $items) {
            Format-PsdValue -Value $item -Indent $Indent
        }
        return '@(' + ($parts -join ', ') + ')'
    }

    return "'" + (([string]$Value) -replace "'", "''") + "'"
}

function Format-ConfigFile {
    param([hashtable]$Config)

    $builder = [System.Text.StringBuilder]::new()
    [void]$builder.AppendLine("# Generated by Setup-MediaPipeline.ps1 (MediaPipeline 1.0) on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$builder.AppendLine("# Edit directly if you need advanced keys such as ShowOverrides.")
    [void]$builder.AppendLine('@{')

    foreach ($key in $script:ConfigOrder) {
        if (-not $Config.ContainsKey($key)) { continue }
        if ($null -eq $Config[$key]) { continue }
        [void]$builder.AppendLine("    $key = $(Format-PsdValue -Value $Config[$key] -Indent 4)")
    }

    $extraKeys = @($Config.Keys | Where-Object { $script:ConfigOrder -notcontains $_ } | Sort-Object)
    if ($extraKeys.Count -gt 0) {
        [void]$builder.AppendLine('')
        [void]$builder.AppendLine('    # Preserved keys')
        foreach ($key in $extraKeys) {
            [void]$builder.AppendLine("    $(Format-PsdKey $key) = $(Format-PsdValue -Value $Config[$key] -Indent 4)")
        }
    }

    [void]$builder.AppendLine('}')
    return $builder.ToString()
}

function Write-ConfigFile {
    param([string]$Path, [string]$Content)
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    $tempPath = "$Path.tmp.$([guid]::NewGuid().ToString('N'))"
    try {
        [System.IO.File]::WriteAllText($tempPath, $Content, [System.Text.UTF8Encoding]::new($false))
        $null = Import-PowerShellDataFile -LiteralPath $tempPath
        Move-Item -LiteralPath $tempPath -Destination $Path -Force
        $tempPath = $null
    } finally {
        if ($tempPath -and (Test-Path -LiteralPath $tempPath)) {
            Remove-Item -LiteralPath $tempPath -Force -ErrorAction SilentlyContinue
        }
    }
}

function Get-ConfigSeed {
    param([hashtable]$Existing)
    $seed = Get-DefaultConfig
    foreach ($key in $Existing.Keys) {
        if ($key -in @('SourceMovies','SourceTV','Outsource','LocalBase')) {
            $seed[$key] = Normalize-UserPath -Path ([string]$Existing[$key]) -BasePath $script:ScriptDir
        } else {
            $seed[$key] = $Existing[$key]
        }
    }
    if ($SourceMovies) { $seed['SourceMovies'] = Normalize-UserPath -Path $SourceMovies -BasePath $script:ScriptDir }
    if ($SourceTV)     { $seed['SourceTV']     = Normalize-UserPath -Path $SourceTV -BasePath $script:ScriptDir }
    if ($Outsource)    { $seed['Outsource']    = Normalize-UserPath -Path $Outsource -BasePath $script:ScriptDir }
    if ($LocalBase)    { $seed['LocalBase']    = Normalize-UserPath -Path $LocalBase -BasePath $script:ScriptDir }
    return $seed
}

function Get-SetupVideoProfiles {
    $defaults = Get-MediaPipelineConfigDefaultValues
    $videoPreset = [string]$defaults['VideoPreset']
    if ($videoPreset -notin @(Get-MediaPipelineVideoPresetNames)) {
        throw "Canonical VideoPreset default is not registered: '$videoPreset'."
    }
    $cpuPreset = [string](Get-MediaPipelineCpuEncodePresetDefault)
    if ($cpuPreset -notin @(Get-MediaPipelineCpuEncodePresetNames)) {
        throw "Canonical CpuEncodePreset default is not registered: '$cpuPreset'."
    }

    return @(
        @{ Codec = 'hevc_nvenc'; VideoPreset = $videoPreset; Quality = 22; Label = 'NVIDIA / NVENC (recommended when available)' }
        @{ Codec = 'hevc_amf';   VideoPreset = $videoPreset; Quality = 22; Label = 'AMD / AMF' }
        @{ Codec = 'hevc_qsv';   VideoPreset = $videoPreset; Quality = 22; Label = 'Intel / QSV' }
        @{ Codec = 'libx265';    VideoPreset = $videoPreset; CpuPreset = $cpuPreset; Quality = 20; Label = 'CPU / libx265' }
    )
}

function Get-SetupVideoProfileDefaultIndex {
    param(
        [Parameter(Mandatory)] [System.Collections.IDictionary] $Existing,
        [Parameter(Mandatory)] [System.Collections.IDictionary] $Gpu
    )

    $existingCodec = if ($Existing.Contains('VideoCodec')) { [string]$Existing['VideoCodec'] } else { '' }
    switch -Regex ($existingCodec) {
        '^hevc_nvenc$' { return 1 }
        '^hevc_amf$'   { return 2 }
        '^hevc_qsv$'   { return 3 }
        '^libx265$'    { return 4 }
    }
    switch ([string]$Gpu['Vendor']) {
        'NVIDIA' { return 1 }
        'AMD'    { return 2 }
        'Intel'  { return 3 }
        default  { return 4 }
    }
}

function Set-SetupVideoProfileConfig {
    param(
        [Parameter(Mandatory)] [System.Collections.IDictionary] $Config,
        [Parameter(Mandatory)] [System.Collections.IDictionary] $Profile
    )

    $Config['VideoCodec'] = [string]$Profile['Codec']
    $Config['VideoPreset'] = [string]$Profile['VideoPreset']
    $Config['VideoQuality'] = [int]$Profile['Quality']
    $Config['ExtraVideoFlags'] = Get-ExtraVideoFlagsForCodec ([string]$Profile['Codec'])
    if ($Profile.Contains('CpuPreset')) {
        $Config['CpuEncodePreset'] = [string]$Profile['CpuPreset']
    }
}

function Get-SetupPresetSelection {
    param([Parameter(Mandatory)] [System.Collections.IDictionary] $Config)

    if ([string]$Config['VideoCodec'] -eq 'libx265') {
        return @{
            ConfigKey = 'CpuEncodePreset'
            Label = 'CPU encode preset'
            Options = @(Get-MediaPipelineCpuEncodePresetNames)
        }
    }
    return @{
        ConfigKey = 'VideoPreset'
        Label = 'Video preset'
        Options = @(Get-MediaPipelineVideoPresetNames)
    }
}

function Invoke-ConfigWizard {
    param([hashtable]$Existing)

    $config = Get-ConfigSeed -Existing $Existing

    Write-Step 1 4 'Folders'
    Write-Header 'Step 1 of 4: Folders'
    Write-Info 'Choose the incoming, scratch, and final-output folders.'
    $config['SourceMovies'] = Read-Path -Prompt 'Movies source folder' -Default ([string]$config['SourceMovies']) -CreateIfMissing -CreateDefaultYes $false
    $config['SourceTV']     = Read-Path -Prompt 'TV source folder'     -Default ([string]$config['SourceTV'])     -CreateIfMissing -CreateDefaultYes $false
    $config['LocalBase']    = Read-Path -Prompt 'Local scratch folder' -Default ([string]$config['LocalBase'])    -CreateIfMissing -MustBeWritable
    $config['Outsource']    = Read-Path -Prompt 'Final output folder'  -Default ([string]$config['Outsource'])    -CreateIfMissing -MustBeWritable
    Test-PathsDisjoint -Paths @{
        SourceMovies = $config['SourceMovies']
        SourceTV     = $config['SourceTV']
        LocalBase    = $config['LocalBase']
        Outsource    = $config['Outsource']
    }

    Write-Step 2 4 'Video'
    Write-Header 'Step 2 of 4: Video'
    $gpu = Get-DetectedGpu
    if ($gpu.Vendor -ne 'None') {
        Write-Ok "Detected $($gpu.Vendor): $($gpu.Name)"
    } else {
        Write-Warn 'No supported GPU was detected. CPU defaults are safest.'
    }

    $videoProfiles = @(Get-SetupVideoProfiles)
    $videoDefault = Get-SetupVideoProfileDefaultIndex -Existing $Existing -Gpu $gpu
    for ($i = 0; $i -lt $videoProfiles.Count; $i++) {
        Write-Host ("  {0}. {1}" -f ($i + 1), $videoProfiles[$i].Label)
    }
    $videoPick = Read-Choice -Prompt 'Video profile' -Options ($videoProfiles | ForEach-Object { $_.Label }) -Default $videoDefault
    $video = $videoProfiles[$videoPick - 1]

    Set-SetupVideoProfileConfig -Config $config -Profile $video

    if (Read-YesNo 'Tune the video quality or preset manually?' -DefaultYes $false) {
        $defaultQuality = [string]$config['VideoQuality']
        $config['VideoQuality'] = Read-PositiveInteger -Prompt 'Video quality (18-28 is the usual range)' -Default $defaultQuality

        $presetSelection = Get-SetupPresetSelection -Config $config
        $presetOptions = @($presetSelection.Options)
        $presetConfigKey = [string]$presetSelection.ConfigKey
        $presetDefault = [array]::IndexOf($presetOptions, [string]$config[$presetConfigKey]) + 1
        if ($presetDefault -lt 1) { $presetDefault = $presetOptions.Count }
        for ($i = 0; $i -lt $presetOptions.Count; $i++) {
            Write-Host ("  {0}. {1}" -f ($i + 1), $presetOptions[$i])
        }
        $presetPick = Read-Choice -Prompt ([string]$presetSelection.Label) -Options $presetOptions -Default $presetDefault
        $config[$presetConfigKey] = $presetOptions[$presetPick - 1]
    }

    Write-Step 3 4 'Playback and subtitles'
    Write-Header 'Step 3 of 4: Playback and subtitles'
    $playbackProfiles = @(
        @{
            Label                    = 'Plex smart TV friendly (recommended)'
            CompatibleAudioCodecs    = @('aac','ac3','eac3','mp3','opus','vorbis','truehd','mlp')
            DropAssAfterConversion   = $false
            DropTx3gAfterConversion  = $false
            DropBdpgsAfterConversion = $false
            RemoveKaraoke            = $true
            KeepSignsAndSongs        = $true
            TreatAssSignsSongsAsForced = $false
            TreatTx3gSignsSongsAsForced = $false
            TreatBdpgsSignsSongsAsForced = $false
        }
        @{
            Label                    = 'AV passthrough / preserve FLAC and DTS'
            CompatibleAudioCodecs    = @('aac','ac3','eac3','mp3','opus','vorbis','flac','truehd','mlp','dts','dts-hd')
            DropAssAfterConversion   = $false
            DropTx3gAfterConversion  = $false
            DropBdpgsAfterConversion = $false
            RemoveKaraoke            = $true
            KeepSignsAndSongs        = $true
            TreatAssSignsSongsAsForced = $false
            TreatTx3gSignsSongsAsForced = $false
            TreatBdpgsSignsSongsAsForced = $false
        }
        @{
            Label                    = 'Custom audio and subtitle choices'
            CompatibleAudioCodecs    = @()
            DropAssAfterConversion   = $false
            DropTx3gAfterConversion  = $false
            DropBdpgsAfterConversion = $false
            RemoveKaraoke            = $true
            KeepSignsAndSongs        = $true
            TreatAssSignsSongsAsForced = $false
            TreatTx3gSignsSongsAsForced = $false
            TreatBdpgsSignsSongsAsForced = $false
        }
    )

    $playbackDefault = 1
    $currentCompat = @($config['CompatibleAudioCodecs'])
    if ($currentCompat -contains 'dts' -or $currentCompat -contains 'dts-hd' -or $currentCompat -contains 'flac') {
        $playbackDefault = 2
    }
    for ($i = 0; $i -lt $playbackProfiles.Count; $i++) {
        Write-Host ("  {0}. {1}" -f ($i + 1), $playbackProfiles[$i].Label)
    }
    $playbackPick = Read-Choice -Prompt 'Playback profile' -Options ($playbackProfiles | ForEach-Object { $_.Label }) -Default $playbackDefault
    $playback = $playbackProfiles[$playbackPick - 1]

    if ($playbackPick -eq 3) {
        $compat = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
        foreach ($codec in @('aac','ac3','eac3','mp3','opus','vorbis','truehd','mlp')) {
            [void]$compat.Add($codec)
        }
        if (Read-YesNo 'Preserve FLAC audio untouched?' -DefaultYes ($currentCompat -contains 'flac')) {
            [void]$compat.Add('flac')
        }
        if (Read-YesNo 'Preserve DTS / DTS-HD audio untouched?' -DefaultYes (($currentCompat -contains 'dts') -or ($currentCompat -contains 'dts-hd'))) {
            [void]$compat.Add('dts')
            [void]$compat.Add('dts-hd')
        }
        $config['CompatibleAudioCodecs'] = @($compat)
        $config['DropAssAfterConversion'] = Read-YesNo 'Drop original ASS tracks after SRT conversion?' -DefaultYes ([bool]$config['DropAssAfterConversion'])
        $config['DropTx3gAfterConversion'] = Read-YesNo 'Drop original TX3G tracks after SRT conversion when the output container can preserve them?' -DefaultYes ([bool]$config['DropTx3gAfterConversion'])
        $config['DropBdpgsAfterConversion'] = Read-YesNo 'Drop original BDPGS tracks after OCR conversion when the output container can preserve them?' -DefaultYes ([bool]$config['DropBdpgsAfterConversion'])
        $config['CreateExternalTx3gSrtSidecars'] = Read-YesNo 'Write external TX3G-derived SRT sidecar files next to the output?' -DefaultYes ([bool]$config['CreateExternalTx3gSrtSidecars'])
        $config['RemoveKaraoke']          = Read-YesNo 'Filter karaoke-style subtitle events during ASS to SRT conversion?' -DefaultYes ([bool]$config['RemoveKaraoke'])
        $config['KeepSignsAndSongs']      = Read-YesNo 'Keep Signs and Songs ASS tracks as separate subtitle tracks?' -DefaultYes ([bool]$config['KeepSignsAndSongs'])
        $config['TreatAssSignsSongsAsForced'] = Read-YesNo 'Mark ASS Signs and Songs tracks as forced subtitles?' -DefaultYes ([bool]$config['TreatAssSignsSongsAsForced'])
        $config['TreatTx3gSignsSongsAsForced'] = Read-YesNo 'Mark TX3G Signs and Songs tracks as forced subtitles?' -DefaultYes ([bool]$config['TreatTx3gSignsSongsAsForced'])
        $config['TreatBdpgsSignsSongsAsForced'] = Read-YesNo 'Mark BDPGS Signs and Songs tracks as forced subtitles?' -DefaultYes ([bool]$config['TreatBdpgsSignsSongsAsForced'])
    } else {
        $config['CompatibleAudioCodecs']  = @($playback.CompatibleAudioCodecs)
        $config['DropAssAfterConversion'] = $playback.DropAssAfterConversion
        $config['DropTx3gAfterConversion'] = $playback.DropTx3gAfterConversion
        $config['DropBdpgsAfterConversion'] = $playback.DropBdpgsAfterConversion
        $config['RemoveKaraoke']          = $playback.RemoveKaraoke
        $config['KeepSignsAndSongs']      = $playback.KeepSignsAndSongs
        $config['TreatAssSignsSongsAsForced'] = $playback.TreatAssSignsSongsAsForced
        $config['TreatTx3gSignsSongsAsForced'] = $playback.TreatTx3gSignsSongsAsForced
        $config['TreatBdpgsSignsSongsAsForced'] = $playback.TreatBdpgsSignsSongsAsForced
    }

    Write-Step 4 4 'Routing and safety'
    Write-Header 'Step 4 of 4: Routing and safety'
    $config['MovieRoute1080pTargetSizeGB'] = Read-PositiveInteger -Prompt 'Movie 1080p target output size in GB' -Default ([string]$config['MovieRoute1080pTargetSizeGB'])
    $config['TVRoute1080pTargetSizeGB'] = Read-PositiveInteger -Prompt 'TV 1080p target output size in GB' -Default ([string]$config['TVRoute1080pTargetSizeGB'])
    $config['MinFreeSpaceGB'] = Read-PositiveInteger -Prompt 'Minimum free space on the scratch disk in GB' -Default ([string]$config['MinFreeSpaceGB'])
    if (Read-YesNo 'Use the same minimum free-space reserve for the outsource path?' -DefaultYes $true) {
        $config['OutsourceMinFreeSpaceGB'] = $config['MinFreeSpaceGB']
    } else {
        $config['OutsourceMinFreeSpaceGB'] = Read-PositiveInteger -Prompt 'Minimum free space on the outsource path in GB' -Default ([string]$config['OutsourceMinFreeSpaceGB'])
    }
    $config['DeferredPublish'] = Read-YesNo 'Defer publishing completed outputs to the share and park them locally?' -DefaultYes ([bool]$config['DeferredPublish'])
    $config['CreateTVSubfolder']  = Read-YesNo 'Store TV files under TV\<Show>\Season NN\' -DefaultYes ([bool]$config['CreateTVSubfolder'])
    $config['AggressiveEpisodeParsing'] = Read-YesNo 'Use aggressive TV episode parsing for anime/import filenames?' -DefaultYes ([bool]$config['AggressiveEpisodeParsing'])
    $config['SkipStabilityCheck'] = -not (Read-YesNo 'Keep the file-stability check enabled?' -DefaultYes (-not [bool]$config['SkipStabilityCheck']))
    $config['DebugMode']          = Read-YesNo 'Enable verbose debug logging?' -DefaultYes ([bool]$config['DebugMode'])

    Write-ConfigHighlights -Config $config
    return $config
}
