from __future__ import annotations

from typing import Any

LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/queue/priority-export",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "priority_queue_export.v1",
        "purpose": "Build and persist a backend-owned export containing only currently runnable effective-High queue entries. This does not launch processing or submit frontend row scope.",
    },
    {
        "method": "POST",
        "path": "/api/queue/priority",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "level", "reason", "items", "clear_all", "position"],
        "allowed_levels": ["high", "normal", "low", "hold"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_priority_manifest.v1",
        "purpose": "Write or clear non-destructive priority manifest entries only. Path/item writes must be absolute paths under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots); clear_all removes priority state only. This does not rename, move, delete, launch, or process media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/strategy",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["strategy"],
        "allowed_strategies": [
            "Standard",
            "FreshestFirst",
            "ShowComplete",
            "RoundRobin",
            "DeadlineAware",
            "SmallFirst",
            "LargeFirst",
            "ManualOrder",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_strategy_state.v1",
        "purpose": "Persist the backend queue ordering strategy for the next queue build without launching work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/scan",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["mode", "force", "scope", "reason"],
        "allowed_modes": ["inventory_then_curate", "inventory_only", "curate_only"],
        "allowed_scopes": ["all"],
        "safe_defaults": {"mode": "inventory_then_curate", "force": True, "scope": "all"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_queue_scan_command.v1",
        "purpose": "Start or observe a serialized backend-owned queue source scan. The fast inventory phase reads configured source roots (SourceMovies, SourceTV, and enabled LibraryProfiles source roots) and writes source-inventory evidence; the curation phase runs the existing queue-plan dry-run to write the authoritative queue snapshot. This does not process, rename, move, delete, publish, drain, or mutate source media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "audio", "subtitles", "routing", "video", "clear", "clear_all", "clear_fields"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Write per-file processing override state only for absolute paths under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), or clear the override manifest. Route/video fields are validated sparse metadata for later processing consumption. This does not process or mutate media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/route-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path", "proposed_override"],
        "response_schema": "queue_file_override_route_preview.v1",
        "purpose": "Preview route/remux/transcode impact for one path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots) using current queue snapshot route evidence. This does not write file_overrides.json, enqueue work, change queue strategy, process media, or mutate queue state.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path", "proposed_override"],
        "response_schema": "queue_file_override_series_preview.v1",
        "purpose": "Preview applying the current per-file override drawer fields to matching current TV queue rows under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Detection is backend-owned from the current queue snapshot and does not write file_overrides.json, create folder/show future policies, enqueue work, process media, or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-apply",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "proposed_override", "confirm_apply", "preview_fingerprint"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "After explicit confirmation and a matching preview fingerprint for a path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), write exact per-file overrides for eligible current TV queue rows in the detected series. Exact manual file overrides are protected, previous series batch overrides may be replaced, and no future folder/show rule is created. This does not process media or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-clear-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["path"],
        "response_schema": "queue_file_override_series_clear_preview.v1",
        "purpose": "Preview clearing exact per-file override entries for matching current TV queue rows under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Detection is backend-owned from the current queue snapshot and does not write file_overrides.json, clear folder/inherited rules, enqueue work, process media, or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/series-clear-apply",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "confirm_apply", "preview_fingerprint"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "After explicit confirmation and a matching preview fingerprint for a path under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots), clear exact per-file override entries for current TV queue rows in the detected series. Folder/inherited rules remain untouched and no media files are processed or mutated.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/remux-pilot-promote",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["pilot_source_paths", "confirm_apply", "reason"],
        "safe_defaults": {"confirm_apply": False},
        "requires_confirmation": True,
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_remux_pilot_promotion.v1",
        "purpose": "After explicit confirmation, validate exactly three distinct completed TV pilot source paths under configured source roots with final remux route evidence, oversized_encode_remux_fallback route reason, and structured fallback-remux size-policy evidence. The backend then writes exact per-file routing.profile=remux overrides only for eligible remaining current queue rows in the detected series, protects exact manual file overrides, replaces previous series batch overrides, and creates no future folder/show rule. This does not process, remux, encode, publish, rename, move, delete, drain, or mutate source media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/folder-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["folder_path", "proposed_override", "options"],
        "response_schema": "queue_file_override_folder_preview.v1",
        "purpose": "Preview the bounded impact of a folder-prefix audio/subtitle track override under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots) using known queue snapshot rows and cached track metadata only. This does not write file_overrides.json, scan source folders, run probes, enqueue work, change queue strategy, process media, or mutate queue state.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides/folder-rule",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["folder_path", "override", "confirmation", "clear"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Save or clear a validated folder-prefix audio/subtitle track override under configured source roots (SourceMovies, SourceTV, or enabled LibraryProfiles source roots). Stream indexes and raw ffmpeg map fields are rejected, source/library roots are rejected, and save requires acknowledgement that future files may match and exact file overrides win. This does not process media or mutate source files.",
    },
    {
        "method": "POST",
        "path": "/api/failures/clear",
        "auth_required": True,
        "effect": "failure-marker-write",
        "request_keys": ["scope", "marker_path", "marker_paths", "source_json", "journal_key", "dry_run", "confirm_clear"],
        "allowed_scopes": ["selected", "visible", "all_markers"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_marker_clear_result.v1",
        "purpose": "Preview or move backend-owned failure marker JSON files out of State\\Failures\\Markers after explicit confirmation. Paths are accepted only when they resolve inside the backend failure marker folder. This does not delete media, reports, completed manifests, pending publish state, or source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/failures/archive-evidence",
        "auth_required": True,
        "effect": "failure-evidence-archive",
        "request_keys": [
            "scope",
            "include_markers",
            "include_reports",
            "dry_run",
            "dry_run_fingerprint",
            "confirm_archive",
            "reason",
            "journal_key",
        ],
        "allowed_scopes": ["all_active"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_evidence_archive_result.v1",
        "purpose": "Preview or move active backend-owned failure marker JSON and round_failures_*.json/.txt reports into a manifest-backed cleared-evidence archive under State\\Failures\\ClearManifests. Confirmed archive requires confirm_archive: true. Reason and dry-run fingerprint are optional for routine current-plan archive; supplied fingerprints are still validated. This does not delete media, logs outside failure reports, completed manifests, pending publish state, or source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/failures/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target", "source_kind"],
        "allowed_targets": ["artifact", "repro", "record_file", "record_folder"],
        "allowed_source_kinds": ["latest_json", "markers"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a backend-owned failure evidence path selected from the current failure preview row. The frontend sends only row_key, target, and source_kind; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/failures/artifacts/cleanup",
        "auth_required": True,
        "effect": "failure-artifact-delete",
        "request_keys": [
            "dry_run",
            "dry_run_fingerprint",
            "confirm_delete",
            "reason",
            "retention_days",
            "target_gb",
            "artifact_paths",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_artifact_cleanup_result.v1",
        "requires_confirmation": True,
        "journaled": True,
        "safe_defaults": {"dry_run": True, "confirm_delete": False},
        "purpose": "Preview or delete backend-owned files under current and legacy failure artifact roots only. Confirmed delete requires confirm_delete: true. Policy-based cleanup may use the current backend plan without a fingerprint; explicit artifact_paths deletion still requires a matching dry-run fingerprint. Reason is optional and defaults to a routine cleanup note. It never deletes source/output media, failure markers, round failure reports, completed manifests, pending publish state, or artifact root directories.",
    },
    {
        "method": "POST",
        "path": "/api/failures/lifecycle",
        "auth_required": True,
        "effect": "failure-resolution-journal-write",
        "request_keys": [
            "journal_key",
            "transition",
            "step_id",
            "operator_note",
            "reason",
            "dry_run",
            "dry_run_fingerprint",
            "confirm_transition",
        ],
        "allowed_transitions": ["acknowledge", "start_work", "complete_step", "waive_step", "mark_resolved", "reopen"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_lifecycle_transition_result.v1",
        "purpose": "Preview or append operator lifecycle state to State\\Failures\\ResolutionJournal\\events.jsonl for an active backend-authored failure group. Mark resolved, reopen, and waive step require a non-empty reason and confirmation; the backend recomputes current blockers at apply time. Supplied fingerprints are still validated. This does not clear markers, archive reports, retry work, mutate queue/publish/completed state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target", "row_scope"],
        "allowed_targets": ["source_file", "source_folder", "source_root"],
        "allowed_row_scopes": ["runnable", "excluded"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a path selected by the backend from a runnable or excluded queue snapshot row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/completed/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["play_output_file", "output_file", "output_folder", "sidecar", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open or play a path selected by the backend from a completed-jobs manifest row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/subtitle-qa/preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["id", "row_key", "path", "source_path", "output_path", "scope", "limit"],
        "response_schema": "subtitle_qa_preview.v1",
        "data_schema": "subtitle_qa_result.v1",
        "purpose": "Preview one already-loaded Queue or Completed row's backend-authored subtitle QA evidence without probing files, running OCR/conversion/sync tools, repairing, rerunning, rewriting sidecars, publishing, draining, or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["play_local_file", "local_file", "manifest", "destination_folder", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open or play a path selected by the backend from the current pending-publish scan; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/recovery-plan",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pending_publish_recovery_plan.v1",
        "purpose": "Build a backend-authored dry-run recovery plan from the current pending-publish scan. This does not drain, repair, rewrite, move, delete, or publish files.",
    },
    {
        "method": "POST",
        "path": "/api/completed/reconcile-manifest-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "completed.reconcile_manifest",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-authored dry-run diff for reconciling loaded completed-preview manifest rows. This does not rewrite the completed manifest, write sidecars, publish, drain, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/completed/reconcile-manifest",
        "auth_required": True,
        "effect": "completed-manifest-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "completed.reconcile_manifest",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Rerun the backend completed manifest reconcile dry-run and, after matching dry_run_fingerprint plus explicit confirmation, back up and atomically rewrite existing selected manifest rows only. This does not add/remove manifest rows, publish, drain, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/completed/repair-sidecar-metadata-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "completed.repair_sidecar_metadata",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-authored dry-run diff for completed sidecar metadata using loaded completed-preview rows and their backend-derived sidecar paths only. This does not write sidecar JSON, rewrite manifests, publish, drain, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/completed/repair-sidecar-metadata",
        "auth_required": True,
        "effect": "completed-sidecar-json-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "completed.repair_sidecar_metadata",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Rerun the backend completed sidecar metadata dry-run and, after matching dry_run_fingerprint plus explicit confirmation, back up and atomically rewrite only backend-derived sidecar metadata fields. Unknown sidecar fields are preserved.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/repair-manifest-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "pending_publish.repair_manifest",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build a backend-authored dry-run diff from the existing pending-publish scan, recovery classification, file inventory, and drain summary evidence. This does not rewrite pending manifests, drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/repair-manifest",
        "auth_required": True,
        "effect": "pending-manifest-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "pending_publish.repair_manifest",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Rerun the backend pending manifest repair dry-run and require matching dry_run_fingerprint, explicit confirmation, complete backend-derived evidence, backup, and validation before any pending manifest write. This does not drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/reconcile-orphan-payloads-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key", "limit", "reason"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_dry_run.v1",
        "candidate_command": "pending_publish.reconcile_orphan_payloads",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build backend-authored orphan payload review evidence from the existing pending-publish scan and file inventory. This does not create manifests, drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/reconcile-orphan-payloads",
        "auth_required": True,
        "effect": "pending-orphan-manifest-write",
        "request_keys": ["scope", "row_key", "limit", "reason", "dry_run_fingerprint", "confirm_apply"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_repair_reconcile_apply.v1",
        "candidate_command": "pending_publish.reconcile_orphan_payloads",
        "mutation_enabled": True,
        "frontend_exposed": True,
        "requires_confirmation": True,
        "journaled": True,
        "purpose": "Manifest-only orphan payload reconcile route. It reruns the backend dry-run and blocks unless backend evidence supplies complete destination/source fields. It never moves, deletes, drains, publishes, or touches payload/source/output media.",
    },
    {
        "method": "POST",
        "path": "/api/startup/reconcile-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "limit", "reason"],
        "allowed_scopes": ["all"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_startup_reconciliation_dry_run.v1",
        "candidate_command": "startup.reconcile_state",
        "mutation_enabled": False,
        "frontend_exposed": False,
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Build backend-authored startup reconciliation evidence for pending manifests, orphaned parked payloads, ActiveJobs, and SQLite mirror posture. This does not repair, rewrite, migrate, rebuild, drain, publish, move, delete, rerun, or touch source/scratch/output media.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/promote-queue",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": ["confirm_promote", "row_keys"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Start the backend-owned queue-wide or selected-row final-library promotion run after explicit confirmation. It copies verified completed outputs from Outsource to configured final-library destinations and may delete only verified publish-output files when cleanup is enabled.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/pause",
        "auth_required": True,
        "effect": "control-state-write",
        "request_keys": ["run_id"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Request cooperative pause of the current final-library promotion run after the active item completes or fails.",
    },
    {
        "method": "POST",
        "path": "/api/final-library-promotion/resume",
        "auth_required": True,
        "effect": "control-state-write",
        "request_keys": ["run_id"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "final_library_promotion_run.v1",
        "purpose": "Resume a paused backend-owned final-library promotion run using the current completed-output queue state.",
    },
)

__all__ = (
    "LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT",
)
