from __future__ import annotations

from typing import Any

LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/pipeline/control",
        "auth_required": True,
        "effect": "control-flag-write",
        "request_keys": ["action", "confirm_force_stop", "expected_run_id"],
        "allowed_actions": ["pause", "stop", "rescan", "kill"],
        "requires_confirmation_for": ["kill"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Write backend-owned pause, graceful stop-after-current, or rescan control flags, or force-kill related pipeline processes. Standard Run Once Backend Queue stop requests require the exact displayed run identity and are re-correlated under the backend process-control lock.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/browse-file",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path"],
        "allowed_selection_modes": ["files"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_pipeline_single_file_browse.v1",
        "purpose": "Open the native Windows file browser and return one operator-selected file for Launch single-file staging only. This does not save config, launch work, mutate queue state, rename, move, delete, publish, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["mode", "sleep_seconds", "show_config", "show_console", "single_file", "schedule_override", "queue_scope", "priority_export_id"],
        "required_request_keys": ["mode"],
        "allowed_modes": ["once", "continuous", "validate", "drain_pending_pushes"],
        "allowed_schedule_overrides": ["", "run_once", "ignore"],
        "allowed_queue_scopes": ["backend_queue", "priority_export"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing pipeline process through the Python service layer. Priority Export scope is Run Once only and is limited to a backend-owned, fingerprint-revalidated export.",
    },
    {
        "method": "POST",
        "path": "/api/audit/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["library_root", "library_roots", "source_ids", "include_sidecars", "show_console"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing audit process through the Python service layer for one or more selected audit roots. Backend launch locking, process lifecycle, and PowerShell audit policy remain authoritative.",
    },
    {
        "method": "POST",
        "path": "/api/audit/stop",
        "auth_required": True,
        "effect": "process-control",
        "request_keys": ["confirm_stop", "reason"],
        "requires_confirmation": True,
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_stop_result.v1",
        "purpose": "After explicit confirmation, stop backend-owned audit process trees only and mark audit_progress.json stopped. This does not stop pipeline/rerun work or mutate source media.",
    },
    {
        "method": "POST",
        "path": "/api/audit/sources",
        "auth_required": True,
        "effect": "audit-source-state-write",
        "request_keys": ["action", "source_id", "path", "label", "enabled"],
        "allowed_actions": ["add", "remove", "delete", "enable", "disable"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_sources.v1",
        "purpose": "Add, remove, enable, or disable backend-owned Audit source roots under State\\Audit. This does not scan folders, process media, save settings, mutate queue state, launch work, rename, move, delete, publish, drain, or touch source files.",
    },
    {
        "method": "POST",
        "path": "/api/audit/sources/scan",
        "auth_required": True,
        "effect": "audit-source-scan-state-write",
        "request_keys": ["scope", "source_id", "source_ids", "path", "max_entries"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_source_scan.v1",
        "purpose": "Recursively count media files, sidecar files, and folders for selected backend-owned Audit source roots, then write aggregate evidence under State\\Audit. The scanner skips symlinked folders and does not process, probe, rewrite sidecars, mutate queue state, launch work, drain, publish, rename, move, delete, or touch source media.",
    },
    {
        "method": "POST",
        "path": "/api/audit/score-policy",
        "auth_required": True,
        "effect": "audit-state-write",
        "request_keys": ["policy", "reset"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_score_policy_result.v2",
        "purpose": "Save or reset backend-owned audit score weights used by future audit report generation without changing queue, settings, or media files.",
    },
    {
        "method": "POST",
        "path": "/api/audit/ignore",
        "auth_required": True,
        "effect": "audit-state-write",
        "request_keys": ["action", "row_keys", "paths", "reason", "priority_only", "limit"],
        "allowed_actions": ["add", "remove"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_ignore_result.v1",
        "purpose": "Save or remove audit-only ignored file entries without queue holds, file overrides, settings saves, or media mutation.",
    },
    {
        "method": "POST",
        "path": "/api/audit/export-rerun-csv",
        "auth_required": True,
        "effect": "report-file-write",
        "request_keys": ["row_keys", "priority_only", "limit"],
        "safe_defaults": {"execution_mode": "one_at_a_time", "destination_mode": "auto_replace_clean_else_pending_review"},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_audit_rerun_export.v1",
        "purpose": "Write a backend-owned rerun import CSV from selected or loaded non-ignored audit rows under State\\Rerun\\ImportCsv and return Queue CSV Rerun handoff metadata without launching rerun work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": [
            "csv_path",
            "execution_mode",
            "destination_mode",
            "window_size",
            "collision_policy",
            "stage_mode",
            "original_mode",
            "return_mode",
            "confirm_replace_final",
            "confirm_source_overwrite",
            "scope",
            "preview_limit",
            "enabled_only",
            "skip_blocked",
            "skip_warning_rows",
            "first_n",
            "issue_filter",
            "bucket_filter",
            "issue_filters",
            "bucket_filters",
            "status_filters",
        ],
        "safe_defaults": {
            "execution_mode": "one_at_a_time",
            "destination_mode": "auto_replace_clean_else_pending_review",
            "collision_policy": "replace_final",
            "window_size": 1,
            "enabled_only": True,
            "skip_blocked": False,
            "skip_warning_rows": False,
        },
        "response_schema": "desktop_rerun_csv_preview.v1",
        "purpose": "Read and summarize a CSV rerun file, recent rerun CSV candidates, backend-owned rule decisions, scope filters, blocked rows, and preview rows without launching work, writing scoped CSVs, mutating queue state, or touching media files. Rule decisions classify rows into explicit remediation policies and may block unsafe or ambiguous rows before launch.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/network-preview",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": [
            "csv_path",
            "execution_mode",
            "destination_mode",
            "window_size",
            "collision_policy",
            "stage_mode",
            "original_mode",
            "return_mode",
            "confirm_replace_final",
            "confirm_source_overwrite",
            "scope",
            "preview_limit",
            "enabled_only",
            "skip_blocked",
            "skip_warning_rows",
            "first_n",
            "issue_filter",
            "bucket_filter",
            "issue_filters",
            "bucket_filters",
            "status_filters",
        ],
        "safe_defaults": {
            "execution_mode": "one_at_a_time",
            "destination_mode": "auto_replace_clean_else_pending_review",
            "collision_policy": "replace_final",
            "window_size": 1,
            "enabled_only": True,
            "skip_blocked": False,
            "skip_warning_rows": False,
        },
        "response_schema": "desktop_rerun_network_preview.v1",
        "effect_flags": {
            "touches_media": False,
            "writes_queue": False,
            "writes_network_state": False,
            "launches_work": False,
        },
        "purpose": "Read and model how scoped CSV rerun rows would become future network row claims, including claimable/skipped/blocked/duplicate rows, source mapping readiness, output handoff readiness, and destination policy risk. This does not start workers, write network batch state, mutate queue state, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/network/start-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": [
            "csv_path",
            "execution_mode",
            "destination_mode",
            "window_size",
            "collision_policy",
            "confirm_replace_final",
            "confirm_source_overwrite",
            "scope",
            "preview_limit",
            "enabled_only",
            "skip_blocked",
            "skip_warning_rows",
            "first_n",
            "issue_filters",
            "bucket_filters",
            "minimum_worker_count",
            "reason",
        ],
        "safe_defaults": {
            "execution_mode": "one_at_a_time",
            "destination_mode": "auto_replace_clean_else_pending_review",
            "collision_policy": "replace_final",
            "window_size": 1,
            "minimum_worker_count": 0,
        },
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_network_start_dry_run.v1",
        "candidate_command": "rerun.network.start",
        "mutation_enabled": False,
        "requires_confirmation": False,
        "journaled": False,
        "effect_flags": {
            "touches_media": False,
            "writes_queue": False,
            "writes_network_state": False,
            "launches_work": False,
        },
        "purpose": "Backend-owned dry-run for a future confirmed network CSV rerun batch start. It validates NetworkRole=coordinator, coordinator lifecycle readiness, active-work and duplicate-batch guards, destination/collision preview safety, worker availability evidence, exact state files the confirmed start would write, rollback expectations, and media paths it will not touch. It does not create worker claims, write network state, mutate queue state, launch work, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/network/start",
        "auth_required": True,
        "effect": "network-state-write",
        "request_keys": [
            "csv_path",
            "execution_mode",
            "destination_mode",
            "window_size",
            "collision_policy",
            "confirm_replace_final",
            "confirm_source_overwrite",
            "scope",
            "preview_limit",
            "enabled_only",
            "skip_blocked",
            "skip_warning_rows",
            "first_n",
            "issue_filters",
            "bucket_filters",
            "minimum_worker_count",
            "reason",
            "dry_run_fingerprint",
            "confirm_start",
        ],
        "safe_defaults": {
            "execution_mode": "one_at_a_time",
            "destination_mode": "auto_replace_clean_else_pending_review",
            "collision_policy": "replace_final",
            "window_size": 1,
            "minimum_worker_count": 0,
            "confirm_start": False,
        },
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_network_start.v1",
        "requires_confirmation": True,
        "requires_strict_boolean": ["confirm_start"],
        "requires_dry_run_fingerprint": True,
        "journaled": True,
        "effect_flags": {
            "touches_media": False,
            "writes_queue": False,
            "writes_network_state": True,
            "launches_work": False,
        },
        "purpose": "After a matching backend dry_run_fingerprint and confirm_start=true, create exactly one coordinator-owned Network CSV rerun batch state file under State\\Rerun\\Network and record strict command journal evidence. Rows are written as claim-disabled/not-yet-claimable until Phase 4. This does not start workers, create claims, stage sources, mutate queue state, mutate pending publish, mutate final output, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/network/retry",
        "auth_required": True,
        "effect": "network-state-write",
        "request_keys": ["batch_id", "row_key", "request_id", "reason", "confirm_retry"],
        "safe_defaults": {"confirm_retry": False},
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_network_retry.v1",
        "requires_confirmation": True,
        "requires_strict_boolean": ["confirm_retry"],
        "journaled": True,
        "duplicate_guarded": True,
        "effect_flags": {
            "touches_media": False,
            "writes_queue": False,
            "writes_network_state": True,
            "launches_work": False,
        },
        "purpose": "After confirm_retry=true, reopen exactly one retry_exhausted Network CSV rerun row only when fresh source size, mtime, and source_identity_v2 evidence still match. request_id provides an idempotent duplicate-command guard. The route preserves failure history and never retries review, corrupt, ambiguous-output, claimed, or otherwise ineligible rows.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": [
            "csv_path",
            "dry_run",
            "plan_only",
            "execution_mode",
            "destination_mode",
            "window_size",
            "collision_policy",
            "stage_mode",
            "original_mode",
            "return_mode",
            "confirm_replace_final",
            "confirm_source_overwrite",
            "show_console",
            "scope",
            "preview_limit",
            "enabled_only",
            "skip_blocked",
            "skip_warning_rows",
            "first_n",
            "issue_filter",
            "bucket_filter",
            "issue_filters",
            "bucket_filters",
            "status_filters",
        ],
        "safe_defaults": {
            "dry_run": False,
            "plan_only": False,
            "execution_mode": "one_at_a_time",
            "destination_mode": "auto_replace_clean_else_pending_review",
            "collision_policy": "replace_final",
            "window_size": 1,
            "enabled_only": True,
            "skip_blocked": False,
            "skip_warning_rows": False,
        },
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_scoped_csv.v1",
        "purpose": "Launch backend-owned CSV rerun v2 with one-at-a-time execution by default. The default destination is auto_replace_clean_else_pending_review: clean outputs may replace the backend-planned final target only with strict replacement confirmation, while outputs with issue evidence are parked in Pending Publish/review. Scope filters may materialize a backend-owned scoped CSV under State\\Rerun\\ScopedCsv before dry-run or live start; scoped CSVs carry backend rule evidence when written, blocked rule rows cannot launch, legacy stage/original/return aliases are accepted but high-level destination/collision fields are authoritative. WebView derives confirm_replace_final from destination/collision selection, source-path overwrite requires confirm_source_overwrite, and backend plus PowerShell still require strict boolean confirmation.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/control",
        "auth_required": True,
        "effect": "process-control",
        "request_keys": ["action", "confirm_stop", "confirm_pause"],
        "requires_strict_boolean": ["confirm_stop", "confirm_pause"],
        "allowed_actions": ["stop_after_current", "pause"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_control.v1",
        "purpose": "After confirm_stop=true or confirm_pause=true, write a backend-owned CSV rerun stop-after-current control marker under State\\Rerun\\Control for exactly one active rerun_csv job. Pause is an operator-facing alias for finishing the current row/window and starting no next CSV row. This does not mutate rerun manifests, queue state, source media, outputs, or pending publish manifests.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/continue",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["manifest_key", "request_id", "confirm_continue"],
        "requires_strict_boolean": ["confirm_continue"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_continue.v1",
        "purpose": "After confirm_continue=true, materialize a backend-owned scoped CSV under State\\Rerun\\ScopedCsv from rows still pending in a stopped_after_current manifest; exact retry_exhausted rows with preserved source-identity evidence in a completed_with_failures manifest; or waiting/retry-scheduled rows only after correlated terminal ActiveJobs evidence proves the prior child exited. A required request_id and durable source-manifest/scope/row recovery key make the operation restart-durable and exactly once. Staged/processing/completed/review rows are left untouched.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["target", "row_key", "csv_key"],
        "allowed_targets": ["review_output", "review_folder", "manifest", "import_csv", "scoped_csv", "csv_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open only backend-derived CSV rerun artifacts by row_key or csv_key; arbitrary filesystem paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/promote-dry-run",
        "auth_required": True,
        "effect": "read-only-preview",
        "request_keys": ["row_key"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_rerun_promote_dry_run.v1",
        "purpose": "Build backend-authored dry-run evidence for promoting an existing rerun review output into Pending Publish without moving files or writing manifests.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/promote",
        "auth_required": True,
        "effect": "pending-manifest-write",
        "request_keys": ["row_key", "dry_run_fingerprint", "confirm_promote"],
        "requires_strict_boolean": ["confirm_promote"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "After matching dry-run evidence and confirm_promote=true, move an existing rerun review output into Pending Publish and write a pending-publish manifest; it does not directly publish or touch source media.",
    },
    {
        "method": "POST",
        "path": "/api/backend/lifecycle/reconcile-dry-run",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["reason"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_lifecycle_reconciliation.v1",
        "requires_confirmation": False,
        "journaled": False,
        "purpose": "Validate and correlate terminal lifecycle recovery evidence, recorded PIDs, and the exact archive transaction without changing lifecycle evidence or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/backend/lifecycle/reconcile",
        "auth_required": True,
        "effect": "lifecycle-evidence-reconciliation",
        "request_keys": ["confirm_apply", "dry_run_fingerprint", "reason"],
        "safe_defaults": {"confirm_apply": False},
        "requires_strict_boolean": ["confirm_apply"],
        "requires_dry_run_fingerprint": True,
        "requires_confirmation": True,
        "journaled": True,
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_lifecycle_reconciliation.v1",
        "purpose": "After an exact dry-run fingerprint and confirm_apply=true, archive only a correlated terminal failed lifecycle recovery chain and record strict durable command evidence; media files are never touched.",
    },
    {
        "method": "POST",
        "path": "/api/backend/shutdown",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "request_keys": ["reason", "force_active_work_shutdown"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Request graceful shutdown of the local API backend owned by the desktop shell; unsafe close-readiness is rejected unless explicit boolean true force cleanup is requested.",
    },
)

__all__ = (
    "LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT",
)
