from __future__ import annotations

from .api_routes_command_file import *  # noqa: F403
from .api_routes_command_operations import *  # noqa: F403
from .api_routes_command_settings_ui import *  # noqa: F403
from .api_routes_command_network import *  # noqa: F403
from .api_routes_command_process import *  # noqa: F403

LOCAL_API_COMMAND_ROUTE_CONTRACT = (
    LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_UI_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT
)


__all__ = [
    "LOCAL_API_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_METRICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_NETWORK_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_UI_COMMAND_ROUTE_CONTRACT",
]
