from __future__ import annotations

from .api_routes_command import LOCAL_API_COMMAND_ROUTE_CONTRACT
from .api_routes_read import LOCAL_API_READ_ROUTE_CONTRACT
from .api_routes_shared import LOCAL_API_CONTRACT_SCHEMA_VERSION


LOCAL_API_ROUTE_CONTRACT = LOCAL_API_READ_ROUTE_CONTRACT + LOCAL_API_COMMAND_ROUTE_CONTRACT


__all__ = [
    "LOCAL_API_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_CONTRACT_SCHEMA_VERSION",
    "LOCAL_API_READ_ROUTE_CONTRACT",
    "LOCAL_API_ROUTE_CONTRACT",
]
