"""Canonical Pydantic contract for MediaPipeline configuration.

The runtime PSD1, the desktop settings schema, and generated JSON Schema
share this flat field shape. Field names intentionally match the PSD1 keys
instead of using snake_case aliases so round-trips do not need a key map.
"""

from __future__ import annotations

from typing import Any, ClassVar, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from mediapipeline.contracts.config_coercion import (
    _coerce_config_bool,
    _mapping_from_json_or_mapping,
    _normalize_config_term_list,
)
from mediapipeline.contracts.config_defaults import (
    _list_default,
    _rename_movie_filter_options_default,
    _rename_movie_remove_terms_default,
    _rename_tv_filter_options_default,
    _rename_tv_remove_terms_default,
)
from mediapipeline.contracts.config_schema_extras import (
    _final_library_promotion_rules_schema_extra,
    _library_profiles_schema_extra,
    _subtitle_cross_field_schema_extra,
)
from mediapipeline.contracts.config_validators import (
    derive_missing_height_tolerance_fields,
    derive_missing_resolution_size_targets,
    reject_boolean_numeric_fields,
    validate_cross_field_config_policy,
)

from mediapipeline.contracts.height_tolerance import (
    DEFAULT_ROUTE_1080P_UPPER_HEIGHT_TOLERANCE_PERCENT,
    DEFAULT_ROUTE_1440P_LOWER_HEIGHT_TOLERANCE_PERCENT,
    DEFAULT_ROUTE_1440P_UPPER_HEIGHT_TOLERANCE_PERCENT,
    DEFAULT_ROUTE_4K_LOWER_HEIGHT_TOLERANCE_PERCENT,
)
from mediapipeline.core.rename.constants import RENAME_MOVIE_FILTER_OPTION_KEYS, RENAME_TV_FILTER_OPTION_KEYS
from mediapipeline.core.rename.movie import rename_movie_filter_default_terms
from mediapipeline.core.rename.tv import rename_tv_filter_default_terms
from mediapipeline.core.validation.strict_json import loads_strict_json

CONFIG_SCHEMA_VERSION: Literal[1] = 1

REQUIRED_CONFIG_KEYS: tuple[str, ...] = (
    "SourceMovies",
    "SourceTV",
    "Outsource",
    "LocalBase",
    "MinFreeSpaceGB",
    "VideoCodec",
    "VideoPreset",
    "VideoQuality",
    "OutputContainer",
    "CompatibleAudioCodecs",
    "SubKeepLanguages",
    "SubSDHTitleKeywords",
    "SubSupplementalKeywords",
    "DropAssAfterConversion",
    "RemuxSafeVideoCodecs",
    "ValidExtensions",
    "FileStabilityWait",
    "EnableIntegrityCheck",
    "CreateTVSubfolder",
    "RobocopyFlags",
    "DebugMode",
    "SkipStabilityCheck",
)

PS_CONFIG_KEY_ORDER: tuple[str, ...] = (
    "ConfigSchemaVersion",
    "SourceMovies",
    "SourceTV",
    "Outsource",
    "LibraryProfiles",
    "LocalBase",
    "MovieRoute1080pTargetSizeGB",
    "MovieRoute1440pTargetSizeGB",
    "MovieRoute4KTargetSizeGB",
    "TVRoute1080pTargetSizeGB",
    "TVRoute1440pTargetSizeGB",
    "TVRoute4KTargetSizeGB",
    "RoutingProfile",
    "RouteThresholdMode",
    "Route1080pUpperHeightTolerancePercent",
    "Route1080pMaxVideoBitrateMbps",
    "Route1440pLowerHeightTolerancePercent",
    "Route1440pUpperHeightTolerancePercent",
    "Route1440pMaxVideoBitrateMbps",
    "Route4KLowerHeightTolerancePercent",
    "Route4KMaxVideoBitrateMbps",
    "AllowH264RemuxIfPlexCompatible",
    "H264RemuxMaxBitrateMbps",
    "H264RemuxMaxHeight",
    "SizeGuardMode",
    "MaxEncodeGrowthPercent",
    "CompatibilityEncodeGrowthPercent",
    "EncodeWasteGuardMode",
    "EncodeWasteGuardPreflightEnabled",
    "EncodeWasteGuardMinProgressPercent",
    "EncodeWasteGuardMinElapsedSeconds",
    "EncodeWasteGuardOversizeMarginPercent",
    "EncodeWasteGuardConsecutiveSamples",
    "EncodeWasteGuardPollSeconds",
    "EncodeWasteGuardPreflightSampleSeconds",
    "EncodeWasteGuardPreflightSampleCount",
    "EncodeWasteGuardPreflightTimeoutSeconds",
    "MinFreeSpaceGB",
    "OutsourceMinFreeSpaceGB",
    "DeferredPublish",
    "PendingPublishDrainMode",
    "PendingPublishDrainBatchSize",
    "FinalLibraryPromotionEnabled",
    "FinalLibraryPromotionRules",
    "FinalLibraryPromotionVerificationMode",
    "FinalLibraryPromotionCleanupAfterVerified",
    "FinalLibraryPromotionOverwriteExisting",
    "VideoCodec",
    "EncoderBackend",
    "VideoPreset",
    "VideoQuality",
    "OutputContainer",
    "DynamicHdrPolicy",
    "DoviToolPath",
    "Hdr10PlusToolPath",
    "EncodeTuningPreset",
    "EncodeLadder",
    "ExtraVideoFlags",
    "AudioPassthroughProfile",
    "CompatibleAudioCodecs",
    "PreferredDefaultAudioLanguages",
    "AudioTranscodeCodec",
    "AudioTranscodeBitrate",
    "AudioTranscodeAutoBitrateByChannels",
    "AudioDownmixMode",
    "AudioMaxChannels",
    "AllowNoAudio",
    "SubKeepLanguages",
    "AllowSubtitleHelperFallback",
    "ConvertTx3gToSrt",
    "DropTx3gAfterConversion",
    "CreateExternalTx3gSrtSidecars",
    "Tx3gExtractLanguages",
    "Tx3gPreserveExistingSrt",
    "Tx3gTreatForcedAsSeparate",
    "ConvertBdpgsToSrt",
    "DropBdpgsAfterConversion",
    "BdpgsExtractLanguages",
    "BdpgsOcrToolPath",
    "BdpgsOcrTessdataPath",
    "ConvertVobSubToSrt",
    "DropVobSubAfterConversion",
    "VobSubExtractLanguages",
    "VobSubOcrToolPath",
    "SubSDHTitleKeywords",
    "SubSupplementalKeywords",
    "DropAssAfterConversion",
    "StripFormatting",
    "RemoveKaraoke",
    "MergeAdjacent",
    "MergeThresholdMs",
    "KeepSignsAndSongs",
    "TreatAssSignsSongsAsForced",
    "TreatTx3gSignsSongsAsForced",
    "TreatBdpgsSignsSongsAsForced",
    "TreatVobSubSignsSongsAsForced",
    "ExcludeSubtitleStyles",
    "IncludeSubtitleStyles",
    "RemuxSafeVideoCodecs",
    "RenameMovieFilterOptions",
    "RenameMovieFilterTerms",
    "RenameMovieRemoveTerms",
    "RenameTVFilterOptions",
    "RenameTVFilterTerms",
    "RenameTVRemoveTerms",
    "ValidExtensions",
    "FileStabilityWait",
    "EnableWatchFolders",
    "WatchFolderRoots",
    "WatchDebounceSeconds",
    "WatchScanTimeoutSeconds",
    "WatchAction",
    "WatchRespectScheduleWindow",
    "SkipStabilityCheck",
    "EnableIntegrityCheck",
    "CreateTVSubfolder",
    "AggressiveEpisodeParsing",
    "RobocopyFlags",
    "DebugMode",
    "LogRetentionDays",
    "InterruptedToolLogRetentionDays",
    "PipelineDebugLogMaxBytes",
    "FailureArtifactWarningThresholdGB",
    "FailureArtifactRetentionDays",
    "FailureArtifactCleanupTargetGB",
    "PriorityMarkers",
    "MixPriorityPhase",
    "QueueOrderingStrategy",
    "ConsoleLogLevel",
    "FileLogLevel",
    "MaxParallelEncodes",
    "ParallelEncodeMode",
    "FallbackCpuQuality",
    "CpuEncodePreset",
    "CpuEncodeProcessPriority",
    "CpuEncodeMaxThreads",
    "OutputSizeMultiplier",
    "FFmpegEncodeTimeoutSeconds",
    "FFmpegCpuEncodeTimeoutSeconds",
    "CpuEncodeMutexWaitSeconds",
    "FFmpegRemuxTimeoutSeconds",
    "MkvmergeRemuxTimeoutSeconds",
    "SubtitleExtractTimeoutSeconds",
    "SubtitleProbeTimeoutSeconds",
    "BdpgsOcrTimeoutSeconds",
    "VobSubOcrTimeoutSeconds",
    "OutputValidationProbeTimeoutSeconds",
    "OutputValidationMinSizeBytes",
    "OutputValidationDurationToleranceSeconds",
    "EnableQualityVerification",
    "QualityMetric",
    "QualitySampleMode",
    "QualitySampleSeconds",
    "QualitySampleCount",
    "QualityWarnThreshold",
    "QualityFailThreshold",
    "QualityFailAction",
    "QualityVerifyTimeoutSeconds",
    "AllowSystemTools",
    "RobocopyTimeoutSeconds",
    "TransientFailureRetryLimit",
    "ConsecutiveRoundFailureBlockLimit",
    "ConsecutiveRoundFailureProbeBackoffSeconds",
    "PendingPublishBacklogBlockThreshold",
    "PendingPublishDeferredBlockThreshold",
    "AutonomyPendingTotalReviewBytes",
    "AutonomyPendingTotalBlockBytes",
    "PauseFlagReviewSeconds",
    "PauseFlagBlockSeconds",
    "LocalWorkerHeartbeatGraceSeconds",
    "QueueExecutionMaxRunnablePerRound",
    "QueueLaunchSnapshotFreshnessSeconds",
    "StateDbMaintenanceIntervalSeconds",
    "StateDbWalReviewBytes",
    "StateDbCompletedJobsMaxRows",
    "IndexScanTimeoutSeconds",
    "SourceScanTimeoutSeconds",
    "CleanupScanTimeoutSeconds",
    "CleanupRemoteStaging",
    "CleanupStaleAgeHours",
    "SourceScanIntervalSeconds",
    "ProcessedIndexRefreshSeconds",
    "MinPipelineVersion",
    "ReprocessAll",
    "ShowOverrides",
    "PlannerRolloutStage",
    "UsePythonPlanner",
    "EnableHandBrakeSettingsUi",
    "PlannerComparisonLogging",
    "NewPlannerCutoverApproved",
)

NETWORK_CONFIG_KEYS: tuple[str, ...] = (
    "NetworkRole",
    "CoordinatorPort",
    "CoordinatorBindAddress",
    "CoordinatorAlsoEncodeLocally",
    "CoordinatorHeartbeatTimeoutMins",
    "CoordinatorMaxJobRetries",
    "CoordinatorAuthToken",
    "NetworkRerunHandoffRoot",
    "WorkerCoordinatorUrl",
    "WorkerName",
    "WorkerAuthToken",
    "WorkerPollIntervalSecs",
    "WorkerSourcePathMap",
    "WorkerEncoderMap",
    "WorkerHonorCoordinatorPolicy",
    "WorkerConfigOverrides",
)

CONFIG_KEY_ORDER: tuple[str, ...] = PS_CONFIG_KEY_ORDER + NETWORK_CONFIG_KEYS

DESKTOP_SCHEMA_CONFIG_KEYS: tuple[str, ...] = (
    "SourceMovies",
    "SourceTV",
    "Outsource",
    "LibraryProfiles",
    "LocalBase",
    "FinalLibraryPromotionEnabled",
    "FinalLibraryPromotionRules",
    "FinalLibraryPromotionVerificationMode",
    "FinalLibraryPromotionCleanupAfterVerified",
    "FinalLibraryPromotionOverwriteExisting",
    "MinFreeSpaceGB",
    "OutsourceMinFreeSpaceGB",
    "CreateTVSubfolder",
    "AudioPassthroughProfile",
    "CompatibleAudioCodecs",
    "PreferredDefaultAudioLanguages",
    "AudioTranscodeCodec",
    "AudioTranscodeBitrate",
    "AudioTranscodeAutoBitrateByChannels",
    "AudioDownmixMode",
    "AudioMaxChannels",
    "AllowNoAudio",
    "MovieRoute1080pTargetSizeGB",
    "MovieRoute1440pTargetSizeGB",
    "MovieRoute4KTargetSizeGB",
    "TVRoute1080pTargetSizeGB",
    "TVRoute1440pTargetSizeGB",
    "TVRoute4KTargetSizeGB",
    "RoutingProfile",
    "RouteThresholdMode",
    "Route1080pUpperHeightTolerancePercent",
    "Route1080pMaxVideoBitrateMbps",
    "Route1440pLowerHeightTolerancePercent",
    "Route1440pUpperHeightTolerancePercent",
    "Route1440pMaxVideoBitrateMbps",
    "Route4KLowerHeightTolerancePercent",
    "Route4KMaxVideoBitrateMbps",
    "AllowH264RemuxIfPlexCompatible",
    "H264RemuxMaxBitrateMbps",
    "H264RemuxMaxHeight",
    "SizeGuardMode",
    "MaxEncodeGrowthPercent",
    "CompatibilityEncodeGrowthPercent",
    "EncodeWasteGuardMode",
    "EncodeWasteGuardPreflightEnabled",
    "EncodeWasteGuardMinProgressPercent",
    "EncodeWasteGuardMinElapsedSeconds",
    "EncodeWasteGuardOversizeMarginPercent",
    "EncodeWasteGuardConsecutiveSamples",
    "EncodeWasteGuardPollSeconds",
    "EncodeWasteGuardPreflightSampleSeconds",
    "EncodeWasteGuardPreflightSampleCount",
    "EncodeWasteGuardPreflightTimeoutSeconds",
    "DeferredPublish",
    "PendingPublishDrainMode",
    "PendingPublishDrainBatchSize",
    "AggressiveEpisodeParsing",
    "VideoCodec",
    "EncoderBackend",
    "VideoPreset",
    "VideoQuality",
    "OutputContainer",
    "DynamicHdrPolicy",
    "DoviToolPath",
    "Hdr10PlusToolPath",
    "EncodeTuningPreset",
    "EncodeLadder",
    "ExtraVideoFlags",
    "RemuxSafeVideoCodecs",
    "FallbackCpuQuality",
    "CpuEncodePreset",
    "CpuEncodeProcessPriority",
    "FFmpegCpuEncodeTimeoutSeconds",
    "CpuEncodeMutexWaitSeconds",
    "MkvmergeRemuxTimeoutSeconds",
    "CpuEncodeMaxThreads",
    "SubKeepLanguages",
    "AllowSubtitleHelperFallback",
    "ConvertTx3gToSrt",
    "DropTx3gAfterConversion",
    "CreateExternalTx3gSrtSidecars",
    "Tx3gExtractLanguages",
    "Tx3gPreserveExistingSrt",
    "Tx3gTreatForcedAsSeparate",
    "ConvertBdpgsToSrt",
    "DropBdpgsAfterConversion",
    "BdpgsExtractLanguages",
    "BdpgsOcrToolPath",
    "BdpgsOcrTessdataPath",
    "ConvertVobSubToSrt",
    "DropVobSubAfterConversion",
    "VobSubExtractLanguages",
    "VobSubOcrToolPath",
    "DropAssAfterConversion",
    "RemoveKaraoke",
    "KeepSignsAndSongs",
    "TreatAssSignsSongsAsForced",
    "TreatTx3gSignsSongsAsForced",
    "TreatBdpgsSignsSongsAsForced",
    "TreatVobSubSignsSongsAsForced",
    "StripFormatting",
    "MergeAdjacent",
    "MergeThresholdMs",
    "SubSDHTitleKeywords",
    "SubSupplementalKeywords",
    "ExcludeSubtitleStyles",
    "IncludeSubtitleStyles",
    "ConfigSchemaVersion",
    "ShowOverrides",
    "PlannerRolloutStage",
    "UsePythonPlanner",
    "EnableHandBrakeSettingsUi",
    "PlannerComparisonLogging",
    "NewPlannerCutoverApproved",
    "RenameMovieFilterOptions",
    "RenameMovieFilterTerms",
    "RenameMovieRemoveTerms",
    "RenameTVFilterOptions",
    "RenameTVFilterTerms",
    "RenameTVRemoveTerms",
    "MaxParallelEncodes",
    "ParallelEncodeMode",
    "DebugMode",
    "ConsoleLogLevel",
    "FileLogLevel",
    "LogRetentionDays",
    "InterruptedToolLogRetentionDays",
    "PipelineDebugLogMaxBytes",
    "FailureArtifactWarningThresholdGB",
    "FailureArtifactRetentionDays",
    "FailureArtifactCleanupTargetGB",
    "FileStabilityWait",
    "SkipStabilityCheck",
    "FFmpegEncodeTimeoutSeconds",
    "FFmpegRemuxTimeoutSeconds",
    "SubtitleExtractTimeoutSeconds",
    "SubtitleProbeTimeoutSeconds",
    "BdpgsOcrTimeoutSeconds",
    "VobSubOcrTimeoutSeconds",
    "AllowSystemTools",
    "RobocopyTimeoutSeconds",
    "TransientFailureRetryLimit",
    "ConsecutiveRoundFailureBlockLimit",
    "ConsecutiveRoundFailureProbeBackoffSeconds",
    "PendingPublishBacklogBlockThreshold",
    "PendingPublishDeferredBlockThreshold",
    "AutonomyPendingTotalReviewBytes",
    "AutonomyPendingTotalBlockBytes",
    "PauseFlagReviewSeconds",
    "PauseFlagBlockSeconds",
    "LocalWorkerHeartbeatGraceSeconds",
    "QueueExecutionMaxRunnablePerRound",
    "QueueLaunchSnapshotFreshnessSeconds",
    "StateDbMaintenanceIntervalSeconds",
    "StateDbWalReviewBytes",
    "StateDbCompletedJobsMaxRows",
    "MinPipelineVersion",
    "OutputSizeMultiplier",
    "OutputValidationProbeTimeoutSeconds",
    "OutputValidationMinSizeBytes",
    "OutputValidationDurationToleranceSeconds",
    "EnableQualityVerification",
    "QualityMetric",
    "QualitySampleMode",
    "QualitySampleSeconds",
    "QualitySampleCount",
    "QualityWarnThreshold",
    "QualityFailThreshold",
    "QualityFailAction",
    "QualityVerifyTimeoutSeconds",
    "EnableIntegrityCheck",
    "RobocopyFlags",
    "PriorityMarkers",
    "MixPriorityPhase",
    "QueueOrderingStrategy",
    "SourceScanIntervalSeconds",
    "SourceScanTimeoutSeconds",
    "ProcessedIndexRefreshSeconds",
    "ReprocessAll",
    "IndexScanTimeoutSeconds",
    "CleanupScanTimeoutSeconds",
    "ValidExtensions",
    "CleanupRemoteStaging",
    "CleanupStaleAgeHours",
    "EnableWatchFolders",
    "WatchFolderRoots",
    "WatchDebounceSeconds",
    "WatchScanTimeoutSeconds",
    "WatchAction",
    "WatchRespectScheduleWindow",
    *NETWORK_CONFIG_KEYS,
)

LIST_CONFIG_KEYS: tuple[str, ...] = (
    "ExtraVideoFlags",
    "CompatibleAudioCodecs",
    "PreferredDefaultAudioLanguages",
    "SubKeepLanguages",
    "Tx3gExtractLanguages",
    "BdpgsExtractLanguages",
    "VobSubExtractLanguages",
    "SubSDHTitleKeywords",
    "SubSupplementalKeywords",
    "ExcludeSubtitleStyles",
    "IncludeSubtitleStyles",
    "RemuxSafeVideoCodecs",
    "ValidExtensions",
    "WatchFolderRoots",
    "RenameMovieRemoveTerms",
    "RenameTVRemoveTerms",
    "RobocopyFlags",
    "PriorityMarkers",
)

NUMERIC_CONFIG_KEYS: tuple[str, ...] = (
    "ConfigSchemaVersion",
    "MovieRoute1080pTargetSizeGB",
    "MovieRoute1440pTargetSizeGB",
    "MovieRoute4KTargetSizeGB",
    "TVRoute1080pTargetSizeGB",
    "TVRoute1440pTargetSizeGB",
    "TVRoute4KTargetSizeGB",
    "Route1080pUpperHeightTolerancePercent",
    "Route1080pMaxVideoBitrateMbps",
    "Route1440pLowerHeightTolerancePercent",
    "Route1440pUpperHeightTolerancePercent",
    "Route1440pMaxVideoBitrateMbps",
    "Route4KLowerHeightTolerancePercent",
    "Route4KMaxVideoBitrateMbps",
    "H264RemuxMaxBitrateMbps",
    "H264RemuxMaxHeight",
    "MaxEncodeGrowthPercent",
    "CompatibilityEncodeGrowthPercent",
    "MinFreeSpaceGB",
    "OutsourceMinFreeSpaceGB",
    "PendingPublishDrainBatchSize",
    "VideoQuality",
    "AudioMaxChannels",
    "MergeThresholdMs",
    "FileStabilityWait",
    "WatchDebounceSeconds",
    "WatchScanTimeoutSeconds",
    "LogRetentionDays",
    "InterruptedToolLogRetentionDays",
    "PipelineDebugLogMaxBytes",
    "FailureArtifactWarningThresholdGB",
    "FailureArtifactRetentionDays",
    "FailureArtifactCleanupTargetGB",
    "MaxParallelEncodes",
    "FallbackCpuQuality",
    "CpuEncodeMaxThreads",
    "OutputSizeMultiplier",
    "FFmpegEncodeTimeoutSeconds",
    "FFmpegCpuEncodeTimeoutSeconds",
    "CpuEncodeMutexWaitSeconds",
    "FFmpegRemuxTimeoutSeconds",
    "MkvmergeRemuxTimeoutSeconds",
    "SubtitleExtractTimeoutSeconds",
    "SubtitleProbeTimeoutSeconds",
    "BdpgsOcrTimeoutSeconds",
    "VobSubOcrTimeoutSeconds",
    "OutputValidationProbeTimeoutSeconds",
    "OutputValidationMinSizeBytes",
    "OutputValidationDurationToleranceSeconds",
    "QualitySampleSeconds",
    "QualitySampleCount",
    "QualityWarnThreshold",
    "QualityFailThreshold",
    "QualityVerifyTimeoutSeconds",
    "RobocopyTimeoutSeconds",
    "TransientFailureRetryLimit",
    "ConsecutiveRoundFailureBlockLimit",
    "ConsecutiveRoundFailureProbeBackoffSeconds",
    "PendingPublishBacklogBlockThreshold",
    "PendingPublishDeferredBlockThreshold",
    "AutonomyPendingTotalReviewBytes",
    "AutonomyPendingTotalBlockBytes",
    "PauseFlagReviewSeconds",
    "PauseFlagBlockSeconds",
    "LocalWorkerHeartbeatGraceSeconds",
    "QueueExecutionMaxRunnablePerRound",
    "QueueLaunchSnapshotFreshnessSeconds",
    "StateDbMaintenanceIntervalSeconds",
    "StateDbWalReviewBytes",
    "StateDbCompletedJobsMaxRows",
    "IndexScanTimeoutSeconds",
    "SourceScanTimeoutSeconds",
    "CleanupScanTimeoutSeconds",
    "CleanupStaleAgeHours",
    "SourceScanIntervalSeconds",
    "ProcessedIndexRefreshSeconds",
    "CoordinatorPort",
    "CoordinatorHeartbeatTimeoutMins",
    "CoordinatorMaxJobRetries",
    "WorkerPollIntervalSecs",
)

LIBRARY_PROFILE_OVERRIDE_KEYS_BY_GROUP: dict[str, tuple[str, ...]] = {
    "editor": (
        "RoutingProfile",
        "RouteThresholdMode",
        "SizeGuardMode",
        "EncodeTuningPreset",
        "EncodeLadder",
        "VideoCodec",
        "OutputContainer",
        "MovieRoute1080pTargetSizeGB",
        "MovieRoute1440pTargetSizeGB",
        "MovieRoute4KTargetSizeGB",
        "TVRoute1080pTargetSizeGB",
        "TVRoute1440pTargetSizeGB",
        "TVRoute4KTargetSizeGB",
        "Route1080pUpperHeightTolerancePercent",
        "Route1080pMaxVideoBitrateMbps",
        "Route1440pLowerHeightTolerancePercent",
        "Route1440pUpperHeightTolerancePercent",
        "Route1440pMaxVideoBitrateMbps",
        "Route4KLowerHeightTolerancePercent",
        "Route4KMaxVideoBitrateMbps",
        "MaxEncodeGrowthPercent",
        "CompatibilityEncodeGrowthPercent",
    ),
    "video": (
        "VideoPreset",
        "VideoQuality",
        "AllowH264RemuxIfPlexCompatible",
        "H264RemuxMaxBitrateMbps",
        "H264RemuxMaxHeight",
        "RemuxSafeVideoCodecs",
        "FallbackCpuQuality",
        "CpuEncodePreset",
        "CpuEncodeProcessPriority",
        "CpuEncodeMaxThreads",
        "CpuEncodeMutexWaitSeconds",
        "ExtraVideoFlags",
    ),
    "subtitles": (
        "SubKeepLanguages",
        "ConvertTx3gToSrt",
        "DropTx3gAfterConversion",
        "CreateExternalTx3gSrtSidecars",
        "Tx3gExtractLanguages",
        "Tx3gPreserveExistingSrt",
        "Tx3gTreatForcedAsSeparate",
        "ConvertBdpgsToSrt",
        "DropBdpgsAfterConversion",
        "BdpgsExtractLanguages",
        "BdpgsOcrToolPath",
        "BdpgsOcrTessdataPath",
        "ConvertVobSubToSrt",
        "DropVobSubAfterConversion",
        "VobSubExtractLanguages",
        "VobSubOcrToolPath",
        "SubtitleExtractTimeoutSeconds",
        "SubtitleProbeTimeoutSeconds",
        "BdpgsOcrTimeoutSeconds",
        "VobSubOcrTimeoutSeconds",
        "SubSDHTitleKeywords",
        "SubSupplementalKeywords",
        "DropAssAfterConversion",
        "StripFormatting",
        "RemoveKaraoke",
        "MergeAdjacent",
        "MergeThresholdMs",
        "KeepSignsAndSongs",
        "TreatAssSignsSongsAsForced",
        "TreatTx3gSignsSongsAsForced",
        "TreatBdpgsSignsSongsAsForced",
        "TreatVobSubSignsSongsAsForced",
        "ExcludeSubtitleStyles",
        "IncludeSubtitleStyles",
    ),
    "audio": (
        "AudioPassthroughProfile",
        "CompatibleAudioCodecs",
        "PreferredDefaultAudioLanguages",
        "AudioTranscodeCodec",
        "AudioTranscodeBitrate",
        "AudioTranscodeAutoBitrateByChannels",
        "AudioDownmixMode",
        "AudioMaxChannels",
        "AllowNoAudio",
    ),
}

LIBRARY_PROFILE_TOP_LEVEL_KEYS: tuple[str, ...] = (
    "id",
    "name",
    "enabled",
    "designation",
    "source_path",
    "output_path",
    "promotion_enabled",
    "promotion_destination",
    "overrides",
    "editor_overrides",
    "media_overrides",
    "default_tracking",
)

FINAL_LIBRARY_PROMOTION_RULE_KEYS: tuple[str, ...] = (
    "id",
    "label",
    "enabled",
    "source_root",
    "output_root",
    "destination_root",
    "library_id",
    "designation",
)

COMPATIBLE_AUDIO_CODECS_DEFAULT: tuple[str, ...] = (
    "aac",
    "ac3",
    "eac3",
    "mp3",
    "opus",
    "vorbis",
    "truehd",
    "mlp",
)
SUBTITLE_LANGUAGE_DEFAULT: tuple[str, ...] = ("eng", "en", "und", "")
SUBTITLE_EXTRACT_LANGUAGE_DEFAULT: tuple[str, ...] = ("eng", "en", "und")
SUB_SDH_KEYWORD_DEFAULT: tuple[str, ...] = (
    "sdh",
    "hearing impaired",
    "hearing-impaired",
    "cc",
    "closed caption",
    "closedcaption",
)
SUB_SUPPLEMENTAL_KEYWORD_DEFAULT: tuple[str, ...] = (
    "sign",
    "song",
    "karaoke",
    "chapter",
    "opening",
    "ending",
)
EXCLUDE_SUBTITLE_STYLES_DEFAULT: tuple[str, ...] = (
    "Sign",
    "Sign *",
    "Sign-*",
    "Signs",
    "Signs *",
    "Signs-*",
    "OP",
    "OP *",
    "OP-*",
    "OP_*",
    "Opening*",
    "ED",
    "ED *",
    "ED-*",
    "ED_*",
    "Ending*",
    "*Lyrics*",
    "*Romaji*",
    "*Kanji*",
    "Song",
    "Song *",
    "Song-*",
    "Title",
    "Show Title",
    "Episode Title",
    "Next Episode",
    "Next *",
    "Credits",
    "Credit*",
    "Note",
    "Note*",
    "Caption",
    "Caption*",
    "fs",
)















__all__ = (
    "CONFIG_SCHEMA_VERSION",
    "REQUIRED_CONFIG_KEYS",
    "PS_CONFIG_KEY_ORDER",
    "NETWORK_CONFIG_KEYS",
    "CONFIG_KEY_ORDER",
    "DESKTOP_SCHEMA_CONFIG_KEYS",
    "LIST_CONFIG_KEYS",
    "NUMERIC_CONFIG_KEYS",
    "LIBRARY_PROFILE_OVERRIDE_KEYS_BY_GROUP",
    "LIBRARY_PROFILE_TOP_LEVEL_KEYS",
    "FINAL_LIBRARY_PROMOTION_RULE_KEYS",
    "COMPATIBLE_AUDIO_CODECS_DEFAULT",
    "SUBTITLE_LANGUAGE_DEFAULT",
    "SUBTITLE_EXTRACT_LANGUAGE_DEFAULT",
    "SUB_SDH_KEYWORD_DEFAULT",
    "SUB_SUPPLEMENTAL_KEYWORD_DEFAULT",
    "EXCLUDE_SUBTITLE_STYLES_DEFAULT",
)
