from __future__ import annotations

import unittest

from tests.python.desktop.application_facade_test_support import served_webview_static_contract_bundle


def _queue_page_html(html: str) -> str:
    start = html.index('data-page-panel="queue"')
    end = html.find('data-page-panel="completed"', start)
    return html[start : end if end != -1 else len(html)]


def _assert_contains_all(testcase: unittest.TestCase, text: str, snippets: tuple[str, ...]) -> None:
    for snippet in snippets:
        with testcase.subTest(snippet=snippet):
            testcase.assertIn(snippet, text)


class ApplicationFacadeWebStaticQueueTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.bundle = served_webview_static_contract_bundle()

    def test_queue_page_dom_and_assets_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.html,
            (
                "/assets/queueView.summary.js",
                "/assets/queueView.review.js",
                "/assets/queueView.detail.js",
                "/assets/queueView.launch.js",
                "/assets/queue/rerunApi.js",
                "/assets/queueView.rerun.js",
                "/assets/queue/rerunRequest.js",
                "/assets/queue/statusPanels.js",
                "/assets/queue/tableView.js",
                "/assets/queue/priority.js",
                "/assets/queue/manualOrder.js",
                "/assets/queue/strategy.js",
                "/assets/queue/controls.js",
                "/assets/queue/excluded.js",
                "/assets/queue/scan.js",
                "/assets/queueView.js",
                'data-queue-tab="main"',
                'data-queue-tab="rerun"',
                'data-queue-tab-panel="main"',
                'data-queue-tab-panel="rerun"',
                "CSV Rerun",
                "rerun-review-header",
                "rerun-review-status",
                "rerun-review-csv",
                "rerun-review-counts",
                "rerun-review-next-action",
                "CSV rerun review summary",
                "rerun-lifecycle-evidence",
                "rerun-lifecycle-title",
                "rerun-lifecycle-phase",
                "rerun-lifecycle-summary",
                "rerun-lifecycle-detail",
                "Lifecycle Evidence",
                "rerun-start-csv-path",
                'aria-describedby="rerun-mode-policy-note"',
                "rerun-start-execution-mode",
                "rerun-start-window-size",
                "rerun-start-destination-mode",
                "rerun-start-collision-policy",
                "publish and replace final output",
                "replace final output",
                "Rerun handling",
                "Destination Collision",
                'data-rerun-policy-card="destination"',
                'data-rerun-policy-card="collision"',
                "Verified outputs stay in review until you choose a backend-owned final placement path.",
                "Use the CSV source path as a final-output target",
                "rerun-csv-path-picker-badge",
                'data-path-picker-target="queue.rerun_csv"',
                'data-path-picker-input="rerun-start-csv-path"',
                "rerun-queue-preflight",
                "rerun-scope-enabled-only",
                "rerun-scope-skip-blocked",
                "rerun-scope-skip-warning-rows",
                "rerun-scope-first-n",
                "rerun-scope-issue-filter",
                "rerun-scope-bucket-filter",
                "rerun-preview-limit",
                "rerun-preview-tiles",
                "rerun-recent-csv-rows",
                "rerun-preview-summary",
                "rerun-policy-panel",
                "rerun-preview-rows",
                "rerun-preview-table",
                "<th scope=\"col\">Identity</th>",
                "<th scope=\"col\">Categories</th>",
                "rerun-results-panel",
                "rerun-state-panel",
                "rerun-history-panel",
                "rerun-state-status-filter",
                "rerun-results-refresh-button",
                "rerun-stop-after-current-button",
                "Refresh backend-owned CSV rerun queue-state and run evidence.",
                "Ask the backend to stop the active CSV rerun after the current row.",
                "rerun-state-table",
                "rerun-state-rows",
                "CSV rerun queue-state rows",
                "Replaced / Returned",
                "rerun-history-summary",
                'id="rerun-open-audit-tool-button"',
                'id="rerun-inspect-csv-button"',
                'id="rerun-open-csv-button"',
                'id="rerun-open-csv-folder-button"',
                "Typed CSV paths can be previewed; Open CSV requires",
                "Typed CSV paths can be previewed; Open Folder requires",
                "Inspect CSV by loading the backend read-only preview.",
                'id="rerun-open-latest-manifest-button"',
                'id="rerun-open-run-logs-button"',
                'id="rerun-open-last-stdout-button"',
                'id="rerun-open-last-stderr-button"',
                'id="rerun-open-active-jobs-button"',
                'id="rerun-show-command-history-button"',
                'data-cross-page-target="reports" data-cross-page-reports-tab="audit"',
                "rerun-start-button",
                "Review &amp; Start",
                "queue-filter",
                "queue-summary",
                "queue-readiness-status",
                "queue-readiness",
                "queue-breakdown-status",
                "queue-breakdown",
                "queue-validation-status",
                "queue-validation",
                "queue-workflow-status",
                "queue-workflow",
                "queue-backend-scope-status",
                "queue-backend-scope-summary",
                "queue-backend-scope-rows",
                "queue-launch-decision-status",
                "queue-launch-decision-summary",
                "queue-launch-decision-rows",
                "queue-launch-decision-detail",
                "queue-review-status",
                "queue-review-board",
                "queue-review-rows",
                "queue-review-legend",
                "queue-collision-status",
                "queue-collision",
                "queue-excluded-status",
                "queue-excluded-summary",
                "queue-excluded-rows",
                "queue-excluded-detail",
                "queue-excluded-open-status",
                'data-open-target-row-actions="queue-excluded"',
                'id="queue-detail" class="prose-block" data-visual-keep="copy-output"',
                "queue-diagnostics-status",
                "queue-diagnostics-guidance",
                "queue-diagnostics-actions",
                "queue-open-status",
                "queue-open-history",
                'data-open-target-row-actions="queue"',
                "queue-progress-bars",
                "queue-progress-summary",
                "Collision Risk",
                "Queue Decision",
                "queue-decision-summary",
                "Attention Required",
                "queue-attention-summary",
                "Search loaded queue rows",
                "Display status filter",
                "Investigation view",
                "Clear Display Filters",
                "Selected Row Detail (not launch scope)",
                "Backend Launch Scope Boundary",
                "Queue-to-Launch Handoff",
                "Backend-Excluded Source Files",
                "Selected Row Diagnostics Links",
                "queue-launch-decision-summary",
                "queue-launch-decision-detail",
                "queue-clear-filters-button",
                "data-queue-refresh-button",
                "Scan Sources asks the backend to inventory configured source roots",
                "queue-source-inventory",
                "Run History",
            ),
        )
        _assert_contains_all(
            self,
            bundle.js,
            (
                'targetDataset: "openQueueExcluded"',
                "Open Excluded Source",
                'targetDataset: "openQueue"',
                "Open Source Root",
                "queueClearFiltersButton.addEventListener(\"click\", () => window.mediaPipelineQueueView?.resetQueueFilters?.())",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_js,
            (
                "function renderRerunReviewHeader",
                "function renderRerunLifecycleEvidence",
                "function renderRerunPreviewCategoryChips",
                "function applyRerunOpenButtonState",
                "lookup_title",
                "relative_path",
                "duplicate_source",
                "entry.raw?.request",
                "Typed CSV paths can be previewed, but Open CSV and Open Folder require",
                "Review & Start submits ${route} to the backend",
            ),
        )
        self.assertLess(bundle.html.index('data-queue-refresh-button'), bundle.html.index('id="queue-rows"'))
        self.assertLess(bundle.html.index('id="queue-rows"'), bundle.html.index('id="queue-readiness"'))

    def test_queue_csv_rerun_routes_and_events_are_static_pinned(self) -> None:
        bundle = self.bundle
        rerun_runtime_js = "\n".join((bundle.queue_rerun_api_js, bundle.queue_view_rerun_js))

        _assert_contains_all(
            self,
            bundle.queue_view_js,
            (
                "const __queueRerunMod = window.__queueRerunModule || {}",
                "delete window.__queueRerunModule",
                "createQueueRerunModule",
                "function activateQueueTab",
                "function initQueueTabNav",
                "function initQueueRerunEvents",
                "startRerunFromForm",
                "refreshRerunPreview",
                "collectRerunExecutionTarget",
                "collectRerunNetworkStartDryRunRequest",
                "collectRerunNetworkStartRequest",
                "confirm_start: true",
                "selectRerunCsvPathForPreview",
                "refreshRerunResults",
                "getRerunResults",
                "requestRerunContinue",
                "checkNetworkRerunStartDryRun",
                'refreshRerunResults({ quiet: true }).catch(() => {})',
                "wireClick(\"rerun-start-button\", () => startRerunFromForm({ dry_run: false }))",
                "wireClick(\"rerun-network-start-dry-run-button\", () => checkNetworkRerunStartDryRun()",
                "mediaPipelineCsvRerunWorkflow",
            ),
        )
        _assert_contains_all(
            self,
            rerun_runtime_js,
            (
                'const RERUN_PREVIEW_ROUTE = "/api/rerun/preview"',
                'const RERUN_NETWORK_PREVIEW_ROUTE = "/api/rerun/network-preview"',
                'const RERUN_NETWORK_START_DRY_RUN_ROUTE = "/api/rerun/network/start-dry-run"',
                'const RERUN_NETWORK_START_ROUTE = "/api/rerun/network/start"',
                'const RERUN_NETWORK_RETRY_ROUTE = "/api/rerun/network/retry"',
                'const RERUN_START_ROUTE = "/api/rerun/start"',
                'const RERUN_RESULTS_ROUTE = "/api/rerun/results?limit=24"',
                'const RERUN_CONTROL_ROUTE = "/api/rerun/control"',
                'const RERUN_CONTINUE_ROUTE = "/api/rerun/continue"',
                'const RERUN_OPEN_ROUTE = "/api/rerun/open"',
                'const RERUN_PROMOTE_DRY_RUN_ROUTE = "/api/rerun/promote-dry-run"',
                'const RERUN_PROMOTE_ROUTE = "/api/rerun/promote"',
                'const DIAGNOSTICS_OPEN_ROUTE = "/api/diagnostics/open"',
                'const COMMAND_HISTORY_ROUTE = "/api/commands?limit=20"',
                "function currentApiPost",
                "function currentApiGet",
                'requireApiPost(RERUN_PREVIEW_ROUTE)("/api/rerun/preview", request)',
                'requireApiPost(RERUN_NETWORK_PREVIEW_ROUTE)("/api/rerun/network-preview", request)',
                'requireApiPost(RERUN_NETWORK_START_DRY_RUN_ROUTE)("/api/rerun/network/start-dry-run", request)',
                'requireApiPost(RERUN_NETWORK_START_ROUTE)("/api/rerun/network/start", request)',
                'requireApiPost(RERUN_START_ROUTE)("/api/rerun/start", request)',
                'requireApiPost(RERUN_CONTROL_ROUTE)("/api/rerun/control", { action: "stop_after_current", confirm_stop: true })',
                'requireApiPost(RERUN_CONTROL_ROUTE)("/api/rerun/control", { action: "pause", confirm_pause: true })',
                'requireApiPost(RERUN_CONTINUE_ROUTE)("/api/rerun/continue", request)',
                "const RERUN_BACKEND_ACTION_ROUTES = new Set([RERUN_CONTINUE_ROUTE, RERUN_NETWORK_RETRY_ROUTE])",
                "function postBackendRerunAction",
                "function requestBackendRerunAction",
                'requireApiPost(RERUN_OPEN_ROUTE)("/api/rerun/open", request)',
                'requireApiPost(DIAGNOSTICS_OPEN_ROUTE)("/api/diagnostics/open", { target })',
                'requireApiPost(RERUN_PROMOTE_DRY_RUN_ROUTE)("/api/rerun/promote-dry-run", { row_key: rowKey })',
                'requireApiPost(RERUN_PROMOTE_ROUTE)("/api/rerun/promote", request)',
                'requireApiGet(RERUN_RESULTS_ROUTE)("/api/rerun/results?limit=24", { timeoutMs: 15000 })',
                'requireApiGet(COMMAND_HISTORY_ROUTE)("/api/commands?limit=20", { timeoutMs: 15000 })',
                "function getRerunResults",
                "function getCommandHistory",
                "function renderRerunQueueStateRows",
                "function rerunIssueTokens",
                "function renderRerunIssueChips",
                'Rule detail: ${item.rerun_rule_reason}',
                'Rule destination: ${item.rerun_rule_destination_behavior}',
                "rerun-issue-chip",
                "function promoteRerunRowToPending",
                "uses_pipeline_start: false",
                "Normal pipeline start route is not used for CSV rerun rows.",
                "Local and Network CSV rerun rows shown here are not normal /api/pipeline/start queue rows.",
                "Network CSV rerun reducer and destination-policy evidence is backend-authored.",
                "function startRerunFromForm",
                "function checkNetworkRerunStartDryRun",
                "function refreshRerunPreview",
                "function selectRerunCsvPathForPreview",
                "function openLatestRerunManifest",
                "function openRerunDiagnosticsTarget",
                "function showRerunCommandHistory",
                'wireClick("rerun-open-run-logs-button", () => openRerunDiagnosticsTarget("run_logs")',
                'wireClick("rerun-show-command-history-button", () => showRerunCommandHistory()',
                'button.textContent = "Open Manifest"',
                "Audit export selected",
                "Backend preview route: ${RERUN_PREVIEW_ROUTE}",
                "function requestRerunContinue",
            ),
        )
        _assert_contains_all(
            self,
            bundle.html,
            (
                'id="rerun-start-target-mode"',
                '<option value="local" selected>local CSV rerun</option>',
                '<option value="network">Network CSV rerun</option>',
                'id="rerun-network-minimum-workers"',
                'id="rerun-network-start-dry-run-button"',
                "Check Network Start",
            ),
        )
        self.assertNotIn('apiPost("/api/pipeline/start"', rerun_runtime_js)
        self.assertNotIn('Rule reason: ${item.rerun_rule_reason}', bundle.queue_view_rerun_js)
        rerun_state_table = bundle.html[
            bundle.html.index('class="workflow-table rerun-state-table"') :
            bundle.html.index("</table>", bundle.html.index('class="workflow-table rerun-state-table"'))
        ]
        self.assertNotIn("<th scope=\"col\">Evidence</th>", rerun_state_table)
        self.assertLess(bundle.html.index('class="rerun-state-panel"'), bundle.html.index('class="rerun-history-panel"'))

    def test_queue_panel_order_is_static_pinned(self) -> None:
        queue_page_html = _queue_page_html(self.bundle.html)
        queue_panel_order = [
            "<h2>Queue Decision</h2>",
            "<h2>Source Scan And Display Filters</h2>",
            "<h2>Attention Required</h2>",
            "<h2>Queue Rows</h2>",
            "<h2>Selected Row Detail (not launch scope)</h2>",
            "<h2>Selected Row Diagnostics Links</h2>",
            "<h2>Backend Launch Scope Boundary</h2>",
            "<h2>Queue-to-Launch Handoff</h2>",
            "<h2>Source Scan Progress</h2>",
            "<h2>Queue Snapshot</h2>",
            "<h2>Readiness</h2>",
            "<h2>Queue Summary</h2>",
            "<h2>Run History</h2>",
            "<h2>Queue Readiness Checklist</h2>",
            "<h2>Next Step</h2>",
            "<h2>Flagged Items</h2>",
            "<h2>Collision Risk</h2>",
            "<h2>Backend-Excluded Source Files</h2>",
        ]
        positions = [queue_page_html.index(marker) for marker in queue_panel_order]
        self.assertEqual(positions, sorted(positions))

    def test_queue_view_namespace_progress_and_snapshot_contracts_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.queue_view_js,
            (
                "window.mediaPipelineQueueView",
                "function renderQueue",
                "function renderQueueRows",
                "function selectQueueRow",
                "function renderQueueProgress",
                "function queueProgressBars",
                "const progressRenderer = window.mediaPipelineProgressView?.renderProgressBarsInto",
                "progressRenderer(\"queue-progress-bars\"",
                "function renderQueueCollision",
                "function queueCollisionStatus",
                "function queueCollisionLines",
                "function renderQueueExcluded",
                "function renderQueueExcludedDetail",
                "function selectQueueExcludedRow",
                "function queueExcludedRowKey",
                "row_scope",
                "Row-level excluded-file detail: unavailable",
                "function renderQueueDetail",
                "function renderQueueSummary",
                "function renderQueueReadiness",
                "function renderQueueBreakdown",
                "function renderQueueRuntime",
                "function renderQueueValidation",
                "function queueReadinessStatus",
                "function queueReadinessLines",
                "function queueBreakdownLines",
                "function queueRuntimeLines",
                "function queueEmptyStateMessage",
                "window.getLastQueuePayload = getLastQueuePayload",
                "window.getLastQueueRows = getLastQueueRows",
                "Route reasons:",
                "Invalid snapshot rows:",
                "Operator note: this is a read-only snapshot breakdown.",
                "No runnable queue rows.",
                "Source candidates:",
                "Completed/blocked exclusions:",
                "Visible blocked rows:",
                "Visible blocked reason codes:",
                "Visible blocked reasons:",
                "Runtime checks deferred:",
                "Runtime deferred checks:",
                "Runtime outcome matches:",
                "Rows with exact source-path runtime history:",
                "Stale history is shown only as context.",
                "Produced:",
                "Snapshot file age",
                "Produced age",
                "Snapshot stale",
                "function queueSnapshotIsStale",
                "Source roots:",
            ),
        )

    def test_queue_launch_scope_and_backend_preflight_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.queue_view_js,
            (
                "function renderQueueBackendLaunchScopePreview",
                "function queueBackendLaunchScopeRows",
                "function renderQueueDecisionHeader",
                "function renderQueueAttentionSummary",
                "Queue decision header:",
                "Attention required:",
                "Backend launch scope boundary:",
                "Queue filters, row selection, and rendered table caps are not submitted as processing scope.",
                "Backend launch scope is owned by Launch; Queue filters, selected rows, and rendered row caps are not submitted as processing scope.",
                "Selecting a row cannot make Launch process only that row.",
                "function renderQueueLaunchDecisionChecklist",
                "function queueLaunchDecisionRows",
                "function queueLaunchDecisionStatusState",
                "function launchViewApi",
                "function queueCurrentFilterScope",
                "function queueFilterScopeDetailLines",
                "Display filter / backend launch scope",
                "Backend launch scope: unchanged.",
                "Launch routes use backend queue/schedule/settings checks, not the visible WebView table subset.",
                "renderQueueLaunchDecisionChecklist(state.payload, state.rows",
                "function queueLaunchBackendPreflightPayload",
                "function queueLaunchBackendPreflightCheckpoint",
                'launchView.launchBackendPreflightPayloadForTarget("pipeline")',
                "launchView.getLastLaunchBackendPreflightRefreshInfo()",
                "Last backend preflight refresh:",
                "Backend launch preflight",
                "Pipeline backend launch preflight has not been loaded",
                "function isQueueLaunchCommand",
                "Queue-to-Launch handoff:",
                "Daily-use handoff: Queue evidence decides whether it is sensible to open Launch",
                "Scope boundary: Queue filters, selected rows, review boards",
                "use backend launch preflight, queue payload, display filter scope, freshness, blocked rows, runtime context, completed exclusions, selected-row proof, command history, and Launch readiness as advisory context",
                "Mutation guardrail: this handoff cannot launch, reorder, drop, rewrite queue snapshots, delete files, clear completed state, override schedule, or bypass backend validation.",
            ),
        )
        _assert_contains_all(
            self,
            bundle.app_refresh_js,
            (
                "function renderQueueRefreshInProgress()",
                'activity: "Scanning"',
                "setQueueRefreshButtonBusy(true)",
                "setQueueRefreshButtonBusy(queueScanRunning)",
            ),
        )

    def test_queue_review_filter_and_diagnostics_contracts_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.queue_view_js,
            (
                "function renderQueueReviewBoard",
                "function queueReviewBoardLines",
                "Operator review board: Queue",
                "function queueValidationChecklistLines",
                "function queueRowReviewChecklistLines",
                "function queueRowIssueDigestLines",
                "function queueRowCombinedReviewPlanLines",
                "function queueSelectedQuickSignalLines",
                "function queueSelectedOpenTargetLines",
                "Open boundary: Queue buttons send only row_key, row_scope, and target.",
                "available_open_target_counts",
                "function queueFilterVisibilityLines",
                "function queueFocusedInvestigationLabels",
                "function resetQueueFilters",
                "Queue display filters cleared.",
                "function queueInvestigationSignalLines",
                "function queueRowTrustSummaryLines",
                "function queueDiagnosticsActionsForRow",
                "function renderQueueDiagnosticsLinks",
                "function requestQueueDiagnosticsAction",
                "Real-media validation checklist:",
                "Mutation guardrail: read-only evidence; backend routes own queue and launch changes.",
                "Selected row review checklist:",
                "Selected row quick signal:",
                "Current filter visibility:",
                "Hidden by current filters:",
                "Selected queue issue digest:",
                "Combined row review plan:",
                "Queue Snapshot",
                "Launch readiness",
                "Guardrail: this combined plan is read-only and cannot change queue order",
                "Investigation view matches:",
                "investigation views are display filters only and do not alter backend launch scope",
                "function queueRealMediaTraceLines",
                "Real-media sample trace: Queue",
                "What remains unproven: FFmpeg execution",
                "review-before-launch",
                "diagnosticsBridgeRowTrustLines",
                "appendDiagnosticsBridgeGroupedButtons(container, actions",
                "Safe next action: use Queue Diagnostics Cross-Links before launch",
                "Safe next action: row is coherent in the current snapshot",
                "selected-row detail is read-only",
                "Diagnostics actions below use backend allowlists. The Queue page never sends arbitrary filesystem paths.",
                "queue-diagnostics-actions",
                "requestDiagnosticsOpen(target)",
                "requestDiagnosticsTail(target)",
            ),
        )

    def test_queue_open_scan_and_operator_state_are_backend_owned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.queue_view_js,
            (
                "[data-queue-refresh-button]",
                "/api/queue/scan",
                "function requestQueueScan()",
                "window.mediaPipelineAppRefresh?.renderQueueRefreshInProgress?.();",
                "function requestQueueOpen",
                "function renderQueueOpenHistory",
                "function isQueueOpenCommand",
                "/api/queue/open",
                "Another queue open command is already in progress.",
                "Backend queue snapshot row keys and target allowlists remain the source of truth.",
                "Mutation guardrail: backend queue mutation and processing start remain backend-owned commands",
                "Select a queue row to see launch readiness",
                "Runtime error code:",
                "Runtime match:",
                "Operator status:",
                "Blocked reason code:",
                "Runtime note:",
                "Operator statuses:",
                "Operator severities:",
                "Backend trust states:",
                "Backend trust state:",
                "Backend proof summary:",
                "operator_trust_state",
                "safe_next_action",
                "unsafe_if_ignored",
                "recommended_diagnostics_targets",
                "Review flags:",
                "Route decision:",
                "Route evidence:",
                "route_evidence_lines",
                "operator_guidance",
            ),
        )


if __name__ == "__main__":
    unittest.main()
