from __future__ import annotations

import unittest

from tests.python.desktop.application_facade_test_support import (
    assert_namespace_export as _assert_namespace_export,
    served_webview_static_contract_bundle,
)


def _assert_contains_all(testcase: unittest.TestCase, text: str, snippets: tuple[str, ...]) -> None:
    for snippet in snippets:
        with testcase.subTest(snippet=snippet):
            testcase.assertIn(snippet, text)


def _assert_not_contains_any(testcase: unittest.TestCase, text: str, snippets: tuple[str, ...]) -> None:
    for snippet in snippets:
        with testcase.subTest(snippet=snippet):
            testcase.assertNotIn(snippet, text)


def _assert_launch_exports(testcase: unittest.TestCase, source: str, symbols: tuple[str, ...]) -> None:
    for symbol in symbols:
        with testcase.subTest(symbol=symbol):
            _assert_namespace_export(testcase, source, "mediaPipelineLaunchView", symbol)


class ApplicationFacadeWebStaticLaunchTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.bundle = served_webview_static_contract_bundle()

    def test_launch_assets_dom_and_tabs_are_static_pinned(self) -> None:
        html = self.bundle.html

        _assert_contains_all(
            self,
            html,
            (
                "/assets/launchReadinessView.js",
                "/assets/launchHistoryView.js",
                "/assets/launch/risk/settingsAccess.js",
                "/assets/launch/risk/mediaPolicyValues.js",
                "/assets/launch/risk/riskRows.js",
                "/assets/launch/risk/policyPatch.js",
                "/assets/launch/risk/policyBoundary.js",
                "/assets/launchView.risk.js",
                "/assets/launchView.scope.js",
                "/assets/launchView.realmedia.js",
                "/assets/launchView.preflight.js",
                "/assets/launch/controllerState.js",
                "/assets/launch/statusRender.js",
                "/assets/launch/startRequest.js",
                "/assets/launch/scopeControls.js",
                "/assets/launch/commandButtons.js",
                "/assets/launchView.js",
                'id="launch-settings-intent-status"',
                'id="launch-settings-intent-summary"',
                'id="launch-settings-intent-rows"',
                'id="launch-settings-intent-detail"',
                'id="launch-scope-reconciliation-status"',
                'id="launch-scope-reconciliation-summary"',
                'id="launch-scope-reconciliation-rows"',
                'id="launch-scope-reconciliation-detail"',
                'id="launch-start-decision-status"',
                'id="launch-start-decision-summary"',
                'id="launch-start-decision-rows"',
                'id="launch-start-decision-detail"',
                'id="launch-real-media-proof-status"',
                'id="launch-real-media-proof-summary"',
                'id="launch-real-media-proof-rows"',
                'id="launch-real-media-proof-detail"',
                'id="launch-sample-execution-status"',
                'id="launch-sample-execution-summary"',
                'id="launch-sample-execution-rows"',
                'id="launch-sample-execution-detail"',
                'id="launch-pilot-readiness-status"',
                'id="launch-pilot-readiness-summary"',
                'id="launch-pilot-readiness-rows"',
                'id="launch-pilot-readiness-detail"',
                'id="launch-backend-preflight-status"',
                'id="launch-backend-preflight-summary"',
                'id="launch-backend-preflight-rows"',
                'id="launch-backend-preflight-detail"',
                'data-page-panel="launch"',
                'data-launch-tab="pipeline"',
                'data-launch-tab="rerun"',
                'data-launch-tab="history"',
                'data-launch-tab-panel="pipeline"',
                'data-launch-tab-panel="rerun"',
                'data-launch-tab-panel="history"',
                "launch-readiness-status",
                "launch-readiness",
                "launch-timing-status",
                "launch-timing",
                "launch-settings-trust-status",
                "launch-settings-trust-summary",
                "launch-settings-risk-status",
                "launch-settings-risk-summary",
                "launch-settings-risk-rows",
                "launch-settings-risk-detail",
                "pipeline-start-mode",
                "pipeline-start-single-file",
                "pipeline-single-file-browse-button",
                "pipeline-single-file-clear-button",
                "pipeline-single-file-browse-status",
                "Advanced Controller",
                "pipeline-start-schedule-override",
                "Start Evidence",
                "pipeline-launch-preflight",
                "pipeline-start-button",
                "rerun-start-csv-path",
                "rerun-launch-preflight",
                'id="rerun-open-audit-tool-button"',
                'data-cross-page-target="reports" data-cross-page-reports-tab="audit"',
                "rerun-start-button",
                "launch-history-status",
                "launch-history",
                "launch-command-review-status",
                "launch-command-review-summary",
                "launch-command-review-rows",
                "launch-command-review-legend",
                "launch-command-review-detail",
                "launch-command-diagnostics-guidance",
                "launch-command-diagnostics-actions",
                "Checklist Correlation",
                "launch-policy-boundary-summary",
                "launch-policy-boundary-detail",
                "launch-backend-preflight-refresh-button",
                "Refresh Backend Preflight",
                "rerun-plan-only-button",
                "Plan CSV Rerun",
                "rerun-dry-run-button",
                "Preview CSV Rerun",
            ),
        )
        self.assertNotIn('data-launch-tab="audit"', html)
        self.assertNotIn('data-launch-tab-panel="audit"', html)
        for absent in (
            "Selected Mode",
            'id="audit-start-library-root"',
            'id="audit-launch-preflight"',
            'id="audit-launch-progress-status"',
            'id="audit-launch-log-rows"',
            'id="audit-score-policy-save-button"',
            "High issue: <code>foreign-audio-no-text-subtitles</code>",
            'id="audit-ignore-selected-button"',
            'id="audit-export-rerun-csv-button"',
            'id="audit-start-button"',
        ):
            self.assertNotIn(absent, html)
        launch_tab_order = [
            'data-launch-tab="pipeline"',
            'data-launch-tab="rerun"',
            'data-launch-tab="history"',
        ]
        prior_index = -1
        for launch_tab in launch_tab_order:
            current_index = html.index(launch_tab)
            self.assertGreater(current_index, prior_index)
            prior_index = current_index
        self.assertEqual(html.count('id="pipeline-start-button"'), 1)
        self.assertLess(html.index('id="pipeline-start-show-console"'), html.index('id="pipeline-start-button"'))
        self.assertLess(html.index('id="pipeline-start-button"'), html.index('id="launch-start-decision-status"'))

    def test_launch_readiness_and_history_contracts_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.launch_readiness_view_js,
            (
                "window.mediaPipelineLaunchReadinessView",
                "function launchReadinessSettingsStatus",
                "function launchReadinessStatus",
                "function launchReadinessLines",
                "function launchReadinessScheduleWatcherSummary",
                "function launchReadinessBackendReadiness",
                "function launchReadinessBackendLines",
                "Launch readiness (backend-authored):",
                "Evidence authority: frontend advisory only until backend preflight payload is loaded.",
                "function launchTimingTrustLines",
                "function renderLaunchTimingTrust",
                "function getLastLaunchReadinessPayload",
                "window.mediaPipelineLaunchView?.renderLaunchSettingsIntentChecklist?.(undefined, lastLaunchReadinessPayload)",
                "Launch timing trust:",
                "Mutation guardrail: this Launch timing panel is read-only",
                "function renderLaunchReadiness",
                "Saved settings:",
                "Settings issue",
                "Saved settings need review",
                "Active work is reported",
                "Backend launch locking and gating remain the source of truth.",
                "Run Once and Continuous are schedule-blocked",
                "Backend continuous watcher:",
                "Continuous schedule-stop watcher",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.launch_readiness_view_js,
            (
                "window.launchReadinessStatus =",
                "window.launchReadinessStatusState =",
                "window.launchReadinessLines =",
                "window.launchReadinessRecoveryActions =",
                "window.renderLaunchReadinessRecoveryActions =",
                "window.launchTimingStatus =",
                "window.launchTimingTrustLines =",
                "window.renderLaunchTimingTrust =",
                "window.renderLaunchReadiness =",
                "window.getLastLaunchReadinessPayload =",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_history_view_js,
            (
                "window.mediaPipelineLaunchHistoryView",
                "function isLaunchCommand",
                "function renderLaunchCommandHistory",
                "function launchHistoryLine",
                "function launchHistoryTarget",
                "function launchHistoryRequest",
                "function launchCommandCorrelationRows",
                "function launchCommandCorrelationStatus",
                "function launchCommandCorrelationSummary",
                "function launchCommandDiagnosticsActions",
                "function launchCommandDiagnosticsGuidanceLines",
                "function renderLaunchCommandDiagnosticsActions",
                "function launchCommandReviewRows",
                "function launchCommandReviewDetailLines",
                "function renderLaunchCommandReview",
                "commandHistoryView.commandHistoryRowKey(entry)",
                "commandHistoryView.selectCommandEntry(item.entry)",
                "commandHistoryView.commandHistoryRefreshTarget(entry)",
                "commandHistoryView.commandHistoryDiagnosticsActions(entry)",
                "commandHistoryView.commandHistorySuggestedAction(entry)",
                "Launch command review:",
                "Checklist correlation:",
                "Correlated checklist/preflight context:",
                "Predicted by checklist",
                "Not predicted by cached checks",
                "Launch diagnostics retry guidance:",
                "Retry rule: do not press Start again until command detail, correlated checklist context, and diagnostics targets agree on the cause.",
                "these actions use backend allowlisted diagnostics targets only",
                "launchCommandDiagnosticsAdd(actions, \"open\", \"queue_snapshot\"",
                "launchCommandDiagnosticsAdd(actions, \"open\", \"active_jobs\"",
                "launchCommandDiagnosticsAdd(actions, \"tail\", \"latest_failure_report\"",
                "requestCommandDiagnosticsAction(action)",
                "function launchViewApi",
                "launchView.launchBackendPreflightPayloadForTarget(target)",
                "queueLaunchDecisionRows(undefined, undefined, history)",
                "launchView.launchSettingsIntentRows(request)",
                "selecting a launch command review row selects that command",
                "launch, CSV rerun, drain, and control commands remain backend-owned",
                "Pending publish drain history remains on the Pending Publish page.",
                "commandHistoryCompactEvidenceLine(entry",
                "Backend launch locking and validation remain the source of truth.",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.launch_history_view_js,
            (
                "typeof commandHistoryRowKey === \"function\"",
                "typeof selectCommandEntry === \"function\"",
                "window.launchCommandCorrelationRows =",
                "window.launchCommandCorrelationStatus =",
                "window.launchCommandDiagnosticsActions =",
                "window.launchCommandReviewRows =",
                "window.launchCommandReviewStatus =",
                "window.launchCommandReviewSummaryLines =",
                "window.renderLaunchCommandHistory =",
                "window.isLaunchCommand =",
                "window.launchHistoryLine =",
            ),
        )

    def test_launch_view_control_and_start_requests_are_backend_owned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.launch_view_js,
            (
                "window.mediaPipelineLaunchView",
                "function requestPipelineControl",
                "function confirmControlAction",
                "let controlCommandInFlight = false",
                "function setControlCommandBusy",
                "function rejectControlCommandWhileBusy",
                "Another pipeline control command is already in progress.",
                "mediaPipelineLaunchReadinessView",
                "mediaPipelineLaunchHistoryView",
                "const launchReadinessStatus = launchReadinessView.launchReadinessStatus || window.launchReadinessStatus",
                "const launchTimingStatus = launchReadinessView.launchTimingStatus || window.launchTimingStatus",
                "const getLastLaunchReadinessPayload = launchReadinessView.getLastLaunchReadinessPayload || window.getLastLaunchReadinessPayload",
                "const isLaunchCommand = launchHistoryView.isLaunchCommand || function () { return false; }",
                "const renderLaunchCommandHistory = launchHistoryView.renderLaunchCommandHistory || function () {}",
                "const launchCommandCorrelationRows = launchHistoryView.launchCommandCorrelationRows",
                "launchCommandReviewRows: typeof launchCommandReviewRows === \"function\" ? launchCommandReviewRows : null",
                "function createLaunchControllerStateModule",
                "window.__launchControllerStateModule",
                "const launchControllerStateModule = window.__launchControllerStateModule || {}",
                "delete window.__launchControllerStateModule",
                "function createLaunchStatusRenderModule",
                "window.__launchStatusRenderModule",
                "const launchStatusRenderModule = window.__launchStatusRenderModule || {}",
                "delete window.__launchStatusRenderModule",
                "function createLaunchStartRequestModule",
                "window.__launchStartRequestModule",
                "const launchStartRequestModule = window.__launchStartRequestModule || {}",
                "delete window.__launchStartRequestModule",
                "function createLaunchScopeControlsModule",
                "window.__launchScopeControlsModule",
                "const launchScopeControlsModule = window.__launchScopeControlsModule || {}",
                "delete window.__launchScopeControlsModule",
                "function createLaunchCommandButtonsModule",
                "window.__launchCommandButtonsModule",
                "const launchCommandButtonsModule = window.__launchCommandButtonsModule || {}",
                "delete window.__launchCommandButtonsModule",
                "const launchCommandButtonIds",
                "function setLaunchCommandBusy",
                "function rejectLaunchCommandWhileBusy",
                "Another launch command is already in progress.",
                "function collectPipelineStartRequest",
                'byId("pipeline-start-single-file")',
                "request.single_file = singleFile",
                "function browsePipelineSingleFile",
                'apiPost("/api/pipeline/browse-file", request)',
                "function startPipelineFromForm",
                "function launchCommandStatusLabel",
                "function launchCommandResultCorrelationLines",
                "Command evidence snapshot:",
                "Diagnostics retry guidance:",
                "launchCommandDiagnosticsActions(entry)",
                "Evidence is explanatory only; backend start routes remain authoritative at submission time.",
                "function formatLaunchCommandDetail",
                "function renderLaunchCommandResult",
                "function initLaunchViewEvents",
                "function initLaunchTabNav",
                "function activateLaunchTab",
                "mediapipeline-launch-tab",
                "commandResultDisplayMessage(payload)",
                "Backend data:",
                "Submitted request:",
                "pending-drain-detail",
                "/api/pipeline/start",
            ),
        )
        _assert_launch_exports(
            self,
            bundle.launch_view_js,
            (
                "requestPipelineControl",
                "isPipelineControlCommand",
                "pipelineControlHistoryLine",
                "renderPipelineControlHistory",
                "syncPipelineModeControls",
                "selectPipelineModePreset",
                "browsePipelineSingleFile",
                "clearPipelineSingleFile",
                "startPipelineFromForm",
                "initLaunchViewEvents",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.launch_view_js,
            (
                "window.requestPipelineControl =",
                "window.isPipelineControlCommand =",
                "window.pipelineControlHistoryLine =",
                "window.renderPipelineControlHistory =",
                "window.launchReadinessStatus =",
                "window.launchReadinessLines =",
                "window.renderLaunchReadiness =",
                "window.isLaunchCommand =",
                "window.renderLaunchCommandHistory =",
                "window.launchHistoryLine =",
                "window.syncPipelineModeControls =",
                "window.selectPipelineModePreset =",
                "window.browsePipelineSingleFile =",
                "window.clearPipelineSingleFile =",
                "window.startPipelineFromForm =",
                "window.initLaunchViewEvents =",
                "function collectAuditStartRequest",
                "function startAuditFromForm",
                "function renderLaunchAuditControls",
                "/api/audit/",
                "renderLaunchAuditIssueRows",
                "function renderLaunchAuditLog",
                "renderLaunchAuditControls",
                "renderLaunchAuditLog",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_preflight_js,
            (
                "function renderPipelineControlHistory",
                "function isPipelineControlCommand",
                "Backend control-flag writes and launch locks remain the source of truth.",
                "Single-file launch: WebView submits the path only",
                "Backend validation and launch locking remain the source of truth.",
                "operator_readiness",
                'Plan only: ${request.plan_only ? "yes - no manifest or media writes" : "no"}',
                'Dry run: ${request.dry_run ? "yes - evidence-writing preview" : request.plan_only ? "no - plan-only request" : "no - live rerun start"}',
                "Safety policy: plan-only stops before writing manifests, temp config, staging files, parked outputs, or source media.",
                "Safety policy: dry-run preview should produce backend evidence without staging, moving, publishing, or touching media.",
                "Safety policy: live rerun copies to scratch, keeps originals, and parks returned outputs.",
            ),
        )

    def test_launch_risk_policy_and_settings_intent_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.launch_view_risk_js,
            (
                "function createLaunchRiskModule",
                "window.__launchViewRiskModule",
                "function launchSettingsTrustStatus",
                "function launchSettingsDecision",
                "function launchSettingsDecisionLines",
                "function launchSettingsRiskLines",
                "function launchRealMediaReadinessLines",
                "function launchSettingsRiskRows",
                "function launchSettingsRiskDetailLines",
                "function renderLaunchSettingsRiskHandoff",
                "Launch Risk Handoff detail:",
                "Daily-driver rule: resolve blocked rows",
                "Proof chain:",
                "function launchPolicyBoundaryRows",
                "function renderLaunchPolicyBoundary",
                "Launch active media-policy boundary:",
                "Active saved subtitle policy",
                "Staged subtitle candidate",
                "Active saved audio policy",
                "Staged audio candidate",
                "Active saved publish/source safety",
                "Staged publish/source candidate",
                "Launch uses the active saved subtitle, audio, and pending-publish/source-safety policy",
                "function launchSettingsIntentRows",
                "function renderLaunchSettingsIntentChecklist",
                "Saved settings evidence:",
                "Launch settings evidence snapshot:",
                "Launch settings risk handoff:",
                "Real-media validation boundary",
                "Preview/build/release checks prove shell/package readiness only",
                "Real-media proof still requires a completed sample run",
                "Saved settings vs launch intent checklist:",
                "Launch uses saved backend settings and selected form intent only",
                "unsaved Settings changes do not count until Save Settings succeeds",
                "Queue display scope",
                "Do not treat the visible Queue table as launch scope",
                "Launch start requests do not include Queue filter text",
                "Backend Launch remains authoritative for queue scope",
                "queueCurrentFilterScope(queueRows)",
                "Mutation guardrail: this checklist is read-only and cannot launch, save settings, drain, rename, repair, delete, publish, or touch media files.",
                "This panel translates saved settings posture into launch-specific operator checks.",
                "Evidence guidance:",
                "Evidence owner: Settings page edits/save; Launch page displays saved posture only.",
                "Backend risk summary:",
                "Deferred publish:",
                "PATH tool fallback:",
                "H.264 copy / remux precision",
                "Container / original subtitle preservation",
                "Plex-compatible H.264 sources should remain copy/remux candidates",
                "MP4 cannot carry every original subtitle format",
                "normal growth=${maxGrowth}%",
                "Do not launch media work with drop-without-convert subtitle contradictions.",
                "No-audio output is unsafe for normal Plex publishing",
                "Backend launch validation, process locks, and Settings Save remain the source of truth.",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_js,
            (
                "const launchRiskModule = window.__launchViewRiskModule || {}",
                "delete window.__launchViewRiskModule",
                "launchRiskModule.createLaunchRiskModule",
            ),
        )
        _assert_launch_exports(
            self,
            bundle.launch_view_js,
            (
                "launchSettingsWorkspace",
                "launchSettingsTrustStatus",
                "launchSettingsDecision",
                "launchSettingsDecisionLines",
                "launchSettingsRiskLines",
                "launchRealMediaReadinessLines",
                "launchSettingsRiskRows",
                "launchSettingsRiskStatus",
                "launchSettingsRiskSummaryLines",
                "launchSettingsRiskDetailLines",
                "renderLaunchSettingsRiskHandoff",
                "launchPolicyBoundaryRows",
                "launchPolicyBoundaryStatus",
                "launchPolicyBoundarySummaryLines",
                "launchPolicyBoundaryDetailLines",
                "renderLaunchPolicyBoundary",
                "launchSettingsIntentRows",
                "launchSettingsIntentStatus",
                "renderLaunchSettingsIntentChecklist",
                "launchSettingsIntentSummaryLines",
                "launchSettingsIntentDetailLines",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.launch_view_js,
            (
                "window.launchSettingsWorkspace =",
                "window.launchSettingsTrustStatus =",
                "window.launchSettingsDecision =",
                "window.launchSettingsDecisionLines =",
                "window.launchSettingsRiskLines =",
                "window.launchRealMediaReadinessLines =",
                "window.launchSettingsRiskRows =",
                "window.launchSettingsRiskStatus =",
                "window.launchSettingsRiskSummaryLines =",
                "window.renderLaunchSettingsRiskHandoff =",
                "window.launchPolicyBoundaryStatus =",
                "window.launchPolicyBoundarySummaryLines =",
                "window.launchPolicyBoundaryDetailLines =",
                "window.renderLaunchPolicyBoundary =",
                "window.launchSettingsIntentRows =",
                "window.launchSettingsIntentStatus =",
                "window.renderLaunchSettingsIntentChecklist =",
                "window.launchSettingsIntentSummaryLines =",
                "window.launchSettingsIntentDetailLines =",
            ),
        )
        self.assertIn("renderLaunchPolicyBoundary()", bundle.launch_view_preflight_js)
        self.assertIn("renderLaunchSettingsIntentChecklist(pipelineRequest)", bundle.launch_view_preflight_js)
        self.assertIn("renderLaunchSettingsRiskHandoff(pipelineRequest)", bundle.launch_view_preflight_js)
        self.assertIn("launchView.renderLaunchSettingsIntentChecklist?.()", bundle.command_history_js)

    def test_launch_scope_realmedia_and_preflight_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.launch_view_scope_js,
            (
                "function createLaunchScopeModule",
                "window.__launchViewScopeModule",
                "function launchScopeReconciliationRows",
                "function renderLaunchScopeReconciliation",
                "Launch scope reconciliation:",
                "visible Queue table, selected Launch mode, cached backend preflight",
                "Mutation guardrail: this reconciliation is read-only",
                "function launchStartDecisionRows",
                "function renderLaunchStartDecisionSummary",
                "Launch start decision summary:",
                "treat Start as sensible only when Launch readiness, backend preflight, Queue, Settings",
                "Mutation guardrail: this summary is read-only",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_realmedia_js,
            (
                "function createLaunchRealMediaModule",
                "window.__launchViewRealMediaModule",
                "function launchPolicyAlignmentQueueIntentEvidence",
                "Saved policy vs Queue route:",
                "Saved policy vs Queue route evidence packet:",
                "Advisory boundary: queue-route matching uses loaded route/status text only.",
                "function launchRealMediaProofRows",
                "function renderLaunchRealMediaProofHandoff",
                "Launch real-media sample proof handoff:",
                "Home Real-Media Validation Worksheet",
                "daily-driver trust still requires post-run output",
                "function launchSampleExecutionRows",
                "function renderLaunchSampleExecutionChecklist",
                "Launch sample execution checklist:",
                "Home's backend-authored operator sample execution checklist",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_preflight_js,
            (
                "function createLaunchPreflightModule",
                "window.__launchViewPreflightModule",
                "function launchPilotRunReadinessRows",
                "function renderLaunchPilotRunReadiness",
                "Launch pilot run readiness:",
                "selected Queue sample, saved Settings policy, backend preflight, pilot category, pending-publish posture, and post-run proof plan",
                "function launchBackendPreflightRows",
                "function getLastLaunchBackendPreflightPayloads",
                "function launchBackendPreflightPayloadForTarget",
                "function getLastLaunchBackendPreflightRefreshInfo",
                "function refreshLaunchBackendPreflight",
                "Last refresh:",
                "fetch_failure_count",
                "renderQueueLaunchDecisionChecklist()",
                "/api/launch/preflight",
                "GET /api/launch/preflight",
                "This read route mirrors backend launch guards without journaling commands or mutating runtime state",
                "Mutation guardrail: this panel cannot launch, reserve locks, clear flags, save settings, drain, rename, repair, delete, publish, or touch media files.",
                "function pipelineLaunchPreflightLines",
                "function rerunLaunchPreflightLines",
                "const launchReadinessView = window.mediaPipelineLaunchReadinessView || {}",
                "launchReadinessView.getLastLaunchReadinessPayload()",
                "launchReadinessView.renderLaunchReadiness({",
                "renderLaunchTimingTrust()",
                "renderScheduleTimingTrust()",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.launch_view_preflight_js,
            (
                "function renderLaunchAuditProgress",
                "audit-launch-progress-bars",
                "function auditLaunchPreflightLines",
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_js,
            (
                "const launchScopeModule = window.__launchViewScopeModule || {}",
                "delete window.__launchViewScopeModule",
                "launchScopeModule.createLaunchScopeModule",
                "const launchRealMediaModule = window.__launchViewRealMediaModule || {}",
                "delete window.__launchViewRealMediaModule",
                "launchRealMediaModule.createLaunchRealMediaModule",
                "const launchPreflightModule = window.__launchViewPreflightModule || {}",
                "delete window.__launchViewPreflightModule",
                "launchPreflightModule.createLaunchPreflightModule",
                "refreshLaunchBackendPreflight()",
                "const scheduleView = window.mediaPipelineScheduleView || {}",
                "renderScheduleTimingTrust: typeof renderScheduleTimingTrust === \"function\" ? renderScheduleTimingTrust : null",
            ),
        )
        _assert_launch_exports(
            self,
            bundle.launch_view_js,
            (
                "launchScopeReconciliationRows",
                "launchScopeReconciliationStatus",
                "launchScopeReconciliationSummaryLines",
                "launchScopeReconciliationDetailLines",
                "launchStartDecisionRows",
                "launchStartDecisionStatus",
                "launchStartDecisionSummaryLines",
                "launchStartDecisionDetailLines",
                "renderLaunchStartDecisionSummary",
                "launchWorksheetRunRows",
                "launchWorksheetRunsMatchingSample",
                "launchPolicyAlignmentPayload",
                "launchPolicyAlignmentRows",
                "launchWorksheetEvidence",
                "launchQueueIntentCategoryMatch",
                "launchPolicyAlignmentQueueIntentEvidence",
                "launchRealMediaProofRows",
                "launchRealMediaProofStatus",
                "launchRealMediaProofSummaryLines",
                "launchRealMediaProofDetailLines",
                "renderLaunchRealMediaProofHandoff",
                "launchSampleSetCoverageLine",
                "launchSampleValidationRecordEvidence",
                "launchSampleValidationRecordRows",
                "launchSampleValidationRecordsMatchingSample",
                "launchSampleExecutionRows",
                "launchSampleExecutionStatus",
                "launchSampleExecutionSummaryLines",
                "launchSampleExecutionDetailLines",
                "renderLaunchSampleExecutionChecklist",
                "launchPilotRunReadinessRows",
                "launchPilotRunReadinessStatus",
                "launchPilotRunReadinessSummaryLines",
                "launchPilotRunReadinessDetailLines",
                "renderLaunchPilotRunReadiness",
                "launchBackendPreflightRows",
                "getLastLaunchBackendPreflightPayloads",
                "launchBackendPreflightPayloadForTarget",
                "getLastLaunchBackendPreflightRefreshInfo",
                "launchBackendPreflightSummaryLines",
                "launchBackendPreflightDetailLines",
                "renderLaunchBackendPreflight",
                "refreshLaunchBackendPreflight",
                "pipelineLaunchPreflightLines",
                "rerunLaunchPreflightLines",
            ),
        )

    def test_launch_rerun_and_pending_drain_commands_are_guarded(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.launch_view_js,
            (
                "function collectRerunStartRequest",
                "function startRerunFromForm",
                "/api/rerun/start",
                'stage_mode: "copy"',
                'original_mode: "keep"',
                'return_mode: "park"',
                'mode: "drain_pending_pushes"',
                'command: "pending_publish.drain"',
                'typeof pendingDrainGuardState === "function" ? pendingDrainGuardState() : null',
                "frontend_guard: true",
                "guard?.confirm_message",
            ),
        )
        _assert_launch_exports(
            self,
            bundle.launch_view_js,
            (
                "collectRerunStartRequest",
                "startStateJournalArchive",
                "startRerunFromForm",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.launch_view_js,
            (
                "window.collectRerunStartRequest =",
                "window.startStateJournalArchive =",
                "window.startRerunFromForm =",
            ),
        )
        _assert_contains_all(
            self,
            bundle.js,
            (
                'launchView.startRerunFromForm?.({ plan_only: true })',
                'launchView.startRerunFromForm?.({ dry_run: true })',
                'launchView.startRerunFromForm?.({ dry_run: false })',
                "function renderLaunchReadinessPanel",
                "window.mediaPipelineLaunchReadinessView?.renderLaunchReadiness?.(payload)",
                "renderLaunchReadinessPanel({",
                "settings: getLastSettings()",
                "settings: values.settings || getLastSettings()",
                "startupProgressLines",
                "bootstrap.startupProgress",
                'refreshGet("/api/health", refreshOptions)',
                "values.health?.startup_progress",
            ),
        )


if __name__ == "__main__":
    unittest.main()
