from __future__ import annotations

import unittest

from tests.python.desktop.application_facade_test_support import (
    assert_namespace_export as _assert_namespace_export,
    served_webview_static_contract_bundle,
)

AssertionRow = tuple[str, ...]


def _run_static_assertions(testcase: unittest.TestCase, bundle: object, rows: tuple[AssertionRow, ...]) -> None:
    for row in rows:
        kind, target, *payload = row
        with testcase.subTest(kind=kind, target=target, payload=payload):
            text = getattr(bundle, target)
            if kind == "in":
                testcase.assertIn(payload[0], text)
            elif kind == "not_in":
                testcase.assertNotIn(payload[0], text)
            elif kind == "namespace":
                _assert_namespace_export(testcase, text, payload[0], payload[1])
            else:  # pragma: no cover - protects future test data edits.
                raise AssertionError(f"unknown assertion kind: {kind}")

OPERATIONS_DOM_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'html', '/assets/networkView.js'),
 ('in', 'html', '/assets/diagnosticsTailView.js'),
 ('in', 'html', '/assets/diagnosticsStateSummaryView.js'),
 ('in', 'html', '/assets/diagnosticsView.activejobs.js'),
 ('in', 'html', '/assets/diagnosticsView.log.js'),
 ('in', 'html', '/assets/diagnosticsView.investigation.js'),
 ('in', 'html', '/assets/diagnosticsView.js'),
 ('in', 'html', '/assets/reportsView.js'),
 ('in', 'html', 'id="report-audit-score-policy-status"'),
 ('in', 'html', 'id="report-audit-score-policy-save-button"'),
 ('in', 'html', 'id="report-audit-score-policy-reset-button"'),
 ('in', 'html', 'id="report-audit-ignore-selected-button"'),
 ('in', 'html', 'id="report-audit-export-rerun-csv-button"'),
 ('in', 'html', 'id="report-audit-export-detail"'),
 ('in', 'html', 'Advanced score controls'),
 ('in', 'html', 'Point issue'),
 ('in', 'html', 'High issue-code marker'),
 ('in', 'html', 'Medium issue-code marker'),
 ('not_in', 'html', 'High issue: <code>ffprobe-open-failed</code>'),
 ('not_in', 'html', 'data-audit-score-policy-mirror="high_issue"'),
 ('in', 'html', '/assets/scheduleView.js'),
 ('in', 'html', '/assets/maintenanceView.js'),
 ('in', 'html', '/assets/telemetryView.js'),
 ('in', 'html', '/assets/progressView.js'),
 ('in', 'html', '/assets/contractView.js'),
 ('in', 'html', '/assets/commandHistory/formatters.js'),
 ('in', 'html', '/assets/commandHistory/diagnostics.js'),
 ('in', 'html', 'api-contract'),
 ('in', 'html', 'api-contract-method'),
 ('in', 'html', 'api-contract-scope'),
 ('in', 'html', 'api-contract-filter'),
 ('in', 'html', 'api-contract-safety-status'),
 ('in', 'html', 'api-contract-safety-summary'),
 ('in', 'html', 'api-contract-safety-rows'),
 ('in', 'html', 'api-contract-safety-detail'),
 ('in', 'html', 'api-contract-rows'),
 ('in', 'html', 'api-contract-detail'),
 ('in', 'html', 'refresh-health'),
 ('in', 'html', 'close-readiness'),
 ('in', 'html', 'class="topbar-status"'),
 ('in', 'html', 'activity-primary'),
 ('in', 'html', 'activity-meta'),
 ('in', 'html', 'evidence-toggle'),
 ('in', 'html', 'home-readiness-status'),
 ('in', 'html', 'home-readiness-summary'),
 ('in', 'html', 'daily-driver-status'),
 ('in', 'html', 'daily-driver-summary'),
 ('in', 'html', 'daily-driver-rows'),
 ('in', 'html', 'daily-driver-legend'),
 ('in', 'html', 'home-next-queue-status'),
 ('in', 'html', 'home-next-queue-list'),
 ('in', 'html', 'Next 5 Videos'),
 ('in', 'html', 'home-settings-trust-status'),
 ('in', 'html', 'home-settings-trust-summary'),
 ('in', 'html', 'home-external-dependencies-status'),
 ('in', 'html', 'home-external-dependencies-summary'),
 ('in', 'html', 'home-active-work-status'),
 ('in', 'html', 'home-active-work-summary'),
 ('in', 'html', 'home-runtime-open-status'),
 ('in', 'html', 'Runtime Files'),
 ('in', 'html', 'The WebView never sends arbitrary filesystem paths.'),
 ('in', 'html', 'control-readiness-status'),
 ('in', 'html', 'control-readiness'),
 ('in', 'html', 'control-history'),
 ('in', 'html', 'progress-detail-rows'),
 ('in', 'html', 'progress-evidence-status'),
 ('in', 'html', 'progress-evidence-summary'),
 ('in', 'html', 'progress-evidence-rows'),
 ('in', 'html', 'progress-evidence-detail'),
 ('in', 'html', 'pipeline-event-rows'),
 ('in', 'html', 'gpu-rows'),
 ('in', 'html', 'data-page-panel="reports"'),
 ('not_in', 'html', 'data-reports-tab="overview"'),
 ('not_in', 'html', 'data-reports-tab-panel="overview"'),
 ('in', 'html', 'data-reports-tab="failures"'),
 ('in', 'html', 'data-reports-tab="audit"'),
 ('in', 'html', 'data-reports-tab="files"'),
 ('in', 'html', 'data-reports-tab-panel="failures"'),
 ('in', 'html', 'data-reports-tab-panel="audit"'),
 ('in', 'html', 'data-reports-tab-panel="files"'),
 ('in', 'html', 'report-triage-status'),
 ('in', 'html', 'report-triage'),
 ('in', 'html', 'report-investigation-status'),
 ('in', 'html', 'report-investigation-checklist'),
 ('not_in', 'html', 'Pre-Launch Context'),
 ('not_in', 'html', 'report-launch-handoff-status'),
 ('not_in', 'html', 'report-launch-handoff'),
 ('not_in', 'html', 'report-go-rerun-button'),
 ('not_in', 'html', 'report-go-audit-button'),
 ('not_in', 'html', 'report-go-diagnostics-button'),
 ('not_in', 'html', 'report-launch-handoff-action-status'),
 ('in', 'html', 'report-progress-status'),
 ('in', 'html', 'report-progress-bars'),
 ('in', 'html', 'report-progress-summary'),
 ('in', 'html', 'report-path-rows'),
 ('in', 'html', 'report-root-rows'),
 ('in', 'html', 'report-warning-status'),
 ('in', 'html', 'report-warning-rows'),
 ('in', 'html', 'failure-filter'),
 ('in', 'html', 'failure-source-markers'),
 ('in', 'html', 'failure-rows'),
 ('in', 'html', 'Suggested fix'),
 ('in', 'html', 'failure-summary'),
 ('in', 'html', 'failure-review-status'),
 ('in', 'html', 'failure-review-board'),
 ('in', 'html', 'failure-review-board-detail'),
 ('in', 'html', 'failure-evidence-links'),
 ('in', 'html', 'failure-detail'),
 ('in', 'html', 'failure-clear-status'),
 ('in', 'html', 'failure-clear-summary'),
 ('in', 'html', 'failure-resolution-summary-strip'),
 ('in', 'html', 'failure-resolution-groups'),
 ('in', 'html', 'failure-primary-action-button'),
 ('in', 'html', 'failure-clear-scope'),
 ('in', 'html', 'failure-clear-confirm-button'),
 ('in', 'html', 'failure-archive-confirm-button'),
 ('in', 'html', 'failure-artifact-select-all'),
 ('in', 'html', 'Clear errors'),
 ('in', 'html', 'Advanced evidence archive'),
 ('in', 'html', 'audit-preview-filter'),
 ('in', 'html', 'audit-preview-priority-only'),
 ('in', 'html', 'audit-preview-rows'),
 ('in', 'html', 'audit-preview-summary'),
 ('in', 'html', 'data-reports-tab-panel="audit" data-panel-type="evidence"'),
 ('in', 'html', 'audit-review-status'),
 ('in', 'html', 'audit-review-board'),
 ('in', 'html', 'audit-preview-detail'),
 ('in', 'html', 'data-page-panel="schedule"'),
 ('in', 'html', 'schedule-day-rows'),
 ('in', 'html', 'schedule-summary'),
 ('in', 'html', 'schedule-guidance-status'),
 ('in', 'html', 'schedule-guidance'),
 ('in', 'html', 'schedule-timing-status'),
 ('in', 'html', 'schedule-timing'),
 ('in', 'html', 'data-page-panel="network"'),
 ('in', 'html', 'network-role'),
 ('in', 'html', 'network-readiness-status'),
 ('in', 'html', 'network-readiness-summary'),
 ('in', 'html', 'data-network-role-panel="coordinator"'),
 ('in', 'html', 'data-network-role-panel="worker"'),
 ('in', 'html', 'network-coordinator-overview-status'),
 ('in', 'html', 'network-coordinator-overview-summary'),
 ('in', 'html', 'network-coordinator-active-rows'),
 ('in', 'html', 'network-coordinator-queue-rows'),
 ('in', 'html', 'network-worker-overview-status'),
 ('in', 'html', 'network-worker-overview-summary'),
 ('in', 'html', 'network-worker-claim-rows'),
 ('in', 'html', 'network-worker-remote-queue-summary'),
 ('in', 'html', 'network-lifecycle-status'),
 ('in', 'html', 'network-lifecycle-summary'),
 ('in', 'html', 'network-lifecycle-rows'),
 ('in', 'html', 'network-lifecycle-legend'),
 ('in', 'html', 'network-lifecycle-detail'),
 ('in', 'html', 'network-evidence-status'),
 ('in', 'html', 'network-evidence-summary'),
 ('in', 'html', 'network-evidence-rows'),
 ('in', 'html', 'network-evidence-legend'),
 ('in', 'html', 'network-evidence-detail'),
 ('in', 'html', 'network-state-files-status'),
 ('in', 'html', 'network-state-files-summary'),
 ('in', 'html', 'network-state-files-rows'),
 ('in', 'html', 'network-state-files-legend'),
 ('in', 'html', 'network-state-files-detail'),
 ('in', 'html', 'network-open-history-status'),
 ('in', 'html', 'network-open-history'),
 ('in', 'html', 'network-worker-status'),
 ('in', 'html', 'network-worker-summary'),
 ('in', 'html', 'network-worker-progress-status'),
 ('in', 'html', 'network-worker-progress-bars'),
 ('in', 'html', 'network-worker-progress-summary'),
 ('in', 'html', 'network-worker-rows'),
 ('in', 'html', 'network-worker-detail'),
 ('in', 'html', 'network-worker-status-filter'),
 ('in', 'html', 'network-worker-filter'),
 ('in', 'html', 'Distributed Mode Settings'),
 ('in', 'html', 'settings-network-role'),
 ('in', 'html', 'settings-network-coordinator-port'),
 ('in', 'html', 'settings-network-worker-url'),
 ('in', 'html', 'settings-network-path-map'),
 ('in', 'html', 'settings-network-apply-button'),
 ('in', 'html', 'network-role-setup-dialog'),
 ('in', 'html', 'network-role-coordinator-setup-button'),
 ('in', 'html', 'network-role-worker-setup-button'),
 ('in', 'html', 'network-settings-preview-button'),
 ('in', 'html', 'network-settings-save-button'),
 ('in', 'html', 'network-settings-patch-handoff'),
 ('in', 'html', 'network-settings-rows'),
 ('in', 'html', 'network-api-summary'),
 ('in', 'html', 'data-page-panel="maintenance"'),
 ('in', 'html', 'maintenance-refresh-button'),
 ('in', 'html', 'maintenance-progress-status'),
 ('in', 'html', 'maintenance-progress-bars'),
 ('in', 'html', 'maintenance-progress-steps'),
 ('in', 'html', 'maintenance-rows'),
 ('in', 'html', 'maintenance-readiness-status'),
 ('in', 'html', 'maintenance-readiness'),
 ('in', 'html', 'maintenance-toolchain-status'),
 ('in', 'html', 'maintenance-toolchain'),
 ('in', 'html', 'maintenance-warnings'),
 ('in', 'html', 'maintenance-table-legend'),
 ('in', 'html', 'maintenance-detail-status'),
 ('in', 'html', 'maintenance-detail'),
 ('in', 'html', 'maintenance-diagnostics-actions'),
 ('in', 'html', 'maintenance-diagnostics-status'),
 ('in', 'html', 'maintenance-dry-run-confidence-status'),
 ('in', 'html', 'maintenance-dry-run-confidence'),
 ('in', 'html', 'release-dry-run-button'),
 ('in', 'html', 'release-build-button'),
 ('in', 'html', 'Preview Deployment'),
 ('in', 'html', 'Zip package'),
 ('in', 'html', 'Verify package'),
 ('in', 'html', 'Preview Deployment runs the release builder with DryRun'),
 ('in', 'html', 'release-build-force'),
 ('in', 'html', 'release-build-detail'),
 ('in', 'html', 'release-build-progress-bars'),
 ('in', 'html', 'release-package-status-strip'),
 ('in', 'html', 'release-dry-run-state-value'),
 ('in', 'html', 'release-build-state-value'),
 ('in', 'html', 'release-dry-run-detail'),
 ('in', 'html', 'release-dry-run-progress-bars'),
 ('in', 'html', 'release-dry-run-optional-tools'),
 ('in', 'html', 'backfill-dry-run-progress-bars'),
 ('in', 'html', 'backfill-dry-run-button'),
 ('in', 'html', 'backfill-dry-run-detail'),
 ('in', 'html', 'dependency-atlas-button'),
 ('in', 'html', 'dependency-atlas-open-folder-button'),
 ('in', 'html', 'dependency-atlas-status'),
 ('in', 'html', 'dependency-atlas-progress-bars'),
 ('in', 'html', 'dependency-atlas-detail'),
 ('in', 'html', 'maintenance-dry-run-history-status'),
 ('in', 'html', 'maintenance-dry-run-history'),
 ('in', 'html', 'command-rows'),
 ('in', 'html', 'command-summary'),
 ('in', 'html', 'command-detail'),
 ('in', 'html', '<th scope="col">Owner</th>'),
 ('in', 'html', '<th scope="col">Issue</th>'),
 ('in', 'html', 'settings-validate-button'),
 ('in', 'html', 'settings-trust-status'),
 ('in', 'html', 'settings-trust-summary'),
 ('in', 'html', 'data-confirm-command="true"'),
 ('in', 'html', 'log-tail'),
 ('in', 'html', 'launch-logs'),
 ('in', 'html', 'diagnostics-close-status'),
 ('in', 'html', 'diagnostics-close-readiness'),
 ('in', 'html', 'backend-lifecycle-status'),
 ('in', 'html', 'backend-lifecycle-summary'),
 ('in', 'html', 'backend-shutdown-button'),
 ('in', 'html', 'backend-shutdown-status'),
 ('in', 'html', 'backend-lifecycle-history'),
 ('in', 'html', 'diagnostics-triage-status'),
 ('in', 'html', 'diagnostics-triage-summary'),
 ('in', 'html', 'diagnostics-investigation-status'),
 ('in', 'html', 'diagnostics-investigation-trail'),
 ('in', 'html', 'diagnostics-investigation-actions'),
 ('in', 'html', 'diagnostics-owner-handoff-status'),
 ('in', 'html', 'diagnostics-owner-handoff'),
 ('in', 'html', 'diagnostics-owner-handoff-rows'),
 ('in', 'html', 'diagnostics-owner-handoff-detail'),
 ('in', 'html', 'diagnostics-owner-handoff-actions'),
 ('in', 'html', 'diagnostics-owner-handoff-nav-status'),
 ('in', 'html', 'diagnostics-drilldown-status'),
 ('in', 'html', 'diagnostics-drilldown-summary'),
 ('in', 'html', 'diagnostics-drilldown-actions'),
 ('in', 'html', 'diagnostics-state-summary-status'),
 ('in', 'html', 'diagnostics-state-summary'),
 ('in', 'html', 'diagnostics-state-recovery-status'),
 ('in', 'html', 'diagnostics-state-recovery'),
 ('in', 'html', 'diagnostics-state-triage-status'),
 ('in', 'html', 'diagnostics-state-triage-summary'),
 ('in', 'html', 'diagnostics-state-triage-rows'),
 ('in', 'html', 'diagnostics-state-triage-detail'),
 ('in', 'html', 'diagnostics-state-triage-actions'),
 ('in', 'html', 'diagnostics-state-summary-rows'),
 ('in', 'html', 'diagnostics-state-summary-detail'),
 ('in', 'html', 'diagnostics-state-summary-actions'),
 ('in', 'html', 'diagnostics-command-status'),
 ('in', 'html', 'diagnostics-command-history'),
 ('in', 'html', 'diagnostics-command-drilldown-status'),
 ('in', 'html', 'diagnostics-command-drilldown-summary'),
 ('in', 'html', 'diagnostics-command-drilldown-rows'),
 ('in', 'html', 'diagnostics-command-drilldown-detail'),
 ('in', 'html', 'diagnostics-command-drilldown-actions'),
 ('in', 'html', 'diagnostics-command-owner-status'),
 ('in', 'html', 'diagnostics-command-owner-summary'),
 ('in', 'html', 'diagnostics-command-owner-rows'),
 ('in', 'html', 'diagnostics-command-owner-legend'),
 ('in', 'html', 'diagnostics-command-evidence-status'),
 ('in', 'html', 'diagnostics-command-evidence-summary'),
 ('in', 'html', 'diagnostics-command-evidence-rows'),
 ('in', 'html', 'diagnostics-command-resolution-status'),
 ('in', 'html', 'diagnostics-command-resolution-summary'),
 ('in', 'html', 'diagnostics-command-resolution-rows'),
 ('in', 'html', 'diagnostics-command-resolution-detail'),
 ('in', 'html', 'diagnostics-command-resolution-legend'),
 ('in', 'html', 'diagnostics-progress-status'),
 ('in', 'html', 'diagnostics-progress-bars'),
 ('in', 'html', 'diagnostics-progress-rows'),
 ('in', 'html', 'diagnostics-progress-detail'),
 ('in', 'html', 'diagnostics-log-status'),
 ('in', 'html', 'diagnostics-log-filter'),
 ('in', 'html', 'diagnostics-log-severity'),
 ('in', 'html', 'diagnostics-log-guidance'),
 ('in', 'html', 'diagnostics-log-rows'),
 ('in', 'html', 'diagnostics-log-detail'),
 ('in', 'html', 'diagnostics-log-actions'),
 ('in', 'html', 'diagnostics-tail-status'),
 ('in', 'html', 'diagnostics-tail-target'),
 ('in', 'html', 'diagnostics-tail-max-bytes'),
 ('in', 'html', 'diagnostics-tail-refresh-button'),
 ('in', 'html', 'diagnostics-tail-detail'),
 ('in', 'html', 'diagnostics-tail-text'),
 ('in', 'html', 'active-job-detail-status'),
 ('in', 'html', 'active-job-detail-rows'),
 ('in', 'html', 'active-job-detail'),
 ('in', 'html', 'telemetry-readiness-status'),
 ('in', 'html', 'telemetry-readiness-summary'),
 ('in', 'html', 'diagnostics-open-status'),
 ('in', 'html', 'data-open-diagnostics="run_logs"'),
 ('in', 'html', 'data-open-diagnostics="cluster_log"'),
 ('in', 'html', 'data-open-diagnostics="last_stdout_log"'),
 ('in', 'html', 'data-open-diagnostics="last_stderr_log"'),
 ('in', 'html', 'data-open-diagnostics="config"'),
 ('in', 'html', 'data-open-diagnostics="pending_publish"'),
 ('in', 'html', 'data-open-diagnostics="active_jobs"'),
 ('in', 'html', 'data-open-diagnostics="queue_snapshot"'),
 ('in', 'html', 'data-open-diagnostics="completed_manifest"'),
 ('in', 'html', 'data-open-diagnostics="failed_markers"'),
 ('in', 'html', 'data-open-diagnostics="sample_validation_log"'),
 ('in', 'html', 'value="sample_validation_log"'),
 ('in', 'html', 'diagnostics-open-history'),
 ('in', 'html', 'report-open-history-status'),
 ('in', 'html', 'report-open-history'))

NETWORK_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'network_view_js', 'window.mediaPipelineNetworkView'),
 ('in', 'network_view_js', 'function renderNetworkView'),
 ('in', 'network_view_js', 'function renderNetworkReadiness'),
 ('in', 'network_view_js', 'function networkReadinessLines'),
 ('in', 'network_view_js', 'function networkLifecycleRows'),
 ('in', 'network_view_js', 'function renderNetworkLifecycleHandoff'),
 ('in', 'network_view_js', 'Network lifecycle handoff:'),
 ('in', 'network_view_js', 'Decision rule: trust only backend-owned Network evidence and lifecycle routes'),
 ('in', 'network_view_js', 'Confirmed lifecycle commands remain confirmation-gated and provider-guarded'),
 ('in', 'network_view_js', 'function networkEvidenceRows'),
 ('in', 'network_view_js', 'function renderNetworkEvidenceChecklist'),
 ('in', 'network_view_js', 'function networkEvidenceSummaryLines'),
 ('in', 'network_view_js', 'Network evidence checklist:'),
 ('in', 'network_view_js', 'persisted worker state is visible through /api/network/workers'),
 ('in', 'network_view_js', 'function renderNetworkWorkerProgress'),
 ('in', 'network_view_js', 'network-worker-progress-bars'),
 ('in', 'network_view_js', 'Mutation guardrail: this panel uses backend-owned Network lifecycle routes only'),
 ('not_in', 'network_view_js', 'function activateNetworkTab'),
 ('not_in', 'network_view_js', 'mediapipeline-network-tab'),
 ('in', 'network_view_js', 'function networkRolePanelIds'),
 ('in', 'network_view_js', 'function syncNetworkRoleDashboards'),
 ('in', 'network_view_js', 'function networkCoordinatorOverviewModel'),
 ('in', 'network_view_js', 'function networkWorkerOverviewModel'),
 ('in', 'network_view_js', 'function renderNetworkRoleDashboards'),
 ('in', 'network_view_js', 'Remote coordinator queue: Phase 2'),
 ('in', 'network_view_js', 'unknown/backend evidence missing'),
 ('in', 'network_view_js', 'function renderNetworkStateFiles'),
 ('in', 'network_view_js', 'function networkStateFileSummaryLines'),
 ('in', 'network_view_js', 'Network runtime state file evidence:'),
 ('in', 'network_view_js', 'Read order: Cluster log -> Coordinator in-flight registry -> Local worker state'),
 ('in', 'network_view_js', 'network-state-files-rows'),
 ('in', 'network_view_js', 'live dispatcher lifecycle rows remain backend-owned'),
 ('in', 'network_view_js', 'This checklist cannot abort, reclaim, release'),
 ('not_in', 'network_view_js', 'not exposed through the local WebView API yet'),
 ('in', 'network_view_js', 'function renderNetworkWorkers'),
 ('in', 'network_view_js', 'function renderNetworkWorkerRows'),
 ('in', 'network_view_js', 'function networkWorkerRowKey'),
 ('in', 'network_view_js', 'function filteredNetworkWorkerRows'),
 ('in', 'network_view_js', 'function initNetworkViewEvents'),
 ('in', 'network_view_js', 'function renderNetworkWorkerDetail'),
 ('in', 'network_view_js', 'function renderNetworkOpenHistory'),
 ('in', 'network_view_js', 'function isNetworkOpenCommand'),
 ('in', 'network_view_js', 'Backend diagnostics target allowlists remain the source of truth.'),
 ('in', 'network_view_js', 'Lifecycle controls remain backend-owned'),
 ('in', 'network_view_js', 'This detail pane is read-only persisted state.'),
 ('in', 'network_view_js', 'read-only persisted state'),
 ('in', 'network_view_js', 'Worker board source:'),
 ('in', 'network_view_js', 'backend Network diagnostics'),
 ('in', 'network_view_js', 'function renderNetworkSettingsRows'),
 ('in', 'network_view_js', 'function renderNetworkSettingsPatchHandoff'),
 ('in', 'network_view_js', 'function previewNetworkSettingsPatch'),
 ('in', 'network_view_js', 'function saveNetworkSettingsPatch'),
 ('in', 'network_view_js', 'NetworkRole'),
 ('in', 'network_view_js', 'WorkerCoordinatorUrl'),
 ('in', 'network_view_js', 'CoordinatorHeartbeatTimeoutMins'),
 ('in', 'network_view_js', 'network-readiness-summary'),
 ('in', 'network_view_js', 'network-settings-rows'),
 ('in', 'network_view_js', 'network-api-summary'),
 ('in', 'js', '/api/network/workers'),
 ('in', 'js', 'networkWorkers: values["network workers"]'),
 ('in', 'js', 'queue: latestQueue'))

DIAGNOSTICS_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'diagnostics_view_active_jobs_js', 'function createDiagnosticsActiveJobsModule'),
 ('in', 'diagnostics_view_active_jobs_js', 'window.__diagnosticsActiveJobsModule'),
 ('in', 'diagnostics_view_log_js', 'function createDiagnosticsLogModule'),
 ('in', 'diagnostics_view_log_js', 'window.__diagnosticsLogModule'),
 ('in', 'diagnostics_view_investigation_js', 'function createDiagnosticsInvestigationModule'),
 ('in', 'diagnostics_view_investigation_js', 'window.__diagnosticsInvestigationModule'),
 ('in', 'diagnostics_view_parent_js', 'const diagnosticsActiveJobsModule = window.__diagnosticsActiveJobsModule || {}'),
 ('in', 'diagnostics_view_parent_js', 'const diagnosticsLogModule = window.__diagnosticsLogModule || {}'),
 ('in',
  'diagnostics_view_parent_js',
  'const diagnosticsInvestigationModule = window.__diagnosticsInvestigationModule || {}'),
 ('in', 'diagnostics_view_parent_js', 'delete window.__diagnosticsActiveJobsModule'),
 ('in', 'diagnostics_view_parent_js', 'delete window.__diagnosticsLogModule'),
 ('in', 'diagnostics_view_parent_js', 'delete window.__diagnosticsInvestigationModule'),
 ('in', 'diagnostics_view_js', 'window.mediaPipelineDiagnosticsView'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'requestTdarrMatrixAudit'),
 ('not_in', 'diagnostics_view_js', 'window.requestTdarrMatrixAudit = requestTdarrMatrixAudit'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'requestTdarrMatrixRunComparison'),
 ('not_in', 'diagnostics_view_js', 'window.requestTdarrMatrixRunComparison = requestTdarrMatrixRunComparison'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'requestTdarrMatrixRerun'),
 ('not_in', 'diagnostics_view_js', 'window.requestTdarrMatrixRerun = requestTdarrMatrixRerun'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'requestTdarrMatrixEvidenceOpen'),
 ('not_in', 'diagnostics_view_js', 'window.requestTdarrMatrixEvidenceOpen = requestTdarrMatrixEvidenceOpen'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'requestTdarrMatrixConsole'),
 ('not_in', 'diagnostics_view_js', 'window.requestTdarrMatrixConsole = requestTdarrMatrixConsole'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'renderTdarrMatrixConsole'),
 ('not_in', 'diagnostics_view_js', 'window.renderTdarrMatrixConsole = renderTdarrMatrixConsole'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'renderTdarrMatrixRunComparison'),
 ('not_in', 'diagnostics_view_js', 'window.renderTdarrMatrixRunComparison = renderTdarrMatrixRunComparison'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'renderTdarrMatrixBucketCoverage'),
 ('not_in', 'diagnostics_view_js', 'window.renderTdarrMatrixBucketCoverage = renderTdarrMatrixBucketCoverage'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'renderTdarrMatrixAuditFindings'),
 ('not_in', 'diagnostics_view_js', 'window.renderTdarrMatrixAuditFindings = renderTdarrMatrixAuditFindings'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'isDiagnosticsOpenCommand'),
 ('not_in', 'diagnostics_view_js', 'window.isDiagnosticsOpenCommand = isDiagnosticsOpenCommand'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'diagnosticsOpenHistoryLine'),
 ('not_in', 'diagnostics_view_js', 'window.diagnosticsOpenHistoryLine = diagnosticsOpenHistoryLine'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'selectedDiagnosticsTailTarget'),
 ('not_in', 'diagnostics_view_js', 'window.selectedDiagnosticsTailTarget = selectedDiagnosticsTailTarget'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'selectedDiagnosticsTailMaxBytes'),
 ('not_in', 'diagnostics_view_js', 'window.selectedDiagnosticsTailMaxBytes = selectedDiagnosticsTailMaxBytes'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'setDiagnosticsTailStatus'),
 ('not_in', 'diagnostics_view_js', 'window.setDiagnosticsTailStatus = setDiagnosticsTailStatus'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'setDiagnosticsTailBusy'),
 ('not_in', 'diagnostics_view_js', 'window.setDiagnosticsTailBusy = setDiagnosticsTailBusy'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'setDiagnosticsTailTarget'),
 ('not_in', 'diagnostics_view_js', 'window.setDiagnosticsTailTarget = setDiagnosticsTailTarget'),
 ('in', 'diagnostics_view_js', 'function renderDiagnostics'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsTriage'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsInvestigationTrail'),
 ('in', 'diagnostics_view_js', 'function diagnosticsInvestigationTrailLines'),
 ('in', 'diagnostics_view_js', 'function diagnosticsFirstResponseRows'),
 ('in', 'diagnostics_view_js', 'function diagnosticsFirstResponseDetailLines'),
 ('in', 'diagnostics_view_js', 'selectedDiagnosticsFirstResponseKey'),
 ('in', 'diagnostics_view_js', 'First-response step:'),
 ('in', 'diagnostics_view_js', 'Mutation guardrail: this detail cannot launch'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsFirstResponse'),
 ('in', 'diagnostics_view_js', 'function diagnosticsRealMediaBoundaryLines'),
 ('in', 'diagnostics_view_js', 'function diagnosticsInvestigationActions'),
 ('in', 'diagnostics_view_js', 'function diagnosticsCrossPageConflictRows'),
 ('in', 'diagnostics_view_js', 'function diagnosticsConflictSignalLabel'),
 ('in', 'diagnostics_view_js', 'Diagnostics investigation trail:'),
 ('in', 'diagnostics_view_js', 'Diagnostics first-response checklist:'),
 ('in', 'diagnostics_view_js', 'External dependency readiness'),
 ('in', 'diagnostics_view_js', 'function diagnosticsSamplePolicyReconciliation'),
 ('in', 'diagnostics_view_js', 'Sample Validation policy reconciliation'),
 ('in', 'diagnostics_view_js', 'Completed saved-policy reconciliation'),
 ('in',
  'diagnostics_view_js',
  'Owner pages: Home owns Preview/Append evidence; Completed owns post-run output proof; Settings owns saved policy.'),
 ('in', 'diagnostics_view_js', 'Resolve blocked Settings OCR or Maintenance toolchain evidence'),
 ('in',
  'diagnostics_view_js',
  'Read order: bounded text first, backend-selected artifact opens next, owning page before any mutation command.'),
 ('in',
  'diagnostics_view_js',
  'Mutation guardrail: this checklist cannot launch, drain, save, rename, repair, delete, publish, clear state, or '
  'touch files.'),
 ('in', 'diagnostics_view_js', 'Real-media validation lens:'),
 ('in', 'diagnostics_view_js', 'Missing diagnostics evidence is not success'),
 ('in', 'diagnostics_view_js', 'Cross-page row review(s):'),
 ('in', 'diagnostics_view_js', 'Cross-page conflict handoff(s):'),
 ('in', 'diagnostics_view_js', 'advisory filename-only'),
 ('in', 'diagnostics_view_js', 'Mutation guardrail: this trail is read-only'),
 ('in', 'js', 'renderDiagnosticsFirstResponseFn(diagnosticsContext)'),
 ('in', 'js', 'renderDiagnosticsInvestigationTrail(diagnosticsContext)'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsDrilldown'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsDrilldownActions'),
 ('in', 'diagnostics_view_js', 'function renderActiveJobRows'),
 ('in', 'diagnostics_view_js', 'function renderActiveJobDetail'),
 ('in', 'diagnostics_view_js', 'function activeJobRowPosture'),
 ('in', 'diagnostics_view_js', 'function activeJobRowsStatusText'),
 ('in', 'diagnostics_view_js', 'active/review='),
 ('in', 'diagnostics_view_js', 'function diagnosticsActiveJobRealMediaTraceLines'),
 ('in', 'diagnostics_view_js', 'Real-media sample trace: ActiveJobs'),
 ('in', 'diagnostics_view_js', 'function activeJobRowKey'),
 ('in', 'diagnostics_view_js', 'payload.active_job_rows'),
 ('in', 'diagnostics_view_js', 'function diagnosticsLogRows'),
 ('in', 'diagnostics_view_js', 'function diagnosticsLogRowKey'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'diagnosticsLogRowKey'),
 ('not_in', 'diagnostics_view_js', 'window.diagnosticsLogRowKey = diagnosticsLogRowKey'),
 ('in', 'diagnostics_view_js', 'function filteredDiagnosticsLogRows'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsLogRows'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsLogDetail'),
 ('in', 'diagnostics_view_js', 'function diagnosticsArtifactsForLine'),
 ('in', 'diagnostics_view_js', 'function diagnosticsLogRowActions'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'diagnosticsLogRowActions'),
 ('not_in', 'diagnostics_view_js', 'window.diagnosticsLogRowActions = diagnosticsLogRowActions'),
 ('in', 'diagnostics_view_js', 'function diagnosticsLogRowNextStep'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'diagnosticsLogRowNextStep'),
 ('not_in', 'diagnostics_view_js', 'window.diagnosticsLogRowNextStep = diagnosticsLogRowNextStep'),
 ('in', 'diagnostics_view_js', 'function diagnosticsLogRealMediaTraceLines'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'diagnosticsLogRealMediaTraceLines'),
 ('not_in', 'diagnostics_view_js', 'window.diagnosticsLogRealMediaTraceLines = diagnosticsLogRealMediaTraceLines'),
 ('in', 'diagnostics_view_js', 'Real-media sample trace: Diagnostics log'),
 ('in',
  'diagnostics_view_js',
  'a single log line is not completion, output, sidecar, size, subtitle/audio, or publish proof'),
 ('in', 'diagnostics_view_js', 'function diagnosticsActionGroups'),
 ('in', 'diagnostics_view_js', 'function diagnosticsActionPlanLines'),
 ('in', 'diagnostics_view_js', 'function activeJobDiagnosticsActions'),
 ('in', 'diagnostics_view_js', 'function renderActiveJobDiagnosticsActions'),
 ('in', 'diagnostics_view_js', 'function diagnosticsLogGuidanceLines'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'diagnosticsLogGuidanceLines'),
 ('not_in', 'diagnostics_view_js', 'window.diagnosticsLogGuidanceLines = diagnosticsLogGuidanceLines'),
 ('in', 'diagnostics_view_js', 'Proof boundary: an empty or clean log view'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsLogActions'),
 ('in', 'diagnostics_view_js', 'function getLastDiagnosticsLogRows'),
 ('in', 'diagnostics_view_js', 'commandHistoryView.renderCommandDiagnosticsEvidence(selectedCommand)'),
 ('in', 'diagnostics_view_js', 'commandHistoryView.commandHistorySuggestedAction(entry)'),
 ('in', 'diagnostics_view_js', 'Diagnostics action plan:'),
 ('in', 'diagnostics_view_js', 'Read first:'),
 ('in', 'diagnostics_view_js', 'Open next:'),
 ('in', 'diagnostics_view_js', 'renderOpenTargetActionGroups?.(container, groups'),
 ('in', 'diagnostics_view_js', 'append: true'),
 ('in', 'diagnostics_view_js', 'groupDataset: "diagnosticsActionGroup"'),
 ('in', 'diagnostics_view_js', 'selected-row actions use backend allowlists'),
 ('in', 'diagnostics_view_js', 'actionDataset: "diagnosticsLogAction"'),
 ('in', 'diagnostics_view_js', 'targetDataset: "diagnosticsLogTarget"'),
 ('in', 'diagnostics_view_js', 'requestDiagnosticsTail(target, button)'),
 ('in', 'diagnostics_view_js', 'requestDiagnosticsOpen(target, button)'),
 ('in', 'diagnostics_view_js', 'Fallback for an error line with no specific artifact match.'),
 ('in', 'diagnostics_view_js', 'Fallback for an active-work line with no specific artifact match.'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'renderDiagnosticsTail'),
 ('not_in', 'diagnostics_view_js', 'window.renderDiagnosticsTail = renderDiagnosticsTail'),
 ('in', 'diagnostics_view_js', 'Mutation guardrail: log triage is read-only'),
 ('in', 'diagnostics_tail_view_js', 'window.mediaPipelineDiagnosticsTailView'),
 ('in', 'diagnostics_tail_view_js', 'function requestDiagnosticsTail'),
 ('in', 'diagnostics_tail_view_js', 'function renderDiagnosticsTail'),
 ('in', 'diagnostics_tail_view_js', 'function setDiagnosticsTailTarget'),
 ('in', 'diagnostics_view_js', 'diagnosticsTailView.requestDiagnosticsTail || window.requestDiagnosticsTail'),
 ('in', 'diagnostics_tail_view_js', 'function diagnosticsTailEvidence'),
 ('in', 'diagnostics_tail_view_js', 'function diagnosticsTailEvidenceLines'),
 ('in', 'diagnostics_tail_view_js', 'Object.assign({ evidence_authority: "backend" }, evidence)'),
 ('in', 'diagnostics_tail_view_js', 'evidence_authority: "frontend_advisory"'),
 ('in', 'diagnostics_tail_view_js', 'Tail posture (advisory text scan)'),
 ('in', 'diagnostics_tail_view_js', 'Evidence authority: ${isFrontendAdvisory ? "frontend advisory only" : "backend"}'),
 ('in',
  'diagnostics_tail_view_js',
  'cannot authorize launch, drain, rename, settings save, lifecycle commands, or file changes'),
 ('in', 'diagnostics_tail_view_js', 'let diagnosticsTailInFlight = false'),
 ('in', 'diagnostics_tail_view_js', '/api/diagnostics/tail'),
 ('in', 'diagnostics_tail_view_js', 'Backend diagnostics tail uses allowlisted targets only.'),
 ('in', 'diagnostics_tail_view_js', 'Diagnostics tail evidence is read-only'),
 ('in', 'diagnostics_state_summary_view_js', 'window.mediaPipelineDiagnosticsStateSummaryView'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateSummary'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateSummaryRows'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateSummaryDetail'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateSummaryActions'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateRecovery'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateTriage'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateTriageRows'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateTriageDetail'),
 ('in', 'diagnostics_state_summary_view_js', 'function renderDiagnosticsStateTriageActions'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateTriageRowKey'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateTriageActionsForItem'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateArtifactMeaning'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateRecommendedFirstAction'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateSummaryRowKey'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateOperatorStatus'),
 ('not_in',
  'diagnostics_state_summary_view_js',
  'window.diagnosticsStateRecommendedFirstAction = diagnosticsStateRecommendedFirstAction'),
 ('not_in',
  'diagnostics_state_summary_view_js',
  'window.diagnosticsStateOperatorStatus = diagnosticsStateOperatorStatus'),
 ('not_in',
  'diagnostics_state_summary_view_js',
  'window.diagnosticsStateRowStatusState = diagnosticsStateRowStatusState'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateSettingsToolPathLines'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateSummaryActionsForItem'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateArtifactRiskLines'),
 ('in', 'diagnostics_state_summary_view_js', 'function diagnosticsStateActionPlanLines'),
 ('in', 'diagnostics_state_summary_view_js', 'Operational interpretation:'),
 ('in', 'diagnostics_state_summary_view_js', 'renderOpenTargetActionGroups?.(actions, groups'),
 ('in', 'diagnostics_state_summary_view_js', 'groupDataset: "diagnosticsStateActionGroup"'),
 ('in', 'diagnostics_state_summary_view_js', 'Process lifecycle evidence'),
 ('in', 'diagnostics_state_summary_view_js', 'Settings tool-path handoff:'),
 ('in', 'diagnostics_state_summary_view_js', 'Open Settings > Media Output'),
 ('in', 'diagnostics_state_summary_view_js', 'Recommended first action:'),
 ('in', 'diagnostics_state_summary_view_js', 'Recovery stage:'),
 ('in', 'diagnostics_state_summary_view_js', 'Unsafe if ignored:'),
 ('in', 'diagnostics_state_summary_view_js', 'Recovery stage and unsafe-if-ignored fields explain'),
 ('in', 'diagnostics_state_summary_view_js', 'State artifact recovery checklist:'),
 ('in', 'diagnostics_state_summary_view_js', 'Backend read order:'),
 ('in', 'diagnostics_state_summary_view_js', 'Backend read-order detail:'),
 ('in', 'diagnostics_state_summary_view_js', 'Diagnostics artifact JSON'),
 ('in', 'diagnostics_state_summary_view_js', 'Diagnostics triage JSON'),
 ('in', 'diagnostics_state_summary_view_js', 'jsonDetailText({'),
 ('in', 'diagnostics_state_summary_view_js', 'targetDataset: "diagnosticsStateTriageTarget"'),
 ('in', 'diagnostics_state_summary_view_js', 'Close Readiness is the authority'),
 ('in', 'diagnostics_state_summary_view_js', 'window.requestDiagnosticsOpen(target, button)'),
 ('in', 'diagnostics_state_summary_view_js', 'window.requestDiagnosticsTail(target, button)'),
 ('in', 'diagnostics_state_summary_view_js', 'Mutation guardrail: this checklist does not repair'),
 ('in', 'diagnostics_state_summary_view_js', 'Guardrail: this view is read-only'),
 ('in', 'html', 'id="active-job-diagnostics-actions"'),
 ('in', 'diagnostics_view_js', 'mediaPipelineDiagnosticsTailView'),
 ('in', 'diagnostics_view_js', 'function initDiagnosticsViewEvents'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'initDiagnosticsViewEvents'),
 ('not_in', 'diagnostics_view_js', 'window.initDiagnosticsViewEvents = initDiagnosticsViewEvents'),
 ('in', 'diagnostics_view_js', 'No diagnostics log rows match the current filter.'),
 ('in', 'diagnostics_view_js', 'selected-row actions use backend allowlists'),
 ('in', 'diagnostics_view_js', 'function diagnosticsSeverityForLine'),
 ('in', 'diagnostics_view_js', 'function diagnosticsMalformedStateLines'),
 ('in', 'diagnostics_view_js', 'function diagnosticsArtifactMatches'),
 ('in', 'diagnostics_view_js', 'diagnosticsArtifactTargets'),
 ('in', 'diagnostics_view_js', 'button.dataset.openDiagnostics = openTarget'),
 ('in', 'diagnostics_view_js', 'requestDiagnosticsOpen(openTarget, button)'),
 ('in', 'diagnostics_view_js', 'tailButton.dataset.readDiagnosticsTail = artifact.tailTarget'),
 ('in', 'diagnostics_view_js', 'requestDiagnosticsTail(artifact.tailTarget, tailButton)'),
 ('in', 'diagnostics_view_js', 'tailTarget: "last_stderr_log"'),
 ('in', 'diagnostics_view_js', 'tailTarget: "queue_snapshot"'),
 ('in', 'diagnostics_view_js', 'tailTarget: "latest_failure_report"'),
 ('in', 'diagnostics_view_js', 'tailTarget: "cluster_log"'),
 ('in', 'diagnostics_view_js', 'BDPGS OCR settings evidence'),
 ('in', 'diagnostics_view_js', 'settings_bdpgs_ocr_paths'),
 ('in', 'diagnostics_view_js', 'VobSub OCR settings evidence'),
 ('in', 'diagnostics_view_js', 'settings_vobsub_ocr_paths'),
 ('in', 'diagnostics_view_js', 'Diagnostics does not edit settings or run OCR.'),
 ('in', 'diagnostics_view_js', 'orphan payload'),
 ('in', 'diagnostics_view_js', 'malformed manifests'),
 ('in', 'diagnostics_view_js', 'Malformed/stale runtime-state hint(s):'),
 ('in', 'diagnostics_view_js', 'Severity groups:'),
 ('in', 'diagnostics_view_js', 'Check Diagnostics > Overview > Shutdown Readiness first'),
 ('in', 'html', 'diagnostics-first-response-status'),
 ('in', 'html', 'diagnostics-first-response-summary'),
 ('in', 'html', 'diagnostics-first-response-rows'),
 ('in', 'html', 'diagnostics-first-response-detail'),
 ('in', 'diagnostics_view_js', 'Artifact drilldown is read-only'),
 ('in', 'diagnostics_view_js', 'Open and Read buttons below use backend allowlists'),
 ('in', 'diagnostics_view_js', 'backend allowlist'),
 ('in', 'diagnostics_view_js', 'function requestDiagnosticsOpen'),
 ('in', 'diagnostics_view_js', 'function setDiagnosticsOpenStatus'),
 ('in', 'diagnostics_view_js', 'home-runtime-open-status'),
 ('in', 'diagnostics_view_js', 'function renderDiagnosticsOpenHistory'),
 ('namespace', 'diagnostics_view_js', 'mediaPipelineDiagnosticsView', 'renderDiagnosticsOpenHistory'),
 ('not_in', 'diagnostics_view_js', 'window.renderDiagnosticsOpenHistory = renderDiagnosticsOpenHistory'),
 ('in', 'diagnostics_view_js', 'function isDiagnosticsOpenCommand'),
 ('in', 'diagnostics_view_js', 'Backend diagnostics target allowlists remain the source of truth.'),
 ('in', 'diagnostics_view_js', 'let diagnosticsOpenInFlight = false'),
 ('in', 'diagnostics_view_js', 'function setDiagnosticsOpenBusy'),
 ('in', 'diagnostics_view_js', 'function rejectDiagnosticsOpenWhileBusy'),
 ('in', 'diagnostics_view_js', 'Another diagnostics open command is already in progress.'),
 ('in', 'diagnostics_view_js', 'log_tail'),
 ('in', 'diagnostics_view_js', '/api/diagnostics/open'),
 ('in', 'diagnostics_view_js', '/api/diagnostics/tdarr-matrix-audit'),
 ('in', 'html', 'data-tdarr-matrix-audit-action'),
 ('not_in', 'diagnostics_tail_view_js', 'window.selectedDiagnosticsTailTarget ='),
 ('not_in', 'diagnostics_tail_view_js', 'window.selectedDiagnosticsTailMaxBytes ='),
 ('not_in', 'diagnostics_tail_view_js', 'window.setDiagnosticsTailTarget ='),
 ('not_in', 'diagnostics_tail_view_js', 'window.setDiagnosticsTailStatus ='),
 ('not_in', 'diagnostics_tail_view_js', 'window.setDiagnosticsTailBusy ='),
 ('not_in', 'diagnostics_tail_view_js', 'window.renderDiagnosticsTail ='),
 ('not_in', 'diagnostics_tail_view_js', 'window.requestDiagnosticsTail ='))

REPORTS_SCHEDULE_MAINTENANCE_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'reports_view_js', 'window.mediaPipelineReportsView'),
 ('in', 'reports_view_js', 'function renderReports'),
 ('in', 'reports_audit_commands_js', 'renderAuditProgressInto({'),
 ('in', 'reports_audit_commands_js', 'report-progress-bars'),
 ('in', 'reports_view_js', 'function renderReportTriage'),
 ('in', 'reports_view_js', 'function renderReportInvestigation'),
 ('in', 'reports_triage_js', 'function reportInvestigationChecklistLines'),
 ('in', 'reports_triage_js', 'Reports investigation checklist:'),
 ('in', 'reports_view_js', 'function initReportsViewEvents'),
 ('not_in', 'reports_view_js', 'window.initReportsViewEvents = initReportsViewEvents'),
 ('not_in', 'reports_view_js', 'window.renderFailureRows = renderFailureRows'),
 ('not_in', 'reports_view_js', 'window.renderAuditRows = renderAuditRows'),
 ('not_in', 'reports_view_js', 'window.renderAuditControls = renderAuditControls'),
 ('not_in', 'reports_view_js', 'window.renderReportOpenHistory = renderReportOpenHistory'),
 ('not_in', 'reports_view_js', 'function renderReportLaunchHandoff'),
 ('not_in', 'reports_view_js', 'function reportLaunchHandoffLines'),
 ('not_in', 'reports_view_js', 'function reportGoToCsvRerun'),
 ('not_in', 'reports_view_js', 'function reportGoToAuditLaunch'),
 ('not_in', 'reports_view_js', 'function reportGoToDiagnostics'),
 ('not_in', 'reports_view_js', 'Reports to Launch handoff:'),
 ('not_in', 'reports_view_js', 'Paste the verified CSV path manually'),
 ('not_in', 'reports_view_js', 'It never fills CSV Path, starts CSV Rerun, runs Audit'),
 ('not_in', 'reports_view_js', 'activateLaunchTab'),
 ('not_in', 'reports_view_js', 'renderLaunchAuditProgress(lastReportSnapshot)'),
 ('in', 'reports_triage_js', 'function reportTriageStatus'),
 ('in', 'reports_triage_js', 'function reportTriageLines'),
 ('in', 'reports_triage_js', 'Mutation guardrail: rerun/export/repair actions must remain backend-owned commands'),
 ('in', 'reports_failure_view_js', 'function renderFailurePreview'),
 ('in', 'reports_failure_view_js', 'function renderFailureRows'),
 ('in', 'reports_failure_view_js', 'function selectFailureRow'),
 ('in', 'reports_failure_model_js', 'function failureRetryStatePayload'),
 ('in', 'reports_failure_model_js', 'desktop_retry_state.v1'),
 ('in', 'reports_failure_model_js', 'Retry route/command:'),
 ('in', 'reports_failure_view_js', 'function toggleFailureRowSelection'),
 ('in', 'reports_failure_commands_js', 'function allFailureMarkerPaths'),
 ('in', 'reports_failure_model_js', 'function failureRecordedText'),
 ('in', 'reports_failure_view_js', 'function renderFailureDetail'),
 ('in', 'reports_failure_view_js', 'function renderFailureReviewBoard'),
 ('in', 'reports_failure_model_js', 'function failureReviewBoardLines'),
 ('in', 'reports_failure_model_js', 'function failureReviewBoardTiles'),
 ('in', 'reports_view_js', 'review-tile'),
 ('in', 'reports_failure_model_js', 'Failure review board:'),
 ('in', 'reports_failure_model_js', 'function failureEmptyStateMessage'),
 ('in', 'reports_failure_model_js', 'No failure rows found for the selected source.'),
 ('in', 'reports_failure_view_js', 'function renderFailureResolutionGroups'),
 ('in', 'reports_failure_view_js', 'function renderFailureResolutionDetail'),
 ('in', 'reports_failure_view_js', 'function renderFailureEvidenceLinks'),
 ('in', 'reports_failure_commands_js', 'Clear errors for the selected scope.'),
 ('in', 'reports_failure_model_js', 'source_json'),
 ('in', 'reports_failure_commands_js', 'function requestFailureMarkerClear'),
 ('in', 'reports_failure_commands_js', 'function requestFailureRowClear'),
 ('in', 'reports_failure_commands_js', 'function requestFailureEvidenceArchive'),
 ('in', 'reports_failure_commands_js', 'function requestFailureLifecycleTransition'),
 ('in', 'reports_shell_js', 'function initReportsTabNav'),
 ('in', 'reports_shell_js', 'function activateReportsTab'),
 ('in', 'reports_failure_commands_js', '/api/failures/clear'),
 ('in', 'reports_failure_commands_js', '/api/failures/archive-evidence'),
 ('in', 'reports_failure_commands_js', '/api/failures/open'),
 ('in', 'reports_failure_commands_js', '/api/failures/lifecycle'),
 ('in', 'reports_failure_commands_js', 'confirm_clear: !dryRun'),
 ('in', 'reports_failure_commands_js', 'Check one or more error rows first.'),
 ('in', 'reports_failure_commands_js', 'media files are not touched'),
 ('in', 'reports_audit_view_js', 'function renderAuditPreview'),
 ('in', 'reports_audit_view_js', 'function renderAuditControls'),
 ('in', 'reports_audit_view_js', 'function renderAuditRows'),
 ('in', 'reports_audit_view_js', 'function selectAuditRow'),
 ('in', 'reports_audit_view_js', 'function toggleAuditRowSelection'),
 ('in', 'reports_audit_view_js', 'function selectedAuditRowKeysList'),
 ('in', 'reports_audit_commands_js', 'apiPost("/api/audit/score-policy", request)'),
 ('in', 'reports_audit_commands_js', 'policy.issue_code_weights = {};'),
 ('in', 'reports_audit_view_js', 'renderReportAuditIssueRows'),
 ('in', 'reports_audit_commands_js', 'apiPost("/api/audit/ignore", request)'),
 ('in', 'reports_audit_commands_js', 'apiPost("/api/audit/export-rerun-csv", request)'),
 ('in', 'reports_audit_view_js', 'function renderAuditDetail'),
 ('in', 'reports_audit_view_js', 'function renderAuditReviewBoard'),
 ('in', 'reports_audit_model_js', 'function auditReviewBoardLines'),
 ('in', 'reports_audit_model_js', 'Audit review board:'),
 ('in', 'reports_audit_model_js', 'function auditEmptyStateMessage'),
 ('in', 'reports_audit_model_js', 'No audit rows found.'),
 ('in', 'reports_audit_view_js', 'Select a row to inspect priority score'),
 ('in', 'reports_view_js', 'latest_paths'),
 ('in', 'reports_audit_view_js', 'priority_score'),
 ('in', 'reports_shell_js', 'function reportOpenTarget'),
 ('in', 'reports_shell_js', 'function isReportOpenCommand'),
 ('in', 'reports_shell_js', 'function renderReportOpenHistory'),
 ('in', 'reports_shell_js', 'Backend diagnostics target allowlists remain the source of truth.'),
 ('in', 'reports_shell_js', 'requestDiagnosticsOpen(target, button)'),
 ('in', 'reports_shell_js', 'latest_failure_report'),
 ('in', 'reports_shell_js', 'latest_audit_csv'),
 ('in', 'reports_shell_js', 'pending_publish'),
 ('in', 'reports_audit_model_js', 'Reports triage is read-only; CSV rerun/export decisions must stay backend-owned.'),
 ('in', 'html', '<th scope="col">Action</th>'),
 ('in', 'schedule_view_js', 'window.mediaPipelineScheduleView'),
 ('in', 'schedule_view_js', 'function renderSchedule'),
 ('in', 'schedule_view_js', 'function scheduleDisplayValue'),
 ('in', 'schedule_view_js', 'function scheduleLaunchGuidanceLines'),
 ('in', 'schedule_view_js', 'function renderScheduleGuidance'),
 ('in', 'schedule_view_js', 'function renderScheduleTimingTrust'),
 ('in', 'schedule_view_js', 'function scheduleTimingTrustLines'),
 ('in', 'schedule_view_js', 'function renderScheduleCoverage'),
 ('in', 'schedule_view_js', 'function scheduleCoverageRows'),
 ('in', 'schedule_view_js', 'function scheduleCoverageDetailLines'),
 ('in', 'schedule_view_js', 'function scheduleWatcherSummary'),
 ('in', 'schedule_view_js', 'Generation:'),
 ('in', 'schedule_view_js', 'Continuous watcher'),
 ('in', 'schedule_view_js', 'Backend continuous watcher:'),
 ('in', 'schedule_view_js', 'function scheduleDayDetailLines'),
 ('in', 'schedule_view_js', 'function renderScheduleEditor'),
 ('in', 'schedule_view_js', 'function initScheduleViewEvents'),
 ('in', 'schedule_view_js', 'function previewScheduleEditor'),
 ('in', 'schedule_view_js', 'function saveScheduleEditor'),
 ('in', 'schedule_view_js', 'function scheduleEditorRequest'),
 ('in', 'schedule_view_js', 'function scheduleSetDayBlocks'),
 ('in', 'schedule_view_js', 'function scheduleBlockLabel'),
 ('in', 'schedule_view_js', 'function loadCurrentScheduleIntoEditor'),
 ('in', 'schedule_view_js', 'function clearScheduleEditorWeek'),
 ('in', 'schedule_view_js', 'function allowAllScheduleEditorWeek'),
 ('not_in', 'schedule_view_js', 'function scheduleCopyEditorDayToTargets'),
 ('in', 'html', 'schedule-coverage-rows'),
 ('in', 'html', 'schedule-coverage-detail'),
 ('in', 'html', 'schedule-day-detail'),
 ('in', 'html', 'schedule-editor-rows'),
 ('in', 'html', 'Select 30-minute blocks per day.'),
 ('in', 'html', 'Edit Schedule'),
 ('not_in', 'html', 'data-schedule-copy-source'),
 ('not_in', 'html', 'data-schedule-copy-target'),
 ('not_in', 'html', 'data-schedule-copy-apply'),
 ('in', 'schedule_view_js', '/api/schedule/preview'),
 ('in', 'schedule_view_js', '/api/schedule/save'),
 ('in', 'schedule_view_js', 'Writes app state'),
 ('in', 'html', 'Coverage Review'),
 ('in', 'schedule_view_js', 'Schedule timing trust:'),
 ('in', 'schedule_view_js', 'Mutation guardrail: this trust panel is read-only'),
 ('in', 'schedule_view_js', 'Mutation guardrail: WebView Schedule can preview and save'),
 ('in', 'schedule_view_js', 'Backend launch gating remains the source of truth.'),
 ('in', 'schedule_view_js', 'schedule-stop watcher'),
 ('in', 'schedule_view_js', 'schedule-day-rows'),
 ('in', 'maintenance_view_js', 'window.mediaPipelineMaintenanceView'),
 ('in', 'maintenance_view_js', 'function renderMaintenance'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceRows'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceDetail'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceHealthProgress'),
 ('in', 'maintenance_view_js', 'function pollMaintenanceProgress'),
 ('in', 'maintenance_view_js', '/api/maintenance/progress'),
 ('in', 'maintenance_view_js', 'function maintenanceDiagnosticsActionsForRow'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceDiagnosticsActions'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceReadiness'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceToolchain'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceReadinessError'),
 ('in', 'maintenance_view_js', 'function maintenanceReadinessStatus'),
 ('in', 'maintenance_view_js', 'function maintenanceToolchainStatus'),
 ('in', 'maintenance_view_js', 'function maintenanceToolchainLines'),
 ('in', 'maintenance_view_js', 'function maintenanceReadinessLines'),
 ('in', 'maintenance_view_js', 'function maintenanceRealMediaBoundaryLines'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceDryRunConfidence'),
 ('in', 'maintenance_view_js', 'function maintenanceDryRunConfidenceLines'),
 ('in', 'maintenance_view_js', 'function maintenanceReleaseOptionReviewLines'),
 ('in', 'maintenance_view_js', 'function initMaintenanceViewEvents'),
 ('in', 'maintenance_view_js', 'Real-media validation boundary:'),
 ('in', 'maintenance_view_js', 'Toolchain readiness:'),
 ('in', 'maintenance_view_js', 'WebView does not resolve arbitrary tools'),
 ('in', 'maintenance_view_js', 'Tool kind:'),
 ('in', 'maintenance_view_js', 'Failure scope:'),
 ('in',
  'maintenance_view_js',
  'Maintenance health and dry-run commands prove packaging/backfill environment posture only.'),
 ('in', 'maintenance_view_js', 'release dry-run output does not validate FFmpeg'),
 ('in', 'maintenance_view_js', 'completed-manifest backfill dry-run output does not prove media processing'),
 ('in', 'maintenance_view_js', 'Maintenance dry-run confidence:'),
 ('in', 'maintenance_view_js', 'Deployment option review:'),
 ('in', 'maintenance_view_js', 'Preview only; no release folder, manifest, or zip was written.'),
 ('in', 'maintenance_view_js', 'preview reports the zip plan, Create writes it'),
 ('in', 'maintenance_view_js', 'Create Deployment may write a release folder/manifest/zip'),
 ('in', 'maintenance_view_js', 'Backfill remains dry-run'),
 ('in', 'maintenance_view_js', 'diagnosticsBridgeRowTrustLines'),
 ('in', 'maintenance_view_js', 'Dry-run trust summary:'),
 ('in', 'maintenance_view_js', 'must remain a backend dry-run command'),
 ('in', 'maintenance_view_js', 'makeRowSelectable'),
 ('in', 'maintenance_view_js', 'updateTableStatusLegend'),
 ('in', 'maintenance_view_js', 'appendDiagnosticsBridgeGroupedButtons'),
 ('in', 'maintenance_view_js', 'function refreshMaintenance'),
 ('in', 'maintenance_view_js', 'let maintenanceRefreshInFlight = false'),
 ('in', 'maintenance_view_js', 'maintenanceRefreshQueued = true'),
 ('in', 'maintenance_view_js', 'window.setTimeout(refreshMaintenance, 0)'),
 ('in', 'maintenance_view_js', 'const maintenanceDryRunButtonIds'),
 ('in', 'maintenance_view_js', 'function setMaintenanceDryRunBusy'),
 ('in', 'maintenance_view_js', 'function rejectMaintenanceDryRunWhileBusy'),
 ('in', 'maintenance_view_js', 'function collectReleaseDryRunRequest'),
 ('in', 'maintenance_view_js', 'function collectReleaseBuildRequest'),
 ('in', 'maintenance_view_js', 'function runReleaseDryRun'),
 ('in', 'maintenance_view_js', 'function runReleaseBuild'),
 ('in', 'maintenance_view_js', 'function renderReleaseBuildResult'),
 ('in', 'maintenance_view_js', 'function renderReleasePackageProgress'),
 ('in', 'maintenance_view_js', 'function renderReleasePackageInFlightProgress'),
 ('in', 'maintenance_view_js', 'function setReleasePackageStatus'),
 ('in', 'maintenance_view_js', 'function releasePackageResultStatus'),
 ('in', 'maintenance_view_js', 'function releasePackageProgressBars'),
 ('in', 'maintenance_view_js', 'targetId = "release-dry-run-progress-bars"'),
 ('in', 'maintenance_view_js', 'renderProgressBarsInto(targetId'),
 ('in', 'maintenance_view_js', 'renderReleasePackageProgress(result, "release-build-progress-bars")'),
 ('in', 'maintenance_view_js', '"Planning"'),
 ('in', 'maintenance_view_js', '"Building"'),
 ('in', 'maintenance_view_js', '"Build done"'),
 ('in', 'maintenance_view_js', 'function runBackfillDryRun'),
 ('in', 'maintenance_view_js', 'function renderBackfillProgress'),
 ('in', 'maintenance_view_js', 'function backfillProgressBars'),
 ('in', 'maintenance_view_js', 'renderProgressBarsInto("backfill-dry-run-progress-bars"'),
 ('in', 'maintenance_view_js', 'function runDependencyAtlas'),
 ('in', 'maintenance_view_js', 'function renderDependencyAtlasResult'),
 ('in', 'maintenance_view_js', 'function renderDependencyAtlasProgress'),
 ('in', 'maintenance_view_js', 'function dependencyAtlasProgressBars'),
 ('in', 'maintenance_view_js', 'function openDependencyAtlasFolder'),
 ('in', 'maintenance_view_js', 'renderProgressBarsInto("dependency-atlas-progress-bars"'),
 ('in', 'maintenance_view_js', 'function isMaintenanceDryRunCommand'),
 ('in', 'maintenance_view_js', 'function renderMaintenanceDryRunHistory'),
 ('in', 'maintenance_view_js', 'maintenance-dry-run-history'),
 ('in', 'maintenance_view_js', '/api/maintenance'),
 ('in', 'maintenance_view_js', '/api/maintenance/release-dry-run'),
 ('in', 'maintenance_view_js', '/api/maintenance/release-build'),
 ('in', 'maintenance_view_js', '/api/maintenance/dependency-atlas'),
 ('in', 'maintenance_view_js', '/api/maintenance/dependency-atlas/open-folder'),
 ('in', 'maintenance_view_js', 'command: "maintenance.release_dry_run"'),
 ('in', 'maintenance_view_js', 'command: "maintenance.release_build"'),
 ('in', 'maintenance_view_js', 'command: "maintenance.completed_backfill_dry_run"'),
 ('in', 'maintenance_view_js', 'command: "maintenance.dependency_atlas"'),
 ('in', 'maintenance_view_js', 'command: "maintenance.dependency_atlas_open_folder"'),
 ('not_in', 'schedule_view_js', 'window.renderSchedule ='),
 ('not_in', 'schedule_view_js', 'window.renderScheduleTimingTrust ='),
 ('not_in', 'schedule_view_js', 'window.initScheduleViewEvents ='),
 ('not_in', 'schedule_view_js', 'window.scheduleTimingTrustStatus ='),
 ('not_in', 'schedule_view_js', 'window.scheduleTimingTrustLines ='),
 ('not_in', 'schedule_view_js', 'window.scheduleCurrentLaunchSelection ='),
 ('not_in', 'schedule_view_js', 'window.scheduleWatcherSummary ='),
 ('not_in', 'schedule_view_js', 'window.schedulePipelineModeLabel ='),
 ('not_in', 'schedule_view_js', 'window.scheduleOverrideLabel ='),
 ('not_in', 'schedule_view_js', 'window.scheduleDisplayValue ='),
 ('not_in', 'maintenance_view_js', 'window.hasMaintenanceLoaded ='),
 ('not_in', 'maintenance_view_js', 'window.getLastMaintenance ='),
 ('not_in', 'maintenance_view_js', 'window.refreshMaintenance ='),
 ('not_in', 'maintenance_view_js', 'window.initMaintenanceViewEvents ='),
 ('not_in', 'maintenance_view_js', 'window.runReleaseDryRun ='),
 ('not_in', 'maintenance_view_js', 'window.runReleaseBuild ='),
 ('not_in', 'maintenance_view_js', 'window.runBackfillDryRun ='))

TELEMETRY_PROGRESS_CONTRACT_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'telemetry_view_js', 'window.mediaPipelineTelemetryView'),
 ('in', 'telemetry_view_js', 'const formatters = window.mediaPipelineFormatters || {}'),
 ('in', 'telemetry_view_js', 'const formatPercent = typeof formatters.formatPercent'),
 ('in', 'telemetry_view_js', 'const formatMemoryMb = typeof formatters.formatMemoryMb'),
 ('in', 'telemetry_view_js', 'function renderTelemetry'),
 ('in', 'telemetry_view_js', 'function renderGpuRows'),
 ('in', 'telemetry_view_js', 'function drawTelemetryChart'),
 ('in', 'telemetry_view_js', 'function formatGpuEncoderPercent'),
 ('in', 'telemetry_view_js', 'function telemetryGpuNote'),
 ('in', 'telemetry_view_js', 'function renderTelemetryReadiness'),
 ('in', 'telemetry_view_js', 'function telemetryReadinessStatus'),
 ('in', 'telemetry_view_js', 'function telemetryReadinessLines'),
 ('in', 'telemetry_view_js', 'function telemetryGpuUsagePayload'),
 ('in', 'telemetry_view_js', 'desktop_gpu_encoder_usage.v1'),
 ('in', 'telemetry_view_js', 'Encoder sessions'),
 ('in', 'telemetry_view_js', 'GPU video encoder telemetry available.'),
 ('in', 'telemetry_view_js', 'Monitoring normal'),
 ('in', 'telemetry_view_js', 'Telemetry sample is stale.'),
 ('in', 'telemetry_view_js', 'function telemetryOperatingState'),
 ('in', 'telemetry_view_js', 'function telemetryChartMetaText'),
 ('not_in', 'telemetry_view_js', '0% idle'),
 ('in', 'telemetry_view_js', 'NVENC idle as expected'),
 ('in', 'telemetry_view_js', 'waiting for sample'),
 ('in', 'telemetry_view_js', 'GPU telemetry source returned no per-device rows.'),
 ('in', 'progress_view_js', 'window.mediaPipelineProgressView'),
 ('in', 'progress_view_js', 'function renderProgressBars'),
 ('in', 'progress_view_js', 'function renderAuditProgressInto'),
 ('in', 'progress_view_js', 'function auditProgressBars'),
 ('in', 'progress_view_js', 'progress-bar-list'),
 ('in', 'progress_view_js', 'diagnostics-progress-bars'),
 ('in', 'progress_view_js', 'report_step_total'),
 ('in', 'progress_view_js', 'role", "progressbar'),
 ('in', 'progress_view_js', 'function renderProgressDetails'),
 ('in', 'progress_view_js', 'function renderProgressEvidence'),
 ('in', 'progress_view_js', 'const formatters = window.mediaPipelineFormatters || {}'),
 ('in', 'progress_view_js', 'const formatProgressValue = typeof formatters.formatProgressValue'),
 ('in', 'progress_view_js', 'function progressEvidenceRows'),
 ('in', 'progress_view_js', 'function progressFfmpegPayload'),
 ('in', 'progress_view_js', 'desktop_ffmpeg_progress.v1'),
 ('in', 'progress_view_js', 'FFmpeg progress proof'),
 ('in', 'progress_view_js', 'function progressEtaPayload'),
 ('in', 'progress_view_js', 'desktop_eta.v1'),
 ('in', 'progress_view_js', 'ETA'),
 ('in', 'progress_view_js', 'Progress evidence board:'),
 ('in',
  'progress_view_js',
  'Progress explains current activity; it is not publish, completion, or output-integrity proof.'),
 ('in', 'progress_view_js', 'Mutation guardrail: this board is read-only'),
 ('in', 'progress_view_js', 'function renderDiagnosticsProgress'),
 ('in', 'progress_view_js', 'function diagnosticsProgressRows'),
 ('in', 'progress_view_js', 'progressFfmpegSummaryLine'),
 ('in', 'progress_view_js', 'Stale progress warning:'),
 ('in', 'progress_view_js', 'Runtime progress looks older than the current backend state'),
 ('in', 'progress_view_js', 'Stale progress review'),
 ('in', 'progress_view_js', 'Mutation guardrail: this table is read-only'),
 ('in', 'progress_view_js', 'function renderPipelineEvents'),
 ('in', 'progress_view_js', 'function renderHomeActiveWork'),
 ('not_in', 'progress_view_js', 'window.renderAuditProgressInto = renderAuditProgressInto'),
 ('not_in', 'progress_view_js', 'window.renderPipelineEvents = renderPipelineEvents'),
 ('not_in', 'progress_view_js', 'window.renderHomeActiveWork = renderHomeActiveWork'),
 ('not_in', 'progress_view_js', 'window.renderLiveRunStrip = renderLiveRunStrip'),
 ('in', 'progress_view_js', 'function activeWorkNextStep'),
 ('in', 'progress_view_js', 'CurrentStagePercent'),
 ('in', 'progress_view_js', 'ActiveJobs:'),
 ('in', 'progress_view_js', 'Inspect Progress Details, Diagnostics > ActiveJobs, and Run Logs'),
 ('in', 'progress_view_js', 'No pipeline events loaded.'),
 ('not_in', 'launch_view_preflight_js', 'function renderLaunchAuditProgress'),
 ('not_in', 'launch_view_preflight_js', 'audit-launch-progress-bars'),
 ('in', 'js', 'window.mediaPipelineReportsView?.initReportsViewEvents?.();'),
 ('not_in', 'js', 'if (typeof initReportsViewEvents === "function") initReportsViewEvents();'),
 ('in', 'js', 'window.mediaPipelineScheduleView?.initScheduleViewEvents?.();'),
 ('not_in', 'js', 'if (typeof initScheduleViewEvents === "function") initScheduleViewEvents();'),
 ('in', 'js', 'const maintenanceView = window.mediaPipelineMaintenanceView || {}'),
 ('in', 'js', 'maintenanceView.initMaintenanceViewEvents?.();'),
 ('in', 'js', 'maintenanceView.runReleaseDryRun?.()'),
 ('in', 'js', 'maintenanceView.runBackfillDryRun?.()'),
 ('not_in', 'js', 'if (typeof initMaintenanceViewEvents === "function") initMaintenanceViewEvents();'),
 ('in', 'contract_view_js', 'window.mediaPipelineContractView'),
 ('in', 'contract_view_js', 'function renderContract'),
 ('in', 'contract_view_js', 'function renderContractRows'),
 ('in', 'contract_view_js', 'function contractSafetyReviewRows'),
 ('in', 'contract_view_js', 'function renderContractSafetyReview'),
 ('in', 'contract_view_js', 'function initContractViewEvents'),
 ('not_in', 'contract_view_js', 'window.initContractViewEvents = initContractViewEvents'),
 ('in', 'contract_view_js', 'Mutation guardrail: WebView controls must use backend-owned routes'),
 ('in', 'contract_view_js', 'Contract safety review:'),
 ('in', 'contract_view_js', 'Decision rule: blocked rows must be fixed before trusting new WebView controls'),
 ('in', 'contract_view_js', 'Network lifecycle boundary'),
 ('in',
  'contract_view_js',
  'Use backend dry-run lifecycle checks first; confirmed Network lifecycle routes remain provider-guarded'),
 ('in', 'contract_view_js', 'Repair/reconcile boundary'),
 ('in', 'contract_view_js', 'Backend dry-runs exist for evidence review; mutation controls remain forbidden'),
 ('in', 'contract_view_js', 'backend dry-runs exist but mutation controls remain forbidden'),
 ('in', 'contract_view_js', 'Dry-run contract fields'),
 ('in', 'contract_view_js', 'Rollback journal fields'),
 ('in', 'contract_view_js', 'Source policy: source media mutation'),
 ('in', 'contract_view_js', 'Route exposure gates'),
 ('in', 'contract_view_js', 'repair_reconcile_contracts'),
 ('in', 'contract_view_js', 'repair_reconcile_summary'),
 ('in', 'contract_view_js', 'network_lifecycle_contracts'),
 ('in', 'contract_view_js', 'network_lifecycle_summary'),
 ('in',
  'contract_view_js',
  'WebView shells must keep tokens on all read, command, open, process, settings, rename, and publish routes'),
 ('in', 'contract_view_js', 'Frontend code stages intent and displays results only'),
 ('in', 'contract_view_js', 'this panel is read-only'),
 ('in', 'contract_view_js', 'Operator safety: this is a guarded backend-owned action'),
 ('in', 'contract_view_js', 'Route contract JSON'),
 ('in', 'contract_view_js', 'jsonDetailText({'),
 ('in', 'contract_view_js', 'formats already-loaded route data only'),
 ('namespace', 'contract_view_js', 'mediaPipelineContractView', 'contractSafetyReviewRows'),
 ('in', 'contract_view_js', 'api-contract-rows'),
 ('in', 'contract_view_js', 'api-contract-safety-rows'),
 ('in', 'contract_view_js', 'api-contract-detail'),
 ('in', 'contract_view_js', 'allowed_row_scopes'),
 ('in', 'contract_view_js', 'Allowed row scopes:'),
 ('not_in', 'progress_view_js', 'window.renderProgressBarsInto ='),
 ('not_in', 'progress_view_js', 'window.renderProgressBars ='),
 ('not_in', 'progress_view_js', 'window.renderProgressDetails ='),
 ('not_in', 'progress_view_js', 'window.renderProgressEvidence ='))


class ApplicationFacadeWebStaticDiagnosticsReportsTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.bundle = served_webview_static_contract_bundle()

    def test_operations_dom_contracts_are_static_pinned(self) -> None:
        _run_static_assertions(self, self.bundle, OPERATIONS_DOM_ASSERTIONS)
        self.assertEqual(self.bundle.html.count('data-evidence-toggle-exempt="true"'), 0)

    def test_network_contract_is_backend_owned(self) -> None:
        _run_static_assertions(self, self.bundle, NETWORK_ASSERTIONS)

    def test_diagnostics_contracts_are_backend_owned(self) -> None:
        _run_static_assertions(self, self.bundle, DIAGNOSTICS_ASSERTIONS)

    def test_reports_schedule_and_maintenance_contracts_are_static_pinned(self) -> None:
        _run_static_assertions(self, self.bundle, REPORTS_SCHEDULE_MAINTENANCE_ASSERTIONS)

    def test_telemetry_progress_and_contract_views_are_static_pinned(self) -> None:
        _run_static_assertions(self, self.bundle, TELEMETRY_PROGRESS_CONTRACT_ASSERTIONS)


if __name__ == "__main__":
    unittest.main()
