from __future__ import annotations

import unittest

from tests.python.desktop.application_facade_test_support import (
    assert_namespace_export as _assert_namespace_export,
    served_webview_static_contract_bundle,
)

AssertionRow = tuple[str, ...]


def _run_static_assertions(testcase: unittest.TestCase, bundle: object, rows: tuple[AssertionRow, ...]) -> None:
    for row in rows:
        kind, target, *payload = row
        with testcase.subTest(kind=kind, target=target, payload=payload):
            text = getattr(bundle, target)
            if kind == "in":
                testcase.assertIn(payload[0], text)
            elif kind == "not_in":
                testcase.assertNotIn(payload[0], text)
            elif kind == "namespace":
                _assert_namespace_export(testcase, text, payload[0], payload[1])
            else:  # pragma: no cover - protects future test data edits.
                raise AssertionError(f"unknown assertion kind: {kind}")

CROSS_PAGE_DOM_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'html', '/assets/crossPageContextView.conflict.js'),
 ('in', 'html', '/assets/crossPageContextView.sample.js'),
 ('in', 'html', '/assets/crossPageContextView.settings.js'),
 ('in', 'html', '/assets/crossPageContextView.sampleValidation.worksheet.js'),
 ('in', 'html', '/assets/crossPageContextView.sampleValidation.runbook.js'),
 ('in', 'html', '/assets/crossPageContextView.sampleValidation.records.js'),
 ('in', 'html', '/assets/crossPageContextView.sampleValidation.js'),
 ('in', 'html', '/assets/crossPageContextView.js'),
 ('in', 'html', 'id="cross-page-context-status"'),
 ('in', 'html', 'id="cross-page-context-summary"'),
 ('in', 'html', 'id="cross-page-conflict-status"'),
 ('in', 'html', 'id="cross-page-conflict-rows"'),
 ('in', 'html', 'id="cross-page-sample-status"'),
 ('in', 'html', 'id="cross-page-sample-rows"'),
 ('in', 'html', 'Evidence Correlation'),
 ('in', 'html', 'id="cross-page-validation-template-status"'),
 ('in', 'html', 'id="cross-page-validation-template"'),
 ('in', 'html', 'Validation Template'),
 ('in', 'html', 'id="cross-page-real-media-status"'),
 ('in', 'html', 'id="cross-page-real-media-summary"'),
 ('in', 'html', 'id="cross-page-real-media-rows"'),
 ('in', 'html', 'id="cross-page-real-media-detail"'),
 ('in', 'html', 'Validation Worksheet'),
 ('in', 'html', 'data-cross-page-target="queue"'))

CROSS_PAGE_CONTEXT_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'app_layout_manager_js', 'function _storedOrderMatchesCurrentPanels'),
 ('in', 'app_layout_manager_js', 'page.dataset.layoutOrderStatus = "schema-reset"'),
 ('in', 'app_layout_manager_js', 'newly added panels appear at their authored default position'),
 ('in', 'app_layout_manager_js', 'function _showLayoutDragHint'),
 ('in', 'app_layout_manager_js', 'Still gated. Click Advanced to make this panel always visible.'),
 ('in', 'cross_page_context_view_js', 'window.mediaPipelineCrossPageContextView'),
 ('in', 'cross_page_context_view_js', 'function renderCrossPageContext'),
 ('in', 'cross_page_context_view_js', 'function crossPageContextLines'),
 ('in', 'cross_page_context_view_js', 'function crossPageInvestigationOrder'),
 ('in', 'cross_page_conflict_js', 'window.__crossPageConflictModule'),
 ('in', 'cross_page_context_view_js', 'const __conflictMod = window.__crossPageConflictModule || {}'),
 ('in', 'cross_page_context_view_js', 'delete window.__crossPageConflictModule'),
 ('in', 'cross_page_conflict_js', 'function renderCrossPageConflictBoard'),
 ('in', 'cross_page_conflict_js', 'function crossPageConflictRows'),
 ('in', 'cross_page_conflict_js', 'function crossPageConflictSummary'),
 ('in', 'cross_page_sample_js', 'window.__crossPageSampleModule'),
 ('in', 'cross_page_context_view_js', 'const __sampleMod = window.__crossPageSampleModule || {}'),
 ('in', 'cross_page_context_view_js', 'delete window.__crossPageSampleModule'),
 ('in', 'cross_page_sample_js', 'function renderCrossPageSampleCorrelation'),
 ('in', 'cross_page_sample_js', 'function crossPageSampleRows'),
 ('in', 'cross_page_sample_js', 'function crossPageSampleEvidenceForSeed'),
 ('in', 'cross_page_sample_js', 'function crossPageValidationTemplateLines'),
 ('in', 'cross_page_sample_js', 'function renderCrossPageValidationTemplate'),
 ('in', 'cross_page_settings_js', 'window.__crossPageSettingsModule'),
 ('in', 'cross_page_context_view_js', 'const __settingsMod = window.__crossPageSettingsModule || {}'),
 ('in', 'cross_page_context_view_js', 'delete window.__crossPageSettingsModule'),
 ('in', 'cross_page_settings_js', 'function crossPageSettingsPolicyEvidence'),
 ('in', 'cross_page_sample_validation_js', 'function crossPageSampleValidationEvidence'),
 ('in', 'cross_page_sample_validation_js', 'function crossPageRealMediaWorksheetRows'),
 ('in', 'cross_page_sample_validation_js', 'function crossPageRealMediaWorksheetStatus'),
 ('in', 'cross_page_sample_validation_js', 'function renderCrossPageRealMediaWorksheet'),
 ('in', 'cross_page_sample_js', 'Filename-only match; compare folders before trusting it.'),
 ('in', 'cross_page_sample_js', 'Completed output/sidecar proof is not exact-matched yet.'),
 ('in', 'cross_page_sample_js', 'No cross-page evidence for this sample is visible in loaded payloads.'),
 ('in', 'cross_page_sample_js', 'Real-media validation log template:'),
 ('in', 'cross_page_sample_validation_js', 'Real-media validation worksheet:'),
 ('in',
  'cross_page_sample_validation_js',
  'Queue route intent, Completed output proof, Pending Publish final-destination proof'),
 ('in', 'cross_page_sample_validation_js', 'Sample Validation evidence posture'),
 ('in', 'cross_page_sample_validation_js', 'Sample Validation readiness'),
 ('in', 'cross_page_sample_validation_js', 'Sample Validation is evidence-only'),
 ('in', 'cross_page_sample_validation_js', 'Sample validation:'),
 ('in', 'cross_page_sample_validation_js', 'Saved media policy'),
 ('in', 'cross_page_sample_validation_js', 'This worksheet is read-only'),
 ('in',
  'cross_page_sample_validation_js',
  'Boundary: this worksheet does not save, accept, repair, rerun, drain, delete, publish, rename, rewrite manifests, '
  'or touch media files.'),
 ('in', 'cross_page_sample_js', 'Generated from loaded WebView payloads only.'),
 ('in', 'cross_page_sample_js', 'use the backend-owned Sample Validation Record panel below'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationCheckedSummary'),
 ('in', 'cross_page_sample_validation_js', 'SAMPLE_VALIDATION_CHECK_FIELDS'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationMergedChecks'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationShellSurface'),
 ('in', 'cross_page_sample_validation_js', 'shell: sampleValidationShellSurface()'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationRecordComparisonRowsForPaths'),
 ('in', 'cross_page_sample_validation_js', 'function syncSampleValidationCheckControls'),
 ('in', 'cross_page_sample_validation_js', 'Manual sample-validation checks cleared'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationLogSummaryLines'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationAuditSummaryLines'),
 ('in', 'cross_page_sample_validation_js', 'Real-media validation audit:'),
 ('in', 'cross_page_sample_validation_js', 'Boundary: validation audit is read-only'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationPolicyAlignmentSummaryLines'),
 ('in', 'cross_page_sample_validation_js', 'Real-media policy alignment:'),
 ('in', 'cross_page_sample_validation_js', 'Read-only real-media policy alignment'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationReadinessLines'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationReconciliationLines'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationGapSummaryLines'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationGapSummary'),
 ('in', 'cross_page_sample_validation_js', 'Real-media evidence gap summary:'),
 ('in', 'cross_page_sample_validation_js', 'Read-only real-media evidence-gap summary'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationRunbookSummaryLines'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationRunbook'),
 ('in', 'cross_page_sample_validation_js', 'Real-media pilot runbook:'),
 ('in', 'cross_page_sample_validation_js', '# Real-Media WebView Pilot Runbook'),
 ('in', 'cross_page_sample_validation_js', 'Read-only real-media pilot runbook'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationExecutionRows'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationExecutionChecklist'),
 ('in', 'cross_page_sample_validation_js', 'Operator-selected real-media sample execution:'),
 ('in', 'cross_page_sample_validation_js', 'Proposed evidence coverage:'),
 ('in', 'cross_page_sample_validation_js', 'Backend readiness:'),
 ('in', 'cross_page_sample_validation_js', 'Readiness next action:'),
 ('in', 'cross_page_sample_validation_js', 'Current evidence reconciliation:'),
 ('in', 'cross_page_sample_validation_js', 'Append readiness:'),
 ('in', 'cross_page_sample_validation_js', 'Post-run evidence capture:'),
 ('in', 'cross_page_sample_validation_js', 'Copyable post-run Markdown:'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationCompletedPacketRows'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationCompletedPolicyReconciliationRow'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationCompletedPolicyReconciliationStatus'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationCompletedPacketHandoff'),
 ('in', 'cross_page_sample_validation_js', 'Completed evidence handoff for Sample Validation:'),
 ('in', 'cross_page_sample_validation_js', 'Saved-policy reconciliation:'),
 ('in',
  'cross_page_context_view_js',
  'window.sampleValidationCompletedPolicyReconciliationRow = sampleValidationCompletedPolicyReconciliationRow'),
 ('in', 'cross_page_sample_validation_js', 'Decision rule: keep Sample Validation at hold/review'),
 ('namespace',
  'cross_page_context_view_js',
  'mediaPipelineCrossPageContextView',
  'renderSampleValidationCompletedPacketHandoff'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationAcceptanceGateRows'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationAcceptanceGate'),
 ('in', 'cross_page_sample_validation_js', 'Sample Validation acceptance readiness gate:'),
 ('in', 'cross_page_sample_validation_js', 'Saved policy reconciliation'),
 ('in', 'cross_page_sample_validation_js', 'Missing visible category tokens are review gaps'),
 ('in', 'cross_page_sample_validation_js', 'Decision rule: accepted sample evidence should not be appended'),
 ('namespace',
  'cross_page_context_view_js',
  'mediaPipelineCrossPageContextView',
  'renderSampleValidationAcceptanceGate'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationRecordReviewRows'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationRecordReview'),
 ('in', 'cross_page_sample_validation_js', 'Accepted sample-validation record proof review:'),
 ('in', 'cross_page_sample_validation_js', 'Decision rule: treat accepted records as current proof only'),
 ('namespace', 'cross_page_context_view_js', 'mediaPipelineCrossPageContextView', 'renderSampleValidationRecordReview'),
 ('in', 'cross_page_sample_validation_js', 'function sampleValidationCategorySummaryRows'),
 ('in', 'cross_page_sample_validation_js', 'function renderSampleValidationCategorySummary'),
 ('in', 'cross_page_sample_validation_js', 'Pilot category validation summary:'),
 ('in',
  'cross_page_sample_validation_js',
  'Decision rule: a category is ready only when an accepted validation record'),
 ('namespace',
  'cross_page_context_view_js',
  'mediaPipelineCrossPageContextView',
  'renderSampleValidationCategorySummary'),
 ('in', 'cross_page_sample_validation_js', 'Read-only post-run evidence capture packet'),
 ('in', 'cross_page_sample_validation_js', 'Required acceptance gaps:'),
 ('in', 'cross_page_sample_validation_js', 'Recommended review gaps:'),
 ('in', 'cross_page_sample_validation_js', 'Read-only append-readiness advice'),
 ('in', 'cross_page_sample_validation_js', 'Reconciliation is read-only'),
 ('in', 'cross_page_sample_validation_js', 'Sample validation records are notes/evidence only'),
 ('in', 'cross_page_sample_js', 'Queue route/remux-vs-encode reason checked'),
 ('in',
  'cross_page_sample_js',
  'this template does not save, accept, repair, rerun, drain, delete, publish, rewrite manifests, or touch media '
  'files'),
 ('in', 'cross_page_context_view_js', 'Operator investigation order:'),
 ('in', 'cross_page_context_view_js', 'Diagnostics: resolve refresh failures'),
 ('in', 'cross_page_context_view_js', 'Pending Publish: review do-not-drain'),
 ('in', 'cross_page_context_view_js', 'Launch: start backend-owned processing'),
 ('in', 'cross_page_context_view_js', 'Exact-match cross-checks:'),
 ('in', 'cross_page_context_view_js', 'Queued source also in Completed source history:'),
 ('in', 'cross_page_context_view_js', 'Pending destination also in Completed output history:'),
 ('in', 'cross_page_conflict_js', 'Cross-page conflict board:'),
 ('in', 'cross_page_conflict_js', 'same-leaf rows are duplicate-title hints only'),
 ('in', 'cross_page_context_view_js', 'Completed has missing-output rows while Pending Publish is empty.'),
 ('in',
  'cross_page_context_view_js',
  'Missing-output posture: Completed reports missing outputs while Pending Publish is empty'),
 ('in', 'cross_page_conflict_js', 'queued-source-pending-publish'),
 ('in',
  'cross_page_context_view_js',
  'Mutation guardrail: this panel does not start, repair, rerun, drain, delete, or rewrite files.'),
 ('in', 'queue_view_js', 'function queueWorkflowStatus'),
 ('in', 'queue_view_js', 'function queueWorkflowLines'),
 ('in', 'queue_view_js', 'function queueReviewStatus'),
 ('in', 'queue_view_js', 'Flagged rows:'),
  ('in', 'queue_view_js', 'QUEUE_READ_ONLY_BOUNDARY'),
 ('in', 'queue_view_js', 'Cross-page workflow: Queue'),
 ('in', 'queue_view_js', 'backend launch commands remain backend-owned'),
 ('in', 'queue_view_js', 'Diagnostics > State Artifact Summary, Queue Snapshot'),
 ('in', 'queue_view_js', 'appendDiagnosticsBridgeButton(container, actions'),
 ('in', 'queue_view_js', 'Diagnostics bridge: Review in Diagnostics switches'),
 ('in', 'completed_view_review_js', 'function completedWorkflowStatus'),
 ('in', 'completed_view_review_js', 'function completedWorkflowLines'),
 ('in', 'completed_view_review_js', 'function completedReviewStatus'),
 ('in', 'completed_view_review_js', 'Flagged rows:'),
  ('in', 'completed_view_review_js', 'COMPLETED_READ_ONLY_BOUNDARY'),
 ('in', 'completed_view_review_js', 'Cross-page workflow: Completed'),
 ('in', 'completed_view_review_js', 'check Pending Publish before rerun'),
  ('in', 'completed_view_review_js', 'COMPLETED_READ_ONLY_BOUNDARY'),
 ('in', 'completed_view_diagnostics_js', 'appendDiagnosticsBridgeButton(container, actions'),
 ('in', 'completed_view_diagnostics_js', 'Diagnostics bridge: Review in Diagnostics switches'),
 ('in', 'pending_publish_view_js', 'function pendingWorkflowStatus'),
 ('in', 'pending_publish_view_js', 'function pendingWorkflowLines'),
 ('in', 'pending_publish_view_js', 'function pendingReviewStatus'),
 ('in', 'pending_publish_view_js', 'Flagged rows:'),
  ('in', 'pending_publish_view_js', 'PENDING_READ_ONLY_BOUNDARY'),
 ('in', 'pending_publish_view_js', 'Cross-page workflow: Pending Publish'),
 ('in', 'pending_publish_view_js', 'Drain Parked Outputs remains backend-owned'),
 ('not_in', 'pending_publish_diagnostics_js', 'appendDiagnosticsBridgeButton(container, actions'),
 ('not_in', 'pending_publish_diagnostics_js', 'Diagnostics bridge: Review in Diagnostics switches'))

APP_SHELL_WORKFLOW_ASSERTIONS: tuple[AssertionRow, ...] = (('in', 'css_components', 'tr[data-status="changed"]'),
 ('in', 'css_components', 'tr[data-status="unknown"]'),
 ('in', 'css_components', 'tr[data-status="unchanged"]'),
 ('in', 'css_components', '.panel-heading strong[data-state="blocked"]'),
 ('in', 'css_components', '.panel-heading strong[data-state="ready"]'),
 ('in', 'css_layout', '.close-readiness'),
 ('in', 'css_layout', '.close-readiness[data-state="blocked"]'),
 ('in', 'css_layout', '.refresh-health'),
 ('in', 'css_layout', '.refresh-health[data-state="warning"]'),
 ('in', 'css_layout', '.refresh-health[data-state="updating"]'),
 ('in', 'dom_helpers_js', 'function selectedRowAtAGlanceLines'),
 ('in', 'dom_helpers_js', 'selectedRowAtAGlanceLines,'),
 ('in', 'dom_helpers_js', 'function reviewFlagExplanationLines'),
 ('in', 'dom_helpers_js', 'reviewFlagExplanationLines,'),
 ('in', 'dom_helpers_js', 'expected output proof is missing'),
 ('in', 'dom_helpers_js', 'translate already-loaded backend markers'),
 ('in', 'dom_helpers_js', 'function selectedRowDetailDrawerLines'),
 ('in', 'dom_helpers_js', 'selectedRowDetailDrawerLines,'),
 ('in', 'dom_helpers_js', 'function payloadFreshnessLines'),
 ('in', 'dom_helpers_js', 'payloadFreshnessLines,'),
 ('in', 'dom_helpers_js', 'function renderOpenTargetActionGroups'),
 ('in', 'dom_helpers_js', 'renderOpenTargetActionGroups,'),
 ('in', 'js', 'Object.defineProperty(payload, "__mediaPipelineRefreshMeta"'),
 ('in', 'js', 'function initPageRefreshButtons'),
 ('in', 'js', '[data-page-refresh-button]'),
 ('in', 'html', 'id="completed-refresh-current-output-button"'),
 ('in', 'html', 'data-page-refresh-button="pending"'),
 ('in', 'html', 'data-page-refresh-button="diagnostics"'),
 ('in', 'queue_view_summary_js', 'payloadFreshnessLines({'),
 ('in', 'queue_view_summary_js', 'label: "Queue"'),
 ('in', 'completed_view_js', 'payloadFreshnessLines({'),
 ('in', 'completed_view_js', 'label: "Output"'),
 ('in', 'pending_publish_view_js', 'payloadFreshnessLines({'),
 ('in', 'pending_publish_view_js', 'label: "Pending Publish"'),
 ('in', 'diagnostics_view_js', 'payloadFreshnessLines({'),
 ('in', 'diagnostics_view_js', 'label: "Diagnostics"'),
 ('in', 'diagnostics_state_summary_view_js', 'payloadFreshnessLines({'),
 ('in', 'diagnostics_state_summary_view_js', 'label: "Diagnostics State"'),
 ('in', 'js', '/api/snapshot'),
 ('in', 'js', '/api/backend/close-readiness'),
 ('in', 'js', '/api/backend/shutdown'),
 ('in', 'js', 'function renderBackendLifecycle'),
 ('in', 'js', 'function requestBackendShutdown'),
 ('in', 'js', 'function renderBackendLifecycleHistory'),
 ('in', 'js', 'function backendLifecycleCommandEntries'),
 ('in', 'js', 'function initEvidenceToggle'),
 ('in', 'js', 'mediapipeline-evidence-hidden'),
 ('in', 'js', 'document.body.classList.toggle("evidence-hidden", hidden)'),
 ('in', 'js', 'initEvidenceToggle()'),
 ('in', 'js', 'function keyboardShortcutRegistry'),
 ('in', 'js', 'function focusActivePageSearch'),
 ('in', 'js', 'function clearActivePageFilters'),
 ('in', 'js', 'function moveActivePageSelection'),
 ('in', 'js', 'function focusActivePageDetail'),
 ('in', 'js', 'Read-only shortcuts. They navigate, refresh, filter, focus, or select rows'),
 ('in', 'js', 'key: "/"'),
 ('in', 'js', 'key: "c"'),
 ('in', 'js', 'key: "j"'),
 ('in', 'js', 'key: "k"'),
 ('in', 'js', 'key: "d"'),
 ('in', 'js', 'function closeReadinessWatcherSummary'),
 ('in', 'js', 'Continuous watcher:'),
 ('in', 'js', 'Watcher note: keep the backend alive'),
 ('in', 'js', 'Another backend shutdown command is already in progress.'),
 ('in', 'js', 'WebView exposes backend shutdown only when the loaded close-readiness payload reports safe.'),
 ('in', 'js', 'Lifecycle command history is evidence only'),
 ('in',
  'css_components',
  'body.evidence-hidden .panel[data-panel-type="evidence"]:not([data-evidence-toggle-exempt="true"])'),
 ('in', 'js', '/api/diagnostics/state-summary'),
 ('in', 'js', '/api/commands'),
 ('in', 'contract_view_js', '/api/contract'),
 ('in', 'js', '/api/completed'),
 ('in', 'js', '/api/failures'),
 ('in', 'js', '/api/audit-results'),
 ('in', 'js', '/api/pending-publish'),
 ('in', 'js', '/api/schedule'),
 ('in', 'js', '/api/settings/workspace'),
 ('in', 'js', 'window.getLastSnapshot = () => lastSnapshot'),
 ('not_in', 'js', 'renderLaunchAuditProgress(lastSnapshot)'),
 ('in', 'js', 'const pendingPublishPayload = values["pending publish"] || (pendingPublishFailure ? {'),
 ('in',
  'js',
  'if (values["pending publish"] || pendingPublishFailure) renderPendingPublish(pendingPublishPayload, values.snapshot '
  '|| lastSnapshot)'),
 ('in', 'js', 'window.mediaPipelineProgressView?.renderProgressBars?.(Array.isArray(snapshot.progress_bars)'),
 ('in', 'js', 'window.mediaPipelineProgressView?.renderProgressDetails?.(snapshot.progress || {})'),
 ('in', 'js', 'window.mediaPipelineProgressView?.renderDiagnosticsProgress?.(lastSnapshot)'),
 ('in', 'js', 'renderDiagnosticsStateSummaryFn(values["diagnostics state summary"])'),
 ('in', 'js', 'const recentEvents = Array.isArray(snapshot.recent_events)'),
 ('in', 'js', 'mediaPipelineProgressView?.renderPipelineEvents?.(recentEvents)'),
 ('in', 'js', 'renderTopbarEventTicker(snapshot)'),
 ('in', 'js', 'window.setTopbarPendingLaunch = setTopbarPendingLaunch'),
 ('in', 'js', 'const telemetryOptions = {'),
 ('in', 'js', 'refreshIntervalMs: AUTOMATIC_REFRESH_INTERVAL_MS'),
 ('in', 'js', '? renderTelemetrySafely(values.telemetry, telemetryOptions)'),
 ('in', 'js', 'unavailableReason: telemetryFailure?.message || "telemetry route returned no payload"'),
 ('in', 'js', 'renderQueueRows'),
 ('in', 'js', 'const queueStatusFilter = byId("queue-status-filter")'),
 ('in', 'js', 'queueStatusFilter.addEventListener("change", () => window.mediaPipelineQueueView?.renderQueueRows?.())'),
 ('in', 'js', 'const queueInvestigationFilter = byId("queue-investigation-filter")'),
 ('in',
  'js',
  'queueInvestigationFilter.addEventListener("change", () => window.mediaPipelineQueueView?.renderQueueRows?.())'),
 ('in', 'queue_view_js', 'function renderQueueReviewDigest'),
 ('in', 'queue_view_js', 'function queueReviewDigestStatus'),
 ('in', 'html', '<pre id="queue-filter-summary" class="prose-block queue-filter-summary" hidden aria-hidden="true">'),
 ('in', 'queue_view_js', 'summary.hidden = true'),
 ('in', 'html', 'queue-status-filter'),
 ('in', 'html', 'queue-investigation-filter'),
 ('in', 'html', 'queue-selected-status'),
 ('in', 'html', 'queue-selected-summary'),
 ('in', 'queue_view_js', 'function queueTableRowStatus'),
 ('in', 'queue_view_js', 'function queueMatchesInvestigationFilter'),
 ('in', 'queue_view_js', 'function queueIsHiddenSidecarBlockedRow'),
 ('in', 'queue_view_js', 'Hidden subtitle sidecars'),
 ('in', 'queue_view_js', 'function queueInvestigationFilterLabel'),
 ('in', 'queue_view_js', 'function renderQueueSelectedAtAGlance'),
 ('in', 'queue_view_js', 'function queueSelectedAtAGlanceLines'),
 ('in', 'queue_view_js', 'window.mediaPipelineDom?.selectedRowAtAGlanceLines'),
 ('in', 'queue_view_js', 'window.mediaPipelineDom?.selectedRowDetailDrawerLines'),
 ('in', 'queue_view_js', 'Queue selected-row detail'),
 ('in', 'queue_view_js', 'reviewFlagExplanationLines(reviewFlags'),
 ('in', 'queue_view_js', 'No Queue review flags were reported for this row.'),
  ('in', 'queue_view_js', 'QUEUE_READ_ONLY_BOUNDARY'),
 ('in', 'queue_view_js', 'byId("queue-status-filter")'),
 ('in', 'queue_view_js', 'byId("queue-investigation-filter")'),
 ('in', 'queue_view_js', 'filterResultSummaryLines'),
 ('in', 'queue_view_js', 'buildFilterSummary({'),
 ('in', 'queue_view_js', 'filterRowsByInvestigation(statusRows, investigationFilter, queueMatchesInvestigationFilter)'),
 ('in', 'queue_view_js', '${renderedCount} shown / ${rows.length} filtered / ${state.rows.length} rows'),
 ('in', 'queue_view_js', 'decisionName: "launch"'),
 ('in', 'queue_view_js', 'Queue review rows'),
 ('in', 'queue_view_js', 'selectQueueRow(item)'),
 ('in', 'js', 'renderCompleted'),
 ('in', 'js', 'renderCompletedRows'),
 ('in', 'html', 'completed-inventory-progress-bars'),
 ('in', 'completed_view_status_boards_js', 'function renderCompletedInventoryProgress'),
 ('in', 'completed_view_status_boards_js', 'function completedInventoryProgressBars'),
 ('in', 'completed_view_status_boards_js', 'renderProgressBarsInto("completed-inventory-progress-bars"'),
 ('in', 'js', '"/api/completed?limit=500"'),
 ('in', 'js', '"/api/completed?limit=500&force_refresh=true&proof=bounded"'),
 ('in', 'js', 'const completedStatusFilter = byId("completed-status-filter")'),
 ('in',
  'js',
  'completedStatusFilter.addEventListener("change", () => window.mediaPipelineCompletedView?.renderCompletedRows?.())'),
 ('in', 'js', 'const completedLibraryFilter = byId("completed-library-filter")'),
 ('in',
  'js',
  'completedLibraryFilter.addEventListener("change", () => '
  'window.mediaPipelineCompletedView?.renderCompletedRows?.())'),
 ('in', 'js', 'const completedInvestigationFilter = byId("completed-investigation-filter")'),
 ('in',
  'js',
  'completedInvestigationFilter.addEventListener("change", () => '
  'window.mediaPipelineCompletedView?.renderCompletedRows?.())'),
 ('in', 'js', 'const completedHistoryFilter = byId("completed-history-filter")'),
 ('in', 'js', 'const completedHistoryStatusFilter = byId("completed-history-status-filter")'),
 ('in', 'js', 'const completedHistoryInvestigationFilter = byId("completed-history-investigation-filter")'),
 ('in', 'completed_view_review_js', 'function renderCompletedReviewDigest'),
 ('in', 'completed_view_review_js', 'function completedReviewDigestStatus'),
 ('in', 'html', 'completed-filter-summary'),
 ('in', 'html', 'completed-status-filter'),
 ('in', 'html', 'completed-library-filter'),
 ('in', 'html', 'completed-investigation-filter'),
 ('in', 'html', 'completed-history-filter-summary'),
 ('in', 'html', 'completed-history-status-filter'),
 ('in', 'html', 'completed-history-investigation-filter'),
 ('in', 'html', 'completed-selected-status'),
 ('in', 'html', 'completed-selected-summary'),
 ('in', 'html', 'completed-raw-detail'),
 ('in', 'html', 'id="completed-selected-summary" class="completed-selected-summary"'),
 ('in', 'html', 'Raw selected-row detail'),
 ('in', 'completed_view_review_js', 'function completedTableRowStatus'),
 ('in', 'completed_view_review_js', 'function completedHasSmallHealthySizeDelta'),
 ('in', 'completed_view_review_js', 'function completedMatchesInvestigationFilter'),
 ('in', 'completed_view_review_js', 'function completedInvestigationFilterLabel'),
 ('in', 'completed_view_review_js', 'function renderCompletedSelectedAtAGlance'),
 ('in', 'completed_view_review_js', 'function completedSelectedAtAGlanceLines'),
 ('in', 'completed_view_review_js', 'function completedSelectedSummaryNodes'),
 ('in', 'completed_view_review_js', 'summaryNode.replaceChildren'),
 ('in', 'completed_view_review_js', 'completed-selected-decision-strip'),
 ('in', 'completed_view_review_js', 'function completedSelectedDiagnosisLine'),
 ('in', 'completed_view_review_js', 'function completedSelectedEvidenceGaps'),
 ('in', 'completed_view_review_js', 'function completedSelectedNextChecks'),
 ('in', 'completed_view_review_js', 'Why this output looks different'),
 ('in', 'completed_view_review_js', 'Trigger / route reason'),
 ('in', 'completed_view_review_js', 'Runtime/log evidence'),
 ('in', 'completed_view_review_js', 'What to check next'),
 ('in', 'completed_view_review_js', 'window.mediaPipelineDom?.selectedRowAtAGlanceLines'),
 ('in', 'completed_view_selection_js', 'selectedRowDetailDrawerLines'),
 ('in', 'completed_view_selection_js', 'Completed selected-row detail'),
 ('in', 'completed_view_review_js', 'reviewFlagExplanationLines(reviewMarkers'),
 ('in', 'completed_view_review_js', 'No Completed review flags or consistency issues were reported for this row.'),
  ('in', 'completed_view_review_js', 'COMPLETED_READ_ONLY_BOUNDARY'),
 ('in', 'completed_view_filters_js', 'byId("completed-status-filter")'),
 ('in', 'completed_view_filters_js', 'byId("completed-library-filter")'),
 ('in', 'completed_view_filters_js', 'byId("completed-investigation-filter")'),
 ('in', 'completed_view_filters_js', 'byId("completed-history-status-filter")'),
 ('in', 'completed_view_filters_js', 'byId("completed-history-investigation-filter")'),
 ('in', 'completed_view_table_js', 'filterResultSummaryLines({'),
 ('in',
  'completed_view_filters_js',
  'filterRowsByInvestigation(statusRows, investigationFilter, completedMatchesInvestigationFilter)'),
 ('in', 'completed_view_filters_js', 'function completedLibraryMatchesFilter'),
 ('in', 'completed_view_filters_js', '${renderedRows} shown / ${visibleRows} filtered / ${totalRows} rows'),
 ('in', 'completed_view_table_js', 'filtering Current Output Status does not mark outputs accepted'),
 ('in', 'completed_view_table_js', 'filtering Completed history does not mark outputs accepted'),
 ('in', 'completed_view_review_js', 'Completed review rows'),
 ('in', 'completed_view_table_js', 'ctx.selectCompletedRow(item)'),
 ('in', 'js', 'requestCompletedOpen'),
 ('in', 'pending_publish_view_js', 'function renderPendingRows'),
 ('in', 'pending_publish_view_js', 'const statusFilter = byId("pending-status-filter")'),
 ('in',
  'pending_publish_view_js',
  'statusFilter.addEventListener("change", renderPendingRows)'),
 ('in', 'pending_publish_view_js', 'const investigationFilter = byId("pending-investigation-filter")'),
 ('in',
  'pending_publish_view_js',
  'investigationFilter.addEventListener("change", renderPendingRows)'),
 ('in', 'pending_publish_view_js', 'function renderPendingReviewDigest'),
 ('in', 'pending_publish_view_js', 'function pendingReviewDigestStatus'),
 ('in', 'html', 'pending-filter-summary'),
 ('in', 'html', 'pending-inventory-progress-bars'),
 ('in', 'pending_publish_view_js', 'function renderPendingInventoryProgress'),
 ('in', 'pending_publish_view_js', 'function pendingInventoryProgressBars'),
 ('in', 'pending_publish_view_js', 'renderProgressBarsInto("pending-inventory-progress-bars"'),
 ('in', 'html', 'pending-file-inventory-status'),
 ('in', 'html', 'pending-file-inventory-summary'),
 ('in', 'html', 'pending-file-inventory-rows'),
 ('in', 'pending_publish_view_js', 'function renderPendingFileInventory'),
 ('in', 'pending_publish_view_js', 'Pending parked file inventory:'),
 ('in', 'pending_publish_view_js', 'directory listing only; file bytes were not read and no files were changed'),
 ('in', 'html', 'pending-status-filter'),
 ('in', 'html', 'pending-investigation-filter'),
 ('in', 'html', 'pending-selected-status'),
 ('in', 'html', 'pending-selected-summary'),
 ('in', 'pending_publish_view_js', 'function pendingTableRowStatus'),
 ('in', 'pending_publish_view_js', 'function pendingMatchesInvestigationFilter'),
 ('in', 'pending_publish_view_js', 'function pendingInvestigationFilterLabel'),
 ('in', 'pending_publish_view_js', 'function renderPendingSelectedAtAGlance'),
 ('in', 'pending_publish_view_js', 'function pendingSelectedAtAGlanceLines'),
  ('in', 'pending_publish_view_js', 'PENDING_READ_ONLY_BOUNDARY'),
 ('in', 'pending_publish_view_js', 'byId("pending-status-filter")'),
 ('in', 'pending_publish_view_js', 'byId("pending-investigation-filter")'),
 ('in', 'pending_publish_view_js', 'filterResultSummaryLines({'),
 ('in',
  'pending_publish_view_js',
  'filterRowsByInvestigation(statusRows, investigationFilter, pendingMatchesInvestigationFilter)'),
 ('in', 'pending_publish_view_js', '${renderedCount} shown / ${rows.length} filtered / ${getLastPendingRows().length} rows'),
 ('in', 'pending_publish_view_js', 'PENDING_READ_ONLY_BOUNDARY'),
 ('in', 'pending_publish_view_js', 'Pending publish review rows'),
 ('in', 'pending_publish_view_js', 'selectPendingRow(item)'),
 ('in', 'launch_view_js', 'startPendingPublishDrain'),
 ('in', 'js', 'window.mediaPipelineSettingsView.initSettingsViewEvents();'),
 ('in', 'js', 'const launchView = window.mediaPipelineLaunchView || {}'),
 ('in', 'js', 'launchView.initLaunchViewEvents?.();'),
 ('in', 'js', 'window.mediaPipelineDiagnosticsView?.initDiagnosticsViewEvents?.();'),
 ('not_in', 'js', '\n  initDiagnosticsViewEvents();'),
 ('in', 'js', 'window.mediaPipelineContractView?.initContractViewEvents?.();'),
 ('not_in', 'js', 'initContractViewEvents();'),
 ('in', 'js', 'window.mediaPipelineSettingsView.renderSettings(values.settings)'),
 ('in', 'js', 'window.mediaPipelineLaunchView?.renderAllLaunchPreflights?.();'),
 ('not_in', 'js', 'window.mediaPipelineLaunchView?.renderLaunchAuditLog?.(values["audit results"])'),
 ('in', 'js', 'window.mediaPipelineReportsView?.renderAuditControls?.(values["audit controls"])'),
 ('not_in', 'js', 'window.mediaPipelineLaunchView?.renderLaunchAuditControls?.(values["audit controls"])'),
 ('in', 'js', 'function showPage'),
 ('in', 'js', 'window.showPage = showPage;'),
 ('in', 'js', 'const crossPageContext = {'),
 ('in', 'js', 'renderCrossPageContext(crossPageContext)'),
 ('in', 'js', 'window.mediaPipelineLaunchView?.renderLaunchRealMediaProofHandoff?.(crossPageContext)'),
 ('in', 'js', 'function renderDailyDriverReadiness'),
 ('in', 'js', 'function dailyDriverRows'),
 ('in', 'js', 'function dailyDriverRealMediaProofRow'),
 ('in', 'js', 'function dailyDriverSummaryLines'),
 ('in', 'js', 'function renderTopbarActivity'),
 ('in', 'js', 'function topbarCurrentWorkMeta'),
 ('in', 'js', 'activity-meta'),
 ('in', 'js', 'topbarCleanCurrentName'),
 ('not_in', 'js', 'function topbarOriginalCurrentName'),
 ('in', 'html', 'id="topbar-event-ticker"'),
 ('not_in', 'html', 'id="topbar-event-ticker" aria-live="polite"'),
 ('in', 'app_lifecycle_js', 'function renderTopbarEventTicker'),
 ('in', 'app_lifecycle_js', 'function setTopbarPendingLaunch'),
 ('in', 'app_lifecycle_js', 'function activateCrossPageTarget'),
 ('in', 'app_lifecycle_js', 'activateReportsTab?.(button.dataset.crossPageReportsTab)'),
 ('in', 'app_lifecycle_js', 'topbarEventTickerLine'),
 ('in', 'app_lifecycle_js', 'function topbarPendingLaunchLine'),
 ('in', 'app_lifecycle_js', 'pending?.label || pending?.command || "pipeline.start"'),
 ('in', 'app_lifecycle_js', 'pending?.statusLabel || "accepted"'),
 ('in', 'app_lifecycle_js', 'waiting for backend event'),
 ('in', 'css_layout', '.topbar-event-ticker'),
 ('in', 'css_layout', 'text-overflow: ellipsis;'),
 ('in', 'css_layout', '.topbar-event-ticker[data-state="pending"]'),
 ('in', 'launch_view_js', 'window.setTopbarPendingLaunch?.({ pid })'),
 ('in', 'js', 'function updatePagePanelEmptyStates'),
 ('in', 'js', 'data-page-empty-state'),
 ('in', 'js', 'No boxes are visible on this tab.'),
 ('in', 'js', 'Boxes may be hidden by'),
 ('in', 'js', 'function renderHomeNextQueue'),
 ('not_in', 'js', 'function homeNextQueueRows'),
 ('in', 'js', 'function homeQueueRowIsRunnable'),
 ('in', 'js', 'home-next-queue-list'),
 ('in', 'html', 'Next 5 Videos'),
 ('in', 'html', 'Run Progress'),
 ('in', 'html', 'Recently Completed'),
 ('not_in', 'js', 'renderHomeNextQueue(dashboardContext)'),
 ('in', 'js', 'failuresPayload: values.failures || {}'),
 ('in', 'js', 'auditResults: values["audit results"] || {}'),
 ('in', 'js', 'Daily-driver readiness checklist:'),
 ('in', 'js', 'Real-media sample proof'),
 ('in', 'js', 'function externalDependencyRows'),
 ('in', 'js', 'function renderExternalDependencyDigest'),
 ('in', 'js', 'window.externalDependencyEvidenceText'),
 ('in', 'js', 'External dependency digest:'),
 ('in', 'js', 'Settings BDPGS OCR paths'),
 ('in', 'js', 'Settings VobSub OCR paths'),
 ('in', 'js', 'Settings raw-key action plan'),
 ('in', 'js', 'stage or save settings, edit secrets'),
 ('in', 'js', 'Maintenance toolchain'),
 ('in', 'js', 'Before treating WebView as daily-driver ready, process a small known batch'),
 ('in', 'js', 'WebView readiness is not proof by itself'),
 ('in', 'js', 'renderDailyDriverReadiness(dashboardContext)'),
 ('in', 'app_refresh_js', 'function renderRefreshInProgress(options = {})'),
 ('in', 'queue_view_js', 'refreshAll({ queueRefresh: true })'),
 ('in', 'js', 'refreshAll({ automatic: true })'),
 ('in', 'js', 'const AUTOMATIC_REFRESH_INTERVAL_MS = 15000'),
 ('in', 'js', 'window.setInterval(() => refreshAll({ automatic: true }), AUTOMATIC_REFRESH_INTERVAL_MS)'),
 ('in', 'js', 'lastRefreshDurationMs'),
 ('in', 'css_layout', '.activity-meta'),
 ('in', 'css_split_assets', 'text-overflow: ellipsis'),
 ('in', 'css_layout', 'text-overflow: ellipsis'),
 ('in', 'css_components', '.page-panel-empty-window'),
 ('in', 'css_components', '.page-panel-empty-window.is-visible'),
 ('in',
  'js',
  'this checklist is read-only and does not launch, repair, drain, save, rename, delete, publish, or touch media '
  'files'),
 ('in', 'js', 'settings: values.settings || window.mediaPipelineSettingsView.getLastSettings()'),
 ('in', 'js', '[data-cross-page-target]'),
 ('in', 'js', 'renderNetworkViewFn({'),
 ('in', 'js', 'window.mediaPipelineReportsView?.renderReports?.(lastSnapshot, window.mediaPipelineSettingsView.getLastSettings())'),
 ('in', 'js', 'source=markers'),
 ('in', 'js', 'priority_only=true'),
 ('in', 'js', 'window.mediaPipelineMaintenanceView?.getLastMaintenance?.()'),
 ('in', 'maintenance_view_js', 'getLastMaintenance'),
 ('in', 'js', 'launchView.startPipelineFromForm?.()'),
 ('not_in', 'js', 'startAuditFromForm'),
 ('in', 'queue_view_js', 'wireClick("rerun-start-button", () => startRerunFromForm({ dry_run: false }))'),
 ('in', 'rename_view_js', 'movie_filter_options'),
 ('in', 'rename_view_js', 'remove_terms_text'),
 ('in', 'rename_view_js', 'final_name_overrides'),
 ('in', 'rename_view_js', 'force_pipeline_name_overrides'),
 ('in', 'rename_view_js', 'applySelectedRename'),
 ('in', 'js', 'renderDiagnostics'),
 ('in', 'js', 'renderCloseReadiness'),
 ('in', 'js', 'formatCloseReadiness'),
 ('in', 'js', 'Watcher generation:'),
 ('in', 'js', 'diagnostics-close-readiness'),
 ('in', 'js', 'function renderHomeReadiness'),
 ('in', 'js', 'function homeReadinessNextStep'),
 ('in', 'js', 'function renderControlReadiness'),
 ('in', 'js', 'function pipelineControlReadinessStatus'),
 ('in', 'js', 'function pipelineControlReadinessLines'),
 ('in', 'js', 'Mutation guardrail: control buttons send backend-owned control flags through /api/pipeline/control'),
 ('in', 'js', 'window.mediaPipelineProgressView?.renderHomeActiveWork?.(liveRunContext)'),
 ('in', 'js', 'Required read failure(s):'),
 ('in', 'js', 'Supporting read issue(s):'),
 ('in', 'js', 'Next step:'),
 ('in', 'js', 'beforeunload'),
 ('in', 'js', 'closeReadinessRequiresWarning'),
 ('in', 'js', 'Promise.allSettled'),
 ('in', 'js', 'renderRefreshHealth'),
 ('in', 'js', 'refreshFailure'),
 ('in', 'js', 'launchView.requestPipelineControl?.(button.dataset.controlAction || "", button)'),
 ('in', 'launch_view_js', 'sourceButton?.dataset?.controlOwner === "run-monitor"'),
 ('in', 'launch_view_js', 'expected_run_id: expectedRunId'),
 ('in', 'launch_view_js', 'confirm_force_stop: true'),
 ('in', 'js', 'let refreshInFlight = false'),
 ('in', 'js', 'let refreshQueued = false'),
 ('in', 'js', 'async function refreshAllNow(options = {})'),
 ('in', 'js', 'if (refreshInFlight)'),
 ('in', 'js', 'if (refreshOptions.automatic) return'),
 ('in', 'js', 'Refresh failed: ${message}'),
 ('in', 'js', 'name: "refresh/render"'),
 ('in', 'js', 'window.setTimeout(() => refreshAll(queuedOptions), 0)'),
 ('in', 'command_history_js', 'formatCommandHistoryTime'),
 ('in', 'command_history_js', 'formatCommandHistoryLines'),
 ('in', 'command_history_js', 'issue=${issue}'),
 ('in', 'command_history_js', 'commandHistoryOwnerPage(item)'),
 ('in', 'command_history_js', 'const issue = commandHistoryIssueLevel(item)'),
 ('in', 'command_history_js', 'diagnostics-command-history'),
 ('in', 'command_history_js', 'function renderDiagnosticsCommandDrilldown'),
 ('in', 'command_history_js', 'function commandHistoryDiagnosticsDrilldownRows'),
 ('in', 'command_history_js', 'function commandHistoryDiagnosticsDrilldownSummaryLines'),
 ('in', 'command_history_js', 'function commandHistoryDiagnosticsEvidenceRows'),
 ('in', 'command_history_js', 'function commandHistoryOwnerImpactRows'),
 ('in', 'command_history_js', 'function renderDiagnosticsCommandOwnerImpact'),
 ('in', 'command_history_js', 'function renderCommandDiagnosticsEvidence'),
 ('namespace', 'command_history_js', 'mediaPipelineCommandHistory', 'renderCommandDiagnosticsEvidence'),
 ('not_in', 'command_history_js', 'window.renderCommandDiagnosticsEvidence = renderCommandDiagnosticsEvidence'),
 ('in', 'command_history_js', 'Diagnostics command-result drilldown:'),
 ('in', 'command_history_js', 'Command owner impact:'),
 ('in', 'command_history_js', 'Selection behavior: selecting an owner row selects its latest command'),
 ('in', 'command_history_js', 'Command / diagnostics evidence correlation:'),
 ('in', 'command_history_js', 'possible related evidence only'),
 ('in', 'command_history_js', 'Read-first order: command detail -> Last Stderr / Latest Failure -> owning page state.'),
 ('in', 'command_history_js', 'Mutation guardrail: Diagnostics drilldown is read-only'),
 ('in', 'command_history_js', 'Guardrail: this correlation cannot prove success/failure by itself'))


class ApplicationFacadeWebStaticCrossPageTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.bundle = served_webview_static_contract_bundle()

    def test_cross_page_dom_assets_and_validation_surfaces_are_static_pinned(self) -> None:
        _run_static_assertions(self, self.bundle, CROSS_PAGE_DOM_ASSERTIONS)

    def test_cross_page_context_and_sample_validation_are_read_only(self) -> None:
        _run_static_assertions(self, self.bundle, CROSS_PAGE_CONTEXT_ASSERTIONS)

    def test_shared_app_shell_workflow_handoffs_are_namespace_owned(self) -> None:
        _run_static_assertions(self, self.bundle, APP_SHELL_WORKFLOW_ASSERTIONS)


if __name__ == "__main__":
    unittest.main()
