from __future__ import annotations

import unittest

from tests.python.desktop.application_facade_test_support import (
    assert_namespace_export as _assert_namespace_export,
    served_webview_static_contract_bundle,
)


def _assert_contains_all(testcase: unittest.TestCase, text: str, snippets: tuple[str, ...]) -> None:
    for snippet in snippets:
        with testcase.subTest(snippet=snippet):
            testcase.assertIn(snippet, text)


def _assert_not_contains_any(testcase: unittest.TestCase, text: str, snippets: tuple[str, ...]) -> None:
    for snippet in snippets:
        with testcase.subTest(snippet=snippet):
            testcase.assertNotIn(snippet, text)


class ApplicationFacadeWebStaticSettingsTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.bundle = served_webview_static_contract_bundle()

    def test_settings_assets_and_dom_contract_are_static_pinned(self) -> None:
        html = self.bundle.html

        _assert_contains_all(
            self,
            html,
            (
                "/assets/settingsOverview.js",
                "/assets/settingsCommandHistory.js",
                "/assets/settingsMetadata.js",
                "/assets/settings/metadataFields.js",
                "/assets/settings/builderControls.js",
                "/assets/settingsView.builders.audio.js",
                "/assets/settingsView.builders.video.js",
                "/assets/settingsView.builders.subtitle.js",
                "/assets/settingsView.builders.queue.js",
                "/assets/settingsView.builders.runtime.js",
                "/assets/settingsView.builders.file_safety.js",
                "/assets/settingsView.builders.pending.js",
                "/assets/settingsView.builders.network.js",
                "/assets/settingsView.rawTriage.js",
                "/assets/settingsView.safetyLocks.js",
                "/assets/settings/finalLibraryPromotion.js",
                "/assets/settings/patchOverview.js",
                "/assets/settings/patchInteractions.js",
                "/assets/settings/patchReadiness.js",
                "/assets/settings/patchReview.js",
                "/assets/settingsView.js",
                'id="settings-audio-auto-bitrate"',
                "settings-filter",
                "settings-profiles",
                "settings-validation",
                "settings-overview-status",
                "settings-overview-rows",
                "settings-safety-lock-status",
                "settings-safety-lock-summary",
                "settings-safety-lock-rows",
                "settings-raw-triage-status",
                "settings-raw-triage",
                "settings-raw-triage-rows",
                "settings-raw-triage-legend",
                "settings-raw-triage-detail",
                "Advanced Key Plan",
                "settings-raw-action-plan-status",
                "settings-raw-action-plan-summary",
                "settings-raw-action-plan-rows",
                "settings-raw-action-plan-legend",
                "settings-raw-action-plan-detail",
                "settings-builder-routing-profile",
                "settings-builder-size-guard",
                "settings-builder-encode-tuning",
                "settings-builder-encode-ladder",
                "settings-builder-max-growth",
                "settings-builder-apply-button",
                "settings-builder-reset-button",
                "settings-builder-guidance",
                'option value="strict"',
                "settings-video-preset",
                "settings-video-quality",
                "settings-video-h264-remux",
                "settings-video-h264-max-bitrate",
                "settings-video-remux-safe-codecs",
                "settings-video-cpu-quality",
                "settings-video-cpu-threads",
                "settings-video-extra-flags",
                "settings-video-apply-button",
                "settings-video-apply-hint",
                "backend owns routing, codec, container, and encoder policy",
                "settings-video-guidance",
                "settings-file-safety-source-movies",
                "settings-file-safety-source-tv",
                "settings-file-safety-outsource",
                "settings-file-safety-local-base",
                "settings-file-safety-valid-extensions",
                "settings-file-safety-robocopy-flags",
                "settings-file-safety-output-size-multiplier",
                "settings-file-safety-deferred-publish",
                "settings-file-safety-skip-stability",
                "settings-file-safety-enable-integrity",
                "settings-file-safety-aggressive-episode",
                "settings-file-safety-create-tv-subfolder",
                "settings-tv-library-folder-evidence",
                "settings-file-safety-apply-button",
                "settings-file-safety-guidance",
                "settings-pending-deferred-publish",
                "settings-pending-cleanup-remote",
                "settings-pending-transient-retry-limit",
                "settings-pending-robocopy-timeout",
                "settings-pending-review-budget-gib",
                "settings-pending-block-budget-gib",
                "settings-pending-robocopy-flags",
                "settings-pending-enable-integrity",
                "settings-pending-apply-button",
                "settings-pending-guidance",
                "settings-network-role",
                "settings-network-coordinator-port",
                "settings-network-worker-url",
                "settings-network-path-map",
                "settings-network-apply-button",
                "settings-network-guidance",
                "settings-queue-priority-markers",
                "settings-queue-processed-index-refresh",
                "settings-queue-min-pipeline-version",
                "settings-queue-reprocess-all",
                "settings-queue-apply-button",
                "settings-queue-guidance",
                "settings-runtime-debug-mode",
                "settings-runtime-console-log",
                "settings-runtime-log-retention",
                "settings-runtime-failure-artifact-threshold",
                "settings-runtime-failure-artifact-retention",
                "settings-runtime-failure-artifact-cleanup-target",
                "settings-runtime-ffmpeg-encode-timeout",
                "settings-runtime-source-scan-interval",
                "settings-runtime-transient-retry-limit",
                "settings-runtime-apply-button",
                "settings-runtime-guidance",
                "settings-subtitle-languages",
                "settings-subtitle-convert-tx3g",
                "settings-subtitle-convert-bdpgs",
                "settings-subtitle-drop-ass",
                "settings-subtitle-bdpgs-path-status",
                "settings-subtitle-bdpgs-path-evidence",
                "settings-subtitle-apply-button",
                "settings-subtitle-guidance",
                "settings-audio-passthrough-profile",
                "settings-audio-compatible-codecs",
                "settings-audio-preferred-languages",
                '<select id="settings-audio-preferred-languages">',
                "English (eng)",
                "Chinese / Mandarin (zho)",
                "Turkish (tur)",
                "settings-audio-downmix-mode",
                "settings-audio-allow-no-audio",
                "settings-audio-apply-button",
                "settings-audio-guidance",
                "settings-media-policy-status",
                "settings-media-policy-summary",
                "settings-media-policy-rows",
                "settings-active-media-policy-status",
                "settings-active-media-policy-summary",
                "settings-active-media-policy-rows",
                "settings-reload-button",
                "settings-save-review-dialog",
                "settings-save-review-dialog-rows",
                "settings-save-patch-button",
                "settings-summarize-patch-button",
                "settings-patch-json",
                "settings-patch-detail",
                "settings-patch-impact-summary",
                "Save Candidate",
                "settings-policy-delta-status",
                "settings-policy-delta-summary",
                "settings-policy-delta-rows",
                "settings-policy-delta-legend",
                "Active Policy",
                "settings-effective-policy-status",
                "settings-effective-policy-summary",
                "settings-effective-policy-rows",
                "settings-effective-policy-legend",
                "settings-effective-policy-detail",
                "settings-save-readiness-status",
                "settings-save-readiness",
                "settings-save-review-rows",
                "settings-save-review-legend",
                "settings-save-review-detail",
                "settings-launch-impact-status",
                "settings-launch-impact-summary",
                "settings-launch-impact-rows",
                "settings-launch-impact-legend",
                "Save Result",
                "settings-backend-result-status",
                "settings-backend-result-summary",
                "settings-backend-result-rows",
                "settings-backend-result-legend",
                "settings-backend-result-detail",
                "settings-patch-summary-rows",
                "settings-patch-summary-status",
                "settings-patch-summary-changed-only",
                "settings-command-history-status",
                "settings-command-history",
                "settings-save-progress-bars",
                "settings-file-safety-source-movies-browse",
                'data-settings-path-key="SourceMovies"',
                'data-settings-path-key="Outsource"',
                "settings-backend-media-policy-rows",
                "Policy Readiness",
            ),
        )
        self.assertNotIn('option value="enforce"', html)
        self.assertNotIn("settings-preview-patch-button", html)

    def test_settings_overview_and_command_history_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.settings_overview_js,
            (
                "window.mediaPipelineSettingsOverview",
                "function renderSettingsOverview",
                "function buildSettingsOverviewRows",
                "function settingsOperatorTrustLines",
                "function renderSettingsOperatorTrust",
                "Saved settings trust checklist:",
                "Source safety:",
                "Publish behavior:",
                "Remux/encode routing:",
                "Subtitle routing:",
                "Audio routing:",
                "Mutation guardrail: settings trust is read-only",
                "media_policy_readiness",
                "Routing / Size",
                "Paths / Safety",
                "Subtitles",
            ),
        )
        for flat_export in (
            "window.buildSettingsOverviewRows =",
            "window.renderSettingsOverview =",
            "window.settingsOperatorTrustStatus =",
            "window.renderSettingsOperatorTrust =",
        ):
            self.assertNotIn(flat_export, bundle.settings_overview_js)
        _assert_contains_all(
            self,
            bundle.settings_command_history_js,
            (
                "window.mediaPipelineSettingsCommandHistory",
                "function isSettingsCommand",
                "function renderSettingsCommandHistory",
                "function settingsCommandHistoryLine",
                "settings.browse_path",
                "settings.preview_patch",
                "settings.save_patch",
                "renderCompactCommandHistoryBlock({",
                "Backend settings patch validation/save remains the source of truth.",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.settings_command_history_js,
            (
                "window.isSettingsCommand = isSettingsCommand",
                "window.settingsCommandHistoryLine = settingsCommandHistoryLine",
                "window.renderSettingsCommandHistory = renderSettingsCommandHistory",
                "window.renderSettingsRawActionPlan = renderSettingsRawActionPlan",
                "window.renderSettings = renderSettings",
                "window.getLastSettings = getLastSettings",
                "window.initSettingsViewEvents = initSettingsViewEvents",
            ),
        )

    def test_settings_metadata_and_builder_modules_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.settings_metadata_js,
            (
                "window.mediaPipelineSettingsMetadata",
                "settingsBuilderFields",
                "fileSafetySettingsBuilderFields",
                "networkSettingsBuilderFields",
                "queueSettingsBuilderFields",
                "videoDetailSettingsBuilderFields",
                "runtimeSettingsBuilderFields",
                "pendingPublishSettingsBuilderFields",
                "subtitleSettingsBuilderFields",
                "audioSettingsBuilderFields",
                "settingsSafetyLockDefinitions",
                "settingsImpactGroups",
                "settingsSpecificImpactHints",
                "settingsChoiceLabels",
                "settings-runtime-cleanup-scan-timeout",
                "settings-file-safety-valid-extensions",
                "settings-file-safety-robocopy-flags",
                "AudioTranscodeAutoBitrateByChannels",
                "Source deletion must remain an explicit opt-in safety decision.",
                "Source deletion is off. Normal processing should copy to scratch and preserve sources.",
                "PATH fallback is enabled. Runs may silently use system FFmpeg",
                "Per-worker overrides are configured, but backend policy currently ignores them for worker encode snapshots.",
                "Robocopy transfer flags affect retry behavior",
                "Plex direct/stream",
                "Queue / reprocess",
                "Paths / file safety",
                "Runtime / diagnostics",
                "Pending publish / recovery",
                "settings-pending-robocopy-timeout",
                "AutonomyPendingTotalReviewBytes",
                "settings-pending-review-budget-gib",
                "AutonomyPendingTotalBlockBytes",
                "settings-pending-block-budget-gib",
                "completed payloads can park",
                "scan cadence, subprocess timeout ceilings",
                "FailureArtifactWarningThresholdGB",
                "FailureArtifactRetentionDays",
                "FailureArtifactCleanupTargetGB",
                "Set 0 to disable only the session toast",
                "deletion still requires a Reports preview and confirmation",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_js,
            (
                "syncSettingsBuilderFromConfig",
                "collectSettingsBuilderPatch",
                "applySettingsBuilderToPatch",
                "refreshSettingsBuilderChoices",
                "renderSettingsBuilderGuidance",
                "markSettingsBuilderDirty",
                "videoDetailSettingsBuilderFields",
                "collectVideoDetailSettingsBuilderPatch",
                "applyVideoDetailSettingsBuilderToPatch",
                "renderVideoDetailSettingsBuilderGuidance",
                "lastSettingsFieldDefinitions",
                "fileSafetySettingsBuilderFields",
                "collectFileSafetySettingsBuilderPatch",
                "applyFileSafetySettingsBuilderToPatch",
                "renderFileSafetySettingsBuilderGuidance",
                "networkSettingsBuilderFields",
                "collectNetworkSettingsBuilderPatch",
                "applyNetworkSettingsBuilderToPatch",
                "renderNetworkSettingsBuilderGuidance",
                "queueSettingsBuilderFields",
                "collectQueueSettingsBuilderPatch",
                "applyQueueSettingsBuilderToPatch",
                "renderQueueSettingsBuilderGuidance",
                "runtimeSettingsBuilderFields",
                "collectRuntimeSettingsBuilderPatch",
                "applyRuntimeSettingsBuilderToPatch",
                "renderRuntimeSettingsBuilderGuidance",
                "pendingPublishSettingsBuilderFields",
                "syncPendingPublishSettingsBuilderFromConfig",
                "collectPendingPublishSettingsBuilderPatch",
                "applyPendingPublishSettingsBuilderToPatch",
                "renderPendingPublishSettingsBuilderGuidance",
                "subtitleSettingsBuilderFields",
                "syncSubtitleSettingsBuilderFromConfig",
                "collectSubtitleSettingsBuilderPatch",
                "applySubtitleSettingsBuilderToPatch",
                "renderSubtitleSettingsBuilderGuidance",
                "settingsBdpgsOcrPathEvidence",
                "renderSettingsBdpgsOcrPathEvidence",
                "settingsVobSubOcrPathEvidence",
                "renderSettingsVobSubOcrPathEvidence",
                "writeSettingsPatchJson",
                "audioSettingsBuilderFields",
                "syncAudioSettingsBuilderFromConfig",
                "collectAudioSettingsBuilderPatch",
                "applyAudioSettingsBuilderToPatch",
                "renderAudioSettingsBuilderGuidance",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_video_builder_js,
            (
                "__settingsViewVideoBuilderModule",
                "RemuxSafeVideoCodecs",
                "FallbackCpuQuality",
                "legacy raw FFmpeg flags should normally stay empty",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_file_safety_builder_js,
            (
                "__settingsViewFileSafetyBuilderModule",
                "SourceMovies",
                "OutputSizeMultiplier",
                "RobocopyFlags",
                "pipeline should copy source files to scratch",
                "high robocopy thread counts can saturate",
                "corrupt or partially-written sources may pass discovery",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_network_builder_js,
            (
                "__settingsViewNetworkBuilderModule",
                "NetworkRole",
                "CoordinatorPort",
                "WorkerSourcePathMap",
                "Secret guardrail",
                "openNetworkRoleSetup",
                "Coordinator/worker runtime command controls remain backend-owned",
                "Validate path rewrites on the worker",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_queue_builder_js,
            (
                "__settingsViewQueueBuilderModule",
                "PriorityMarkers",
                "ProcessedIndexRefreshSeconds",
                "ReprocessAll",
                "queue mutation and processing starts remain backend-owned",
                "backend risk preview should flag this",
                "zero disables processed-index caching",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_runtime_builder_js,
            (
                "__settingsViewRuntimeBuilderModule",
                "FFmpegEncodeTimeoutSeconds",
                "FailureArtifactWarningThresholdGB",
                "FailureArtifactRetentionDays",
                "FailureArtifactCleanupTargetGB",
                "settings-runtime-failure-artifact-threshold",
                "settings-runtime-failure-artifact-retention",
                "settings-runtime-failure-artifact-cleanup-target",
                "AllowSystemTools",
                "long-running process ceilings",
                "artifact size remains visible on Home and Reports",
                "age-based artifact cleanup is disabled",
                "target-size artifact cleanup is disabled",
                "release validation should normally use bundled tools",
                "zero-day retention can remove forensic logs quickly",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_pending_builder_js,
            (
                "__settingsViewPendingPublishBuilderModule",
                "DeferredPublish",
                "CleanupRemoteStaging",
                "Drain Parked Outputs",
                "direct publish plus skipped stability checks",
                "high robocopy thread counts can saturate pending-publish drains",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_subtitle_builder_js,
            (
                "__settingsViewSubtitleBuilderModule",
                "Saved BDPGS OCR path evidence:",
                "Saved VobSub OCR path evidence:",
                "WebView does not resolve arbitrary paths or run OCR",
                "Default policy: original subtitle tracks are preserved",
                "Subtitle routing summary:",
                'byId("settings-subtitle-languages")',
                "ConvertTx3gToSrt",
                'setSubtitleBuilderControl("settings-subtitle-convert-bdpgs", "ConvertBdpgsToSrt", "bool", true)',
                "preferred-language TX3G/mov_text subtitles will not generate SRT without conversion enabled.",
                "Drop TX3G is enabled while Convert TX3G to SRT is disabled.",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_audio_builder_js,
            (
                "__settingsViewAudioBuilderModule",
                "Audio routing summary:",
                "settings-audio-auto-bitrate",
                "normalizePreferredAudioLanguageValue",
                "list_select",
                "Default policy: keep no-audio output disabled",
                "no-audio outputs can publish files Plex users may treat as broken",
                "custom codec list makes copy-vs-transcode depend on the manual codec list",
            ),
        )

    def test_settings_raw_triage_safety_and_view_namespace_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.settings_view_js,
            (
                "window.mediaPipelineSettingsView",
                "const settingsMetadata = window.mediaPipelineSettingsMetadata",
                "function renderSettingsRows",
                "function settingsRawTriageRows",
                "function settingsRawTriageStatus",
                "function renderSettingsRawTriage",
                "function settingsRawTriageDetailLines",
                "function settingsRawActionPlanRows",
                "function settingsRawActionPlanStatus",
                "function settingsRawActionPlanDetailLines",
                "function renderSettingsRawActionPlan",
                "function settingsSafetyLockRows",
                "function renderSettingsSafetyLocks",
                "Settings raw-key triage:",
                "Unknown raw keys:",
                "Mutation guardrail: this triage is read-only",
                "Settings raw-key action plan:",
                "BDPGS OCR path evidence",
                "VobSub OCR path evidence",
                "Network auth secrets",
                "No raw-key action-plan row selected.",
                "Settings safety lock review:",
                "Mutation guardrail: this panel is read-only",
                "function renderSettings",
                "function getLastSettings",
                "function initSettingsViewEvents",
                "reloadSettingsFromDisk",
                "const settingsCommandButtonIds",
                "function setSettingsCommandBusy",
                "function rejectSettingsCommandWhileBusy",
                "Another settings command is already in progress.",
                "mediaPipelineSettingsCommandHistory",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_raw_triage_js,
            ("__settingsRawTriageModule",),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_safety_locks_js,
            ("__settingsSafetyLocksModule",),
        )
        _assert_contains_all(
            self,
            bundle.settings_view_parent_js,
            (
                "const settingsRawTriageModule = window.__settingsRawTriageModule || {}",
                "const settingsSafetyLocksModule = window.__settingsSafetyLocksModule || {}",
            ),
        )
        _assert_not_contains_any(
            self,
            bundle.settings_view_js,
            (
                "window.isSettingsCommand = isSettingsCommand",
                "window.settingsCommandHistoryLine = settingsCommandHistoryLine",
                "window.renderSettingsCommandHistory = renderSettingsCommandHistory",
            ),
        )

    def test_settings_policy_save_and_launch_handoff_are_static_pinned(self) -> None:
        bundle = self.bundle

        _assert_contains_all(
            self,
            bundle.settings_view_js,
            (
                "function settingsLaunchImpactRows",
                "function settingsLaunchImpactStatus",
                "function settingsLaunchImpactSummaryLines",
                "function renderSettingsLaunchImpactHandoffFromEntries",
                "settingsBackendPolicyImpact",
                'settingsPolicyImpactDo("renderSettingsLaunchImpactHandoffFromEntries", [entries])',
                "Launch uses saved backend settings, not unsaved edits.",
                "backend launch validation remains authoritative",
                "let settingsPatchTouched = false",
                "/api/settings/browse-path",
                "function browseSettingsPath",
                "backend-owned Windows folder picker",
                "It cannot save settings, launch work, rewrite queue state, publish, rename, delete, or touch media files.",
                "function settingsPatchEffectiveChangedEntries",
                "function settingsPatchHasUnsavedChanges",
                "lastSettingsPatchPreviewEvidence",
                "lastSettingsPatchSaveEvidence",
                "function settingsStableJsonValue",
                "function settingsPatchSignature",
                "Only backend command results count as persistence evidence.",
                "renderAllLaunchPreflights",
                "function settingsMediaPolicyRows",
                "function renderSettingsMediaPolicyCrossCheck",
                "function settingsBackendMediaPolicyReadiness",
                "function renderSettingsBackendMediaPolicyReadiness",
                "function settingsActiveMediaPolicyRows",
                "function renderSettingsActiveMediaPolicyHandoff",
                "Backend media-policy readiness:",
                "Audio / subtitle policy cross-check:",
                "SRT creation, original-track preservation, language routing, and audio predictability",
                "Save Settings remains backend-owned; this panel does not change FFmpeg",
                "Active media-policy handoff:",
                "Builder edits are not launch-active until backend Save succeeds",
                "Plex-compatible H.264 sources can remain copy/remux candidates",
                "MP4 cannot carry every original subtitle format",
                "Do not drop TX3G while conversion is disabled",
                "Do not drop BDPGS while OCR is disabled",
                "settings-builder-routing-profile",
                "settings-builder-size-guard",
                "previewSettingsPatch",
                "let settingsPatchPreviewRequestId = 0",
                "const rawAtRequest = raw",
                "requestId !== state.settingsPatchPreviewRequestId",
                "Preview replaced",
                "saveSettingsPatch",
                "function settingsCommandProgressBars",
                "function renderSettingsSaveProgress",
                'renderProgressBarsInto("settings-save-progress-bars"',
                "Settings save/reload progress:",
                "appendSettingsRiskSummaryLines",
                "Risk summary:",
                "risk_summary",
                "renderSettingsPatchSummary",
                "function settingsPatchImpactEntries",
                "function renderSettingsPatchImpactSummaryFromEntries",
                "function settingsPatchSaveReadinessIssues",
                "function renderSettingsPatchSaveReadinessFromEntries",
                "function settingsPolicyDeltaRows",
                "function renderSettingsPolicyDeltaFromEntries",
                "Save-candidate media-policy delta:",
                "This compares current saved values against the local save candidate",
                "renderSettingsPolicyDeltaFromEntries(impactEntries)",
                "function settingsEffectivePolicyRows",
                "function settingsEffectivePolicyTrustStatus",
                "function renderSettingsEffectivePolicyTrustFromEntries",
                "Effective policy trust summary:",
                "Launch-active policy is the saved backend config",
                "WebView builder edits are candidates only",
                "renderSettingsEffectivePolicyTrustFromEntries(impactEntries)",
                "settings-patch-impact-summary",
                "settings-policy-delta-summary",
                "settings-effective-policy-summary",
                "settings-save-readiness",
                "Backend Save remains authoritative",
                "Local save readiness checklist:",
                "function settingsSaveReviewRows",
                "function renderSettingsSaveReviewFromEntries",
                "Settings Save remains backend-owned",
                "selectedSettingsSaveReviewKey",
                "press Save Settings and review the change dialog",
                "Mutation guardrail: this checklist does not save settings",
                "parseSettingsPatchJson",
                "settings-summarize-patch-button",
                "settings-patch-summary-changed-only",
                "No changed or unknown keys to show.",
                "confirm_save",
                "redacted_diff_lines",
                "/api/settings/validate",
                "/api/settings/reload",
                "/api/settings/preview-patch",
                "/api/settings/save-patch",
            ),
        )
        _assert_namespace_export(self, bundle.settings_view_js, "mediaPipelineSettingsView", "settingsLaunchImpactRows")
        _assert_namespace_export(self, bundle.settings_view_js, "mediaPipelineSettingsView", "settingsPatchHasUnsavedChanges")
        _assert_namespace_export(self, bundle.settings_view_js, "mediaPipelineSettingsView", "settingsBackendResultRows")
        _assert_namespace_export(self, bundle.settings_view_js, "mediaPipelineSettingsView", "settingsBackendResultDetailLines")
        _assert_namespace_export(self, bundle.settings_view_js, "mediaPipelineSettingsView", "renderSettingsActiveMediaPolicyHandoff")
        _assert_namespace_export(self, bundle.settings_view_js, "mediaPipelineSettingsView", "settingsEffectivePolicyRows")
        self.assertNotIn("window.settingsLaunchImpactRows = settingsLaunchImpactRows", bundle.settings_view_js)
        _assert_contains_all(
            self,
            bundle.settings_backend_result_js,
            (
                "function settingsBackendResultRows",
                "function settingsBackendResultRowKey",
                "function settingsBackendResultDetailLines",
                "function renderSettingsBackendResultFromEntries",
                "Save candidate identity:",
                "Redacted diff lines:",
                "Evidence matches current JSON:",
                "Backend data JSON",
                "jsonDetailText({",
                "Backend save handoff:",
                "Save Settings will review the current values before writing.",
                "Save Settings is the persistence command",
                "The backend save command requires confirm_save=true",
                "Launch uses saved backend settings only",
            ),
        )
        _assert_contains_all(
            self,
            bundle.settings_policy_impact_js,
            (
                "settings_policy_impact.v1",
                "settingsBackendPolicyImpact",
                'settingsMediaPolicyBool("settings-subtitle-convert-bdpgs", "ConvertBdpgsToSrt", false)',
                'settingsPatchCandidateBool(entries, "ConvertBdpgsToSrt", false)',
                'settingsPatchCurrentBool("ConvertBdpgsToSrt", false)',
            ),
        )
        _assert_contains_all(
            self,
            bundle.launch_view_risk_js,
            (
                "function launchUnsavedSettingsPatchLines",
                "Unsaved Settings changes:",
                "Launch uses saved backend settings only.",
                "Save-candidate media-policy delta:",
                "settingsPolicyDeltaRows",
                "settingsPolicyDeltaStatus",
                "settings_launch_risk_handoff.v1",
                "launchSettingsBackendRiskRows",
                'launchSettingsConfigValue(config, "ConvertBdpgsToSrt"), false',
                'launchPolicyCandidateValue(config, entryMap, "ConvertBdpgsToSrt", false), false',
            ),
        )
        _assert_namespace_export(self, bundle.launch_view_js, "mediaPipelineLaunchView", "launchUnsavedSettingsPatchLines")
        _assert_contains_all(
            self,
            bundle.cross_page_settings_js,
            (
                "Backend media-policy readiness",
                "media readiness=",
            ),
        )


if __name__ == "__main__":
    unittest.main()
