from __future__ import annotations

from typing import Any


LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/queue/priority",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "level", "reason", "items"],
        "allowed_levels": ["high", "normal", "low", "hold"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_priority_manifest.v1",
        "purpose": "Write non-destructive priority manifest entries only for absolute paths under configured SourceMovies/SourceTV roots. This does not rename, move, delete, launch, or process media.",
    },
    {
        "method": "POST",
        "path": "/api/queue/strategy",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["strategy"],
        "allowed_strategies": [
            "Standard",
            "FreshestFirst",
            "ShowComplete",
            "RoundRobin",
            "DeadlineAware",
            "SmallFirst",
            "LargeFirst",
            "ManualOrder",
        ],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_strategy_state.v1",
        "purpose": "Persist the backend queue ordering strategy for the next queue build without launching work or touching media files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/file-overrides",
        "auth_required": True,
        "effect": "queue-state-write",
        "request_keys": ["path", "audio", "subtitles", "clear", "clear_all"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "queue_file_overrides.v1",
        "purpose": "Write per-file processing override state only for absolute paths under configured SourceMovies/SourceTV roots, or clear the override manifest. This does not process or mutate media files.",
    },
    {
        "method": "POST",
        "path": "/api/failures/clear",
        "auth_required": True,
        "effect": "failure-marker-write",
        "request_keys": ["scope", "marker_path", "marker_paths", "source_json", "dry_run", "confirm_clear"],
        "allowed_scopes": ["selected", "visible", "all_markers"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "failure_marker_clear_result.v1",
        "purpose": "Preview or move backend-owned failure marker JSON files out of State\\Failures\\Markers after explicit confirmation. Paths are accepted only when they resolve inside the backend failure marker folder. This does not delete media, reports, completed manifests, pending publish state, or source/output files.",
    },
    {
        "method": "POST",
        "path": "/api/queue/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target", "row_scope"],
        "allowed_targets": ["source_file", "source_folder", "source_root"],
        "allowed_row_scopes": ["runnable", "excluded"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a path selected by the backend from a runnable or excluded queue snapshot row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/completed/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["output_file", "output_folder", "sidecar", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a path selected by the backend from a completed-jobs manifest row; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["row_key", "target"],
        "allowed_targets": ["local_file", "manifest", "destination_folder", "source_folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open a path selected by the backend from the current pending-publish scan; arbitrary frontend paths are not accepted.",
    },
    {
        "method": "POST",
        "path": "/api/pending-publish/recovery-plan",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["scope", "row_key"],
        "allowed_scopes": ["all", "selected"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "pending_publish_recovery_plan.v1",
        "purpose": "Build a backend-authored dry-run recovery plan from the current pending-publish scan. This does not drain, repair, rewrite, move, delete, or publish files.",
    },
)

LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/maintenance/release-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "keep_personal_config",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": False,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "keep_personal_config": False,
            "timeout_seconds": 900,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the existing release builder with -DryRun only. No release folder, zip, or manifest is written.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/release-build",
        "auth_required": True,
        "effect": "deployment-write",
        "request_keys": [
            "destination_root",
            "zip_package",
            "verify",
            "include_tests",
            "include_dev_docs",
            "include_optional_tools",
            "include_tool_docs",
            "keep_personal_config",
            "force",
            "confirm_create",
            "timeout_seconds",
        ],
        "safe_defaults": {
            "zip_package": True,
            "verify": True,
            "include_tests": False,
            "include_dev_docs": False,
            "include_optional_tools": False,
            "include_tool_docs": False,
            "keep_personal_config": False,
            "force": False,
            "confirm_create": False,
            "timeout_seconds": 7200,
        },
        "response_schema": "desktop_command_result.v1",
        "purpose": "Create a deployable release package through the backend release builder after explicit confirmation and active-work checks. It may create a release folder, manifest, and zip outside the source bundle.",
    },
    {
        "method": "POST",
        "path": "/api/maintenance/completed-backfill-dry-run",
        "auth_required": True,
        "effect": "process-dry-run",
        "request_keys": ["timeout_seconds"],
        "safe_defaults": {"timeout_seconds": 600},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Run the completed-jobs manifest backfill with -DryRun only. The completed manifest is not rewritten.",
    },
)

LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/diagnostics/open",
        "auth_required": True,
        "effect": "shell-open",
        "request_keys": ["target"],
        "allowed_targets": [
            "run_logs",
            "cluster_log",
            "config",
            "config_folder",
            "workspace",
            "state",
            "pending_publish",
            "failed_reports",
            "failed_markers",
            "audit_reports",
            "queue_snapshot",
            "active_jobs",
            "completed_manifest",
            "latest_failure_report",
            "latest_failure_json",
            "latest_audit_csv",
            "latest_priority_csv",
            "last_stdout_log",
            "last_stderr_log",
            "sample_validation_log",
        ],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open backend-allowlisted diagnostics/log/config locations through the OS shell.",
    },
)

LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/rename/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["paths", "mode", "show_name", "season", "start_episode", "movie_title", "movie_year"],
        "response_schema": "desktop_rename_preview.v1",
        "purpose": "Generate rename predictions without applying filesystem changes.",
    },
    {
        "method": "POST",
        "path": "/api/rename/browse",
        "auth_required": True,
        "effect": "shell-dialog",
        "request_keys": ["selection_mode", "initial_path"],
        "allowed_selection_modes": ["files", "folder"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Open the native Windows file/folder browser and return operator-selected absolute paths for Rename staging. This does not preview, apply, rename, move, delete, or touch media files.",
    },
    {
        "method": "POST",
        "path": "/api/rename/apply",
        "auth_required": True,
        "effect": "filesystem-mutation",
        "request_keys": ["paths", "selected_sources", "confirm_apply", "allow_outside_configured_roots"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Rebuild the rename plan in the backend and apply only explicitly selected source rows through the transactional rename service. Paths outside configured media roots require an additional outside-root confirmation.",
    },
)

LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/settings/validate",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["values"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Validate settings values without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/preview-patch",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["changes", "remove_keys"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted config and return a redacted diff without writing the PSD1 config.",
    },
    {
        "method": "POST",
        "path": "/api/settings/save-patch",
        "auth_required": True,
        "effect": "config-write",
        "request_keys": ["changes", "remove_keys", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Merge explicit settings changes with the backend's unredacted config, validate, back up, atomically save the active PSD1, and reload backend resolved state.",
    },
    {
        "method": "POST",
        "path": "/api/settings/reload",
        "auth_required": True,
        "effect": "none",
        "request_keys": [],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Reload resolved paths and config data from the current PSD1 without writing config or starting pipeline work.",
    },
)

LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/schedule/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["enabled", "day_windows", "grid"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_patch_preview.v1",
        "purpose": "Validate and preview schedule/app-state changes without writing app state, starting work, or editing media state.",
    },
    {
        "method": "POST",
        "path": "/api/schedule/save",
        "auth_required": True,
        "effect": "app-state-write",
        "request_keys": ["enabled", "day_windows", "grid", "confirm_save"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_schedule_save_result.v1",
        "purpose": "Atomically save schedule_enabled and schedule_grid to desktop app state through the backend service while preserving unrelated app-state keys. This does not launch work, bypass schedule gates, or mutate media files.",
    },
)

LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/sample-validation/preview",
        "auth_required": True,
        "effect": "none",
        "request_keys": ["schema", "source_path", "output_path", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Validate and normalize a proposed sample validation record without writing the validation log or changing media/pipeline state.",
    },
    {
        "method": "POST",
        "path": "/api/sample-validation/append",
        "auth_required": True,
        "effect": "validation-log-write",
        "request_keys": ["schema", "source_path", "output_path", "proof_strength", "operator_decision", "checks", "evidence", "operator_notes"],
        "response_schema": "desktop_command_result.v1",
        "data_schema": "desktop_sample_validation_preview.v1",
        "purpose": "Append an operator evidence-only sample validation record under State\\Validation. This must not mark jobs complete, clear failures, drain pending publish, rewrite manifests/sidecars, launch work, or mutate media files.",
    },
)

LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "method": "POST",
        "path": "/api/pipeline/control",
        "auth_required": True,
        "effect": "control-flag-write",
        "request_keys": ["action"],
        "allowed_actions": ["pause", "stop", "rescan", "kill"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Write backend-owned pause, stop, or rescan control flags, or force-kill related pipeline processes.",
    },
    {
        "method": "POST",
        "path": "/api/pipeline/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["mode", "sleep_seconds", "show_config", "show_console", "single_file", "schedule_override"],
        "allowed_modes": ["once", "continuous", "validate", "drain_pending_pushes"],
        "allowed_schedule_overrides": ["", "run_once", "ignore"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing pipeline process through the Python service layer.",
    },
    {
        "method": "POST",
        "path": "/api/audit/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["library_root", "include_sidecars", "show_console"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing audit process through the Python service layer.",
    },
    {
        "method": "POST",
        "path": "/api/rerun/start",
        "auth_required": True,
        "effect": "process-launch",
        "request_keys": ["csv_path", "dry_run", "stage_mode", "original_mode", "return_mode", "show_console"],
        "safe_defaults": {"dry_run": False, "stage_mode": "copy", "original_mode": "keep", "return_mode": "park"},
        "response_schema": "desktop_command_result.v1",
        "purpose": "Launch the existing CSV rerun process with conservative media-safe defaults.",
    },
    {
        "method": "POST",
        "path": "/api/backend/shutdown",
        "auth_required": True,
        "effect": "backend-lifecycle",
        "request_keys": ["reason", "force_active_work_shutdown"],
        "response_schema": "desktop_command_result.v1",
        "purpose": "Request graceful shutdown of the local API backend owned by the desktop shell; unsafe close-readiness is rejected unless explicit force cleanup is requested.",
    },
)


LOCAL_API_COMMAND_ROUTE_CONTRACT = (
    LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT
    + LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT
)


__all__ = [
    "LOCAL_API_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_DIAGNOSTICS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_FILE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_MAINTENANCE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_PROCESS_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_RENAME_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SCHEDULE_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SAMPLE_VALIDATION_COMMAND_ROUTE_CONTRACT",
    "LOCAL_API_SETTINGS_COMMAND_ROUTE_CONTRACT",
]
