"""Advanced-page settings field definitions."""

from __future__ import annotations

from mediapipeline.core.rename.constants import PLEX_RENAME_DEFAULT_REMOVE_TERMS, RENAME_MOVIE_FILTER_OPTION_KEYS
from mediapipeline.core.rename.movie import rename_movie_filter_default_terms

from .policy import LOG_LEVEL_VALUES


def _rename_movie_filter_options_default() -> dict[str, bool]:
    return {key: True for key in RENAME_MOVIE_FILTER_OPTION_KEYS}


ADVANCED_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "ConfigSchemaVersion",
        "label": "Config Schema Version",
        "kind": "int",
        "default": 1,
        "help": "Backend PSD1 schema marker. Treat edits as migration work and verify with backend Preview Patch before saving.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "ShowOverrides",
        "label": "Per-Show Overrides",
        "kind": "json",
        "default": {},
        "help": "Advanced direct-config mapping of show-name patterns to per-show routing, video, audio, and subtitle overrides. Treat edits as media-policy work and verify with backend Preview Patch.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameMovieFilterOptions",
        "label": "Rename Movie Filter Options",
        "kind": "json",
        "default": _rename_movie_filter_options_default(),
        "help": "Backend-owned movie rename cleaning category toggles. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameMovieFilterTerms",
        "label": "Rename Movie Filter Terms",
        "kind": "json",
        "default": rename_movie_filter_default_terms(),
        "help": "Backend-owned movie rename cleaning term lists by category. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameMovieRemoveTerms",
        "label": "Rename Movie Remove Terms",
        "kind": "list",
        "default": list(PLEX_RENAME_DEFAULT_REMOVE_TERMS),
        "help": "Backend-owned extra movie rename terms removed from cleaned titles. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "MaxParallelEncodes",
        "label": "Max Parallel Encodes",
        "kind": "combo_int",
        "choices": ("1", "2"),
        "default": 1,
        "help": "Maximum local encode slots. Keep at 1 unless the machine and scratch/output paths have been validated for local parallel encode pressure.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "ParallelEncodeMode",
        "label": "Parallel Encode Mode",
        "kind": "combo",
        "choices": ("single", "local_worker_slots"),
        "default": "single",
        "help": "Enables local worker-slot scheduling only when MaxParallelEncodes is greater than 1. Single is the safe default.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "DebugMode",
        "label": "Verbose Debug Logging",
        "kind": "bool",
        "help": "Enable more detailed pipeline debug output.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "ConsoleLogLevel",
        "label": "Console Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "Console log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "FileLogLevel",
        "label": "File Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "File log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "LogRetentionDays",
        "label": "Log Retention Days",
        "kind": "int",
        "default": 7,
        "help": "Number of days to keep rotated pipeline log files.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinFreeSpaceGB",
        "label": "Scratch Free Space Reserve (GB)",
        "kind": "int",
        "default": 50,
        "help": "Minimum free space reserved on the scratch drive.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FileStabilityWait",
        "label": "File Stability Wait (s)",
        "kind": "int",
        "default": 15,
        "help": "Seconds a discovered source must remain stable before processing.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SkipStabilityCheck",
        "label": "Skip File Stability Check",
        "kind": "bool",
        "default": False,
        "help": "Bypass source file-stability checks. Use only for deliberate diagnostics, never for normal unattended intake.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutsourceMinFreeSpaceGB",
        "label": "Output Free Space Reserve (GB)",
        "kind": "int",
        "default": 50,
        "help": "Minimum free space reserved on the output destination.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegEncodeTimeoutSeconds",
        "label": "Encode Timeout (s)",
        "kind": "int",
        "default": 21600,
        "help": "Timeout limit for FFmpeg encode jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegRemuxTimeoutSeconds",
        "label": "Remux Timeout (s)",
        "kind": "int",
        "default": 7200,
        "help": "Timeout limit for FFmpeg remux jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleExtractTimeoutSeconds",
        "label": "Subtitle Extract Timeout (s)",
        "kind": "int",
        "default": 180,
        "help": "Timeout limit for ASS/TX3G subtitle extraction helpers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleProbeTimeoutSeconds",
        "label": "Subtitle Probe Timeout (s)",
        "kind": "int",
        "default": 30,
        "help": "Timeout limit for subtitle stream probing commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "BdpgsOcrTimeoutSeconds",
        "label": "BDPGS OCR Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Timeout limit for external BDPGS OCR commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "VobSubOcrTimeoutSeconds",
        "label": "VobSub OCR Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Timeout limit for external VobSub OCR commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "AllowSystemTools",
        "label": "Allow PATH Tool Fallback",
        "kind": "bool",
        "help": "Developer-only fallback. Leave off so the portable bundle requires its bundled FFmpeg, ffprobe, mkvmerge, and Python.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyTimeoutSeconds",
        "label": "Copy Timeout (s)",
        "kind": "int",
        "default": 14400,
        "help": "Timeout limit for robocopy source, scratch, and publish transfers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "TransientFailureRetryLimit",
        "label": "Transient Failure Retry Limit",
        "kind": "int",
        "default": 3,
        "help": "Repeated matching transient failures escalate to operator_required at this count.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinPipelineVersion",
        "label": "Minimum Pipeline Version",
        "kind": "optional_string",
        "help": "Optional version floor used for reprocess decisions.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputSizeMultiplier",
        "label": "Output Size Multiplier",
        "kind": "optional_float",
        "help": "Optional size safety multiplier for route validation.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputValidationProbeTimeoutSeconds",
        "label": "Output Probe Timeout (s)",
        "kind": "int",
        "default": 60,
        "help": "Maximum ffprobe time for completed-output validation before routing the job to review.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputValidationMinSizeBytes",
        "label": "Minimum Output Size (bytes)",
        "kind": "int",
        "default": 1024,
        "help": "Minimum completed-output byte size accepted by output validation.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputValidationDurationToleranceSeconds",
        "label": "Duration Tolerance (s)",
        "kind": "int",
        "default": 2,
        "help": "Allowed duration mismatch between source and output validation probes.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "EnableIntegrityCheck",
        "label": "Enable Integrity Check",
        "kind": "bool",
        "help": "Probe source media before processing so corrupt or incomplete files can be held back.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyFlags",
        "label": "Robocopy Flags",
        "kind": "list",
        "help": "Flags used for source-to-scratch and scratch-to-output robocopy transfers. Keep retries, waits, and logging flags explicit.",
    },
)
