"""Advanced-page settings field definitions."""

from __future__ import annotations

from mediapipeline.core.rename.constants import PLEX_RENAME_DEFAULT_REMOVE_TERMS, RENAME_MOVIE_FILTER_OPTION_KEYS, RENAME_TV_FILTER_OPTION_KEYS
from mediapipeline.core.rename.movie import rename_movie_filter_default_terms
from mediapipeline.core.rename.tv import rename_tv_filter_default_terms

from .policy import LOG_LEVEL_VALUES


def _rename_movie_filter_options_default() -> dict[str, bool]:
    return {key: True for key in RENAME_MOVIE_FILTER_OPTION_KEYS}


def _rename_tv_filter_options_default() -> dict[str, bool]:
    return {key: True for key in RENAME_TV_FILTER_OPTION_KEYS}


QUALITY_METRIC_DESCRIPTIONS = {
    "vmaf": "Perceptual similarity score using the bundled ffmpeg libvmaf filter.",
    "ssim": "Structural similarity score parsed from ffmpeg stderr. Use thresholds in 0-1 units.",
    "psnr": "Peak signal-to-noise ratio parsed from ffmpeg stderr. Use thresholds in dB.",
}

QUALITY_SAMPLE_MODE_DESCRIPTIONS = {
    "sampled": "Measure evenly spaced windows across the encode.",
    "full": "Measure the full encoded output against the scratch source.",
}

QUALITY_FAIL_ACTION_DESCRIPTIONS = {
    "warn_only": "Record warnings but never block publish based on quality score.",
    "block_review": "Reject measured below-floor encodes before publish and route the source to operator review.",
}


ADVANCED_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "ConfigSchemaVersion",
        "label": "Config Schema Version",
        "kind": "int",
        "default": 1,
        "help": "Backend PSD1 schema marker. Treat edits as migration work and verify with backend Preview Patch before saving.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "ShowOverrides",
        "label": "Per-Show Overrides",
        "kind": "json",
        "default": {},
        "help": "Advanced direct-config mapping of show-name patterns to per-show routing, video, audio, and subtitle overrides. Treat edits as media-policy work and verify with backend Preview Patch.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "PlannerRolloutStage",
        "label": "Planner Rollout Stage",
        "kind": "combo",
        "choices": (
            "legacy",
            "shadow",
            "selected_jobs",
            "ui_old_backend",
            "new_planner_default",
            "deprecation_cleanup",
        ),
        "default": "legacy",
        "help": "Backend planner rollout stage. Legacy keeps PowerShell execution authoritative; shadow enables Python preview comparison only.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "UsePythonPlanner",
        "label": "Use Python Planner",
        "kind": "bool",
        "default": False,
        "help": "Requests the Python planner for controlled rollout stages. Execution remains legacy unless the cutover stage is also approved.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "EnableHandBrakeSettingsUi",
        "label": "Enable New Planner UI",
        "kind": "bool",
        "default": False,
        "help": "Shows the new planner/settings UI surface while backend execution authority stays controlled by the rollout stage.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "PlannerComparisonLogging",
        "label": "Planner Comparison Logging",
        "kind": "bool",
        "default": False,
        "help": "Records legacy-versus-Python planner comparison evidence during dry-run preview and shadow rollout.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "NewPlannerCutoverApproved",
        "label": "Approve Python Planner Cutover",
        "kind": "bool",
        "default": False,
        "help": "Explicit operator approval required before the Python planner can own execution in a cutover stage.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameMovieFilterOptions",
        "label": "Rename Movie Filter Options",
        "kind": "json",
        "default": _rename_movie_filter_options_default(),
        "help": "Backend-owned movie rename cleaning category toggles. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameMovieFilterTerms",
        "label": "Rename Movie Filter Terms",
        "kind": "json",
        "default": rename_movie_filter_default_terms(),
        "help": "Backend-owned movie rename cleaning term lists by category. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameMovieRemoveTerms",
        "label": "Rename Movie Remove Terms",
        "kind": "list",
        "default": list(PLEX_RENAME_DEFAULT_REMOVE_TERMS),
        "help": "Backend-owned extra movie rename terms removed from cleaned titles. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameTVFilterOptions",
        "label": "Rename TV Filter Options",
        "kind": "json",
        "default": _rename_tv_filter_options_default(),
        "help": "Backend-owned TV rename cleaning category toggles. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameTVFilterTerms",
        "label": "Rename TV Filter Terms",
        "kind": "json",
        "default": rename_tv_filter_default_terms(),
        "help": "Backend-owned TV rename cleaning term lists by category. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "RenameTVRemoveTerms",
        "label": "Rename TV Remove Terms",
        "kind": "list",
        "default": list(PLEX_RENAME_DEFAULT_REMOVE_TERMS),
        "help": "Backend-owned extra TV rename terms removed from cleaned show and episode titles. Saving through Settings affects future pipeline naming and Rename apply planning.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "MaxParallelEncodes",
        "label": "Max Parallel Encodes",
        "kind": "combo_int",
        "choices": ("1", "2"),
        "default": 1,
        "help": "Maximum local encode slots. Keep at 1 unless the machine and scratch/output paths have been validated for local parallel encode pressure.",
    },
    {
        "page": "Advanced",
        "section": "Runtime",
        "key": "ParallelEncodeMode",
        "label": "Parallel Encode Mode",
        "kind": "combo",
        "choices": ("single", "local_worker_slots"),
        "default": "single",
        "help": "Enables local worker-slot scheduling only when MaxParallelEncodes is greater than 1. Single is the safe default.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "DebugMode",
        "label": "Verbose Debug Logging",
        "kind": "bool",
        "help": "Enable more detailed pipeline debug output.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "ConsoleLogLevel",
        "label": "Console Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "Console log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "FileLogLevel",
        "label": "File Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "File log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "LogRetentionDays",
        "label": "Log Retention Days",
        "kind": "int",
        "default": 7,
        "help": "Number of days to keep rotated pipeline log files.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FileStabilityWait",
        "label": "File Stability Wait (s)",
        "kind": "int",
        "default": 15,
        "help": "Seconds a discovered source must remain stable before processing.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SkipStabilityCheck",
        "label": "Skip File Stability Check",
        "kind": "bool",
        "default": False,
        "help": "Bypass source file-stability checks. Use only for deliberate diagnostics, never for normal unattended intake.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegEncodeTimeoutSeconds",
        "label": "Encode Timeout (s)",
        "kind": "int",
        "default": 21600,
        "help": "Timeout limit for FFmpeg encode jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegRemuxTimeoutSeconds",
        "label": "Remux Timeout (s)",
        "kind": "int",
        "default": 7200,
        "help": "Timeout limit for FFmpeg remux jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleExtractTimeoutSeconds",
        "label": "Subtitle Extract Timeout (s)",
        "kind": "int",
        "default": 180,
        "help": "Timeout limit for ASS/TX3G subtitle extraction helpers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleProbeTimeoutSeconds",
        "label": "Subtitle Probe Timeout (s)",
        "kind": "int",
        "default": 30,
        "help": "Timeout limit for subtitle stream probing commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "BdpgsOcrTimeoutSeconds",
        "label": "BDPGS OCR Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Timeout limit for external BDPGS OCR commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "VobSubOcrTimeoutSeconds",
        "label": "VobSub OCR Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Timeout limit for external VobSub OCR commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "AllowSystemTools",
        "label": "Allow PATH Tool Fallback",
        "kind": "bool",
        "help": "Developer-only fallback. Leave off so the portable bundle requires its bundled FFmpeg, ffprobe, mkvmerge, and Python.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyTimeoutSeconds",
        "label": "Copy Timeout (s)",
        "kind": "int",
        "default": 14400,
        "help": "Timeout limit for robocopy source, scratch, and publish transfers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "TransientFailureRetryLimit",
        "label": "Transient Failure Retry Limit",
        "kind": "int",
        "default": 3,
        "help": "Repeated matching transient failures escalate to operator_required at this count.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinPipelineVersion",
        "label": "Minimum Pipeline Version",
        "kind": "optional_string",
        "help": "Optional version floor used for reprocess decisions.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputSizeMultiplier",
        "label": "Output Size Multiplier",
        "kind": "optional_float",
        "help": "Optional size safety multiplier for route validation.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputValidationProbeTimeoutSeconds",
        "label": "Output Probe Timeout (s)",
        "kind": "int",
        "default": 60,
        "help": "Maximum ffprobe time for completed-output validation before routing the job to review.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputValidationMinSizeBytes",
        "label": "Minimum Output Size (bytes)",
        "kind": "int",
        "default": 1024,
        "help": "Minimum completed-output byte size accepted by output validation.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputValidationDurationToleranceSeconds",
        "label": "Duration Tolerance (s)",
        "kind": "int",
        "default": 2,
        "help": "Allowed duration mismatch between source and output validation probes.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "EnableQualityVerification",
        "label": "Enable Quality Verification",
        "kind": "bool",
        "default": False,
        "help": "After lossy encodes, measure objective similarity against the scratch source before publish. Remux paths do not run quality verification.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualityMetric",
        "label": "Quality Metric",
        "kind": "combo",
        "choices": ("vmaf", "ssim", "psnr"),
        "choice_help": QUALITY_METRIC_DESCRIPTIONS,
        "default": "vmaf",
        "help": "Metric used by ffmpeg after lossy encodes. VMAF uses the bundled libvmaf filter without an external model file.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualitySampleMode",
        "label": "Sample Mode",
        "kind": "combo",
        "choices": ("sampled", "full"),
        "choice_help": QUALITY_SAMPLE_MODE_DESCRIPTIONS,
        "default": "sampled",
        "help": "Sampled mode measures multiple windows and full mode measures the entire output. Long full-file VMAF runs can be expensive.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualitySampleSeconds",
        "label": "Sample Seconds",
        "kind": "int",
        "default": 10,
        "help": "Seconds measured per sampled quality window. Clamped by the backend to 2-60 seconds.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualitySampleCount",
        "label": "Sample Count",
        "kind": "int",
        "default": 3,
        "help": "Number of sampled quality windows. Clamped by the backend to 1-10 windows.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualityWarnThreshold",
        "label": "Warn Threshold",
        "kind": "float",
        "default": 90,
        "help": "Interpreted in the selected metric's units. Defaults assume VMAF (0-100). For SSIM use 0-1 (e.g. warn 0.95 / fail 0.90); for PSNR use dB (e.g. warn 38 / fail 32). 0 disables the tier.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualityFailThreshold",
        "label": "Fail Threshold",
        "kind": "float",
        "default": 75,
        "help": "Interpreted in the selected metric's units. Defaults assume VMAF (0-100). For SSIM use 0-1 (e.g. warn 0.95 / fail 0.90); for PSNR use dB (e.g. warn 38 / fail 32). 0 disables the tier.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualityFailAction",
        "label": "Fail Action",
        "kind": "combo",
        "choices": ("warn_only", "block_review"),
        "choice_help": QUALITY_FAIL_ACTION_DESCRIPTIONS,
        "default": "warn_only",
        "help": "block_review rejects the encode before publish and routes the source to operator review.",
    },
    {
        "page": "Advanced",
        "section": "Quality Verification",
        "key": "QualityVerifyTimeoutSeconds",
        "label": "Verify Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Per-ffmpeg quality verification timeout. Tool errors, parse errors, and timeouts fail open and do not block publish.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "EnableIntegrityCheck",
        "label": "Enable Integrity Check",
        "kind": "bool",
        "help": "Probe source media before processing so corrupt or incomplete files can be held back.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyFlags",
        "label": "Robocopy Flags",
        "kind": "list",
        "help": "Flags used for source-to-scratch and scratch-to-output robocopy transfers. Keep retries, waits, and logging flags explicit.",
    },
)
