"""Processing and routing Basic-page settings metadata."""

from __future__ import annotations

from .policy import (
    ROUTE_THRESHOLD_MODE_DEFAULT,
    ROUTE_THRESHOLD_MODE_DESCRIPTIONS,
    ROUTE_THRESHOLD_MODE_NAMES,
    ROUTING_PROFILE_DEFAULT,
    ROUTING_PROFILE_DESCRIPTIONS,
    ROUTING_PROFILE_NAMES,
    SIZE_GUARD_MODE_DEFAULT,
    SIZE_GUARD_MODE_DESCRIPTIONS,
    SIZE_GUARD_MODE_NAMES,
)

BASIC_ROUTE_AND_SIZE_FIELDS = (
{
        "page": "Basic",
        "section": "Routing",
        "key": "MovieRoute1080pTargetSizeGB",
        "label": "Movie 1080p target output size (GB)",
        "kind": "int",
        "default": 8,
        "help": "GB target output size for known-height movie sources in the 1080p bucket. Unknown-height movies use Movie target output size.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "MovieRoute1440pTargetSizeGB",
        "label": "Movie 1440p target output size (GB)",
        "kind": "int",
        "default": 8,
        "help": "GB target output size for known-height movie sources in the 1440p bucket. Unknown-height movies use Movie target output size.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "MovieRoute4KTargetSizeGB",
        "label": "Movie 4K target output size (GB)",
        "kind": "int",
        "default": 8,
        "help": "GB target output size for known-height movie sources in the 4K bucket. Unknown-height movies use Movie target output size.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "TVRoute1080pTargetSizeGB",
        "label": "TV 1080p target output size (GB)",
        "kind": "int",
        "default": 3,
        "help": "GB target output size for known-height TV sources in the 1080p bucket. Unknown-height TV uses TV target output size.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "TVRoute1440pTargetSizeGB",
        "label": "TV 1440p target output size (GB)",
        "kind": "int",
        "default": 3,
        "help": "GB target output size for known-height TV sources in the 1440p bucket. Unknown-height TV uses TV target output size.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "TVRoute4KTargetSizeGB",
        "label": "TV 4K target output size (GB)",
        "kind": "int",
        "default": 3,
        "help": "GB target output size for known-height TV sources in the 4K bucket. Unknown-height TV uses TV target output size.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "RoutingProfile",
        "label": "Library goal",
        "kind": "combo",
        "choices": ROUTING_PROFILE_NAMES,
        "default": ROUTING_PROFILE_DEFAULT,
        "choice_help": ROUTING_PROFILE_DESCRIPTIONS,
        "help": "Overall library intent. Controls the copy/remux-first policy before an encode is considered.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "RouteThresholdMode",
        "label": "What forces an encode?",
        "kind": "combo",
        "choices": ROUTE_THRESHOLD_MODE_NAMES,
        "default": ROUTE_THRESHOLD_MODE_DEFAULT,
        "choice_help": ROUTE_THRESHOLD_MODE_DESCRIPTIONS,
        "help": "Used before processing to decide copy/remux versus encode. Selects which route gates are hard: target output size, max bitrate for direct copy, or either.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route1080pUpperHeightTolerancePercent",
        "label": "1080p upper height tolerance %",
        "kind": "float",
        "default": 11.111111,
        "help": "Percent above 1080 used to derive the top of the 1080p direct-copy bitrate bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route1080pMaxVideoBitrateMbps",
        "label": "1080p max bitrate",
        "kind": "int",
        "default": 20,
        "help": "Direct-copy/remux bitrate cap in Mbps for sources in the 1080p height bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route1440pLowerHeightTolerancePercent",
        "label": "1440p lower height tolerance %",
        "kind": "float",
        "default": 16.597222,
        "help": "Percent below 1440 used to derive the first height in the 1440p direct-copy bitrate bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route1440pUpperHeightTolerancePercent",
        "label": "1440p upper height tolerance %",
        "kind": "float",
        "default": 24.930556,
        "help": "Percent above 1440 used to derive the top of the 1440p direct-copy bitrate bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route1440pMaxVideoBitrateMbps",
        "label": "1440p max bitrate",
        "kind": "int",
        "default": 35,
        "help": "Direct-copy/remux bitrate cap in Mbps for sources in the 1440p height bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route4KLowerHeightTolerancePercent",
        "label": "4K lower height tolerance %",
        "kind": "float",
        "default": 16.666667,
        "help": "Percent below 2160 used to derive the first height in the 4K direct-copy bitrate bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "Route4KMaxVideoBitrateMbps",
        "label": "4K max bitrate",
        "kind": "int",
        "default": 35,
        "help": "Direct-copy/remux bitrate cap in Mbps for sources in the 4K height bucket.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "AllowH264RemuxIfPlexCompatible",
        "label": "Copy Compatible H.264",
        "kind": "bool",
        "default": True,
        "help": "Allow low-risk H.264/AVC sources to stay remux/copy when bitrate, resolution, and Plex compatibility are acceptable.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "H264RemuxMaxBitrateMbps",
        "label": "H.264 Copy Max Mbps",
        "kind": "int",
        "default": 35,
        "help": "Maximum estimated source bitrate for the Plex-compatible H.264 shortcut and effective H.264 copy scoring; not a universal remux safety limit.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "H264RemuxMaxHeight",
        "label": "H.264 Copy Max Height",
        "kind": "combo_int",
        "choices": ("720", "1080", "2160"),
        "default": 1080,
        "help": "Maximum video height allowed for the Plex-compatible H.264 shortcut; codec-safe fallback can still remux taller H.264 when hard routing does not force encode.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "SizeGuardMode",
        "label": "If encoded output is too large",
        "kind": "combo",
        "choices": SIZE_GUARD_MODE_NAMES,
        "default": SIZE_GUARD_MODE_DEFAULT,
        "choice_help": SIZE_GUARD_MODE_DESCRIPTIONS,
        "help": "Checked after encode. Warn-only records oversized output. Strict blocks publish. Fallback remux applies existing growth buffers to automatic size/bitrate-threshold encodes, tries safe remux first, and rejects the oversized encode for review when remux is blocked. Forced route overrides warn only.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "MaxEncodeGrowthPercent",
        "label": "Normal Growth Limit %",
        "kind": "int",
        "default": 5,
        "help": "Checked after encode. Allowed output growth for quality encodes; Output Size Check warns or blocks publish when configured to block.",
    },
{
        "page": "Basic",
        "section": "Routing",
        "key": "CompatibilityEncodeGrowthPercent",
        "label": "Compatibility Growth Limit %",
        "kind": "int",
        "default": 15,
        "help": "Checked after encode. Allowed output growth for compatibility encodes; Output Size Check warns or blocks publish when configured to block.",
    },
)

BASIC_PROCESSING_BEHAVIOR_FIELDS = (
{
        "page": "Basic",
        "section": "Routing",
        "key": "AggressiveEpisodeParsing",
        "label": "Aggressive Episode Parsing",
        "kind": "bool",
        "help": "Use folder season hints and loose anime/import filename patterns to build SxxEyy when strict parsing fails.",
    },
)
