"""Basic-page settings field definitions."""

from __future__ import annotations

from .basic_media_policy import (
    BASIC_AUDIO_FIELDS,
    BASIC_FINAL_LIBRARY_PROMOTION_FIELDS,
    BASIC_PENDING_PUBLISH_FIELDS,
)
from .basic_paths import BASIC_PATH_BEHAVIOR_FIELDS, BASIC_PATH_FIELDS
from .basic_processing import BASIC_PROCESSING_BEHAVIOR_FIELDS, BASIC_ROUTE_AND_SIZE_FIELDS

BASIC_CONFIG_FIELD_DEFINITIONS = (
    *BASIC_PATH_FIELDS,
    *BASIC_FINAL_LIBRARY_PROMOTION_FIELDS,
    *BASIC_PATH_BEHAVIOR_FIELDS,
    *BASIC_AUDIO_FIELDS,
    *BASIC_ROUTE_AND_SIZE_FIELDS,
    *BASIC_PENDING_PUBLISH_FIELDS,
    *BASIC_PROCESSING_BEHAVIOR_FIELDS,
)
