"""Settings field display and enrichment metadata."""

from __future__ import annotations

from .field_scope import METADATA_LIBRARY_OVERRIDE_GROUP_BY_KEY, _metadata_scope

METADATA_ADVANCED_VISIBILITY_VALUES = (
    "standard",
    "advanced",
)

METADATA_RULE_TAXONOMY_VALUES = (
    "routing",
    "compatibility",
    "quality",
    "size",
    "bitrate",
    "output",
    "playback",
    "verification",
    "reliability",
    "publish",
    "advisory",
    "source_fact",
    "computed_evidence",
    "advanced",
)

METADATA_STRICTNESS_VALUES = (
    "hard",
    "soft",
    "advisory",
    "computed",
    "read_only",
    "inherited",
    "explicit",
    "advanced",
)

_DISPLAY_SECTION_BY_LEGACY_SECTION = {
    "Paths": "Source / Compatibility",
    "Libraries": "Source / Compatibility",
    "Final Library Promotion": "Verification / Publish",
    "Audio": "Audio",
    "Routing": "Routing",
    "Video": "Video",
    "NVENC / Encode": "Video",
    "Remux / Safety": "Advanced",
    "Shared Subtitle Policy": "Subtitles",
    "TX3G Subtitles": "Subtitles",
    "BDPGS Subtitles": "Subtitles",
    "VobSub Subtitles": "Subtitles",
    "ASS / SSA Subtitles": "Filters",
    "Runtime": "Advanced",
    "Logging": "Advanced",
    "Safety": "Advanced",
    "Queue": "Advanced",
    "Role": "Advanced",
    "Coordinator": "Advanced",
    "Worker": "Advanced",
}

_DEFAULT_DISPLAY_RULE_BY_SECTION = {
    "Source / Compatibility": ("source_fact", "compatibility"),
    "Routing": ("routing",),
    "Dimensions": ("compatibility",),
    "Filters": ("playback",),
    "Video": ("quality", "output"),
    "Audio": ("playback", "compatibility"),
    "Subtitles": ("playback", "output"),
    "Container": ("output", "compatibility"),
    "Size / Bitrate Guards": ("size", "bitrate", "verification"),
    "Verification / Publish": ("verification", "publish"),
    "Presets": ("quality",),
    "Advanced": ("advanced",),
}

_PHASE3_DISPLAY_METADATA_BY_KEY: dict[str, dict[str, object]] = {
    "RoutingProfile": {
        "label": "Library goal",
        "short_label": "Goal",
        "section": "Routing",
        "rule_taxonomy": ("routing", "playback"),
        "strictness": "hard",
        "help_text": "Overall library intent. Controls the copy/remux-first policy before an encode is considered.",
    },
    "RouteThresholdMode": {
        "label": "What forces an encode?",
        "short_label": "Encode Trigger",
        "section": "Routing",
        "rule_taxonomy": ("routing", "size", "bitrate"),
        "strictness": "hard",
        "help_text": "Used before processing to decide copy/remux versus encode. Selects which route gates are hard: target output size, max bitrate for direct copy, or either.",
    },
    "SizeGuardMode": {
        "label": "If encoded output is too large",
        "short_label": "Oversize Action",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "hard",
        "help_text": "Checked after encode. Warn-only records oversized output. Strict blocks publish. Fallback remux applies existing growth buffers to automatic size/bitrate-threshold encodes, tries safe remux first, and rejects the oversized encode for review when remux is blocked. Forced route overrides warn only.",
    },
    "EncodeWasteGuardMode": {
        "label": "GPU waste guard",
        "short_label": "Waste Guard",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification", "routing"),
        "strictness": "hard",
        "help_text": "Optional early projection guard for fallback-remux-eligible size/bitrate encodes. Off preserves current behavior; dry run records evidence; enforce can abort projected-oversize GPU work and try remux fallback.",
    },
    "EncodeWasteGuardPreflightEnabled": {
        "label": "GPU waste preflight",
        "short_label": "Waste Preflight",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Runs short video-only samples before the full hardware encode when the GPU waste guard is enabled.",
    },
    "EncodeTuningPreset": {
        "label": "NVENC tuning bundle",
        "short_label": "NVENC Tuning",
        "section": "Presets",
        "rule_taxonomy": ("quality", "output"),
        "strictness": "soft",
        "help_text": "Applies only when encoding is required. Chooses the encoder speed/compression tradeoff without changing copy/remux decisions by itself.",
    },
    "EncodeLadder": {
        "label": "How encode targets are calculated",
        "short_label": "Target Math",
        "section": "Presets",
        "rule_taxonomy": ("quality", "size", "bitrate"),
        "strictness": "soft",
        "help_text": "Applies only when encoding is required. Chooses target selection for one output; it does not produce multiple renditions.",
    },
    "VideoCodec": {
        "label": "Video Encoder",
        "short_label": "Encoder",
        "section": "Video",
        "rule_taxonomy": ("quality", "output"),
        "strictness": "soft",
        "help_text": "Applies only when encoding is required. Selects the video encoder used for encoded output.",
    },
    "EncoderBackend": {
        "label": "Encoder Backend Preference",
        "short_label": "Backend",
        "section": "Video",
        "rule_taxonomy": ("quality", "output"),
        "strictness": "advisory",
        "help_text": "Stored backend preference for encoder capability diagnostics. Normal encode selection remains controlled by VideoCodec until descriptor-backed activation is validated.",
    },
    "OutputContainer": {
        "label": "Output Container",
        "short_label": "Container",
        "section": "Container",
        "rule_taxonomy": ("output", "compatibility"),
        "strictness": "hard",
        "help_text": "Output container format used when muxing or encoding creates the saved output; it does not decide whether video is re-encoded.",
    },
    "DynamicHdrPolicy": {
        "label": "Dynamic HDR Policy",
        "short_label": "Dynamic HDR",
        "section": "Dynamic HDR",
        "rule_taxonomy": ("output", "compatibility"),
        "strictness": "hard",
        "help_text": "Controls Dolby Vision and HDR10+ preservation handling. Warn is the safe default until preserve modes have real-media remux evidence.",
    },
    "DoviToolPath": {
        "label": "dovi_tool Path",
        "short_label": "DoVi Tool",
        "section": "Dynamic HDR",
        "rule_taxonomy": ("advanced", "output"),
        "strictness": "advanced",
        "help_text": "Optional path override for dovi_tool.exe. Leave blank to use the bundled tool drop-zone when present.",
    },
    "Hdr10PlusToolPath": {
        "label": "hdr10plus_tool Path",
        "short_label": "HDR10+ Tool",
        "section": "Dynamic HDR",
        "rule_taxonomy": ("advanced", "output"),
        "strictness": "advanced",
        "help_text": "Optional path override for hdr10plus_tool.exe. Leave blank to use the bundled tool drop-zone when present.",
    },
    "MovieRoute1080pTargetSizeGB": {
        "label": "Movie 1080p target output size",
        "short_label": "Movie 1080p",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "routing"),
        "strictness": "soft",
        "library_profile_designations": ("movie", "auto"),
        "help_text": "GB target output size for movie sources in the 1080p bucket. Unknown-height movies use this 1080p target.",
    },
    "MovieRoute1440pTargetSizeGB": {
        "label": "Movie 1440p target output size",
        "short_label": "Movie 1440p",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "routing"),
        "strictness": "soft",
        "library_profile_designations": ("movie", "auto"),
        "help_text": "GB target output size for known-height movie sources in the 1440p bucket. Unknown-height movies use Movie target output size.",
    },
    "MovieRoute4KTargetSizeGB": {
        "label": "Movie 4K target output size",
        "short_label": "Movie 4K",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "routing"),
        "strictness": "soft",
        "library_profile_designations": ("movie", "auto"),
        "help_text": "GB target output size for known-height movie sources in the 4K bucket. Unknown-height movies use Movie target output size.",
    },
    "TVRoute1080pTargetSizeGB": {
        "label": "TV 1080p target output size",
        "short_label": "TV 1080p",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "routing"),
        "strictness": "soft",
        "library_profile_designations": ("tv", "auto"),
        "help_text": "GB target output size for TV sources in the 1080p bucket. Unknown-height TV uses this 1080p target.",
    },
    "TVRoute1440pTargetSizeGB": {
        "label": "TV 1440p target output size",
        "short_label": "TV 1440p",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "routing"),
        "strictness": "soft",
        "library_profile_designations": ("tv", "auto"),
        "help_text": "GB target output size for known-height TV sources in the 1440p bucket. Unknown-height TV uses TV target output size.",
    },
    "TVRoute4KTargetSizeGB": {
        "label": "TV 4K target output size",
        "short_label": "TV 4K",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "routing"),
        "strictness": "soft",
        "library_profile_designations": ("tv", "auto"),
        "help_text": "GB target output size for known-height TV sources in the 4K bucket. Unknown-height TV uses TV target output size.",
    },
    "Route1080pUpperHeightTolerancePercent": {
        "label": "1080p upper height tolerance",
        "short_label": "1080p Upper %",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Percent above 1080 used to derive the top of the 1080p height bucket. The next height belongs to 1440p.",
    },
    "Route1080pMaxVideoBitrateMbps": {
        "label": "1080p max bitrate for direct copy",
        "short_label": "1080p Mbps",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Direct-copy/remux bitrate cap in Mbps for sources in the 1080p height bucket. The same bucket selects the 1080p Movie/TV target output size.",
    },
    "Route1440pLowerHeightTolerancePercent": {
        "label": "1440p lower height tolerance",
        "short_label": "1440p Lower %",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Percent below 1440 used to derive the first height in the 1440p height bucket.",
    },
    "Route1440pUpperHeightTolerancePercent": {
        "label": "1440p upper height tolerance",
        "short_label": "1440p Upper %",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Percent above 1440 used to derive the top of the 1440p height bucket. The next height belongs to 4K.",
    },
    "Route1440pMaxVideoBitrateMbps": {
        "label": "1440p max bitrate for direct copy",
        "short_label": "1440p Mbps",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Direct-copy/remux bitrate cap in Mbps for sources in the 1440p height bucket. The same bucket selects the 1440p Movie/TV target output size.",
    },
    "Route4KLowerHeightTolerancePercent": {
        "label": "4K lower height tolerance",
        "short_label": "4K Lower %",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Percent below 2160 used to derive the first height in the 4K height bucket.",
    },
    "Route4KMaxVideoBitrateMbps": {
        "label": "4K max bitrate for direct copy",
        "short_label": "4K Mbps",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "bitrate", "routing"),
        "strictness": "hard",
        "help_text": "Direct-copy/remux bitrate cap in Mbps for sources in the 4K height bucket. The same bucket selects the 4K Movie/TV target output size.",
    },
    "MaxEncodeGrowthPercent": {
        "label": "Quality-encode size tolerance",
        "short_label": "Quality Tolerance",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Checked after encode. Allowed output growth for quality encodes; Output Size Check warns or blocks publish when configured to block.",
    },
    "CompatibilityEncodeGrowthPercent": {
        "label": "Compatibility-encode size tolerance",
        "short_label": "Compat Tolerance",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Checked after encode. Allowed output growth for compatibility encodes; Output Size Check warns or blocks publish when configured to block.",
    },
    "EncodeWasteGuardMinProgressPercent": {
        "label": "Waste guard minimum progress %",
        "short_label": "Waste Min %",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Live guard waits for this encode progress before trusting projected output size.",
    },
    "EncodeWasteGuardMinElapsedSeconds": {
        "label": "Waste guard minimum elapsed seconds",
        "short_label": "Waste Min Time",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Live guard waits this long before aborting based on projected output size.",
    },
    "EncodeWasteGuardOversizeMarginPercent": {
        "label": "Waste guard oversize margin %",
        "short_label": "Waste Margin",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Extra margin above the configured growth limit before projection is considered wasteful.",
    },
    "EncodeWasteGuardConsecutiveSamples": {
        "label": "Waste guard consecutive samples",
        "short_label": "Waste Samples",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Consecutive live oversized projections required before enforce mode aborts.",
    },
    "EncodeWasteGuardPollSeconds": {
        "label": "Waste guard poll seconds",
        "short_label": "Waste Poll",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Minimum seconds between live projection checks during hardware encode.",
    },
    "EncodeWasteGuardPreflightSampleSeconds": {
        "label": "Waste preflight sample seconds",
        "short_label": "Sample Seconds",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Seconds per video-only preflight sample.",
    },
    "EncodeWasteGuardPreflightSampleCount": {
        "label": "Waste preflight sample count",
        "short_label": "Sample Count",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Number of preflight samples spread across the source.",
    },
    "EncodeWasteGuardPreflightTimeoutSeconds": {
        "label": "Waste preflight timeout seconds",
        "short_label": "Sample Timeout",
        "section": "Size / Bitrate Guards",
        "rule_taxonomy": ("size", "verification"),
        "strictness": "soft",
        "help_text": "Maximum time allowed for each preflight FFmpeg sample.",
    },
    "AllowH264RemuxIfPlexCompatible": {
        "label": "Copy Plex-Compatible H.264",
        "short_label": "H.264 Copy",
        "section": "Source / Compatibility",
        "rule_taxonomy": ("compatibility", "routing"),
        "strictness": "hard",
        "help_text": "Allows compatible H.264 sources to remain direct-copy/remux candidates when bitrate, dimensions, and routing policy allow it.",
    },
    "H264RemuxMaxBitrateMbps": {
        "label": "H.264 Direct Copy Max Bitrate",
        "short_label": "H.264 Max Mbps",
        "section": "Source / Compatibility",
        "rule_taxonomy": ("bitrate", "compatibility"),
        "strictness": "hard",
        "help_text": "Maximum H.264 video bitrate eligible for the Plex-compatible direct-copy shortcut.",
    },
    "H264RemuxMaxHeight": {
        "label": "H.264 Direct Copy Max Height",
        "short_label": "H.264 Max Height",
        "section": "Dimensions",
        "rule_taxonomy": ("compatibility",),
        "strictness": "hard",
        "help_text": "Maximum H.264 source height eligible for the Plex-compatible direct-copy shortcut.",
    },
    "VideoPreset": {
        "label": "Encoder Speed Preset",
        "short_label": "Speed Preset",
        "section": "Video",
        "rule_taxonomy": ("quality",),
        "strictness": "soft",
        "help_text": "Applies only when encoding is required. Selects the encoder speed/compression tradeoff.",
    },
    "VideoQuality": {
        "label": "Quality Target",
        "short_label": "Quality",
        "section": "Video",
        "rule_taxonomy": ("quality", "size"),
        "strictness": "soft",
        "help_text": "Applies only when encoding is required. Lower values target higher visual quality and larger files.",
    },
    "RemuxSafeVideoCodecs": {
        "label": "Direct Copy Video Codec Allowlist",
        "short_label": "Video Allowlist",
        "section": "Source / Compatibility",
        "rule_taxonomy": ("compatibility", "routing"),
        "strictness": "hard",
        "help_text": "Used before processing to decide whether source video codecs may remain direct-copy/remux candidates without re-encoding.",
    },
    "FallbackCpuQuality": {
        "label": "CPU Fallback Quality",
        "short_label": "CPU Quality",
        "section": "Advanced",
        "rule_taxonomy": ("quality", "advanced"),
        "strictness": "advanced",
        "help_text": "Advanced quality target. Applies only when CPU encoding is selected or required.",
    },
    "CpuEncodePreset": {
        "label": "CPU Encoder Speed Preset",
        "short_label": "CPU Speed",
        "section": "Advanced",
        "rule_taxonomy": ("quality", "advanced"),
        "strictness": "advanced",
        "help_text": "Advanced libx265 speed/compression preset. Applies only when CPU encoding is selected or required.",
    },
    "CpuEncodeProcessPriority": {
        "label": "CPU Encoder Process Priority",
        "short_label": "CPU Priority",
        "section": "Advanced",
        "rule_taxonomy": ("advanced",),
        "strictness": "advanced",
        "help_text": "Advanced Windows process priority used for CPU encode jobs.",
    },
    "CpuEncodeMaxThreads": {
        "label": "CPU Encoder Max Threads",
        "short_label": "CPU Threads",
        "section": "Advanced",
        "rule_taxonomy": ("advanced",),
        "strictness": "advanced",
        "help_text": "Advanced CPU encode thread cap. Zero keeps the encoder default behavior.",
    },
    "CpuEncodeMutexWaitSeconds": {
        "label": "CPU Encoder Mutex Wait",
        "short_label": "CPU Mutex Wait",
        "section": "Advanced",
        "rule_taxonomy": ("reliability", "advanced"),
        "strictness": "advanced",
        "help_text": "Maximum time to wait for an existing CPU encode slot before recording a transient mutex failure.",
    },
    "ExtraVideoFlags": {
        "label": "Advanced Encoder Flags",
        "short_label": "Extra Flags",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "output"),
        "strictness": "advanced",
        "help_text": "Advanced raw encoder flags. Applies only when encoding is required through explicit legacy/custom flag paths.",
    },
    "AudioPassthroughProfile": {
        "label": "Audio Passthrough Policy",
        "short_label": "Passthrough",
        "section": "Audio",
        "rule_taxonomy": ("playback", "compatibility"),
        "strictness": "hard",
        "help_text": "Audio copy policy. Controls which audio codecs may pass through instead of being transcoded.",
    },
    "CompatibleAudioCodecs": {
        "label": "Audio Direct Copy Codec Allowlist",
        "short_label": "Audio Allowlist",
        "section": "Audio",
        "rule_taxonomy": ("compatibility", "playback"),
        "strictness": "hard",
        "help_text": "Manual audio codec allowlist used when the passthrough policy selects custom codec control.",
    },
    "PreferredDefaultAudioLanguages": {
        "label": "Primary Default Audio Language",
        "short_label": "Audio Language",
        "section": "Audio",
        "rule_taxonomy": ("playback",),
        "strictness": "soft",
        "help_text": "Primary language preference for selecting the default audio track when matching tracks are present.",
    },
    "AudioTranscodeCodec": {
        "label": "Audio Transcode Codec",
        "short_label": "Transcode Codec",
        "section": "Audio",
        "rule_taxonomy": ("output", "playback"),
        "strictness": "soft",
        "help_text": "Codec used when an audio track is transcoded instead of copied.",
    },
    "AudioTranscodeBitrate": {
        "label": "Audio Transcode Bitrate",
        "short_label": "Audio Bitrate",
        "section": "Audio",
        "rule_taxonomy": ("bitrate", "quality"),
        "strictness": "soft",
        "help_text": "Target bitrate used when audio is transcoded and automatic channel-based bitrate is not active.",
    },
    "AudioTranscodeAutoBitrateByChannels": {
        "label": "Auto Audio Bitrate by Channels",
        "short_label": "Auto Bitrate",
        "section": "Audio",
        "rule_taxonomy": ("bitrate", "quality"),
        "strictness": "soft",
        "help_text": "Chooses audio transcode bitrate from codec and channel count instead of a fixed bitrate value.",
    },
    "AudioDownmixMode": {
        "label": "Audio Downmix Policy",
        "short_label": "Downmix",
        "section": "Audio",
        "rule_taxonomy": ("playback", "output"),
        "strictness": "soft",
        "help_text": "Controls channel count handling when an audio track is transcoded.",
    },
    "AudioMaxChannels": {
        "label": "Max Audio Channels",
        "short_label": "Max Channels",
        "section": "Audio",
        "rule_taxonomy": ("playback",),
        "strictness": "soft",
        "help_text": "Maximum channel count used when downmix policy caps transcoded audio.",
    },
    "AllowNoAudio": {
        "label": "Allow Outputs Without Audio",
        "short_label": "No Audio",
        "section": "Audio",
        "rule_taxonomy": ("verification", "playback"),
        "strictness": "hard",
        "help_text": "Allows source files with no audio tracks to produce outputs without audio.",
    },
    "SubKeepLanguages": {
        "label": "Subtitle Language Policy",
        "short_label": "Subtitle Langs",
        "section": "Subtitles",
        "rule_taxonomy": ("playback",),
        "strictness": "hard",
        "help_text": "Subtitle language tags kept during subtitle processing and output muxing.",
    },
    "ConvertTx3gToSrt": {
        "label": "Convert TX3G to SRT",
        "short_label": "TX3G to SRT",
        "section": "Subtitles",
        "rule_taxonomy": ("compatibility", "output"),
        "strictness": "hard",
        "help_text": "Subtitle processing option that converts embedded TX3G/mov_text subtitle tracks to SRT.",
    },
    "DropTx3gAfterConversion": {
        "label": "Drop TX3G After Conversion",
        "short_label": "Drop TX3G",
        "section": "Subtitles",
        "rule_taxonomy": ("output",),
        "strictness": "hard",
        "help_text": "Subtitle processing option that drops original TX3G tracks after successful conversion.",
    },
    "CreateExternalTx3gSrtSidecars": {
        "label": "Write TX3G SRT Sidecars",
        "short_label": "TX3G Sidecars",
        "section": "Subtitles",
        "rule_taxonomy": ("output",),
        "strictness": "soft",
        "help_text": "Also writes external SRT sidecars for converted TX3G subtitles.",
    },
    "Tx3gExtractLanguages": {
        "label": "TX3G Extraction Languages",
        "short_label": "TX3G Langs",
        "section": "Subtitles",
        "rule_taxonomy": ("playback", "output"),
        "strictness": "hard",
        "help_text": "Language tags eligible for TX3G subtitle extraction and conversion.",
    },
    "Tx3gPreserveExistingSrt": {
        "label": "Preserve Existing TX3G SRTs",
        "short_label": "Keep TX3G SRTs",
        "section": "Subtitles",
        "rule_taxonomy": ("output",),
        "strictness": "advisory",
        "help_text": "Leaves matching existing TX3G-derived SRT sidecars in place unless reprocessing is explicitly enabled.",
    },
    "Tx3gTreatForcedAsSeparate": {
        "label": "Separate Forced TX3G Subtitles",
        "short_label": "Forced TX3G",
        "section": "Subtitles",
        "rule_taxonomy": ("playback", "output"),
        "strictness": "soft",
        "help_text": "Keeps forced TX3G subtitle outputs separate from full subtitle outputs.",
    },
    "ConvertBdpgsToSrt": {
        "label": "OCR BDPGS to SRT",
        "short_label": "BDPGS OCR",
        "section": "Subtitles",
        "rule_taxonomy": ("compatibility", "output"),
        "strictness": "hard",
        "help_text": "Subtitle processing option that OCRs BDPGS image subtitles to SRT using the configured OCR tool.",
    },
    "DropBdpgsAfterConversion": {
        "label": "Drop BDPGS After OCR",
        "short_label": "Drop BDPGS",
        "section": "Subtitles",
        "rule_taxonomy": ("output",),
        "strictness": "hard",
        "help_text": "Subtitle processing option that drops original BDPGS image subtitles after successful OCR conversion.",
    },
    "BdpgsExtractLanguages": {
        "label": "BDPGS OCR Languages",
        "short_label": "BDPGS Langs",
        "section": "Subtitles",
        "rule_taxonomy": ("playback", "output"),
        "strictness": "hard",
        "help_text": "Language tags eligible for BDPGS OCR subtitle conversion.",
    },
    "BdpgsOcrToolPath": {
        "label": "BDPGS OCR Tool Path",
        "short_label": "BDPGS Tool",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "output"),
        "strictness": "advanced",
        "help_text": "Advanced path to the BDPGS OCR tool used when BDPGS OCR conversion is enabled.",
    },
    "BdpgsOcrTessdataPath": {
        "label": "BDPGS Tessdata Path",
        "short_label": "Tessdata",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "output"),
        "strictness": "advanced",
        "help_text": "Advanced optional tessdata path used by the BDPGS OCR tool.",
    },
    "ConvertVobSubToSrt": {
        "label": "OCR VobSub to SRT",
        "short_label": "VobSub OCR",
        "section": "Subtitles",
        "rule_taxonomy": ("compatibility", "output"),
        "strictness": "hard",
        "help_text": "Subtitle processing option that OCRs VobSub bitmap subtitles to SRT using the configured OCR tool.",
    },
    "DropVobSubAfterConversion": {
        "label": "Drop VobSub After OCR",
        "short_label": "Drop VobSub",
        "section": "Subtitles",
        "rule_taxonomy": ("output",),
        "strictness": "hard",
        "help_text": "Subtitle processing option that drops embedded VobSub tracks after successful OCR conversion. External source files are not deleted.",
    },
    "VobSubExtractLanguages": {
        "label": "VobSub OCR Languages",
        "short_label": "VobSub Langs",
        "section": "Subtitles",
        "rule_taxonomy": ("playback", "output"),
        "strictness": "hard",
        "help_text": "Language tags eligible for VobSub OCR subtitle conversion.",
    },
    "VobSubOcrToolPath": {
        "label": "VobSub OCR Tool Path",
        "short_label": "VobSub Tool",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "output"),
        "strictness": "advanced",
        "help_text": "Advanced path to the VobSub OCR tool used when VobSub OCR conversion is enabled.",
    },
    "VobSubOcrTimeoutSeconds": {
        "label": "VobSub OCR Timeout",
        "short_label": "VobSub Timeout",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "verification"),
        "strictness": "advanced",
        "help_text": "Advanced timeout for external VobSub OCR commands.",
    },
    "TreatVobSubSignsSongsAsForced": {
        "label": "Treat VobSub Signs/Songs as Forced",
        "short_label": "VobSub Forced",
        "section": "Subtitles",
        "rule_taxonomy": ("playback", "output"),
        "strictness": "soft",
        "help_text": "Marks kept or OCR-converted VobSub signs/songs subtitles as forced.",
    },
    "SubtitleExtractTimeoutSeconds": {
        "label": "Subtitle Extraction Timeout",
        "short_label": "Extract Timeout",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "verification"),
        "strictness": "advanced",
        "help_text": "Advanced timeout for subtitle extraction helper commands.",
    },
    "SubtitleProbeTimeoutSeconds": {
        "label": "Subtitle Probe Timeout",
        "short_label": "Probe Timeout",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "verification"),
        "strictness": "advanced",
        "help_text": "Advanced timeout for subtitle probing helper commands.",
    },
    "BdpgsOcrTimeoutSeconds": {
        "label": "BDPGS OCR Timeout",
        "short_label": "BDPGS Timeout",
        "section": "Advanced",
        "rule_taxonomy": ("advanced", "verification"),
        "strictness": "advanced",
        "help_text": "Advanced timeout for external BDPGS OCR commands.",
    },
}

_NUMERIC_LIMITS_BY_KEY = {
    "MovieRoute1080pTargetSizeGB": {"min": 1, "step": 1, "unit": "GB"},
    "MovieRoute1440pTargetSizeGB": {"min": 1, "step": 1, "unit": "GB"},
    "MovieRoute4KTargetSizeGB": {"min": 1, "step": 1, "unit": "GB"},
    "TVRoute1080pTargetSizeGB": {"min": 1, "step": 1, "unit": "GB"},
    "TVRoute1440pTargetSizeGB": {"min": 1, "step": 1, "unit": "GB"},
    "TVRoute4KTargetSizeGB": {"min": 1, "step": 1, "unit": "GB"},
    "Route1080pUpperHeightTolerancePercent": {"min": 0, "max": 100, "step": 0.000001, "unit": "percent"},
    "Route1080pMaxVideoBitrateMbps": {"min": 1, "max": 500, "step": 1, "unit": "Mbps"},
    "Route1440pLowerHeightTolerancePercent": {"min": 0, "max": 100, "step": 0.000001, "unit": "percent"},
    "Route1440pUpperHeightTolerancePercent": {"min": 0, "max": 100, "step": 0.000001, "unit": "percent"},
    "Route1440pMaxVideoBitrateMbps": {"min": 1, "max": 500, "step": 1, "unit": "Mbps"},
    "Route4KLowerHeightTolerancePercent": {"min": 0, "max": 100, "step": 0.000001, "unit": "percent"},
    "Route4KMaxVideoBitrateMbps": {"min": 1, "max": 500, "step": 1, "unit": "Mbps"},
    "H264RemuxMaxBitrateMbps": {"min": 1, "max": 500, "step": 1, "unit": "Mbps"},
    "H264RemuxMaxHeight": {"min": 1, "max": 4320, "step": 1, "unit": "pixels"},
    "MaxEncodeGrowthPercent": {"min": 0, "max": 1000, "step": 1, "unit": "percent"},
    "CompatibilityEncodeGrowthPercent": {"min": 0, "max": 1000, "step": 1, "unit": "percent"},
    "EncodeWasteGuardMinProgressPercent": {"min": 0, "max": 95, "step": 1, "unit": "percent"},
    "EncodeWasteGuardMinElapsedSeconds": {"min": 0, "max": 86400, "step": 1, "unit": "seconds"},
    "EncodeWasteGuardOversizeMarginPercent": {"min": 0, "max": 1000, "step": 1, "unit": "percent"},
    "EncodeWasteGuardConsecutiveSamples": {"min": 1, "max": 10, "step": 1},
    "EncodeWasteGuardPollSeconds": {"min": 1, "max": 600, "step": 1, "unit": "seconds"},
    "EncodeWasteGuardPreflightSampleSeconds": {"min": 5, "max": 600, "step": 1, "unit": "seconds"},
    "EncodeWasteGuardPreflightSampleCount": {"min": 1, "max": 10, "step": 1},
    "EncodeWasteGuardPreflightTimeoutSeconds": {"min": 30, "max": 86400, "step": 1, "unit": "seconds"},
    "MinFreeSpaceGB": {"min": 0, "step": 1, "unit": "GB"},
    "OutsourceMinFreeSpaceGB": {"min": 0, "step": 1, "unit": "GB"},
    "PendingPublishDrainBatchSize": {"min": 1, "max": 1000000, "step": 1},
    "FailureArtifactWarningThresholdGB": {"min": 0, "step": 1, "unit": "GB"},
    "FailureArtifactRetentionDays": {"min": 0, "step": 1, "unit": "days"},
    "FailureArtifactCleanupTargetGB": {"min": 0, "step": 1, "unit": "GB"},
    "VideoQuality": {"min": 1, "max": 51, "step": 1},
    "AudioMaxChannels": {"min": 1, "max": 16, "step": 1, "unit": "channels"},
    "MergeThresholdMs": {"min": 0, "max": 5000, "step": 1, "unit": "ms"},
    "FFmpegEncodeTimeoutSeconds": {"min": 1, "step": 1, "unit": "seconds"},
    "FFmpegCpuEncodeTimeoutSeconds": {"min": 1, "step": 1, "unit": "seconds"},
    "CpuEncodeMutexWaitSeconds": {"min": 0, "max": 86400, "step": 1, "unit": "seconds"},
    "FFmpegRemuxTimeoutSeconds": {"min": 1, "step": 1, "unit": "seconds"},
    "MkvmergeRemuxTimeoutSeconds": {"min": 60, "max": 86400, "step": 1, "unit": "seconds"},
    "SubtitleExtractTimeoutSeconds": {"min": 30, "max": 3600, "step": 1, "unit": "seconds"},
    "SubtitleProbeTimeoutSeconds": {"min": 5, "max": 600, "step": 1, "unit": "seconds"},
    "BdpgsOcrTimeoutSeconds": {"min": 60, "max": 14400, "step": 1, "unit": "seconds"},
    "VobSubOcrTimeoutSeconds": {"min": 60, "max": 14400, "step": 1, "unit": "seconds"},
    "TransientFailureRetryLimit": {"min": 1, "max": 100, "step": 1},
    "ConsecutiveRoundFailureBlockLimit": {"min": 1, "max": 1000, "step": 1},
    "ConsecutiveRoundFailureProbeBackoffSeconds": {"min": 30, "max": 86400, "step": 1, "unit": "seconds"},
    "PendingPublishBacklogBlockThreshold": {"min": 1, "max": 1000000, "step": 1},
    "PendingPublishDeferredBlockThreshold": {"min": 1, "max": 1000000, "step": 1},
    "AutonomyPendingTotalReviewBytes": {"min": 1048576, "max": 10995116277760, "step": 1073741824, "unit": "bytes"},
    "AutonomyPendingTotalBlockBytes": {"min": 1048576, "max": 10995116277760, "step": 1073741824, "unit": "bytes"},
    "PipelineDebugLogMaxBytes": {"min": 1048576, "max": 2147483647, "step": 1, "unit": "bytes"},
    "PauseFlagReviewSeconds": {"min": 60, "max": 86400, "step": 1, "unit": "seconds"},
    "PauseFlagBlockSeconds": {"min": 300, "max": 604800, "step": 1, "unit": "seconds"},
    "LocalWorkerHeartbeatGraceSeconds": {"min": 60, "max": 86400, "step": 1, "unit": "seconds"},
    "QueueExecutionMaxRunnablePerRound": {"min": 1, "max": 1000000, "step": 1},
    "StateDbMaintenanceIntervalSeconds": {"min": 60, "max": 604800, "step": 1, "unit": "seconds"},
    "StateDbWalReviewBytes": {"min": 1048576, "max": 2147483647, "step": 1, "unit": "bytes"},
    "StateDbCompletedJobsMaxRows": {"min": 1000, "max": 10000000, "step": 1},
    "CoordinatorMaxJobRetries": {"min": 1, "max": 100, "step": 1},
    "SourceScanIntervalSeconds": {"min": 0, "step": 1, "unit": "seconds"},
    "ProcessedIndexRefreshSeconds": {"min": 0, "step": 1, "unit": "seconds"},
    "RobocopyTimeoutSeconds": {"min": 60, "max": 172800, "step": 1, "unit": "seconds"},
    "SourceScanTimeoutSeconds": {"min": 30, "max": 86400, "step": 1, "unit": "seconds"},
    "IndexScanTimeoutSeconds": {"min": 30, "max": 86400, "step": 1, "unit": "seconds"},
    "CleanupScanTimeoutSeconds": {"min": 30, "max": 7200, "step": 1, "unit": "seconds"},
    "WatchScanTimeoutSeconds": {"min": 1, "max": 86400, "step": 1, "unit": "seconds"},
    "CleanupStaleAgeHours": {"min": 1, "max": 720, "step": 1, "unit": "hours"},
    "FallbackCpuQuality": {"min": 1, "max": 51, "step": 1},
    "OutputSizeMultiplier": {"min": 0.1, "max": 2.0, "step": "any"},
    "CpuEncodeMaxThreads": {"min": 0, "max": 256, "step": 1, "unit": "threads"},
}

_KIND_VALUE_TYPES = {
    "bool": "boolean",
    "combo": "string",
    "combo_int": "integer",
    "float": "number",
    "int": "integer",
    "json": "json",
    "list": "list",
    "optional_float": "number",
    "optional_int": "integer",
    "optional_string": "string",
    "path": "path",
    "string": "string",
}

def _value_type(field: dict[str, object]) -> str:
    kind = str(field.get("kind") or "")
    return _KIND_VALUE_TYPES.get(kind, "unknown")

def _advanced_visibility(field: dict[str, object]) -> str:
    return "advanced" if field.get("page") == "Advanced" else "standard"

def _display_section(field: dict[str, object], display_metadata: dict[str, object]) -> str:
    if "section" in display_metadata:
        return str(display_metadata["section"])
    legacy_section = str(field.get("section") or "")
    return _DISPLAY_SECTION_BY_LEGACY_SECTION.get(legacy_section, legacy_section)

def _rule_taxonomy(field: dict[str, object], display_metadata: dict[str, object], display_section: str) -> tuple[str, ...]:
    if "rule_taxonomy" in display_metadata:
        return tuple(str(value) for value in display_metadata["rule_taxonomy"])
    return _DEFAULT_DISPLAY_RULE_BY_SECTION.get(display_section, ("advisory",))

def _strictness(field: dict[str, object], display_metadata: dict[str, object], display_section: str) -> str:
    if "strictness" in display_metadata:
        return str(display_metadata["strictness"])
    if display_section == "Advanced" or field.get("page") in {"Advanced", "Network", "Queue"}:
        return "advanced"
    if display_section in {"Source / Compatibility", "Routing", "Container", "Verification / Publish"}:
        return "hard"
    return "soft"

def _enrich_field_definition(field: dict[str, object], override_groups: dict[str, str]) -> dict[str, object]:
    key = str(field["key"])
    override_group = override_groups.get(key)
    limits = _NUMERIC_LIMITS_BY_KEY.get(key, {})
    display_metadata = _PHASE3_DISPLAY_METADATA_BY_KEY.get(key, {})
    display_section = _display_section(field, display_metadata)
    enriched = dict(field)
    enriched.update(
        {
            "label": display_metadata.get("label", field.get("label")),
            "short_label": display_metadata.get("short_label", display_metadata.get("label", field.get("label"))),
            "help_text": display_metadata.get("help_text", field.get("help")),
            "section": display_section,
            "rule_taxonomy": _rule_taxonomy(field, display_metadata, display_section),
            "strictness": _strictness(field, display_metadata, display_section),
            "unavailable_reason": display_metadata.get("unavailable_reason"),
            "persisted_key": key,
            "override_group": override_group,
            "scope": _metadata_scope(field, override_group),
            "value_type": _value_type(field),
            "allowed_values": tuple(field["choices"]) if "choices" in field else None,
            "min": limits.get("min"),
            "max": limits.get("max"),
            "step": limits.get("step"),
            "unit": limits.get("unit"),
            "default_source": "field_definition" if "default" in field else "unknown",
            "default_value": field.get("default"),
            "library_override_allowed": override_group is not None,
            "advanced_visibility": _advanced_visibility(field),
            "validation_owner": "backend",
            "runtime_consumer": "deferred",
            "migration_status": "stable_persisted_key",
        }
    )
    if "library_profile_designations" in display_metadata:
        enriched["library_profile_designations"] = tuple(
            str(value) for value in display_metadata["library_profile_designations"]
        )
    return enriched

def _enrich_field_definitions(fields: tuple[dict[str, object], ...]) -> tuple[dict[str, object], ...]:
    return tuple(_enrich_field_definition(dict(field), METADATA_LIBRARY_OVERRIDE_GROUP_BY_KEY) for field in fields)
