"""Combined settings field definitions in public render order."""

from __future__ import annotations

from .field_display import (
    METADATA_ADVANCED_VISIBILITY_VALUES,
    METADATA_RULE_TAXONOMY_VALUES,
    METADATA_STRICTNESS_VALUES,
    _enrich_field_definitions,
)
from .field_registry import _RAW_CONFIG_FIELD_DEFINITIONS
from .field_scope import (
    METADATA_LIBRARY_OVERRIDE_GROUP_BY_KEY,
    METADATA_LIBRARY_OVERRIDE_KEYS_BY_GROUP,
    METADATA_MIGRATION_STATUS_VALUES,
    METADATA_SCOPE_VALUES,
)

CONFIG_FIELD_DEFINITIONS = _enrich_field_definitions(_RAW_CONFIG_FIELD_DEFINITIONS)

CONFIG_MANAGED_KEYS = [field["key"] for field in CONFIG_FIELD_DEFINITIONS]

__all__ = [
    "CONFIG_FIELD_DEFINITIONS",
    "CONFIG_MANAGED_KEYS",
    "METADATA_ADVANCED_VISIBILITY_VALUES",
    "METADATA_LIBRARY_OVERRIDE_GROUP_BY_KEY",
    "METADATA_LIBRARY_OVERRIDE_KEYS_BY_GROUP",
    "METADATA_MIGRATION_STATUS_VALUES",
    "METADATA_RULE_TAXONOMY_VALUES",
    "METADATA_SCOPE_VALUES",
    "METADATA_STRICTNESS_VALUES",
]
