"""Policy and enum-like static metadata for settings controls."""

from __future__ import annotations

from mediapipeline.core.config.constants import (
    AUDIO_PASSTHROUGH_PROFILE_DEFAULT,
    AUDIO_PASSTHROUGH_PROFILE_DESCRIPTIONS,
    AUDIO_PASSTHROUGH_PROFILE_NAMES,
    LOG_LEVEL_VALUES,
    ROUTE_THRESHOLD_MODE_DEFAULT,
    ROUTE_THRESHOLD_MODE_DESCRIPTIONS,
    ROUTE_THRESHOLD_MODE_NAMES,
    ROUTING_PROFILE_DEFAULT,
    ROUTING_PROFILE_DESCRIPTIONS,
    ROUTING_PROFILE_NAMES,
    SIZE_GUARD_MODE_DEFAULT,
    SIZE_GUARD_MODE_DESCRIPTIONS,
    SIZE_GUARD_MODE_NAMES,
)
