"""Subtitle-page settings field definitions."""

from __future__ import annotations


SUBTITLE_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "SubKeepLanguages",
        "label": "Subtitle Languages",
        "kind": "list",
        "help": "Subtitle languages to keep during remux/cleanup.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "AllowSubtitleHelperFallback",
        "label": "Allow Subtitle Helper Fallback",
        "kind": "bool",
        "default": False,
        "help": "When off, a broken ASS helper self-check blocks launch instead of silently falling back to degraded conversion behavior.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "ConvertTx3gToSrt",
        "label": "Convert TX3G to SRT",
        "kind": "bool",
        "help": "Convert embedded MP4 Timed Text / mov_text subtitle tracks to SRT tracks during output muxing.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "DropTx3gAfterConversion",
        "label": "Drop TX3G After Conversion",
        "kind": "bool",
        "help": "Drop the original TX3G track after conversion. When disabled, FFmpeg MP4 outputs keep the original TX3G track when the container supports it.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "CreateExternalTx3gSrtSidecars",
        "label": "Write TX3G SRT Sidecars",
        "kind": "bool",
        "help": "Also write external TX3G-derived SRT files next to the output. Converted subtitles are still muxed into the output when conversion is enabled.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "Tx3gExtractLanguages",
        "label": "TX3G Extract Languages",
        "kind": "list",
        "help": "Language tags eligible for tx3g-to-SRT extraction. Undefined tracks use und.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "Tx3gPreserveExistingSrt",
        "label": "Preserve Existing TX3G SRTs",
        "kind": "bool",
        "help": "Leave matching external SRT files in place unless full reprocessing is explicitly enabled.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "Tx3gTreatForcedAsSeparate",
        "label": "Separate Forced TX3G",
        "kind": "bool",
        "help": "Include forced status in tx3g SRT filenames so forced and full subtitles do not collide.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "ConvertBdpgsToSrt",
        "label": "OCR BDPGS to SRT",
        "kind": "bool",
        "default": True,
        "help": "OCR Blu-ray PGS image subtitles to SRT tracks using an external PgsToSrt-compatible tool.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "DropBdpgsAfterConversion",
        "label": "Drop BDPGS After OCR",
        "kind": "bool",
        "help": "Drop the original BDPGS image subtitle after OCR conversion. When disabled, MKV outputs keep the original image subtitle track.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "BdpgsExtractLanguages",
        "label": "BDPGS OCR Languages",
        "kind": "list",
        "help": "Language tags eligible for BDPGS OCR. Undefined tracks use und.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "BdpgsOcrToolPath",
        "label": "BDPGS OCR Tool",
        "kind": "string",
        "help": "Path to PgsToSrt.exe or PgsToSrt.dll. Relative paths are resolved from the Pipeline folder.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "BdpgsOcrTessdataPath",
        "label": "BDPGS Tessdata",
        "kind": "string",
        "help": "Optional Tesseract tessdata folder for BDPGS OCR.",
    },
    {
        "page": "Subtitles",
        "section": "VobSub Subtitles",
        "key": "ConvertVobSubToSrt",
        "label": "OCR VobSub to SRT",
        "kind": "bool",
        "help": "OCR DVD/VobSub bitmap subtitles to SRT tracks using Subtitle Edit 4.x with Tesseract.",
    },
    {
        "page": "Subtitles",
        "section": "VobSub Subtitles",
        "key": "DropVobSubAfterConversion",
        "label": "Drop VobSub After OCR",
        "kind": "bool",
        "help": "Drop embedded VobSub tracks after OCR conversion. External .idx/.sub source files are never deleted.",
    },
    {
        "page": "Subtitles",
        "section": "VobSub Subtitles",
        "key": "VobSubExtractLanguages",
        "label": "VobSub OCR Languages",
        "kind": "list",
        "help": "Language tags eligible for VobSub OCR. Undefined tracks use und.",
    },
    {
        "page": "Subtitles",
        "section": "VobSub Subtitles",
        "key": "VobSubOcrToolPath",
        "label": "VobSub OCR Tool",
        "kind": "string",
        "help": "Path to Subtitle Edit 4.x SubtitleEdit.exe. Relative paths are resolved from the Pipeline folder.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "DropAssAfterConversion",
        "label": "Drop ASS After Conversion",
        "kind": "bool",
        "help": "Remove the original ASS track after an SRT conversion when enabled.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "RemoveKaraoke",
        "label": "Filter Karaoke Styling",
        "kind": "bool",
        "help": "Exclude karaoke-style events during ASS to SRT conversion.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "KeepSignsAndSongs",
        "label": "Keep Signs & Songs",
        "kind": "bool",
        "help": "Preserve supplemental Signs & Songs subtitle tracks as separate tracks.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "TreatAssSignsSongsAsForced",
        "label": "ASS Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark ASS/SSA supplemental Signs & Songs tracks as forced when they are kept or converted.",
    },
    {
        "page": "Subtitles",
        "section": "TX3G Subtitles",
        "key": "TreatTx3gSignsSongsAsForced",
        "label": "TX3G Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark TX3G supplemental Signs & Songs tracks as forced when converted.",
    },
    {
        "page": "Subtitles",
        "section": "BDPGS Subtitles",
        "key": "TreatBdpgsSignsSongsAsForced",
        "label": "BDPGS Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark BDPGS supplemental Signs & Songs tracks as forced when kept or OCR-converted.",
    },
    {
        "page": "Subtitles",
        "section": "VobSub Subtitles",
        "key": "TreatVobSubSignsSongsAsForced",
        "label": "VobSub Signs/Songs Forced",
        "kind": "bool",
        "help": "Mark VobSub supplemental Signs & Songs tracks as forced when kept or OCR-converted.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "StripFormatting",
        "label": "Strip ASS Formatting",
        "kind": "bool",
        "help": "Remove inline ASS formatting when converting to SRT.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "MergeAdjacent",
        "label": "Merge Adjacent Cues",
        "kind": "bool",
        "help": "Merge neighboring subtitle cues that are separated by a very small gap.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "MergeThresholdMs",
        "label": "Subtitle Merge Window (ms)",
        "kind": "int",
        "default": 150,
        "help": "Maximum subtitle cue gap, in milliseconds, for adjacent merge logic.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "SubSDHTitleKeywords",
        "label": "SDH Title Keywords",
        "kind": "list",
        "help": "Keywords used to identify SDH / hearing-impaired subtitle tracks.",
    },
    {
        "page": "Subtitles",
        "section": "Shared Subtitle Policy",
        "key": "SubSupplementalKeywords",
        "label": "Supplemental Title Keywords",
        "kind": "list",
        "help": "Keywords used to identify sign/song/supplemental subtitle tracks.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "ExcludeSubtitleStyles",
        "label": "Excluded Subtitle Styles",
        "kind": "list",
        "help": "ASS style names or patterns that should be filtered out during conversion.",
    },
    {
        "page": "Subtitles",
        "section": "ASS / SSA Subtitles",
        "key": "IncludeSubtitleStyles",
        "label": "Included Subtitle Styles",
        "kind": "list",
        "help": "Optional allowlist of ASS style names or patterns to keep.",
    },
)
