"""Video-page settings field definitions."""

from __future__ import annotations

from ..metadata_support import (
    ENCODE_LADDER_DESCRIPTIONS,
    ENCODE_TUNING_PRESET_DESCRIPTIONS,
)
from .policy import (
    DYNAMIC_HDR_POLICY_DEFAULT,
    DYNAMIC_HDR_POLICY_DESCRIPTIONS,
    DYNAMIC_HDR_POLICY_NAMES,
    ENCODER_BACKEND_DEFAULT,
    ENCODER_BACKEND_DESCRIPTIONS,
    ENCODER_BACKEND_NAMES,
)


VIDEO_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoCodec",
        "label": "Hardware / Codec",
        "kind": "combo",
        "choices": (
            "hevc_nvenc",
            "hevc_qsv",
            "hevc_amf",
            "libx265",
            "h264_nvenc",
            "h264_qsv",
            "h264_amf",
            "libx264",
            "av1_nvenc",
            "av1_qsv",
            "av1_amf",
            "libaom-av1",
        ),
        "help": "Applies only when encoding is required. Selects the video encoder used for encoded output.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "EncoderBackend",
        "label": "Encoder Backend Preference",
        "kind": "combo",
        "choices": ENCODER_BACKEND_NAMES,
        "default": ENCODER_BACKEND_DEFAULT,
        "choice_help": ENCODER_BACKEND_DESCRIPTIONS,
        "help": "Stored backend preference for encoder capability diagnostics. Normal encode selection remains controlled by VideoCodec until descriptor-backed activation is validated.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoPreset",
        "label": "Preset",
        "kind": "combo",
        "choices": ("p1", "p2", "p3", "p4", "p5", "p6", "p7"),
        "help": "Applies only when encoding is required. p1 is fastest with the weakest compression efficiency; p7 is slowest with the best compression efficiency.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoQuality",
        "label": "Quality",
        "kind": "combo_int",
        "choices": ("18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"),
        "default": 22,
        "help": "Applies only when encoding is required. Lower quality numbers target cleaner, larger output; higher numbers target softer, smaller output.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "OutputContainer",
        "label": "Container",
        "kind": "combo",
        "choices": ("mkv", "mp4"),
        "help": "Output container format used when muxing or encoding creates the saved output; it does not decide whether video is re-encoded.",
    },
    {
        "page": "Video",
        "section": "Dynamic HDR",
        "key": "DynamicHdrPolicy",
        "label": "Dynamic HDR Policy",
        "kind": "combo",
        "choices": DYNAMIC_HDR_POLICY_NAMES,
        "default": DYNAMIC_HDR_POLICY_DEFAULT,
        "choice_help": DYNAMIC_HDR_POLICY_DESCRIPTIONS,
        "help": "Controls Dolby Vision and HDR10+ preservation handling. Warn is the current safe default until preserve modes have real-media remux evidence.",
    },
    {
        "page": "Video",
        "section": "Dynamic HDR",
        "key": "DoviToolPath",
        "label": "dovi_tool Path",
        "kind": "optional_string",
        "default": "",
        "help": "Optional path override for dovi_tool.exe. Leave blank to use the bundled tool drop-zone when present.",
    },
    {
        "page": "Video",
        "section": "Dynamic HDR",
        "key": "Hdr10PlusToolPath",
        "label": "hdr10plus_tool Path",
        "kind": "optional_string",
        "default": "",
        "help": "Optional path override for hdr10plus_tool.exe. Leave blank to use the bundled tool drop-zone when present.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "EncodeTuningPreset",
        "label": "NVENC tuning bundle",
        "kind": "combo",
        "choices": ("balanced_nvenc", "quality_nvenc", "fast_nvenc", "compatibility", "custom_legacy_flags"),
        "default": "balanced_nvenc",
        "choice_help": ENCODE_TUNING_PRESET_DESCRIPTIONS,
        "help": "Applies only when encoding is required. Chooses the encoder speed/compression tradeoff without changing copy/remux decisions by itself.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "EncodeLadder",
        "label": "How encode targets are calculated",
        "kind": "combo",
        "choices": ("auto", "tv_balanced", "tv_space_saver", "movie_balanced", "movie_archive", "plex_compat"),
        "default": "auto",
        "choice_help": ENCODE_LADDER_DESCRIPTIONS,
        "help": "Applies only when encoding is required. Chooses target selection for one output; it does not produce multiple renditions.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "ExtraVideoFlags",
        "label": "Advanced Encoder Flags",
        "kind": "list",
        "help": "Advanced raw FFmpeg/NVENC flags. Applies only when encoding is required through explicit legacy/custom flag paths.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "RemuxSafeVideoCodecs",
        "label": "Remux-Safe Video Codecs",
        "kind": "list",
        "help": "Used before processing to decide whether source video codecs may remain direct-copy/remux candidates without re-encoding.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "FallbackCpuQuality",
        "label": "CPU Fallback Quality",
        "kind": "optional_int",
        "help": "Optional quality target used when GPU encoding falls back to CPU. Note: this is a libx265 -crf value, not an NVENC -cq, so a value tuned for NVENC may produce a different size on CPU.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodePreset",
        "label": "CPU Encode Preset",
        "kind": "combo",
        "choices": (
            "ultrafast", "superfast", "veryfast", "faster", "fast",
            "medium", "slow", "slower", "veryslow", "placebo",
        ),
        "default": "medium",
        "help": "libx265 -preset used for CPU encodes (fallback or primary). Faster presets are responsive but lose quality; slower presets compress better but can run for many hours.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodeProcessPriority",
        "label": "CPU Encode Process Priority",
        "kind": "combo",
        "choices": ("inherit", "idle", "belownormal", "normal", "abovenormal", "high"),
        "default": "belownormal",
        "help": "Windows process priority class applied to ffmpeg when running a CPU encode. BelowNormal keeps the desktop UI responsive while libx265 saturates the cores.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "FFmpegCpuEncodeTimeoutSeconds",
        "label": "CPU Encode Timeout (seconds)",
        "kind": "int",
        "default": 43200,
        "help": "Hard ceiling for ffmpeg CPU encode wall-clock time. CPU encodes can take 5-15x longer than NVENC, so this should usually be larger than the GPU timeout.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "MkvmergeRemuxTimeoutSeconds",
        "label": "Mkvmerge Remux Timeout (seconds)",
        "kind": "int",
        "default": 7200,
        "help": "Hard ceiling for the mkvmerge step of a remux job. Defaults to 2 hours, matching the ffmpeg-remux timeout. Replaces a former hard-coded 600s ceiling that was too short for large MKVs over slow scratch volumes.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodeMaxThreads",
        "label": "CPU Encode Max Threads",
        "kind": "int",
        "default": 0,
        "help": "Maximum number of libx265 threads. 0 = autodetect (use every logical core, default libav behavior). Setting a positive value caps both ffmpeg -threads and the libx265 pool/frame-thread budget so the desktop UI stays responsive on smaller CPUs.",
    },
)
