from __future__ import annotations

import json
import re
import sys
import tempfile
import unittest
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mediapipeline_desktop_app.api import LocalApiServer
from mediapipeline_desktop_app.api.static_files import render_index
from mediapipeline_desktop_app.application import MediaPipelineApplicationFacade
from mediapipeline_desktop_app.models import ResolvedPaths


PROJECT_ROOT = Path(__file__).resolve().parents[2]


class SampleValidationService:
    def __init__(self) -> None:
        self.opened: list[Path] = []

    def open_path(self, path: Path) -> None:
        self.opened.append(path)


def _resolved(root: Path) -> ResolvedPaths:
    state = root / "State"
    return ResolvedPaths(
        app_root=root,
        workspace_root=root,
        pipeline_path=root / "Pipeline" / "MediaPipeline.ps1",
        config_path=root / "config.psd1",
        audit_script_path=root / "Pipeline" / "Audit-MediaLibrary.ps1",
        rerun_script_path=root / "Pipeline" / "Rerun-FailedFromCsv.ps1",
        powershell_host=str(root / "pwsh.exe"),
        local_base=root,
        state_root=state,
        active_jobs_path=state / "ActiveJobs",
        source_movies=root / "Movies",
        source_tv=root / "TV",
        pending_push_path=state / "PendingPush",
        queue_snapshot_path=state / "Progress" / "queue_snapshot.json",
        completed_manifest_path=state / "completed_jobs.jsonl",
        config_data={"Outsource": str(root / "Outsource")},
    )


def _request_json(url: str, *, method: str = "GET", payload: object | None = None, token: str | None = None) -> tuple[int, dict]:
    headers = {}
    data = None
    if token:
        headers["Authorization"] = f"Bearer {token}"
    if payload is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(payload, ensure_ascii=False, allow_nan=False).encode("utf-8")
    request = Request(url, data=data, headers=headers, method=method)
    try:
        with urlopen(request, timeout=5) as response:  # noqa: S310 - localhost test server
            return response.status, json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        return exc.code, json.loads(exc.read().decode("utf-8"))


def _sample_request(source: Path, output: Path, *, decision: str = "accepted") -> dict[str, object]:
    return {
        "schema": "sample_validation_record.v1",
        "shell": "webview",
        "source_path": str(source),
        "output_path": str(output),
        "sample_label": "Serial Experiments Lain - S02E01 - Weird.mkv",
        "sample_category": "h264-remux-safe",
        "proof_strength": "exact-path",
        "operator_decision": decision,
        "checks": {
            "queue_route_checked": True,
            "ffmpeg_log_checked": True,
            "subtitle_checked": True,
            "audio_checked": True,
            "completed_output_checked": True,
            "sidecar_manifest_checked": True,
            "size_growth_checked": True,
            "pending_publish_checked": False,
            "diagnostics_checked": True,
        },
        "evidence": {
            "queue": [{"field": "source", "value": str(source), "strength": "exact"}],
            "completed": [{"field": "output", "value": str(output), "strength": "exact"}],
            "pending_publish": [],
            "diagnostics": [{"field": "run logs", "value": "sample completed without errors", "strength": "advisory"}],
            "commands": [],
        },
        "operator_notes": "Plex playback, subtitle, audio, output size, sidecar, and diagnostics were checked.",
    }


def _assert_namespace_export(testcase: unittest.TestCase, source: str, namespace: str, symbol: str) -> None:
    testcase.assertRegex(
        source,
        rf"window\.{re.escape(namespace)}\s*=\s*\{{[\s\S]*?\b{re.escape(symbol)}\b\s*(?:,|:|\n\s*\}})",
    )


def _write_validation_worksheet(root: Path, source: Path, *, category: str = "h264-remux-safe", expected_route: str = "remux") -> Path:
    worksheet = root / "Docs" / "RealMediaValidationRuns" / "real_media_validation_unit.md"
    worksheet.parent.mkdir(parents=True, exist_ok=True)
    worksheet.write_text(
        "\n".join(
            [
                "<!--",
                "Generated by New-RealMediaValidationWorksheet.ps1.",
                "-->",
                "# Real-Media Validation Evidence Template",
                "## Validation Run Identity",
                "| Field | Value |",
                "|---|---|",
                "| Operator | Unit Test |",
                "| Launch surface | WebView preview |",
                "## Sample Batch",
                "| # | Source file | Category | Expected route |",
                "|---|---|---|---|",
                f"| 1 | {source} | {category} | {expected_route} |",
                "## WebView Pilot Evidence Packet Capture",
                "| Sample # | Sample label | Packet status | Queue route proof | Completed output/sidecar proof | Diagnostics/run-log proof | Pending Publish posture | Playback/subtitle/audio/size proof | Stop condition hit? |",
                "|---|---|---|---|---|---|---|---|---|",
                "| 1 | Serial Experiments Lain - S02E01 - Weird.mkv | pilot-evidence-ready | ready | ready | ready | reviewed | checked | no |",
            ]
        ),
        encoding="utf-8",
    )
    return worksheet


class SampleValidationApiTests(unittest.TestCase):
    def test_sample_validation_preview_append_read_and_tail_are_backend_owned(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            source = resolved.source_tv / "Serial Experiments Lain" / "Season 02" / "Serial Experiments Lain S02E01 Weird.mkv"
            output = root / "Outsource" / "TV" / "Serial Experiments Lain" / "Season 02" / "Serial Experiments Lain - S02E01 - Weird.mkv"
            source.parent.mkdir(parents=True, exist_ok=True)
            output.parent.mkdir(parents=True, exist_ok=True)
            source.write_bytes(b"source-media")
            output.write_bytes(b"output-media")
            resolved.queue_snapshot_path.parent.mkdir(parents=True, exist_ok=True)
            resolved.queue_snapshot_path.write_text(
                json.dumps({"rows": [{"source_path": str(source), "route": "remux", "route_reason": "copy safe"}]}),
                encoding="utf-8",
            )
            resolved.completed_manifest_path.parent.mkdir(parents=True, exist_ok=True)
            resolved.completed_manifest_path.write_text(
                json.dumps({"source_path": str(source), "output_path": str(output), "sidecar_path": str(output) + ".pipeline.json", "route": "remux"})
                + "\n",
                encoding="utf-8",
            )
            run_log = root / "RunLogs" / "run.stderr.log"
            run_log.parent.mkdir(parents=True, exist_ok=True)
            run_log.write_text(f"ffmpeg remux complete for sample source={source} output={output}\n", encoding="utf-8")
            worksheet = root / "Docs" / "RealMediaValidationRuns" / "real_media_validation_unit.md"
            worksheet.parent.mkdir(parents=True, exist_ok=True)
            worksheet.write_text(
                "\n".join(
                    [
                        "<!--",
                        "Generated by New-RealMediaValidationWorksheet.ps1.",
                        "-->",
                        "# Real-Media Validation Evidence Template",
                        "## Validation Run Identity",
                        "| Field | Value |",
                        "|---|---|",
                        "| Operator | Unit Test |",
                        "| Launch surface | WebView preview |",
                        "## Sample Batch",
                        "| # | Source file | Category | Expected route |",
                        "|---|---|---|---|",
                        f"| 1 | {source} | h264-remux-safe | remux |",
                        "## WebView Pilot Evidence Packet Capture",
                        "| Sample # | Sample label | Packet status | Queue route proof | Completed output/sidecar proof | Diagnostics/run-log proof | Pending Publish posture | Playback/subtitle/audio/size proof | Stop condition hit? |",
                        "|---|---|---|---|---|---|---|---|---|",
                        "| 1 | Serial Experiments Lain - S02E01 - Weird.mkv | pilot-evidence-ready | ready | ready | ready | reviewed | checked | no |",
                    ]
                ),
                encoding="utf-8",
            )
            pending_manifest = resolved.pending_push_path / "parked.manifest.json"
            pending_manifest.parent.mkdir(parents=True, exist_ok=True)
            pending_manifest.write_text('{"pending":true}', encoding="utf-8")
            watched = {
                source: source.read_bytes(),
                output: output.read_bytes(),
                resolved.queue_snapshot_path: resolved.queue_snapshot_path.read_bytes(),
                resolved.completed_manifest_path: resolved.completed_manifest_path.read_bytes(),
                pending_manifest: pending_manifest.read_bytes(),
                run_log: run_log.read_bytes(),
                worksheet: worksheet.read_bytes(),
            }

            service = SampleValidationService()
            facade = MediaPipelineApplicationFacade(service, app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                request = _sample_request(source, output)

                denied_status, denied = _request_json(f"{server.url}/api/sample-validation/append", method="POST", payload=request)
                self.assertEqual(denied_status, 401)
                self.assertEqual(denied["error"], "unauthorized")
                self.assertFalse((resolved.state_root / "Validation" / "sample_validation_log.jsonl").exists())

                preview_status, preview = _request_json(
                    f"{server.url}/api/sample-validation/preview",
                    method="POST",
                    payload=request,
                    token="sample-token",
                )
                self.assertEqual(preview_status, 200)
                self.assertTrue(preview["ok"])
                self.assertEqual(preview["record"]["schema"], "sample_validation_record.v1")
                self.assertEqual(preview["current_evidence"]["schema_version"], "desktop_sample_validation_current_evidence.v1")
                self.assertEqual(preview["current_evidence"]["status"], "current")
                self.assertEqual(preview["current_evidence"]["severity"], "info")
                self.assertTrue(preview["current_evidence"]["matches"]["completed_output"])
                self.assertTrue(preview["current_evidence"]["matches"]["diagnostics_source_or_output"])
                self.assertIn("completed_output=yes", preview["current_evidence"]["evidence"])
                self.assertIn("Read-only current-evidence preview", preview["current_evidence"]["guardrail"])
                self.assertEqual(preview["append_readiness"]["schema_version"], "desktop_sample_validation_append_readiness.v1")
                self.assertEqual(preview["append_readiness"]["operator_status"], "ready-to-append-evidence")
                self.assertTrue(preview["append_readiness"]["append_allowed"])
                self.assertTrue(preview["append_readiness"]["accepted_ready"])
                self.assertEqual(preview["append_readiness"]["required_acceptance_gaps"], [])
                self.assertTrue(preview["append_readiness"]["current_backend_proof_clean"])
                self.assertTrue(any("Append readiness:" in line for line in preview["append_readiness"]["summary_lines"]))
                self.assertIn("Read-only append-readiness advice", preview["append_readiness"]["guardrail"])
                self.assertEqual(preview["pilot_evidence_packet"]["schema_version"], "desktop_sample_validation_evidence_packet.v1")
                self.assertEqual(preview["pilot_evidence_packet"]["operator_status"], "pilot-evidence-ready")
                self.assertEqual(preview["pilot_evidence_packet"]["required_checked_count"], preview["pilot_evidence_packet"]["required_check_count"])
                self.assertEqual(preview["pilot_evidence_packet"]["blocked_count"], 0)
                packet_rows = {row["checkpoint"]: row for row in preview["pilot_evidence_packet"]["rows"]}
                self.assertEqual(packet_rows["Queue route proof"]["status"], "ready")
                self.assertEqual(packet_rows["Completed output and sidecar proof"]["status"], "ready")
                self.assertEqual(packet_rows["Diagnostics and run-log proof"]["status"], "ready")
                self.assertTrue(any("Pilot evidence packet:" in line for line in preview["pilot_evidence_packet"]["summary_lines"]))
                self.assertIn("Read-only pilot evidence packet", preview["pilot_evidence_packet"]["guardrail"])
                capture = preview["post_run_capture"]
                self.assertEqual(capture["schema_version"], "desktop_sample_validation_post_run_capture.v1")
                self.assertEqual(capture["operator_status"], "ready-to-record")
                self.assertEqual(capture["required_gaps"], [])
                capture_rows = {row["checkpoint"]: row for row in capture["rows"]}
                self.assertEqual(capture_rows["Remux vs encode decision"]["status"], "ready")
                self.assertEqual(capture_rows["Completed output and sidecar"]["status"], "ready")
                self.assertEqual(capture_rows["Diagnostics and FFmpeg logs"]["status"], "ready")
                self.assertEqual(capture_rows["Pending Publish or final placement"]["status"], "manual")
                self.assertIn("# Real-Media Post-Run Evidence Capture", capture["markdown_text"])
                self.assertIn("Read-only post-run evidence capture packet", capture["guardrail"])
                self.assertFalse((resolved.state_root / "Validation" / "sample_validation_log.jsonl").exists())

                append_status, append = _request_json(
                    f"{server.url}/api/sample-validation/append",
                    method="POST",
                    payload=request,
                    token="sample-token",
                )
                self.assertEqual(append_status, 200)
                self.assertTrue(append["ok"])
                self.assertEqual(append["command"], "sample_validation.append")
                self.assertEqual(append["data"]["written"], True)
                self.assertEqual(append["data"]["current_evidence"]["status"], "current")
                self.assertEqual(append["data"]["append_readiness"]["operator_status"], "ready-to-append-evidence")
                self.assertEqual(append["data"]["pilot_evidence_packet"]["operator_status"], "pilot-evidence-ready")
                self.assertEqual(append["data"]["post_run_capture"]["operator_status"], "ready-to-record")
                self.assertIn("operator evidence only", append["message"])

                log_path = resolved.state_root / "Validation" / "sample_validation_log.jsonl"
                self.assertTrue(log_path.exists())
                line = log_path.read_text(encoding="utf-8").strip()
                record = json.loads(line)
                self.assertEqual(record["schema"], "sample_validation_record.v1")
                self.assertEqual(record["source_path"], str(source))
                self.assertEqual(record["sample_category"], "h264-remux-safe")
                self.assertEqual(record["output_path"], str(output))

                read_status, read_payload = _request_json(f"{server.url}/api/sample-validation?limit=5", token="sample-token")
                self.assertEqual(read_status, 200)
                self.assertEqual(read_payload["schema_version"], "desktop_sample_validation_log.v1")
                self.assertEqual(len(read_payload["records"]), 1)
                self.assertEqual(read_payload["records"][0]["record_id"], record["record_id"])
                self.assertEqual(read_payload["summary"]["schema_version"], "desktop_sample_validation_summary.v1")
                self.assertEqual(read_payload["summary"]["operator_status"], "evidence-present")
                self.assertEqual(read_payload["summary"]["decision_counts"]["accepted"], 1)
                self.assertEqual(read_payload["summary"]["proof_strength_counts"]["exact-path"], 1)
                self.assertEqual(read_payload["summary"]["sample_category_counts"]["h264-remux-safe"], 1)
                self.assertEqual(read_payload["summary"]["latest"]["sample_category"], "h264-remux-safe")
                self.assertEqual(read_payload["summary"]["checked_counts"]["queue_route_checked"], 1)
                self.assertEqual(read_payload["summary"]["checked_counts"]["pending_publish_checked"], 0)
                self.assertEqual(read_payload["summary"]["evidence_counts"]["queue"], 1)
                self.assertEqual(read_payload["summary"]["evidence_counts"]["completed"], 1)
                self.assertEqual(read_payload["summary"]["latest"]["record_id"], record["record_id"])
                self.assertIn("Accepted sample evidence exists", read_payload["summary"]["safe_next_action"])
                self.assertEqual(read_payload["readiness"]["schema_version"], "desktop_sample_validation_readiness.v1")
                self.assertEqual(read_payload["readiness"]["operator_status"], "review")
                self.assertTrue(read_payload["readiness"]["ready_to_record"])
                self.assertEqual(read_payload["readiness"]["required_ready_count"], read_payload["readiness"]["required_count"])
                readiness_rows = {row["area"]: row for row in read_payload["readiness"]["rows"]}
                self.assertEqual(readiness_rows["Queue route evidence"]["status"], "ready")
                self.assertEqual(readiness_rows["Completed output proof"]["status"], "ready")
                self.assertEqual(readiness_rows["Diagnostics run log proof"]["status"], "ready")
                self.assertEqual(readiness_rows["Pending Publish posture"]["status"], "review")
                self.assertIn("Read-only readiness evidence", read_payload["readiness"]["guardrail"])
                worksheet_runs = read_payload["worksheet_runs"]
                self.assertEqual(worksheet_runs["schema_version"], "desktop_real_media_worksheet_runs.v1")
                self.assertEqual(worksheet_runs["operator_status"], "worksheet-evidence-present")
                self.assertEqual(worksheet_runs["run_count"], 1)
                self.assertEqual(worksheet_runs["sample_count"], 1)
                self.assertEqual(worksheet_runs["packet_row_count"], 1)
                self.assertEqual(worksheet_runs["rows"][0]["file_name"], "real_media_validation_unit.md")
                self.assertEqual(worksheet_runs["rows"][0]["samples"][0]["source_path"], str(source))
                self.assertEqual(worksheet_runs["rows"][0]["samples"][0]["category"], "h264-remux-safe")
                self.assertEqual(worksheet_runs["rows"][0]["packet_rows"][0]["packet_status"], "pilot-evidence-ready")
                self.assertIn("Read-only generated worksheet evidence", worksheet_runs["guardrail"])
                pilot_plan = read_payload["pilot_plan"]
                self.assertEqual(pilot_plan["schema_version"], "desktop_real_media_pilot_plan.v1")
                self.assertEqual(pilot_plan["operator_status"], "review")
                self.assertFalse(pilot_plan["sample_run_required"])
                self.assertIn("Start with 1-3 small known files", pilot_plan["recommended_sample_count"])
                self.assertEqual(pilot_plan["required_stage_count"], 5)
                self.assertEqual(pilot_plan["ready_stage_count"], 3)
                self.assertEqual(pilot_plan["manual_stage_count"], 1)
                self.assertGreaterEqual(pilot_plan["attention_stage_count"], 1)
                self.assertIn("next_required_action", pilot_plan)
                self.assertIsInstance(pilot_plan["pilot_attention"], list)
                self.assertTrue(any("Required checkpoints ready" in line for line in pilot_plan["summary_lines"]))
                pilot_stages = {row["stage"]: row for row in pilot_plan["rows"]}
                self.assertEqual(pilot_stages["Select a small known sample"]["status"], "ready")
                self.assertEqual(pilot_stages["Verify Completed output and sidecar"]["status"], "ready")
                self.assertEqual(pilot_stages["Review Pending Publish posture"]["status"], "review")
                self.assertIn("Read-only real-media pilot plan", pilot_plan["guardrail"])
                self.assertTrue(any("Completed output/sidecar proof is missing" in item for item in pilot_plan["stop_conditions"]))
                self.assertEqual(pilot_plan["execution_checklist_schema"], "desktop_real_media_execution_checklist.v1")
                self.assertEqual(pilot_plan["execution_required_count"], 5)
                self.assertEqual(pilot_plan["execution_ready_count"], 3)
                self.assertEqual(pilot_plan["execution_manual_count"], 1)
                self.assertGreaterEqual(pilot_plan["execution_attention_count"], 1)
                self.assertTrue(any("Operator-selected real-media sample execution" in line for line in pilot_plan["execution_summary_lines"]))
                execution_rows = {(row["phase"], row["check"]): row for row in pilot_plan["execution_checklist"]}
                self.assertEqual(execution_rows[("Before Launch", "Select one known sample row")]["status"], "ready")
                self.assertEqual(execution_rows[("Backend Launch Boundary", "Start only through backend-owned Launch")]["status"], "manual")
                self.assertEqual(execution_rows[("Post-run Completed Proof", "Verify Completed output, sidecar, manifest, route, and size")]["status"], "ready")
                self.assertIn("Read-only execution checklist", execution_rows[("Evidence Record", "Preview then append evidence-only validation note")]["guardrail"])
                cutover_gate = read_payload["cutover_gate"]
                self.assertEqual(cutover_gate["schema_version"], "desktop_webview_cutover_gate.v1")
                self.assertEqual(cutover_gate["operator_status"], "review")
                self.assertFalse(cutover_gate["gate_ready"])
                self.assertEqual(cutover_gate["accepted_record_count"], 1)
                self.assertEqual(cutover_gate["current_accepted_record_count"], 1)
                self.assertTrue(cutover_gate["current_required_checks_complete"])
                self.assertFalse(cutover_gate["current_recommended_checks_complete"])
                self.assertGreaterEqual(cutover_gate["review_count"], 1)
                cutover_rows = {row["checkpoint"]: row for row in cutover_gate["rows"]}
                self.assertEqual(cutover_rows["Current accepted sample record"]["status"], "ready")
                self.assertEqual(cutover_rows["Playback subtitle audio publish checks"]["status"], "review")
                self.assertTrue(any("WebView cutover gate:" in line for line in cutover_gate["summary_lines"]))
                self.assertIn("Read-only WebView cutover evidence", cutover_gate["guardrail"])
                sample_set = read_payload["sample_set_guide"]
                self.assertEqual(sample_set["schema_version"], "desktop_real_media_sample_set_guide.v1")
                self.assertEqual(sample_set["operator_status"], "coverage-needed")
                self.assertFalse(sample_set["sample_set_ready"])
                self.assertEqual(sample_set["recommended_sample_count"], "3-5 representative files")
                self.assertEqual(sample_set["worksheet_sample_count"], 1)
                self.assertEqual(sample_set["current_accepted_record_count"], 1)
                sample_set_rows = {row["category_key"]: row for row in sample_set["rows"]}
                self.assertEqual(sample_set_rows["h264-remux-safe"]["status"], "ready")
                self.assertEqual(sample_set_rows["h264-remux-safe"]["worksheet_sample_count"], 1)
                self.assertEqual(sample_set_rows["h264-remux-safe"]["accepted_record_match_count"], 1)
                self.assertEqual(sample_set_rows["h264-remux-safe"]["current_record_match_count"], 1)
                self.assertEqual(sample_set_rows["h264-remux-safe"]["stale_record_match_count"], 0)
                self.assertEqual(sample_set_rows["h264-remux-safe"]["review_record_match_count"], 0)
                self.assertEqual(sample_set_rows["subtitle-srt-generation"]["status"], "needs-sample")
                self.assertTrue(any("Recommended real-media sample set:" in line for line in sample_set["summary_lines"]))
                self.assertIn("Read-only representative sample-set guidance", sample_set["guardrail"])
                policy_alignment = read_payload["policy_alignment"]
                self.assertEqual(policy_alignment["schema_version"], "desktop_real_media_policy_alignment.v1")
                self.assertEqual(policy_alignment["operator_status"], "ready-looking")
                self.assertTrue(policy_alignment["policy_ready"])
                self.assertEqual(policy_alignment["required_ready_count"], 4)
                self.assertEqual(policy_alignment["required_count"], 4)
                policy_rows = {row["category_key"]: row for row in policy_alignment["rows"]}
                self.assertEqual(policy_rows["h264-remux-safe"]["status"], "ready")
                self.assertEqual(policy_rows["subtitle-srt-generation"]["status"], "ready")
                self.assertEqual(policy_rows["audio-routing"]["status"], "ready")
                self.assertEqual(policy_rows["encode-size-policy"]["status"], "ready")
                self.assertEqual(policy_rows["deferred-publish"]["status"], "manual")
                self.assertTrue(any("Real-media policy alignment:" in line for line in policy_alignment["summary_lines"]))
                self.assertIn("Read-only real-media policy alignment", policy_alignment["guardrail"])
                evidence_gap = read_payload["evidence_gap_summary"]
                self.assertEqual(evidence_gap["schema_version"], "desktop_real_media_evidence_gap.v1")
                self.assertEqual(evidence_gap["operator_status"], "missing-required-evidence")
                self.assertGreaterEqual(evidence_gap["ready_count"], 3)
                self.assertGreaterEqual(evidence_gap["review_count"], 1)
                self.assertGreaterEqual(evidence_gap["required_gap_count"], 1)
                self.assertIn("Representative category coverage", evidence_gap["required_gaps"])
                gap_rows = {row["checkpoint"]: row for row in evidence_gap["rows"]}
                self.assertEqual(gap_rows["Current backend evidence"]["status"], "ready")
                self.assertEqual(gap_rows["Post-run Completed and Diagnostics proof"]["status"], "ready")
                self.assertEqual(gap_rows["Representative category coverage"]["status"], "missing")
                self.assertIn("Read-only real-media evidence-gap summary", evidence_gap["guardrail"])
                pilot_runbook = read_payload["pilot_runbook"]
                self.assertEqual(pilot_runbook["schema_version"], "desktop_real_media_pilot_runbook.v1")
                self.assertEqual(pilot_runbook["operator_status"], "missing-required-evidence")
                self.assertGreaterEqual(pilot_runbook["ready_count"], 2)
                self.assertGreaterEqual(pilot_runbook["required_gap_count"], 1)
                self.assertIn("Choose one representative sample and category", pilot_runbook["required_gaps"])
                runbook_rows = {row["step"]: row for row in pilot_runbook["rows"]}
                self.assertEqual(runbook_rows["Verify Completed output, route, sidecar, and size"]["status"], "ready")
                self.assertEqual(runbook_rows["Preview and append evidence-only validation note"]["status"], "ready")
                self.assertIn("# Real-Media WebView Pilot Runbook", pilot_runbook["markdown_text"])
                self.assertIn("Read-only real-media pilot runbook", pilot_runbook["guardrail"])
                validation_audit = read_payload["validation_audit"]
                self.assertEqual(validation_audit["schema_version"], "desktop_real_media_validation_audit.v1")
                self.assertEqual(validation_audit["operator_status"], "missing-required-evidence")
                self.assertFalse(validation_audit["validation_ready"])
                self.assertGreaterEqual(validation_audit["required_count"], 6)
                self.assertIn("Representative category coverage", validation_audit["missing_required"])
                self.assertIn("Evidence gap status", validation_audit["missing_required"])
                self.assertIn("Pilot runbook", validation_audit["missing_required"])
                audit_rows = {row["area"]: row for row in validation_audit["rows"]}
                self.assertIn(audit_rows["Current backend proof"]["status"], {"ready", "review"})
                self.assertEqual(audit_rows["Sample validation records"]["status"], "ready")
                self.assertEqual(audit_rows["Representative category coverage"]["status"], "missing")
                self.assertEqual(audit_rows["Saved media policy alignment"]["status"], "ready")
                self.assertEqual(audit_rows["Evidence gap status"]["status"], "missing")
                self.assertEqual(audit_rows["Pilot runbook"]["status"], "missing")
                self.assertEqual(audit_rows["WebView cutover posture"]["status"], "review")
                self.assertTrue(any("Real-media validation audit:" in line for line in validation_audit["summary_lines"]))
                self.assertIn("Read-only real-media validation audit", validation_audit["guardrail"])
                self.assertEqual(read_payload["reconciliation"]["schema_version"], "desktop_sample_validation_reconciliation.v1")
                self.assertEqual(read_payload["reconciliation"]["operator_status"], "current")
                self.assertEqual(read_payload["reconciliation"]["current_count"], 1)
                self.assertEqual(read_payload["reconciliation"]["stale_count"], 0)
                self.assertIn("Read-only stale-evidence comparison", read_payload["reconciliation"]["guardrail"])
                self.assertEqual(read_payload["reconciliation"]["rows"][0]["status"], "current")
                self.assertTrue(read_payload["reconciliation"]["rows"][0]["matches"]["completed_output"])
                self.assertTrue(read_payload["reconciliation"]["rows"][0]["matches"]["diagnostics_source_or_output"])

                tail_status, tail_payload = _request_json(
                    f"{server.url}/api/diagnostics/tail?target=sample_validation_log&max_bytes=4096",
                    token="sample-token",
                )
                self.assertEqual(tail_status, 200)
                self.assertTrue(tail_payload["ok"])
                self.assertIn(record["record_id"], tail_payload["text"])

                state_status, state_payload = _request_json(f"{server.url}/api/diagnostics/state-summary", token="sample-token")
                self.assertEqual(state_status, 200)
                targets = {item["target"]: item for item in state_payload["targets"]}
                self.assertIn("sample_validation_log", targets)
                self.assertEqual(targets["sample_validation_log"]["status"], "ok")
                self.assertIn("sample_validation_record.v1", "\n".join(targets["sample_validation_log"]["facts"]))
                self.assertEqual(targets["sample_validation_log"]["recovery_stage"], "operator_validation_evidence")

                command_status, command_payload = _request_json(f"{server.url}/api/commands?limit=5", token="sample-token")
                self.assertEqual(command_status, 200)
                self.assertEqual(command_payload["entries"][0]["command"], "sample_validation.append")

                contract_status, contract = _request_json(f"{server.url}/api/contract", token="sample-token")
                self.assertEqual(contract_status, 200)
                effects = {route["path"]: route["effect"] for route in contract["routes"]}
                self.assertEqual(effects["/api/sample-validation"], "none")
                self.assertEqual(effects["/api/sample-validation/preview"], "none")
                self.assertEqual(effects["/api/sample-validation/append"], "validation-log-write")
                diagnostics_route = next(route for route in contract["routes"] if route["path"] == "/api/diagnostics/open")
                self.assertIn("sample_validation_log", diagnostics_route["allowed_targets"])
            finally:
                server.stop()

            for path, before in watched.items():
                self.assertEqual(path.read_bytes(), before, path)

    def test_sample_validation_append_rejects_malformed_and_oversized_records_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            source = resolved.source_tv / "Show" / "Season 01" / "Show S01E01.mkv"
            output = root / "Outsource" / "TV" / "Show" / "Season 01" / "Show - S01E01.mkv"
            facade = MediaPipelineApplicationFacade(SampleValidationService(), app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                malformed = _sample_request(source, output)
                malformed.pop("schema")
                malformed_status, malformed_payload = _request_json(
                    f"{server.url}/api/sample-validation/append",
                    method="POST",
                    payload=malformed,
                    token="sample-token",
                )
                self.assertEqual(malformed_status, 200)
                self.assertFalse(malformed_payload["ok"])
                self.assertIn("schema must be sample_validation_record.v1", "\n".join(malformed_payload["errors"]))

                unknown_category = _sample_request(source, output)
                unknown_category["sample_category"] = "not-a-real-category"
                category_status, category_payload = _request_json(
                    f"{server.url}/api/sample-validation/preview",
                    method="POST",
                    payload=unknown_category,
                    token="sample-token",
                )
                self.assertEqual(category_status, 200)
                self.assertTrue(category_payload["ok"])
                self.assertEqual(category_payload["record"]["sample_category"], "")
                self.assertIn("sample_category was not one of the known", "\n".join(category_payload["warnings"]))

                oversized = _sample_request(source, output)
                oversized["operator_notes"] = "x" * 70000
                oversized_status, oversized_payload = _request_json(
                    f"{server.url}/api/sample-validation/append",
                    method="POST",
                    payload=oversized,
                    token="sample-token",
                )
                self.assertEqual(oversized_status, 200)
                self.assertFalse(oversized_payload["ok"])
                self.assertIn("too large", "\n".join(oversized_payload["errors"]))
            finally:
                server.stop()
            self.assertFalse((resolved.state_root / "Validation" / "sample_validation_log.jsonl").exists())

    def test_sample_validation_preview_warns_when_accepted_record_lacks_current_backend_proof(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            source = resolved.source_tv / "Show" / "Season 01" / "Show S01E01.mkv"
            output = root / "Outsource" / "TV" / "Show" / "Season 01" / "Show - S01E01.mkv"
            facade = MediaPipelineApplicationFacade(SampleValidationService(), app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                status, payload = _request_json(
                    f"{server.url}/api/sample-validation/preview",
                    method="POST",
                    payload=_sample_request(source, output, decision="accepted"),
                    token="sample-token",
                )
            finally:
                server.stop()

        self.assertEqual(status, 200)
        self.assertTrue(payload["ok"])
        current = payload["current_evidence"]
        self.assertEqual(current["schema_version"], "desktop_sample_validation_current_evidence.v1")
        self.assertEqual(current["status"], "stale")
        self.assertEqual(current["severity"], "warning")
        self.assertIn("Completed manifest no longer contains the recorded output path.", current["missing_current_evidence"])
        self.assertIn("fully current backend proof", "\n".join(payload["warnings"]))
        readiness = payload["append_readiness"]
        self.assertEqual(readiness["schema_version"], "desktop_sample_validation_append_readiness.v1")
        self.assertEqual(readiness["operator_status"], "review-before-append")
        self.assertTrue(readiness["append_allowed"])
        self.assertFalse(readiness["accepted_ready"])
        self.assertEqual(readiness["required_acceptance_gaps"], [])
        self.assertIn("Current backend proof clean: no", "\n".join(readiness["summary_lines"]))
        packet = payload["pilot_evidence_packet"]
        self.assertEqual(packet["schema_version"], "desktop_sample_validation_evidence_packet.v1")
        self.assertEqual(packet["operator_status"], "review-before-append")
        self.assertEqual(packet["blocked_count"], 0)
        self.assertGreaterEqual(packet["review_count"], 1)
        packet_rows = {row["checkpoint"]: row for row in packet["rows"]}
        self.assertEqual(packet_rows["Queue route proof"]["status"], "review")
        self.assertEqual(packet_rows["Completed output and sidecar proof"]["status"], "review")
        self.assertEqual(packet_rows["Diagnostics and run-log proof"]["status"], "review")
        self.assertIn("Read-only pilot evidence packet", packet["guardrail"])
        capture = payload["post_run_capture"]
        self.assertEqual(capture["schema_version"], "desktop_sample_validation_post_run_capture.v1")
        self.assertEqual(capture["operator_status"], "review-before-append")
        self.assertIn("Remux vs encode decision", capture["required_gaps"])
        self.assertIn("Completed output and sidecar", capture["required_gaps"])
        self.assertIn("Diagnostics and FFmpeg logs", capture["required_gaps"])
        capture_rows = {row["checkpoint"]: row for row in capture["rows"]}
        self.assertEqual(capture_rows["Append decision"]["status"], "review")
        self.assertIn("Completed manifest no longer contains the recorded output path.", capture_rows["Append decision"]["missing_capture"])
        self.assertIn("Read-only post-run evidence capture packet", capture["guardrail"])
        self.assertFalse((resolved.state_root / "Validation" / "sample_validation_log.jsonl").exists())

    def test_sample_validation_readiness_reports_missing_required_evidence_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            facade = MediaPipelineApplicationFacade(SampleValidationService(), app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                status, payload = _request_json(f"{server.url}/api/sample-validation?limit=5", token="sample-token")
            finally:
                server.stop()

        self.assertEqual(status, 200)
        self.assertTrue(payload["ok"])
        self.assertFalse(payload["exists"])
        readiness = payload["readiness"]
        self.assertEqual(readiness["schema_version"], "desktop_sample_validation_readiness.v1")
        self.assertEqual(readiness["operator_status"], "not-ready")
        self.assertFalse(readiness["ready_to_record"])
        self.assertIn("Queue route evidence", readiness["missing_required"])
        self.assertIn("Completed output proof", readiness["missing_required"])
        self.assertIn("Diagnostics run log proof", readiness["missing_required"])
        self.assertIn("Read-only readiness evidence", readiness["guardrail"])
        pilot_plan = payload["pilot_plan"]
        self.assertEqual(pilot_plan["schema_version"], "desktop_real_media_pilot_plan.v1")
        self.assertEqual(pilot_plan["operator_status"], "pilot-needed")
        self.assertTrue(pilot_plan["sample_run_required"])
        self.assertEqual(pilot_plan["required_stage_count"], 5)
        self.assertEqual(pilot_plan["ready_stage_count"], 0)
        self.assertEqual(pilot_plan["manual_stage_count"], 1)
        self.assertGreaterEqual(pilot_plan["attention_stage_count"], 4)
        self.assertIn("Select a small known sample", [row["stage"] for row in pilot_plan["pilot_attention"]])
        self.assertIn("Refresh Queue", pilot_plan["next_required_action"])
        pilot_stages = {row["stage"]: row for row in pilot_plan["rows"]}
        self.assertEqual(pilot_stages["Select a small known sample"]["status"], "needs-sample")
        self.assertEqual(pilot_stages["Verify Completed output and sidecar"]["status"], "post-run-needed")
        self.assertEqual(pilot_plan["execution_checklist_schema"], "desktop_real_media_execution_checklist.v1")
        self.assertEqual(pilot_plan["execution_required_count"], 5)
        self.assertEqual(pilot_plan["execution_ready_count"], 0)
        self.assertEqual(pilot_plan["execution_manual_count"], 1)
        self.assertGreaterEqual(pilot_plan["execution_attention_count"], 4)
        self.assertTrue(any("Execution required ready: 0/5" in line for line in pilot_plan["execution_summary_lines"]))
        execution_rows = {(row["phase"], row["check"]): row for row in pilot_plan["execution_checklist"]}
        self.assertEqual(execution_rows[("Before Launch", "Select one known sample row")]["status"], "needs-sample")
        self.assertIn("Queue payload should identify", execution_rows[("Before Launch", "Select one known sample row")]["backend_evidence"])
        self.assertEqual(execution_rows[("Post-run Completed Proof", "Verify Completed output, sidecar, manifest, route, and size")]["status"], "post-run-needed")
        self.assertIn("backend-owned Launch", pilot_plan["safe_next_action"])
        cutover_gate = payload["cutover_gate"]
        self.assertEqual(cutover_gate["schema_version"], "desktop_webview_cutover_gate.v1")
        self.assertEqual(cutover_gate["operator_status"], "pilot-needed")
        self.assertFalse(cutover_gate["gate_ready"])
        self.assertEqual(cutover_gate["current_accepted_record_count"], 0)
        self.assertIn("Run one small known sample", cutover_gate["safe_next_action"])
        self.assertIn("not a production cutover switch", "\n".join(cutover_gate["summary_lines"]))
        sample_set = payload["sample_set_guide"]
        self.assertEqual(sample_set["schema_version"], "desktop_real_media_sample_set_guide.v1")
        self.assertEqual(sample_set["operator_status"], "pilot-needed")
        self.assertEqual(sample_set["worksheet_sample_count"], 0)
        self.assertEqual(sample_set["missing_count"], 5)
        self.assertTrue(any("Recommended real-media sample set:" in line for line in sample_set["summary_lines"]))
        evidence_gap = payload["evidence_gap_summary"]
        self.assertEqual(evidence_gap["schema_version"], "desktop_real_media_evidence_gap.v1")
        self.assertEqual(evidence_gap["operator_status"], "missing-required-evidence")
        self.assertGreaterEqual(evidence_gap["missing_count"], 4)
        self.assertIn("Current backend evidence", evidence_gap["required_gaps"])
        self.assertIn("Selected sample and saved policy", evidence_gap["required_gaps"])
        gap_rows = {row["checkpoint"]: row for row in evidence_gap["rows"]}
        self.assertEqual(gap_rows["Current backend evidence"]["status"], "missing")
        self.assertIn("Queue route evidence", gap_rows["Current backend evidence"]["missing_evidence"])
        self.assertIn("Read-only real-media evidence-gap summary", evidence_gap["guardrail"])
        pilot_runbook = payload["pilot_runbook"]
        self.assertEqual(pilot_runbook["schema_version"], "desktop_real_media_pilot_runbook.v1")
        self.assertEqual(pilot_runbook["operator_status"], "missing-required-evidence")
        self.assertGreaterEqual(pilot_runbook["missing_count"], 4)
        self.assertIn("Choose one representative sample and category", pilot_runbook["required_gaps"])
        runbook_rows = {row["step"]: row for row in pilot_runbook["rows"]}
        self.assertEqual(runbook_rows["Confirm saved media policy before launch"]["status"], "missing")
        self.assertIn("## Checklist", "\n".join(pilot_runbook["markdown_lines"]))
        self.assertIn("Read-only real-media pilot runbook", pilot_runbook["guardrail"])
        policy_alignment = payload["policy_alignment"]
        self.assertEqual(policy_alignment["schema_version"], "desktop_real_media_policy_alignment.v1")
        self.assertEqual(policy_alignment["operator_status"], "ready-looking")
        self.assertTrue(policy_alignment["policy_ready"])
        self.assertEqual(policy_alignment["required_ready_count"], 4)
        self.assertEqual(policy_alignment["required_count"], 4)
        self.assertTrue(any("Real-media policy alignment:" in line for line in policy_alignment["summary_lines"]))
        validation_audit = payload["validation_audit"]
        self.assertEqual(validation_audit["schema_version"], "desktop_real_media_validation_audit.v1")
        self.assertEqual(validation_audit["operator_status"], "missing-required-evidence")
        self.assertFalse(validation_audit["validation_ready"])
        audit_rows = {row["area"]: row for row in validation_audit["rows"]}
        self.assertEqual(audit_rows["Current backend proof"]["status"], "missing")
        self.assertEqual(audit_rows["Sample validation records"]["status"], "missing")
        self.assertEqual(audit_rows["Representative category coverage"]["status"], "missing")
        self.assertEqual(audit_rows["Generated worksheet context"]["status"], "review")
        self.assertEqual(audit_rows["Saved media policy alignment"]["status"], "ready")
        self.assertIn("Current backend proof", validation_audit["missing_required"])
        self.assertIn("Sample validation records", validation_audit["missing_required"])
        self.assertIn("Boundary: validation audit is read-only", "\n".join(validation_audit["summary_lines"]))
        self.assertFalse((resolved.state_root / "Validation" / "sample_validation_log.jsonl").exists())

    def test_generated_worksheet_alone_cannot_satisfy_cutover_or_sample_set(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            source = resolved.source_tv / "Serial Experiments Lain" / "Season 02" / "Serial Experiments Lain S02E01 Weird.mkv"
            output = root / "Outsource" / "TV" / "Serial Experiments Lain" / "Season 02" / "Serial Experiments Lain - S02E01 - Weird.mkv"
            source.parent.mkdir(parents=True, exist_ok=True)
            output.parent.mkdir(parents=True, exist_ok=True)
            source.write_bytes(b"source-media")
            output.write_bytes(b"output-media")
            resolved.queue_snapshot_path.parent.mkdir(parents=True, exist_ok=True)
            resolved.queue_snapshot_path.write_text(
                json.dumps({"rows": [{"source_path": str(source), "route": "remux", "route_reason": "copy safe"}]}),
                encoding="utf-8",
            )
            resolved.completed_manifest_path.parent.mkdir(parents=True, exist_ok=True)
            resolved.completed_manifest_path.write_text(
                json.dumps({"source_path": str(source), "output_path": str(output), "sidecar_path": str(output) + ".pipeline.json", "route": "remux"})
                + "\n",
                encoding="utf-8",
            )
            run_log = root / "RunLogs" / "run.stderr.log"
            run_log.parent.mkdir(parents=True, exist_ok=True)
            run_log.write_text(f"ffmpeg remux complete for sample source={source} output={output}\n", encoding="utf-8")
            worksheet = _write_validation_worksheet(root, source)
            watched = {
                source: source.read_bytes(),
                output: output.read_bytes(),
                resolved.queue_snapshot_path: resolved.queue_snapshot_path.read_bytes(),
                resolved.completed_manifest_path: resolved.completed_manifest_path.read_bytes(),
                run_log: run_log.read_bytes(),
                worksheet: worksheet.read_bytes(),
            }

            facade = MediaPipelineApplicationFacade(SampleValidationService(), app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                status, payload = _request_json(f"{server.url}/api/sample-validation?limit=5", token="sample-token")
            finally:
                server.stop()

            self.assertEqual(status, 200)
            self.assertTrue(payload["ok"])
            self.assertFalse(payload["exists"])
            worksheet_runs = payload["worksheet_runs"]
            self.assertEqual(worksheet_runs["operator_status"], "worksheet-evidence-present")
            self.assertEqual(worksheet_runs["run_count"], 1)
            self.assertEqual(worksheet_runs["sample_count"], 1)
            self.assertEqual(worksheet_runs["packet_row_count"], 1)
            cutover_gate = payload["cutover_gate"]
            self.assertEqual(cutover_gate["schema_version"], "desktop_webview_cutover_gate.v1")
            self.assertEqual(cutover_gate["operator_status"], "pilot-needed")
            self.assertFalse(cutover_gate["gate_ready"])
            self.assertEqual(cutover_gate["accepted_record_count"], 0)
            self.assertEqual(cutover_gate["current_accepted_record_count"], 0)
            self.assertEqual(cutover_gate["worksheet_run_count"], 1)
            self.assertEqual(cutover_gate["worksheet_sample_count"], 1)
            self.assertIn("Generated worksheet rows", cutover_gate["acceptance_evidence_boundary"])
            self.assertTrue(any("generated worksheets are context only" in line for line in cutover_gate["summary_lines"]))
            cutover_rows = {row["checkpoint"]: row for row in cutover_gate["rows"]}
            self.assertEqual(cutover_rows["Current accepted sample record"]["status"], "review")
            self.assertEqual(cutover_rows["Worksheet or run-note context"]["status"], "ready")
            sample_set = payload["sample_set_guide"]
            self.assertEqual(sample_set["schema_version"], "desktop_real_media_sample_set_guide.v1")
            self.assertFalse(sample_set["sample_set_ready"])
            self.assertEqual(sample_set["worksheet_sample_count"], 1)
            self.assertEqual(sample_set["current_accepted_record_count"], 0)
            self.assertIn("Worksheet sample rows", sample_set["acceptance_evidence_boundary"])
            self.assertTrue(any("worksheet samples are planned/context rows only" in line for line in sample_set["summary_lines"]))
            sample_set_rows = {row["category_key"]: row for row in sample_set["rows"]}
            self.assertEqual(sample_set_rows["h264-remux-safe"]["status"], "planned")
            self.assertEqual(sample_set_rows["h264-remux-safe"]["worksheet_sample_count"], 1)
            self.assertEqual(sample_set_rows["h264-remux-safe"]["current_record_match_count"], 0)
            validation_audit = payload["validation_audit"]
            self.assertEqual(validation_audit["schema_version"], "desktop_real_media_validation_audit.v1")
            self.assertEqual(validation_audit["operator_status"], "missing-required-evidence")
            self.assertFalse(validation_audit["validation_ready"])
            audit_rows = {row["area"]: row for row in validation_audit["rows"]}
            self.assertEqual(audit_rows["Generated worksheet context"]["status"], "ready")
            self.assertEqual(audit_rows["Sample validation records"]["status"], "missing")
            self.assertEqual(audit_rows["Representative category coverage"]["status"], "missing")
            self.assertEqual(audit_rows["Saved media policy alignment"]["status"], "ready")
            self.assertEqual(audit_rows["WebView cutover posture"]["status"], "missing")
            self.assertIn("Sample validation records", validation_audit["missing_required"])
            self.assertIn("Representative category coverage", validation_audit["missing_required"])
            self.assertFalse((resolved.state_root / "Validation" / "sample_validation_log.jsonl").exists())
            for path, contents in watched.items():
                self.assertEqual(path.read_bytes(), contents, path)

    def test_sample_validation_policy_alignment_reports_risky_saved_policy(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            resolved.config_data.update(
                {
                    "SizeGuardMode": "off",
                    "ConvertTx3gToSrt": False,
                    "ConvertBdpgsToSrt": False,
                    "DropBdpgsAfterConversion": True,
                    "AllowNoAudio": True,
                    "DeferredPublish": True,
                }
            )
            facade = MediaPipelineApplicationFacade(SampleValidationService(), app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                status, payload = _request_json(f"{server.url}/api/sample-validation?limit=5", token="sample-token")
            finally:
                server.stop()

            self.assertEqual(status, 200)
            policy_alignment = payload["policy_alignment"]
            self.assertEqual(policy_alignment["schema_version"], "desktop_real_media_policy_alignment.v1")
            self.assertEqual(policy_alignment["operator_status"], "blocked")
            self.assertFalse(policy_alignment["policy_ready"])
            self.assertGreaterEqual(policy_alignment["blocked_count"], 2)
            rows = {row["category_key"]: row for row in policy_alignment["rows"]}
            self.assertEqual(rows["subtitle-srt-generation"]["status"], "blocked")
            self.assertEqual(rows["audio-routing"]["status"], "blocked")
            self.assertEqual(rows["encode-size-policy"]["status"], "review")
            self.assertIn("Resolve blocked saved-policy evidence", policy_alignment["safe_next_action"])
            validation_audit = payload["validation_audit"]
            self.assertEqual(validation_audit["operator_status"], "blocked")
            audit_rows = {row["area"]: row for row in validation_audit["rows"]}
            self.assertEqual(audit_rows["Saved media policy alignment"]["status"], "blocked")
            self.assertIn("Saved media policy alignment", validation_audit["missing_required"])

    def test_sample_validation_reconciliation_marks_accepted_record_stale_when_current_proof_disappears(self) -> None:
        with tempfile.TemporaryDirectory() as raw_root:
            root = Path(raw_root)
            resolved = _resolved(root)
            source = resolved.source_tv / "Show" / "Season 01" / "Show S01E01.mkv"
            output = root / "Outsource" / "TV" / "Show" / "Season 01" / "Show - S01E01.mkv"
            log_path = resolved.state_root / "Validation" / "sample_validation_log.jsonl"
            log_path.parent.mkdir(parents=True, exist_ok=True)
            log_path.write_text(json.dumps(_sample_request(source, output), ensure_ascii=False) + "\n", encoding="utf-8")
            resolved.queue_snapshot_path.parent.mkdir(parents=True, exist_ok=True)
            resolved.queue_snapshot_path.write_text(json.dumps({"rows": []}), encoding="utf-8")
            resolved.completed_manifest_path.parent.mkdir(parents=True, exist_ok=True)
            resolved.completed_manifest_path.write_text(
                json.dumps({"source_path": str(root / "other.mkv"), "output_path": str(root / "other-out.mkv")}) + "\n",
                encoding="utf-8",
            )
            before = {
                log_path: log_path.read_bytes(),
                resolved.queue_snapshot_path: resolved.queue_snapshot_path.read_bytes(),
                resolved.completed_manifest_path: resolved.completed_manifest_path.read_bytes(),
            }
            facade = MediaPipelineApplicationFacade(SampleValidationService(), app_version="v5-test")
            server = LocalApiServer(facade, token="sample-token", resolved_provider=lambda: resolved)
            try:
                server.start()
                status, payload = _request_json(f"{server.url}/api/sample-validation?limit=5", token="sample-token")
            finally:
                server.stop()

            self.assertEqual(status, 200)
            reconciliation = payload["reconciliation"]
            self.assertEqual(reconciliation["schema_version"], "desktop_sample_validation_reconciliation.v1")
            self.assertEqual(reconciliation["operator_status"], "stale")
            self.assertEqual(reconciliation["stale_count"], 1)
            self.assertEqual(reconciliation["rows"][0]["status"], "stale")
            self.assertIn("Completed manifest no longer contains the recorded output path.", reconciliation["rows"][0]["missing_current_evidence"])
            self.assertIn("Current Queue/Completed evidence no longer contains the recorded source path.", reconciliation["rows"][0]["missing_current_evidence"])
            self.assertIn("Read-only stale-evidence comparison", reconciliation["guardrail"])
            cutover_gate = payload["cutover_gate"]
            self.assertEqual(cutover_gate["schema_version"], "desktop_webview_cutover_gate.v1")
            self.assertFalse(cutover_gate["gate_ready"])
            self.assertEqual(cutover_gate["current_accepted_record_count"], 0)
            self.assertTrue(any(row["checkpoint"] == "Stale or review history" for row in cutover_gate["rows"]))
            for path, contents in before.items():
                self.assertEqual(path.read_bytes(), contents, path)

    def test_sample_validation_static_webview_controls_use_backend_routes(self) -> None:
        webview_root = PROJECT_ROOT / "DesktopApp" / "mediapipeline_desktop_app" / "ui_web" / "static"
        rendered = render_index(
            webview_root,
            {"token": "test-token", "appVersion": "v5-test", "shellSurface": "webview"},
        )
        self.assertEqual(rendered.status, 200)
        html = rendered.body.decode("utf-8")
        app_js = (PROJECT_ROOT / "DesktopApp" / "mediapipeline_desktop_app" / "ui_web" / "static" / "assets" / "app.js").read_text(encoding="utf-8")
        cross_page_js = (
            PROJECT_ROOT / "DesktopApp" / "mediapipeline_desktop_app" / "ui_web" / "static" / "assets" / "crossPageContextView.js"
        ).read_text(encoding="utf-8")
        sample_validation_assets_root = PROJECT_ROOT / "DesktopApp" / "mediapipeline_desktop_app" / "ui_web" / "static" / "assets"
        cross_page_sample_validation_js = "\n".join(
            (
                (sample_validation_assets_root / "crossPageContextView.sampleValidation.worksheet.js").read_text(encoding="utf-8"),
                (sample_validation_assets_root / "crossPageContextView.sampleValidation.runbook.js").read_text(encoding="utf-8"),
                (sample_validation_assets_root / "crossPageContextView.sampleValidation.records.js").read_text(encoding="utf-8"),
                (sample_validation_assets_root / "crossPageContextView.sampleValidation.js").read_text(encoding="utf-8"),
            )
        )
        cross_page_js = cross_page_js + "\n" + cross_page_sample_validation_js
        command_history_assets_root = PROJECT_ROOT / "DesktopApp" / "mediapipeline_desktop_app" / "ui_web" / "static" / "assets"
        command_history_js = "\n".join(
            (
                (command_history_assets_root / "commandHistory" / "formatters.js").read_text(encoding="utf-8"),
                (command_history_assets_root / "commandHistory" / "diagnostics.js").read_text(encoding="utf-8"),
                (command_history_assets_root / "commandHistory.js").read_text(encoding="utf-8"),
            )
        )

        self.assertIn("sample-validation-preview-button", html)
        self.assertIn("/assets/crossPageContextView.sampleValidation.worksheet.js", html)
        self.assertIn("/assets/crossPageContextView.sampleValidation.runbook.js", html)
        self.assertIn("/assets/crossPageContextView.sampleValidation.records.js", html)
        self.assertIn("/assets/crossPageContextView.sampleValidation.js", html)
        self.assertIn("window.__crossPageSampleValidationModule", cross_page_sample_validation_js)
        self.assertIn("window.__crossPageSvWorksheetModule", cross_page_sample_validation_js)
        self.assertIn("window.__crossPageSvRunbookModule", cross_page_sample_validation_js)
        self.assertIn("window.__crossPageSvRecordsModule", cross_page_sample_validation_js)
        self.assertIn("sample-validation-append-button", html)
        self.assertIn("sample-validation-category", html)
        self.assertIn('<th scope="col">Category</th>', html)
        self.assertIn('<th scope="col">Current Evidence</th>', html)
        self.assertIn('<th scope="col">Gap</th>', html)
        self.assertIn("h264-remux-safe", html)
        self.assertIn("sample-validation-check-status", html)
        self.assertIn("sample-validation-check-diagnostics", html)
        self.assertIn("sample-validation-clear-checks-button", html)
        self.assertIn("sample-validation-execution-rows", html)
        self.assertIn("sample-validation-execution-detail", html)
        self.assertIn("sample-validation-cutover-status", html)
        self.assertIn("sample-validation-cutover-rows", html)
        self.assertIn("sample-validation-cutover-detail", html)
        self.assertIn("sample-validation-sample-set-status", html)
        self.assertIn("sample-validation-sample-set-rows", html)
        self.assertIn("sample-validation-sample-set-detail", html)
        self.assertIn("sample-validation-use-sample-set-category-button", html)
        self.assertIn("sample-validation-worksheet-status", html)
        self.assertIn("sample-validation-worksheet-rows", html)
        self.assertIn("sample-validation-worksheet-detail", html)
        self.assertIn("sample-validation-completed-packet-status", html)
        self.assertIn("sample-validation-completed-packet-summary", html)
        self.assertIn("sample-validation-completed-packet-rows", html)
        self.assertIn("sample-validation-completed-packet-detail", html)
        self.assertIn("sample-validation-completed-packet-markdown", html)
        self.assertIn("sample-validation-acceptance-gate-status", html)
        self.assertIn("sample-validation-acceptance-gate-summary", html)
        self.assertIn("sample-validation-acceptance-gate-rows", html)
        self.assertIn("sample-validation-acceptance-gate-detail", html)
        self.assertIn("sample-validation-record-review-status", html)
        self.assertIn("sample-validation-record-review-summary", html)
        self.assertIn("sample-validation-record-review-rows", html)
        self.assertIn("sample-validation-record-review-detail", html)
        self.assertIn("sample-validation-category-summary-status", html)
        self.assertIn("sample-validation-category-summary", html)
        self.assertIn("sample-validation-category-summary-rows", html)
        self.assertIn("sample-validation-category-summary-detail", html)
        self.assertIn("Validation Record", html)
        self.assertIn('<tr><td colspan="7">No sample validation records loaded.</td></tr>', html)
        self.assertIn("Sample Checklist", html)
        self.assertIn("Pilot Worksheets", html)
        self.assertIn("Cutover Gate", html)
        self.assertIn("Evidence Handoff", html)
        self.assertIn("Sample Guide", html)
        self.assertIn('/api/sample-validation?limit=10', app_js)
        self.assertIn('/api/sample-validation/preview', cross_page_js)
        self.assertIn('/api/sample-validation/append', cross_page_js)
        self.assertIn("buildSampleValidationRequest", cross_page_js)
        self.assertIn("sample_category", cross_page_js)
        self.assertIn('record.sample_category || "general"', cross_page_js)
        self.assertIn("function sampleValidationRecordCurrentEvidenceLabel", cross_page_js)
        self.assertIn("function sampleValidationRecordGapLabel", cross_page_js)
        self.assertIn("function sampleValidationRecordRowState", cross_page_js)
        self.assertIn("no reconciliation row is loaded for this record", cross_page_js)
        self.assertIn("clearRows(tbody, 7", cross_page_js)
        self.assertIn("Pilot category:", cross_page_js)
        self.assertIn("SAMPLE_VALIDATION_CHECK_FIELDS", cross_page_js)
        self.assertIn("function sampleValidationMergedChecks", cross_page_js)
        self.assertIn("function sampleValidationRecordComparisonRowsForPaths", cross_page_js)
        self.assertIn("function syncSampleValidationCheckControls", cross_page_js)
        self.assertIn("Manual sample-validation checks cleared", cross_page_js)
        self.assertIn("function sampleValidationCheckedSummary", cross_page_js)
        self.assertIn("function sampleValidationLogSummaryLines", cross_page_js)
        self.assertIn("function sampleValidationAuditSummaryLines", cross_page_js)
        self.assertIn("Real-media validation audit:", cross_page_js)
        self.assertIn("Boundary: validation audit is read-only", cross_page_js)
        self.assertIn("function sampleValidationPolicyAlignmentSummaryLines", cross_page_js)
        self.assertIn("Real-media policy alignment:", cross_page_js)
        self.assertIn("Read-only real-media policy alignment", cross_page_js)
        self.assertIn("function sampleValidationReadinessLines", cross_page_js)
        self.assertIn("function sampleValidationReconciliationLines", cross_page_js)
        self.assertIn("Proposed evidence coverage:", cross_page_js)
        self.assertIn("Backend readiness:", cross_page_js)
        self.assertIn("Required evidence ready:", cross_page_js)
        self.assertIn("Readiness next action:", cross_page_js)
        self.assertIn("function sampleValidationPilotPlanLines", cross_page_js)
        self.assertIn("function sampleValidationCutoverRows", cross_page_js)
        self.assertIn("function renderSampleValidationCutoverGate", cross_page_js)
        self.assertIn("WebView cutover gate:", cross_page_js)
        self.assertIn("Acceptance evidence boundary:", cross_page_js)
        self.assertIn("Read-only WebView cutover evidence", cross_page_js)
        self.assertIn("function sampleValidationSampleSetRows", cross_page_js)
        self.assertIn("function renderSampleValidationSampleSetGuide", cross_page_js)
        self.assertIn("function useSelectedSampleSetCategory", cross_page_js)
        self.assertIn("Pilot category set to", cross_page_js)
        self.assertIn("Recommended real-media sample set:", cross_page_js)
        self.assertIn("Read-only representative sample-set guidance", cross_page_js)
        self.assertIn("function sampleValidationExecutionRows", cross_page_js)
        self.assertIn("function renderSampleValidationExecutionChecklist", cross_page_js)
        self.assertIn("function sampleValidationWorksheetSummaryLines", cross_page_js)
        self.assertIn("function renderSampleValidationWorksheets", cross_page_js)
        self.assertIn("Real-media pilot plan:", cross_page_js)
        self.assertIn("Operator-selected real-media sample execution:", cross_page_js)
        self.assertIn("Generated real-media worksheets:", cross_page_js)
        self.assertIn("Worksheet evidence is read-only Markdown context", cross_page_js)
        self.assertIn("Read-only execution checklist", cross_page_js)
        self.assertIn("Pilot checkpoints:", cross_page_js)
        self.assertIn("Pilot next required action:", cross_page_js)
        self.assertIn("Pilot attention:", cross_page_js)
        self.assertIn("Pilot plan is read-only", cross_page_js)
        self.assertIn("Append readiness:", cross_page_js)
        self.assertIn("Required acceptance gaps:", cross_page_js)
        self.assertIn("Read-only append-readiness advice", cross_page_js)
        self.assertIn("Pilot evidence packet:", cross_page_js)
        self.assertIn("Read-only pilot evidence packet", cross_page_js)
        self.assertIn("function sampleValidationCompletedPacketRows", cross_page_js)
        self.assertIn("function renderSampleValidationCompletedPacketHandoff", cross_page_js)
        self.assertIn("Completed evidence handoff for Sample Validation:", cross_page_js)
        self.assertIn("Decision rule: keep Sample Validation at hold/review", cross_page_js)
        _assert_namespace_export(self, cross_page_js, "mediaPipelineCrossPageContextView", "renderSampleValidationCompletedPacketHandoff")
        self.assertIn("function sampleValidationAcceptanceGateRows", cross_page_js)
        self.assertIn("function renderSampleValidationAcceptanceGate", cross_page_js)
        self.assertIn("Sample Validation acceptance readiness gate:", cross_page_js)
        self.assertIn("Decision rule: accepted sample evidence should not be appended", cross_page_js)
        _assert_namespace_export(self, cross_page_js, "mediaPipelineCrossPageContextView", "renderSampleValidationAcceptanceGate")
        self.assertIn("function sampleValidationRecordReviewRows", cross_page_js)
        self.assertIn("function renderSampleValidationRecordReview", cross_page_js)
        self.assertIn("Accepted sample-validation record proof review:", cross_page_js)
        self.assertIn("Decision rule: treat accepted records as current proof only", cross_page_js)
        _assert_namespace_export(self, cross_page_js, "mediaPipelineCrossPageContextView", "renderSampleValidationRecordReview")
        self.assertIn("function sampleValidationCategorySummaryRows", cross_page_js)
        self.assertIn("function renderSampleValidationCategorySummary", cross_page_js)
        self.assertIn("Pilot category validation summary:", cross_page_js)
        self.assertIn("Decision rule: a category is ready only when an accepted validation record", cross_page_js)
        _assert_namespace_export(self, cross_page_js, "mediaPipelineCrossPageContextView", "renderSampleValidationCategorySummary")
        self.assertIn("function crossPageSampleValidationEvidence", cross_page_js)
        self.assertIn("Sample Validation readiness", cross_page_js)
        self.assertIn("Sample Validation is evidence-only", cross_page_js)
        self.assertIn("Current evidence reconciliation:", cross_page_js)
        self.assertIn("Stale evidence", cross_page_js)
        self.assertIn("Reconciliation is read-only", cross_page_js)
        self.assertIn("Log posture:", cross_page_js)
        self.assertIn("History decisions:", cross_page_js)
        self.assertIn("This will not mark the job complete", cross_page_js)
        self.assertIn("records do not mark jobs complete", cross_page_js)
        self.assertIn('command.startsWith("sample_validation.")', command_history_js)
        self.assertIn("Home / Validation", command_history_js)
        self.assertIn("sample_validation_log", command_history_js)
        self.assertNotIn("localStorage.setItem(\"sample", cross_page_js)


if __name__ == "__main__":
    unittest.main()
