from __future__ import annotations

import unittest

from app.config.service import ConfigProfileServiceMixin
from app.config.load import (
    order_top_level_config,
    psd1_key,
    psd1_quote,
    serialize_psd1_document,
)


class ServiceConfigPsd1Tests(unittest.TestCase):
    def test_serialize_psd1_document_quotes_and_renders_nested_values(self) -> None:
        text = serialize_psd1_document(
            {
                "Custom Key": "Layne's value",
                "Nested": {"Enabled": True, "Empty": [], "Nothing": None},
                "List": ["one", 2, 3.5],
            }
        )

        self.assertIn("# Generated by MediaPipelineRemuxEncodeAIO Desktop App.", text)
        self.assertIn("'Custom Key' = 'Layne''s value'", text)
        self.assertIn("Enabled = $true", text)
        self.assertIn("Empty = @()", text)
        self.assertIn("Nothing = $null", text)
        self.assertIn("'one',", text)
        self.assertIn("2,", text)
        self.assertIn("3.5", text)

    def test_order_top_level_config_prefers_pipeline_order_then_alpha_unknowns(self) -> None:
        ordered = order_top_level_config({"zz": 1, "SourceTV": 2, "aa": 3, "SourceMovies": 4})

        self.assertEqual(list(ordered), ["SourceMovies", "SourceTV", "aa", "zz"])

    def test_service_mixin_preserves_psd1_wrapper_methods(self) -> None:
        service = ConfigProfileServiceMixin()

        self.assertEqual(service._psd1_key("simpleKey"), "simpleKey")
        self.assertEqual(service._psd1_key("not simple"), "'not simple'")
        self.assertEqual(service._psd1_quote("a'b"), psd1_quote("a'b"))
        self.assertEqual(
            service.serialize_psd1_document({"SourceMovies": r"C:\Movies"}),
            serialize_psd1_document({"SourceMovies": r"C:\Movies"}),
        )


if __name__ == "__main__":
    unittest.main()
