"""Generate PROJECT_INDEX.md and DEPENDENCY_GRAPH.md from summaries/.

PROJECT_INDEX.md is a flat table: one row per source file with path,
owner_domain, token_priority, pipeline_stage, and a short purpose line
extracted from its summary.

DEPENDENCY_GRAPH.md emits a Mermaid graph of cross-domain imports (Python)
and dot-includes (PowerShell). Edges are aggregated by owner_domain pair
so the graph stays legible.

Run after refresh_summaries.py.
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SUMMARY_ROOT = REPO_ROOT / "summaries"
INDEX_PATH = REPO_ROOT / "PROJECT_INDEX.md"
GRAPH_PATH = REPO_ROOT / "DEPENDENCY_GRAPH.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
PURPOSE_RE = re.compile(r"\*\*Purpose:\*\*\s*(.+)")
IMPORTS_RE = re.compile(r"\*\*In-repo imports:\*\*\s*(.+)")
DOTINC_RE = re.compile(r"\*\*Dot-sourced:\*\*\s*(.+)")


def parse_frontmatter(text: str) -> dict[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        out[k.strip()] = v.strip()
    return out


def parse_first(text: str, regex: re.Pattern[str]) -> str:
    m = regex.search(text)
    return m.group(1).strip() if m else ""


def iter_summaries() -> list[Path]:
    return sorted(SUMMARY_ROOT.rglob("*.md"))


def short_purpose(text: str, limit: int = 90) -> str:
    p = parse_first(text, PURPOSE_RE)
    p = p.replace("(no module docstring)", "—").replace("(no .SYNOPSIS block)", "—")
    if len(p) > limit:
        p = p[: limit - 1].rstrip() + "…"
    return p


def render_index(summaries: list[Path]) -> str:
    rows: list[tuple[str, str, str, str, str]] = []
    counts: dict[str, int] = defaultdict(int)
    priorities: dict[str, int] = defaultdict(int)
    for s in summaries:
        text = s.read_text(encoding="utf-8", errors="replace")
        fm = parse_frontmatter(text)
        file = fm.get("file", "?")
        domain = fm.get("owner_domain", "?")
        priority = fm.get("token_priority", "?")
        stage = fm.get("pipeline_stage", "?")
        purpose = short_purpose(text)
        rows.append((file, domain, priority, stage, purpose))
        counts[domain] += 1
        priorities[priority] += 1

    lines: list[str] = []
    lines.append("# PROJECT_INDEX")
    lines.append("")
    lines.append("Generated by `scripts/dev/generate_project_index.py`. Do not hand-edit.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Source files indexed: **{len(rows)}**")
    lines.append("- By owner domain:")
    for dom in sorted(counts):
        lines.append(f"  - `{dom}`: {counts[dom]}")
    lines.append("- By token priority:")
    for pri in ("high", "medium", "low"):
        lines.append(f"  - `{pri}`: {priorities.get(pri, 0)}")
    lines.append("")
    lines.append("## Files")
    lines.append("")
    lines.append("| File | Domain | Priority | Stage | Purpose |")
    lines.append("|---|---|---|---|---|")
    for file, domain, priority, stage, purpose in rows:
        safe_purpose = purpose.replace("|", "\\|")
        lines.append(f"| `{file}` | {domain} | {priority} | {stage} | {safe_purpose} |")
    lines.append("")
    return "\n".join(lines)


def render_graph(summaries: list[Path]) -> str:
    edges: dict[tuple[str, str], int] = defaultdict(int)
    nodes: set[str] = set()
    for s in summaries:
        text = s.read_text(encoding="utf-8", errors="replace")
        fm = parse_frontmatter(text)
        src_domain = fm.get("owner_domain", "unknown")
        nodes.add(src_domain)
        py_imports = parse_first(text, IMPORTS_RE)
        if py_imports:
            for tok in re.findall(r"`([^`]+)`", py_imports):
                target = _domain_of_python_import(tok)
                if target and target != src_domain:
                    edges[(src_domain, target)] += 1
                    nodes.add(target)
        ps_inc = parse_first(text, DOTINC_RE)
        if ps_inc:
            for tok in re.findall(r"`([^`]+)`", ps_inc):
                target = _domain_of_ps_include(tok)
                if target and target != src_domain:
                    edges[(src_domain, target)] += 1
                    nodes.add(target)

    lines: list[str] = []
    lines.append("# DEPENDENCY_GRAPH")
    lines.append("")
    lines.append("Generated by `scripts/dev/generate_project_index.py`. Do not hand-edit.")
    lines.append("Edges aggregate cross-domain Python imports and PowerShell dot-includes.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph LR")
    for node in sorted(nodes):
        safe = re.sub(r"[^A-Za-z0-9_]", "_", node) or "unknown"
        lines.append(f"  {safe}[\"{node}\"]")
    for (src, dst), n in sorted(edges.items(), key=lambda kv: (-kv[1], kv[0])):
        src_id = re.sub(r"[^A-Za-z0-9_]", "_", src) or "unknown"
        dst_id = re.sub(r"[^A-Za-z0-9_]", "_", dst) or "unknown"
        lines.append(f"  {src_id} -->|{n}| {dst_id}")
    lines.append("```")
    lines.append("")
    lines.append("## Edge counts")
    lines.append("")
    lines.append("| From | To | Edges |")
    lines.append("|---|---|---|")
    for (src, dst), n in sorted(edges.items(), key=lambda kv: (-kv[1], kv[0]))[:200]:
        lines.append(f"| {src} | {dst} | {n} |")
    lines.append("")
    return "\n".join(lines)


def _domain_of_python_import(tok: str) -> str:
    # Strip package roots and infer domain from path.
    norm = tok.replace(".", "/").strip("/")
    if "facade" in norm:
        return "application"
    if norm.startswith("app/"):
        parts = norm.split("/")
        return parts[1] if len(parts) > 1 else "app"
    if "api" in norm:
        return "api"
    if "network" in norm:
        return "network"
    if "contract" in norm:
        return "contracts"
    return ""


def _domain_of_ps_include(tok: str) -> str:
    name = tok.split(".")[0]
    return name or ""


def main() -> int:
    if not SUMMARY_ROOT.exists():
        print("summaries/ does not exist. Run refresh_summaries.py first.")
        return 1
    summaries = iter_summaries()
    INDEX_PATH.write_text(render_index(summaries), encoding="utf-8")
    GRAPH_PATH.write_text(render_graph(summaries), encoding="utf-8")
    print(f"Wrote {INDEX_PATH.name} and {GRAPH_PATH.name} from {len(summaries)} summaries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
