# Generated by MediaPipelineRemuxEncodeAIO Desktop App.
# Unknown keys are preserved, but original comments/formatting are not.
@{
    ConfigSchemaVersion = 1
    SourceMovies = '\\LAYNE-SERVER\Users\Layne\Videos\Encode\Movies'
    SourceTV = '\\LAYNE-SERVER\Users\Layne\Videos\Encode\TV'
    Outsource = '\\LAYNE-SERVER\Users\Layne\Videos\outsource'
    LocalBase = 'E:\Videos\Scratch'
    EncodeThresholdGB = 8
    TVEncodeThresholdGB = 3
    RoutingProfile = 'plex_direct_stream'
    RouteThresholdMode = 'compatibility_advisory'
    MovieRouteMaxVideoBitrateMbps = 35
    TVRouteMaxVideoBitrateMbps = 18
    AllowH264RemuxIfPlexCompatible = $true
    H264RemuxMaxBitrateMbps = 35
    H264RemuxMaxHeight = 1080
    SizeGuardMode = 'advisory'
    MaxEncodeGrowthPercent = 5
    CompatibilityEncodeGrowthPercent = 15
    MinFreeSpaceGB = 50
    OutsourceMinFreeSpaceGB = 50
    VideoCodec = 'hevc_nvenc'
    VideoPreset = 'p7'
    VideoQuality = 21
    OutputContainer = 'mkv'
    EncodeTuningPreset = 'balanced_nvenc'
    EncodeLadder = 'auto'
    ExtraVideoFlags = @(
        '-rc',
        'vbr',
        '-rc-lookahead',
        '60',
        '-spatial-aq',
        '1',
        '-temporal-aq',
        '1',
        '-aq-strength',
        '8',
        '-multipass',
        'fullres',
        '-bf',
        '4',
        '-tune',
        'hq'
    )
    CompatibleAudioCodecs = @(
        'aac',
        'ac3',
        'eac3',
        'mp3',
        'opus',
        'vorbis',
        'flac',
        'truehd',
        'mlp',
        'dts',
        'dts-hd'
    )
    SubKeepLanguages = @(
        'eng',
        'en',
        'und'
    )
    ConvertTx3gToSrt = $true
    DropTx3gAfterConversion = $false
    CreateExternalTx3gSrtSidecars = $false
    Tx3gExtractLanguages = @(
        'eng',
        'en',
        'und'
    )
    Tx3gPreserveExistingSrt = $true
    Tx3gTreatForcedAsSeparate = $true
    ConvertBdpgsToSrt = $true
    DropBdpgsAfterConversion = $false
    BdpgsExtractLanguages = @(
        'eng',
        'en',
        'und'
    )
    BdpgsOcrToolPath = 'Tools\PgsToSrt\PgsToSrt.exe'
    BdpgsOcrTessdataPath = 'Tools\PgsToSrt\tessdata'
    SubSDHTitleKeywords = @(
        'sdh',
        'hearing impaired',
        'hearing-impaired',
        'cc',
        'closed caption',
        'closedcaption'
    )
    SubSupplementalKeywords = @(
        'sign',
        'song',
        'karaoke',
        'chapter',
        'opening',
        'ending'
    )
    DropAssAfterConversion = $false
    StripFormatting = $true
    RemoveKaraoke = $true
    MergeAdjacent = $true
    MergeThresholdMs = 150
    KeepSignsAndSongs = $true
    TreatAssSignsSongsAsForced = $false
    TreatTx3gSignsSongsAsForced = $false
    TreatBdpgsSignsSongsAsForced = $false
    ExcludeSubtitleStyles = @(
        'Sign',
        'Sign *',
        'Sign-*',
        'Signs',
        'Signs *',
        'Signs-*',
        'OP',
        'OP *',
        'OP-*',
        'OP_*',
        'Opening*',
        'ED',
        'ED *',
        'ED-*',
        'ED_*',
        'Ending*',
        '*Lyrics*',
        '*Romaji*',
        '*Kanji*',
        'Song',
        'Song *',
        'Song-*',
        'Title',
        'Show Title',
        'Episode Title',
        'Next Episode',
        'Next *',
        'Credits',
        'Credit*',
        'Note',
        'Note*',
        'Caption',
        'Caption*',
        'fs'
    )
    IncludeSubtitleStyles = @()
    RemuxSafeVideoCodecs = @(
        'hevc',
        'h265',
        'h.265',
        # AV1 sources are Plex direct-play compatible and mkvmerge can
        # stream-copy them into MKV without re-encoding. Without this
        # entry, AV1 sources fall back to the encode path and the
        # re-encode (CQ 22 HEVC NVENC) typically inflates them since
        # AV1 is more efficient than HEVC at equivalent quality.
        'av1'
    )
    ValidExtensions = @(
        '.mkv',
        '.mp4',
        '.avi',
        '.mov',
        '.m4v',
        '.ts',
        '.m2ts'
    )
    FileStabilityWait = 15
    SkipStabilityCheck = $false
    EnableIntegrityCheck = $true
    CreateTVSubfolder = $true
    AggressiveEpisodeParsing = $true
    RobocopyFlags = @(
        '/J',
        '/R:3',
        '/W:15',
        '/MT:2',
        '/NP',
        '/NDL',
        '/NFL'
    )
    DebugMode = $true
    LogRetentionDays = 7
    ConsoleLogLevel = 'DEBUG'
    FileLogLevel = 'INFO'
    PriorityMarkers = @(
        '!',
        '[NOW]'
    )
    MaxParallelEncodes = 1
    ParallelEncodeMode = 'single'
    ReprocessAll = $false
    OutputSizeMultiplier = 0.7
    FallbackCpuQuality = 20
    CpuEncodePreset = 'medium'
    CpuEncodeProcessPriority = 'belownormal'
    CpuEncodeMaxThreads = 0
    FFmpegEncodeTimeoutSeconds = 21600
    FFmpegCpuEncodeTimeoutSeconds = 43200
    FFmpegRemuxTimeoutSeconds = 7200
    MkvmergeRemuxTimeoutSeconds = 7200
    SubtitleExtractTimeoutSeconds = 180
    SubtitleProbeTimeoutSeconds = 30
    BdpgsOcrTimeoutSeconds = 1800
    OutputValidationProbeTimeoutSeconds = 60
    OutputValidationMinSizeBytes = 1024
    OutputValidationDurationToleranceSeconds = 2
    AllowSystemTools = $false
    RobocopyTimeoutSeconds = 14400
    TransientFailureRetryLimit = 3
    SourceScanIntervalSeconds = 300
    SourceScanTimeoutSeconds = 1800
    ProcessedIndexRefreshSeconds = 900
    IndexScanTimeoutSeconds = 1800
    CleanupScanTimeoutSeconds = 300
    CleanupRemoteStaging = $false
    CleanupStaleAgeHours = 24
    CoordinatorAlsoEncodeLocally = $false
    CoordinatorAuthToken = ''
    CoordinatorHeartbeatTimeoutMins = 5
    CoordinatorPort = 7830
    DeferredPublish = $false
    NetworkRole = 'standalone'
    PreferredDefaultAudioLanguages = @(
        'english'
    )
    WorkerAuthToken = 'e1c1e2cc7d5acbadd5ee03f63de6d4243383ec258e925a4e56c8d30314c7c004'
    WorkerConfigOverrides = ''
    WorkerCoordinatorUrl = 'http://192.168.0.161:7830'
    WorkerName = 'GamingPC desktop'
    WorkerPollIntervalSecs = 10
    WorkerSourcePathMap = ''
}
