"""Advanced-page settings field definitions."""

from __future__ import annotations

from .policy import LOG_LEVEL_VALUES


ADVANCED_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "DebugMode",
        "label": "Verbose Debug Logging",
        "kind": "bool",
        "help": "Enable more detailed pipeline debug output.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "ConsoleLogLevel",
        "label": "Console Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "Console log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "FileLogLevel",
        "label": "File Log Level",
        "kind": "combo",
        "choices": LOG_LEVEL_VALUES,
        "help": "File log verbosity.",
    },
    {
        "page": "Advanced",
        "section": "Logging",
        "key": "LogRetentionDays",
        "label": "Log Retention Days",
        "kind": "int",
        "default": 7,
        "help": "Number of days to keep rotated pipeline log files.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinFreeSpaceGB",
        "label": "Scratch Free Space Reserve (GB)",
        "kind": "int",
        "default": 50,
        "help": "Minimum free space reserved on the scratch drive.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutsourceMinFreeSpaceGB",
        "label": "Output Free Space Reserve (GB)",
        "kind": "int",
        "default": 50,
        "help": "Minimum free space reserved on the output destination.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegEncodeTimeoutSeconds",
        "label": "Encode Timeout (s)",
        "kind": "int",
        "default": 21600,
        "help": "Kill threshold for ffmpeg encode jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "FFmpegRemuxTimeoutSeconds",
        "label": "Remux Timeout (s)",
        "kind": "int",
        "default": 7200,
        "help": "Kill threshold for ffmpeg remux jobs.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleExtractTimeoutSeconds",
        "label": "Subtitle Extract Timeout (s)",
        "kind": "int",
        "default": 180,
        "help": "Kill threshold for ASS/tx3g subtitle extraction helpers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "SubtitleProbeTimeoutSeconds",
        "label": "Subtitle Probe Timeout (s)",
        "kind": "int",
        "default": 30,
        "help": "Kill threshold for subtitle stream probing commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "BdpgsOcrTimeoutSeconds",
        "label": "BDPGS OCR Timeout (s)",
        "kind": "int",
        "default": 1800,
        "help": "Kill threshold for external BDPGS OCR commands.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "AllowSystemTools",
        "label": "Allow PATH Tool Fallback",
        "kind": "bool",
        "help": "Developer-only fallback. Leave off so the portable bundle requires its bundled FFmpeg, ffprobe, mkvmerge, and Python.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyTimeoutSeconds",
        "label": "Copy Timeout (s)",
        "kind": "int",
        "default": 14400,
        "help": "Kill threshold for robocopy source, scratch, and publish transfers.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "TransientFailureRetryLimit",
        "label": "Transient Failure Retry Limit",
        "kind": "int",
        "default": 3,
        "help": "Repeated matching transient failures escalate to operator_required at this count.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "MinPipelineVersion",
        "label": "Minimum Pipeline Version",
        "kind": "optional_string",
        "help": "Optional version floor used for reprocess decisions.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "OutputSizeMultiplier",
        "label": "Output Size Multiplier",
        "kind": "optional_float",
        "help": "Optional size safety multiplier for route validation.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "EnableIntegrityCheck",
        "label": "Enable Integrity Check",
        "kind": "bool",
        "help": "Probe source media before processing so corrupt or incomplete files can be held back.",
    },
    {
        "page": "Advanced",
        "section": "Safety",
        "key": "RobocopyFlags",
        "label": "Robocopy Flags",
        "kind": "list",
        "help": "Flags used for source-to-scratch and scratch-to-output robocopy transfers. Keep retries, waits, and logging flags explicit.",
    },
)
