"""Basic-page settings field definitions."""

from __future__ import annotations

from ..metadata_support import (
    AUDIO_DOWNMIX_MODE_DESCRIPTIONS,
    AUDIO_MAX_CHANNEL_DESCRIPTIONS,
    AUDIO_TRANSCODE_CODEC_DESCRIPTIONS,
)
from .policy import (
    AUDIO_PASSTHROUGH_PROFILE_DEFAULT,
    AUDIO_PASSTHROUGH_PROFILE_DESCRIPTIONS,
    AUDIO_PASSTHROUGH_PROFILE_NAMES,
    ROUTE_THRESHOLD_MODE_DEFAULT,
    ROUTE_THRESHOLD_MODE_DESCRIPTIONS,
    ROUTE_THRESHOLD_MODE_NAMES,
    ROUTING_PROFILE_DEFAULT,
    ROUTING_PROFILE_DESCRIPTIONS,
    ROUTING_PROFILE_NAMES,
    SIZE_GUARD_MODE_DEFAULT,
    SIZE_GUARD_MODE_DESCRIPTIONS,
    SIZE_GUARD_MODE_NAMES,
)


BASIC_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Basic",
        "section": "Paths",
        "key": "SourceMovies",
        "label": "Movies Source",
        "kind": "path",
        "help": "Folder the pipeline scans for incoming movie files.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "SourceTV",
        "label": "TV Source",
        "kind": "path",
        "help": "Folder the pipeline scans for incoming TV files.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "Outsource",
        "label": "Final Output",
        "kind": "path",
        "help": "Final processed library destination.",
    },
    {
        "page": "Basic",
        "section": "Libraries",
        "key": "LibraryProfiles",
        "label": "Library Profiles",
        "kind": "json",
        "default": "[]",
        "help": "Per-library source, output, designation, optional promotion destination, and explicit editor/video/subtitle/audio overrides. Movie and TV are synthesized from legacy paths when this is not configured.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "LocalBase",
        "label": "Scratch Disk",
        "kind": "path",
        "help": "Fast local working directory for copies, remuxes, and temporary files.",
    },
    {
        "page": "Basic",
        "section": "Final Library Promotion",
        "key": "FinalLibraryPromotionEnabled",
        "label": "Enable Promotion",
        "kind": "bool",
        "default": False,
        "help": "Expose the manual Promote Queue to Final Library workflow for completed publish output.",
    },
    {
        "page": "Basic",
        "section": "Final Library Promotion",
        "key": "FinalLibraryPromotionRules",
        "label": "Source to Destination Rules",
        "kind": "string",
        "default": "[]",
        "help": "JSON array of rules with label, enabled, source_root, and destination_root. The longest matching source_root wins.",
    },
    {
        "page": "Basic",
        "section": "Final Library Promotion",
        "key": "FinalLibraryPromotionVerificationMode",
        "label": "Verification Mode",
        "kind": "combo",
        "choices": ("cautious", "fast"),
        "default": "cautious",
        "help": "Cautious verifies byte size and SHA-256 hashes. Fast verifies destination existence and byte size only.",
    },
    {
        "page": "Basic",
        "section": "Final Library Promotion",
        "key": "FinalLibraryPromotionCleanupAfterVerified",
        "label": "Cleanup After Verified",
        "kind": "bool",
        "default": False,
        "help": "After verified promotion, delete only copied publish-output files and remove empty folders below Outsource.",
    },
    {
        "page": "Basic",
        "section": "Final Library Promotion",
        "key": "FinalLibraryPromotionOverwriteExisting",
        "label": "Overwrite Existing Final Files",
        "kind": "bool",
        "default": False,
        "help": "Destructive: delete the existing final file immediately before copying the replacement.",
    },
    {
        "page": "Basic",
        "section": "Paths",
        "key": "CreateTVSubfolder",
        "label": "Create TV Library Folders",
        "kind": "bool",
        "help": "When enabled, TV outputs are placed under TV\\Show\\Season NN style folders for Plex-style libraries.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioPassthroughProfile",
        "label": "Audio Passthrough Profile",
        "kind": "combo",
        "choices": AUDIO_PASSTHROUGH_PROFILE_NAMES,
        "default": AUDIO_PASSTHROUGH_PROFILE_DEFAULT,
        "choice_help": AUDIO_PASSTHROUGH_PROFILE_DESCRIPTIONS,
        "help": "Structured policy for which audio codecs can be copied. Use custom_codec_list only when you need manual codec control.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "CompatibleAudioCodecs",
        "label": "Custom Audio Passthrough Codecs",
        "kind": "list",
        "help": "Manual codecs copied only when Audio Passthrough Profile is custom_codec_list. Structured profiles populate this list on save.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "PreferredDefaultAudioLanguages",
        "label": "Preferred Default Audio Languages",
        "kind": "list",
        "help": "Ordered language preference for the default audio track. If none of these are present, the highest-fidelity non-commentary track is chosen. The text field controls the exact order.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioTranscodeCodec",
        "label": "Transcode Codec",
        "kind": "combo",
        "choices": ("eac3", "ac3", "aac"),
        "default": "eac3",
        "choice_help": AUDIO_TRANSCODE_CODEC_DESCRIPTIONS,
        "help": "Codec used when an audio track must be normalized instead of copied.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioTranscodeBitrate",
        "label": "Transcode Bitrate",
        "kind": "combo",
        "choices": ("384k", "448k", "640k", "768k"),
        "default": "640k",
        "help": "Bitrate used for normalized audio tracks. Ignored when 'Auto Bitrate by Channels' is on.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioTranscodeAutoBitrateByChannels",
        "label": "Auto Bitrate by Channels",
        "kind": "bool",
        "default": False,
        "help": "When on, audio transcode bitrate is picked from a codec/channel-count table (e.g. 192k for 2.0 EAC3, 448k for 5.1 EAC3, 640k for 7.1 EAC3) instead of the static 'Transcode Bitrate' value. Saves space on commentary / stereo tracks; gives 7.1 mixes more bit pool.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioDownmixMode",
        "label": "Downmix Mode",
        "kind": "combo",
        "choices": ("max_channels", "preserve", "stereo"),
        "default": "max_channels",
        "choice_help": AUDIO_DOWNMIX_MODE_DESCRIPTIONS,
        "help": "Controls channel count when audio is transcoded: cap to the maximum, preserve source channels, or force stereo.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AudioMaxChannels",
        "label": "Max Channels",
        "kind": "combo_int",
        "choices": ("2", "6", "8"),
        "default": 6,
        "choice_help": AUDIO_MAX_CHANNEL_DESCRIPTIONS,
        "help": "Maximum channels for transcodes when Downmix Mode is max_channels.",
    },
    {
        "page": "Basic",
        "section": "Audio",
        "key": "AllowNoAudio",
        "label": "Allow No-Audio Outputs",
        "kind": "bool",
        "default": False,
        "help": "Permit silent source files to be processed without audio. Leave off for normal Plex media.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "EncodeThresholdGB",
        "label": "Movie target output size (GB)",
        "kind": "int",
        "default": 8,
        "help": "GB target output size used as the movie size budget for route and size-policy checks; not the Mbps max bitrate for direct copy.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "TVEncodeThresholdGB",
        "label": "TV target output size (GB)",
        "kind": "int",
        "default": 3,
        "help": "GB target output size used as the TV episode size budget for route and size-policy checks; not the Mbps max bitrate for direct copy.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "RoutingProfile",
        "label": "Routing Profile",
        "kind": "combo",
        "choices": ROUTING_PROFILE_NAMES,
        "default": ROUTING_PROFILE_DEFAULT,
        "choice_help": ROUTING_PROFILE_DESCRIPTIONS,
        "help": "High-level remux vs encode policy. Plex Direct/Stream is the default for avoiding unnecessary re-encodes of compatible sources.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "RouteThresholdMode",
        "label": "Enforcement Mode",
        "kind": "combo",
        "choices": ROUTE_THRESHOLD_MODE_NAMES,
        "default": ROUTE_THRESHOLD_MODE_DEFAULT,
        "choice_help": ROUTE_THRESHOLD_MODE_DESCRIPTIONS,
        "help": "Used before processing to decide copy/remux versus encode. Selects which route gates are hard: target output size, max bitrate for direct copy, or either.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "MovieRouteMaxVideoBitrateMbps",
        "label": "Movie max bitrate for direct copy",
        "kind": "int",
        "default": 35,
        "help": "Maximum movie video bitrate in Mbps used before processing to decide whether direct copy/remux remains eligible. Above this cap, routing may choose encode.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "TVRouteMaxVideoBitrateMbps",
        "label": "TV max bitrate for direct copy",
        "kind": "int",
        "default": 18,
        "help": "Maximum TV video bitrate in Mbps used before processing to decide whether direct copy/remux remains eligible. Above this cap, routing may choose encode.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "AllowH264RemuxIfPlexCompatible",
        "label": "Copy Compatible H.264",
        "kind": "bool",
        "default": True,
        "help": "Allow low-risk H.264/AVC sources to stay remux/copy when bitrate, resolution, and Plex compatibility are acceptable.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "H264RemuxMaxBitrateMbps",
        "label": "H.264 Copy Max Mbps",
        "kind": "int",
        "default": 35,
        "help": "Maximum estimated source bitrate for the Plex-compatible H.264 shortcut and effective H.264 copy scoring; not a universal remux safety limit.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "H264RemuxMaxHeight",
        "label": "H.264 Copy Max Height",
        "kind": "combo_int",
        "choices": ("720", "1080", "2160"),
        "default": 1080,
        "help": "Maximum video height allowed for the Plex-compatible H.264 shortcut; codec-safe fallback can still remux taller H.264 when hard routing does not force encode.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "SizeGuardMode",
        "label": "Output Size Check",
        "kind": "combo",
        "choices": SIZE_GUARD_MODE_NAMES,
        "default": SIZE_GUARD_MODE_DEFAULT,
        "choice_help": SIZE_GUARD_MODE_DESCRIPTIONS,
        "help": "Checked after encode. Warns but does not block in warn-only mode. Blocks publish when configured to block if output exceeds the configured size budget.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "MaxEncodeGrowthPercent",
        "label": "Normal Growth Limit %",
        "kind": "int",
        "default": 5,
        "help": "Checked after encode. Allowed output growth for quality encodes; Output Size Check warns or blocks publish when configured to block.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "CompatibilityEncodeGrowthPercent",
        "label": "Compatibility Growth Limit %",
        "kind": "int",
        "default": 15,
        "help": "Checked after encode. Allowed output growth for compatibility encodes; Output Size Check warns or blocks publish when configured to block.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "DeferredPublish",
        "label": "Deferred Publish",
        "kind": "bool",
        "help": "Park completed outputs locally instead of uploading them immediately. Use the recovery action to publish parked outputs later.",
    },
    {
        "page": "Basic",
        "section": "Routing",
        "key": "AggressiveEpisodeParsing",
        "label": "Aggressive Episode Parsing",
        "kind": "bool",
        "help": "Use folder season hints and loose anime/import filename patterns to build SxxEyy when strict parsing fails.",
    },
)
