"""Video-page settings field definitions."""

from __future__ import annotations

from ..metadata_support import (
    ENCODE_LADDER_DESCRIPTIONS,
    ENCODE_TUNING_PRESET_DESCRIPTIONS,
)


VIDEO_CONFIG_FIELD_DEFINITIONS = (
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoCodec",
        "label": "Hardware / Codec",
        "kind": "combo",
        "choices": ("hevc_nvenc", "libx265", "h264_nvenc", "libx264", "av1_nvenc"),
        "help": "Primary video output path used for encode jobs.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoPreset",
        "label": "Preset",
        "kind": "combo",
        "choices": ("p1", "p2", "p3", "p4", "p5", "p6", "p7"),
        "help": "NVENC preset. p1 is fastest with the weakest compression efficiency. p7 is slowest with the best compression efficiency.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "VideoQuality",
        "label": "Quality",
        "kind": "combo_int",
        "choices": ("18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"),
        "default": 22,
        "help": "CQ/CRF-style target. Lower is cleaner and larger. Higher is softer and smaller.",
    },
    {
        "page": "Video",
        "section": "Video",
        "key": "OutputContainer",
        "label": "Container",
        "kind": "combo",
        "choices": ("mkv", "mp4"),
        "help": "Final container format for encoded outputs.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "EncodeTuningPreset",
        "label": "Encode Tuning Preset",
        "kind": "combo",
        "choices": ("balanced_nvenc", "quality_nvenc", "fast_nvenc", "compatibility", "custom_legacy_flags"),
        "default": "balanced_nvenc",
        "choice_help": ENCODE_TUNING_PRESET_DESCRIPTIONS,
        "help": "Structured NVENC tuning profile. Use custom_legacy_flags only when you intentionally need raw ExtraVideoFlags.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "EncodeLadder",
        "label": "Encode Ladder",
        "kind": "combo",
        "choices": ("auto", "tv_balanced", "tv_space_saver", "movie_balanced", "movie_archive", "plex_compat"),
        "default": "auto",
        "choice_help": ENCODE_LADDER_DESCRIPTIONS,
        "help": "Structured output target. Auto picks a TV or movie profile; plex_compat uses conservative bitrate and compatibility flags.",
    },
    {
        "page": "Video",
        "section": "NVENC / Encode",
        "key": "ExtraVideoFlags",
        "label": "Legacy Extra Video Flags",
        "kind": "list",
        "help": "Raw ffmpeg/NVENC flags used only when Encode Tuning Preset is custom_legacy_flags or when loading an old config without a preset.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "RemuxSafeVideoCodecs",
        "label": "Remux-Safe Video Codecs",
        "kind": "list",
        "help": "Video codecs the pipeline may remux directly without re-encoding.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "FallbackCpuQuality",
        "label": "CPU Fallback Quality",
        "kind": "optional_int",
        "help": "Optional quality target used when GPU encoding falls back to CPU. Note: this is a libx265 -crf value, not an NVENC -cq, so a value tuned for NVENC may produce a different size on CPU.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodePreset",
        "label": "CPU Encode Preset",
        "kind": "combo",
        "choices": (
            "ultrafast", "superfast", "veryfast", "faster", "fast",
            "medium", "slow", "slower", "veryslow", "placebo",
        ),
        "default": "medium",
        "help": "libx265 -preset used for CPU encodes (fallback or primary). Faster presets are responsive but lose quality; slower presets compress better but can run for many hours.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodeProcessPriority",
        "label": "CPU Encode Process Priority",
        "kind": "combo",
        "choices": ("inherit", "idle", "belownormal", "normal", "abovenormal", "high"),
        "default": "belownormal",
        "help": "Windows process priority class applied to ffmpeg when running a CPU encode. BelowNormal keeps the desktop UI responsive while libx265 saturates the cores.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "FFmpegCpuEncodeTimeoutSeconds",
        "label": "CPU Encode Timeout (seconds)",
        "kind": "int",
        "default": 43200,
        "help": "Hard ceiling for ffmpeg CPU encode wall-clock time. CPU encodes can take 5-15x longer than NVENC, so this should usually be larger than the GPU timeout.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "MkvmergeRemuxTimeoutSeconds",
        "label": "Mkvmerge Remux Timeout (seconds)",
        "kind": "int",
        "default": 7200,
        "help": "Hard ceiling for the mkvmerge step of a remux job. Defaults to 2 hours, matching the ffmpeg-remux timeout. Replaces a former hard-coded 600s ceiling that was too short for large MKVs over slow scratch volumes.",
    },
    {
        "page": "Video",
        "section": "Remux / Safety",
        "key": "CpuEncodeMaxThreads",
        "label": "CPU Encode Max Threads",
        "kind": "int",
        "default": 0,
        "help": "Maximum number of libx265 threads. 0 = autodetect (use every logical core, default libav behavior). Setting a positive value caps both ffmpeg -threads and the libx265 pool/frame-thread budget so the desktop UI stays responsive on smaller CPUs.",
    },
)
