"""Generate a focused exact duplicate Python test-name report.

The report groups bare test function/method names that appear in more than one
test file. Existing duplicates are review candidates only; --check verifies
that the generated report is current.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import sys
from dataclasses import dataclass
from pathlib import Path

from mediapipeline.tools.paths import find_repo_root


REPO_ROOT = find_repo_root(Path(__file__))
OUTPUT_PATH = REPO_ROOT / "docs" / "generated" / "DUPLICATE_TEST_NAMES.md"
RUN_COMMAND = (
    "apps/desktop/runtime/Python/python.exe ops/scripts/dev/run-python-tool.py "
    "mediapipeline.tools.dev.generate_duplicate_test_name_report"
)
TEST_ROOTS = ("tests/python", "tests/webview")


@dataclass(frozen=True)
class TestDefinition:
    name: str
    path: str
    qualname: str
    line: int


def repo_rel(repo_root: Path, path: Path) -> str:
    return path.relative_to(repo_root).as_posix()


def iter_test_files(repo_root: Path = REPO_ROOT) -> list[Path]:
    files: list[Path] = []
    for root_name in TEST_ROOTS:
        root = repo_root / root_name
        if root.exists():
            files.extend(sorted(root.rglob("test_*.py")))
    return sorted(files)


def collect_definitions_from_tree(repo_root: Path, path: Path, tree: ast.AST) -> list[TestDefinition]:
    definitions: list[TestDefinition] = []

    def visit_body(nodes: list[ast.stmt], class_stack: tuple[str, ...] = ()) -> None:
        for node in nodes:
            if isinstance(node, ast.ClassDef):
                visit_body(node.body, class_stack + (node.name,))
                continue
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test"):
                qualname = ".".join(class_stack + (node.name,))
                definitions.append(
                    TestDefinition(
                        line=node.lineno,
                        name=node.name,
                        path=repo_rel(repo_root, path),
                        qualname=qualname,
                    )
                )

    if isinstance(tree, ast.Module):
        visit_body(tree.body)
    return definitions


def collect_test_definitions(repo_root: Path = REPO_ROOT) -> list[TestDefinition]:
    definitions: list[TestDefinition] = []
    for path in iter_test_files(repo_root):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"), filename=str(path))
        except SyntaxError:
            continue
        definitions.extend(collect_definitions_from_tree(repo_root, path, tree))
    return sorted(definitions, key=lambda item: (item.name, item.path, item.line, item.qualname))


def duplicate_groups(definitions: list[TestDefinition]) -> dict[str, list[TestDefinition]]:
    by_name: dict[str, list[TestDefinition]] = {}
    for definition in definitions:
        by_name.setdefault(definition.name, []).append(definition)
    return {
        name: entries
        for name, entries in sorted(by_name.items())
        if len({entry.path for entry in entries}) > 1
    }


def render_duplicate_test_name_report(repo_root: Path = REPO_ROOT) -> str:
    definitions = collect_test_definitions(repo_root)
    groups = duplicate_groups(definitions)

    lines: list[str] = []
    lines.append("# Duplicate Test Names")
    lines.append("")
    lines.append(f"Generated by `{RUN_COMMAND}`. Do not hand-edit.")
    lines.append("")
    lines.append(
        "This report groups exact bare Python test function/method names that appear in more than one file. "
        "Entries are overlap review candidates, not removal instructions."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Test roots: {', '.join(f'`{root}`' for root in TEST_ROOTS)}")
    lines.append(f"- Python test definitions scanned: **{len(definitions)}**")
    lines.append(f"- Duplicate bare names across files: **{len(groups)}**")
    lines.append("")
    lines.append("## Duplicate Names")
    lines.append("")
    if not groups:
        lines.append("No exact duplicate bare test names were found across files.")
        lines.append("")
        return "\n".join(lines)

    for name, entries in groups.items():
        lines.append(f"### `{name}`")
        lines.append("")
        lines.append("| File | Qualname | Line |")
        lines.append("|---|---|---:|")
        for entry in sorted(entries, key=lambda item: (item.path, item.line, item.qualname)):
            lines.append(f"| `{entry.path}` | `{entry.qualname}` | {entry.line} |")
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, text: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def check_current(path: Path, expected: str) -> int:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        print(f"OK: {path.relative_to(REPO_ROOT)} is current.")
        return 0
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(REPO_ROOT)),
        tofile=f"{path.relative_to(REPO_ROOT)} (generated)",
        lineterm="",
    )
    print("Duplicate test-name report drift detected. Regenerate with:")
    print(f"  {RUN_COMMAND}")
    print("\n".join(list(diff)[:160]))
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated duplicate-name report.")
    args = parser.parse_args(argv)

    expected = render_duplicate_test_name_report()
    if args.check:
        return check_current(OUTPUT_PATH, expected)
    changed = write_if_changed(OUTPUT_PATH, expected)
    status = "updated" if changed else "current"
    print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} {status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
