"""Generate the file lifecycle/state-machine map from mediapipeline.contracts.lifecycle."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from mediapipeline.tools.paths import find_repo_root


REPO_ROOT = find_repo_root(Path(__file__))
LIFECYCLE_MAP_PATH = REPO_ROOT / "docs" / "architecture" / "FILE_LIFECYCLE_MAP.md"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _codes(values: tuple[str, ...]) -> str:
    if not values:
        return "none"
    return ", ".join(f"`{item}`" for item in values)


def render_lifecycle_map() -> str:
    from mediapipeline.contracts.lifecycle import LIFECYCLE_SCHEMA_VERSION, LIFECYCLE_STATES, LIFECYCLE_TRANSITIONS

    lines: list[str] = []
    lines.append("# File lifecycle map")
    lines.append("")
    lines.append("Generated by `python -m mediapipeline.tools.dev.generate_lifecycle_map` from `src/mediapipeline/contracts/lifecycle.py`. Do not hand-edit.")
    lines.append("")
    lines.append(f"Schema version: `{LIFECYCLE_SCHEMA_VERSION}`")
    lines.append("")
    lines.append("This map describes the current file lifecycle and explicitly marks desired-but-absent")
    lines.append("folder concepts so AI agents do not infer runtime states that the pipeline does not own.")
    lines.append("")
    lines.append("## Source references")
    lines.append("")
    lines.append("- `docs/operator/NO_TOUCH_BOUNDARY_REGISTER.md`")
    lines.append("- `docs/inventories/RUNTIME_ARTIFACT_INVENTORY.md`")
    lines.append("- `docs/inventories/STATE_FILE_SCHEMA_REFERENCE.md`")
    lines.append("- `docs/architecture/LOCAL_API_EVIDENCE_MUTATION_MATRIX.md`")
    lines.append("- `docs/architecture/REPAIR_RECONCILE_MUTATION_CONTRACT.md`")
    lines.append("")
    lines.append("## States")
    lines.append("")
    lines.append("| State | Implemented | Owner | Description | Validation |")
    lines.append("|---|---|---|---|---|")
    for state in LIFECYCLE_STATES:
        lines.append(
            "| `{}` | {} | {} | {} | `{}` |".format(
                state.state_id,
                "yes" if state.implemented else "no",
                _cell(state.owner),
                _cell(state.description),
                state.validation_rung,
            )
        )
    lines.append("")
    lines.append("## State details")
    lines.append("")
    for state in LIFECYCLE_STATES:
        lines.append(f"### {state.label}")
        lines.append("")
        lines.append(f"- **State id:** `{state.state_id}`")
        lines.append(f"- **Implemented:** {'yes' if state.implemented else 'no'}")
        lines.append(f"- **Owner:** {state.owner}")
        lines.append(f"- **Allowed operations:** {_codes(state.allowed_operations)}")
        lines.append(f"- **Forbidden operations:** {_codes(state.forbidden_operations)}")
        lines.append(f"- **Artifacts:** {_codes(state.artifacts)}")
        lines.append(f"- **Recovery rule:** {state.recovery_rule}")
        lines.append(f"- **Cleanup rule:** {state.cleanup_rule}")
        lines.append(f"- **Validation rung:** `{state.validation_rung}`")
        lines.append("")
    lines.append("## Transitions")
    lines.append("")
    lines.append("| From | To | Trigger | Guard | Evidence |")
    lines.append("|---|---|---|---|---|")
    for transition in LIFECYCLE_TRANSITIONS:
        lines.append(
            "| `{}` | `{}` | {} | {} | {} |".format(
                transition.source,
                transition.target,
                _cell(transition.trigger),
                _cell(transition.guard),
                _cell(transition.evidence),
            )
        )
    lines.append("")
    lines.append("## Validation")
    lines.append("")
    lines.append("- `python -m mediapipeline.tools.dev.generate_lifecycle_map --check` fails when this generated map drifts.")
    lines.append("- Lifecycle contract tests validate unique state ids and transition endpoints.")
    lines.append("- Runtime behavior changes must update `src/mediapipeline/contracts/lifecycle.py` first, then regenerate this file.")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, text: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def check_current(path: Path, expected: str) -> int:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        print(f"OK: {path.relative_to(REPO_ROOT)} is current.")
        return 0
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(REPO_ROOT)),
        tofile=f"{path.relative_to(REPO_ROOT)} (generated)",
        lineterm="",
    )
    print("Lifecycle map drift detected. Regenerate with:")
    print("  python -m mediapipeline.tools.dev.generate_lifecycle_map")
    print("\n".join(list(diff)[:160]))
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated lifecycle map without rewriting.")
    args = parser.parse_args(argv)

    expected = render_lifecycle_map()
    if args.check:
        return check_current(LIFECYCLE_MAP_PATH, expected)
    changed = write_if_changed(LIFECYCLE_MAP_PATH, expected)
    status = "updated" if changed else "current"
    print(f"{LIFECYCLE_MAP_PATH.relative_to(REPO_ROOT)} {status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
